#!/usr/bin/env python3
"""ciu installer — get.py  (generated by cmru get-py)

Transactional, fail-closed installer: private-repo asset auth, per-release
directories (own venv each) with an atomic `current` symlink, state + rollback,
system/user scope, offline hash-locked wheel install, SHA256 verification of the
bundle and a verified manifest that covers everything that runs, and an optional
minisign signature over that manifest (verified whenever a key is configured).

Usage
-----
Install (system scope, requires root):
    sudo python3 get.py install [--config HOST.toml]

Install (user scope):
    python3 get.py install --scope user

Pin a specific version (installs exactly that tag):
    sudo python3 get.py install --version ciu-v0.2.0

Select a variant (multi-variant releases — one asset per interpreter):
    sudo python3 get.py install --variant py311

Update (latest, or --version X):
    sudo python3 get.py update

Status:
    python3 get.py status

Rollback (to the recorded previous release):
    sudo python3 get.py rollback

Requires: python3 (stdlib only); system tools: python3
"""
from __future__ import annotations

import argparse
import fcntl
import fnmatch
import hashlib
import json
import os
import platform
import posixpath
import re
import shutil
import signal
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

# ─── Project constants (injected by cmru get-py) ─────────────────────────────
REPO_OWNER       = "volkb79-2"
REPO_NAME        = "vbpub"
TAG_PREFIX       = "ciu-v"
ASSET_SUFFIX     = ".tar.xz"
MANIFEST_NAME    = "manifest.json"
SIGNATURE_NAME   = "manifest.json.minisig"
PROJECT_NAME     = "ciu"     # the minisign trusted comment must name it
ENTRYPOINT       = ""           # "" means no adapter
# minisign public key (base64). "" => the release is unsigned (SHA256 only).
MANIFEST_PUBKEY  = ""
REQUIRED_COMMANDS: List[str] = ["python3"]
PRESERVE_PATHS: List[str]    = []
# [(glob, distribution), ...] in install order (cli-extended is hoisted first at install).
WHEEL_SPECS: List[Tuple[str, str]] = [["vendor/ciu-*.whl", "ciu"]]
# Commands exposed as <root>/bin/<cmd> -> ../current/venv/bin/<cmd>.
LAUNCHERS: List[str] = []
# Per-interpreter variants (S-REL.6). [] ⇒ one unambiguous single-asset release.
# When non-empty the release carries one asset per variant, named <tag>-<name><suffix>,
# and the operator MUST select one at install time with --variant NAME (no silent default).
VARIANTS: List[dict] = []  # e.g. [{"name": "py39", "label": "Python 3.9"}, ...]

# Scope directories (injected)
INSTALL_DIR_SYSTEM = "/opt/ciu"
INSTALL_DIR_USER   = "ciu"   # leaf; expanded under XDG_DATA_HOME

RELEASES_API = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases"

# Allowed hosts for HTTPS downloads (transport hardening S5)
_ALLOWED_HOSTS = {
    "api.github.com",
    "github.com",
    "objects.githubusercontent.com",
    "uploads.github.com",
}

MANIFEST_SCHEMA = 1
_MAX_MANIFEST_BYTES = 8 * 1024 * 1024
# Resource bounds (documented in SPEC S6): a bundle larger than these is refused, never
# truncated. Download = the compressed asset; extract = the sum of the member sizes the
# tar headers declare (checked BEFORE anything is written); members = the entry count.
_MAX_DOWNLOAD_BYTES = 512 * 1024 * 1024
_MAX_EXTRACT_BYTES = 2 * 1024 * 1024 * 1024
_MAX_MEMBERS = 50_000
_SHA256_RE = re.compile(r"[0-9a-f]{64}")
_WHEEL_VERSION_RE = re.compile(r"[0-9][0-9A-Za-z.!+_]*")
_TAG_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+-]*")
_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+-]*")

# ─── Exit codes (S8 / CIU S10.3) ─────────────────────────────────────────────
EXIT_OK     = 0
EXIT_FAIL   = 1   # download / verify / install / adapter failure
EXIT_CONFIG = 2   # configuration / schema failure
EXIT_PREREQ = 3   # missing prerequisite / required env absent


# ─── ANSI helpers (suppressed when not a TTY) ────────────────────────────────
_NO_COLOUR = not sys.stdout.isatty()
_C = {"RED": "\033[0;31m", "YEL": "\033[0;33m", "GRN": "\033[0;32m",
      "CYN": "\033[0;36m", "BLD": "\033[1m",    "RST": "\033[0m"}


def _c(code: str, text: str) -> str:
    return text if _NO_COLOUR else f"{_C[code]}{text}{_C['RST']}"


def info(msg: str)  -> None: print(f"{_c('CYN', '==>')} {msg}", flush=True)
def ok(msg: str)    -> None: print(f"{_c('GRN', '  ok')} {msg}", flush=True)
def warn(msg: str)  -> None: print(f"{_c('YEL', 'warn')} {msg}", file=sys.stderr, flush=True)
def err(msg: str)   -> None: print(f"{_c('RED', ' err')} {msg}", file=sys.stderr, flush=True)
def hr()            -> None: print("─" * 79)


def fatal(msg: str, code: int = EXIT_FAIL) -> None:
    err(msg)
    raise SystemExit(code)


# ─── Project extensions (cmru `[project.installer] extensions`) ──────────────
# A fragment inlined by cmru at the extensions marker (below) registers itself with a
# top-level `_EXTENSIONS.append(register)`; `main()` calls each registered
# function with the subparsers action and expects {command: handler} back.
# Handlers are called as handler(args, token).
_EXTENSIONS: List[Callable[[argparse._SubParsersAction],
                           Dict[str, Callable[[argparse.Namespace, Optional[str]], None]]]] = []

# STABILITY CONTRACT. These are the ONLY template top-level names an extension
# fragment may reference (cmru checks this at render time; anything else is a
# render error). Renaming, changing the signature of, or removing a name here
# requires updating every in-repo fragment in the same change. Names are only
# ever added deliberately, with the fragment that needs them.
#
# Semantics fragments may rely on:
#   do_install(args, token)  args needs .scope, .version, .variant, .config (all
#                            optional via getattr); installs/updates and returns,
#                            or raises SystemExit on failure.
#   _current_version(root)   the installed release TAG (str) or None.
#   _root_dir(scope)         the install root Path for "system" or "user".
EXTENSION_API = (
    "EXIT_CONFIG",
    "EXIT_FAIL",
    "EXIT_PREREQ",
    "_EXTENSIONS",
    "_c",
    "_current_version",
    "_root_dir",
    "do_install",
    "fatal",
    "hr",
    "info",
    "ok",
    "warn",
)


# ─── Token / auth helpers (S5) ───────────────────────────────────────────────

def _validate_token_file(path: Path) -> None:
    """Reject token files with bad permissions or foreign owner."""
    if not path.exists():
        fatal(f"Token file not found: {path}", EXIT_CONFIG)
    if path.is_symlink():
        real = path.resolve()
        if not real.exists():
            fatal(f"Token file symlink broken: {path}", EXIT_CONFIG)
    st = path.stat()
    if st.st_mode & 0o077:
        fatal(
            f"Token file {path} has loose permissions ({oct(st.st_mode & 0o777)}); "
            "chmod 600 it.", EXIT_CONFIG
        )
    if st.st_uid != os.getuid():
        fatal(
            f"Token file {path} is owned by uid {st.st_uid}, "
            f"not current user {os.getuid()}.",
            EXIT_CONFIG,
        )


def _resolve_token(args: argparse.Namespace) -> Optional[str]:
    """Resolve GitHub token: CLI arg > file/stdin > env (S5).

    Warns when --github-token is used (leaks via ps/shell history).
    Token is never logged in full. An empty --github-token-stdin is a
    configuration error, never a silent "no token".
    """
    token: Optional[str] = None

    # Lowest priority: env
    for env_var in ("CMRU_GITHUB_TOKEN", "GITHUB_TOKEN"):
        v = os.environ.get(env_var, "").strip()
        if v:
            token = v
            break

    # stdin
    if getattr(args, "github_token_stdin", False):
        line = sys.stdin.readline().strip()
        if not line:
            fatal(
                "--github-token-stdin was given but stdin is empty. Under "
                "`curl ... | python3 -` stdin is the script itself; use "
                "--github-token-file or the CMRU_GITHUB_TOKEN environment variable.",
                EXIT_CONFIG,
            )
        token = line

    # file
    tok_file = getattr(args, "github_token_file", None)
    if tok_file:
        fp = Path(tok_file).expanduser()
        _validate_token_file(fp)
        line = fp.read_text().strip()
        if line:
            token = line

    # CLI arg (highest priority — warn)
    tok_arg = getattr(args, "github_token", None)
    if tok_arg:
        warn("--github-token leaks via shell history/process list; "
             "prefer --github-token-file or CMRU_GITHUB_TOKEN env var.")
        token = tok_arg

    return token or None


# ─── Transport hardening (S5) ─────────────────────────────────────────────────

def _check_url(url: str) -> None:
    """Reject http:// and unknown hosts (applied to the request AND every redirect hop)."""
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https":
        fatal(f"HTTPS-only: refusing {parsed.scheme}:// URL: {url}", EXIT_FAIL)
    host = parsed.hostname or ""
    allowed = (
        host in _ALLOWED_HOSTS
        or host.endswith(".githubusercontent.com")
        or host.endswith(".github.com")
    )
    if not allowed:
        fatal(f"Host not in allowlist: {host}", EXIT_FAIL)


class _RedirectGuard(urllib.request.HTTPRedirectHandler):
    """Every redirect hop is re-checked (HTTPS + allowlist) and NEVER carries the token (S5)."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # type: ignore[override]
        _check_url(newurl)
        new_req = super().redirect_request(req, fp, code, msg, headers, newurl)
        if new_req is not None:
            new_req.remove_header("Authorization")
            new_req.remove_header("authorization")
        return new_req


def _gh_request(
    url: str,
    *,
    token: Optional[str] = None,
    accept: str = "application/vnd.github+json",
    stream_to: Optional[Path] = None,
    timeout: int = 30,
    max_bytes: Optional[int] = None,
) -> Tuple[int, bytes]:
    """Low-level GitHub request.

    Per S5 / release.py invariant: only sends Authorization when token is present.
    An empty 'Bearer ' header causes GitHub to 401 even on public repos.
    A streamed body larger than ``max_bytes`` is refused (EXIT_FAIL), never truncated.
    """
    _check_url(url)
    headers: dict = {"Accept": accept, "User-Agent": "ciu/get.py"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    opener = urllib.request.build_opener(_RedirectGuard)
    try:
        with opener.open(req, timeout=timeout) as resp:
            if stream_to:
                total = 0
                too_big = False
                with open(stream_to, "wb") as fh:
                    while True:
                        chunk = resp.read(65536)
                        if not chunk:
                            break
                        total += len(chunk)
                        if max_bytes is not None and total > max_bytes:
                            too_big = True
                            break
                        fh.write(chunk)
                if too_big:
                    stream_to.unlink()
                    fatal(f"Download of {url} exceeds the {max_bytes}-byte limit; refusing.",
                          EXIT_FAIL)
                return resp.status, b""
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        body = exc.read() if exc.fp else b""
        return exc.code, body
    except urllib.error.URLError as exc:
        fatal(f"Network error fetching {url}: {exc}", EXIT_FAIL)
        return 0, b""  # unreachable


def _gh_json(url: str, token: Optional[str] = None) -> object:
    status, body = _gh_request(url, token=token)
    if status in (401, 403):
        hint = " (token may be missing or expired)" if not token else ""
        fatal(f"GitHub API {status}{hint}: {url}", EXIT_FAIL)
    if status >= 400:
        fatal(
            f"GitHub API {status}: {url}\n"
            f"  {body.decode('utf-8', errors='replace')}",
            EXIT_FAIL,
        )
    try:
        return json.loads(body)
    except ValueError:
        fatal(f"GitHub API returned invalid JSON: {url}", EXIT_FAIL)
        return None  # unreachable


# ─── Tag / release resolution ─────────────────────────────────────────────────

def _semver_key(tag: str) -> tuple:
    ver = tag[len(TAG_PREFIX):]
    tokens: list = []
    for chunk in ver.replace("-", ".").split("."):
        for run in re.findall(r"\d+|\D+", chunk):
            tokens.append((0, int(run), "") if run.isdigit() else (1, 0, run))
    return tuple(tokens)


def resolve_latest_tag(token: Optional[str] = None) -> str:
    """Return the highest-semver ciu-v* release tag."""
    releases = _gh_json(f"{RELEASES_API}?per_page=100", token=token)
    if not isinstance(releases, list):
        fatal("GitHub releases listing has an unexpected shape.", EXIT_FAIL)
    candidates = [
        r["tag_name"] for r in releases
        if isinstance(r, dict)
        and isinstance(r.get("tag_name"), str)
        and r["tag_name"].startswith(TAG_PREFIX)
        and not r.get("draft")
        and not r.get("prerelease")
    ]
    if not candidates:
        fatal(
            f"No ciu releases found (prefix: {TAG_PREFIX!r}). "
            "Check network access or pass --version.",
            EXIT_FAIL,
        )
    return max(candidates, key=_semver_key)


def normalize_tag(version_arg: str) -> str:
    if version_arg.startswith(TAG_PREFIX):
        return version_arg
    # Drop a single leading "v" prefix only — NOT str.lstrip('v'), which strips a
    # whole leading run of 'v' chars (so "v1.0.0" is fine but a hypothetical multi-'v'
    # or 'v'-initial token would be corrupted). Prefix-strip, not charset-strip.
    bare = version_arg[1:] if version_arg.startswith("v") else version_arg
    return f"{TAG_PREFIX}{bare}"


def _validate_tag(tag: str) -> str:
    """A tag becomes a URL component and a directory name: refuse anything odd."""
    if (not tag.startswith(TAG_PREFIX) or not _TAG_RE.fullmatch(tag) or ".." in tag
            or not _TAG_RE.fullmatch(tag[len(TAG_PREFIX):])):
        fatal(f"Refusing release tag {tag!r}: expected {TAG_PREFIX}<version> "
              "(letters, digits, '.', '_', '+', '-').", EXIT_CONFIG)
    return tag


def _resolve_tag(args: argparse.Namespace, token: Optional[str]) -> str:
    """`--version X` installs exactly X; without it, resolve the latest and print it."""
    version = getattr(args, "version", None)
    if version is not None:  # an EMPTY --version (unset shell variable) must not mean "latest"
        tag = _validate_tag(normalize_tag(version))
        info(f"Pinned version: {_c('BLD', tag)}")
        return tag
    info("Resolving latest release ...")
    tag = _validate_tag(resolve_latest_tag(token))
    info(f"Latest: {_c('BLD', tag)}  (resolved; pass --version {tag} to pin it)")
    return tag


def _find_asset_by_name(assets: list, name: str) -> Optional[dict]:
    for a in assets:
        if a.get("name") == name:
            return a
    return None


# ─── Variant selection (S-REL.6 / S6.12) ──────────────────────────────────────

def _variant_names() -> List[str]:
    return [v["name"] for v in VARIANTS]


def _format_variants() -> str:
    lines = []
    for v in VARIANTS:
        label = v.get("label")
        lines.append(f"  - {v['name']}" + (f"  ({label})" if label else ""))
    return "\n".join(lines)


def _variant_marker_path(root: Path) -> Path:
    """Where the selected variant is remembered so `update` keeps the host's choice."""
    return root / "shared" / ".variant"


def _persist_variant(root: Path, variant: Optional[str]) -> None:
    if not variant:
        return
    marker = _variant_marker_path(root)
    _mkdir_secure(marker.parent)
    _atomic_write(marker, (variant + "\n").encode("utf-8"), 0o644)


def _installed_variant(root: Path) -> Optional[str]:
    """The variant recorded by the last install/update (None if single-asset / unset)."""
    marker = _variant_marker_path(root)
    if marker.exists():
        return marker.read_text(encoding="utf-8").strip() or None
    return None


def _select_variant(args: argparse.Namespace, root: Path) -> Optional[str]:
    """Resolve which per-interpreter variant to install/update (S6.12).

    Returns None for a single-asset release (VARIANTS empty). Otherwise, in priority order:
    an explicit --variant (validated); a variant
    remembered from a prior install (so `update` stays on the same interpreter); an
    interactive prompt on a TTY; else a fatal error listing the choices. No silent default.
    """
    if not VARIANTS:
        return None
    names = _variant_names()
    chosen = getattr(args, "variant", None)
    if chosen:
        if chosen not in names:
            fatal(f"Unknown --variant {chosen!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
        return chosen
    marker = _variant_marker_path(root)
    if marker.exists():
        prev = marker.read_text(encoding="utf-8").strip()
        if prev in names:
            info(f"Using previously selected variant: {_c('BLD', prev)}")
            return prev
    if sys.stdin.isatty():
        info("This release ships multiple variants — choose one:")
        for i, v in enumerate(VARIANTS, 1):
            label = v.get("label")
            print(f"  {i}) {v['name']}" + (f"  ({label})" if label else ""))
        raw = input("Variant [name or number]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(VARIANTS):
            return VARIANTS[int(raw) - 1]["name"]
        if raw in names:
            return raw
        fatal(f"Invalid selection {raw!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
    fatal(
        "This release ships multiple per-interpreter variants; none was selected.\n"
        f"Re-run with --variant NAME. Available variants:\n{_format_variants()}",
        EXIT_CONFIG,
    )
    return None  # unreachable (fatal raises)


# ─── Download (public or private) (S5) ────────────────────────────────────────

def _download_asset(tag: str, asset_name: str, dest: Path, token: Optional[str]) -> None:
    """Download a release asset — private path if token present, public URL otherwise."""
    if token:
        # Private path: resolve release → list assets → find by name → download by ID
        status, body = _gh_request(
            f"{RELEASES_API}/tags/{tag}", token=token
        )
        if status >= 400:
            fatal(f"Could not fetch release {tag} (HTTP {status})", EXIT_FAIL)
        try:
            rel = json.loads(body)
        except ValueError:
            fatal(f"Release {tag}: GitHub returned invalid JSON.", EXIT_FAIL)
        assets = rel.get("assets", []) if isinstance(rel, dict) else []
        asset = _find_asset_by_name(assets, asset_name)
        if asset is None:
            fatal(
                f"Asset {asset_name!r} not found in release {tag}. "
                f"Available: {[a.get('name') for a in assets]}",
                EXIT_FAIL,
            )
        # Download by asset ID — the token is never forwarded across the redirect (S5)
        asset_url = (
            f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/assets/{asset['id']}"
        )
        status, _ = _gh_request(asset_url, token=token, accept="application/octet-stream",
                                stream_to=dest, timeout=300, max_bytes=_MAX_DOWNLOAD_BYTES)
    else:
        url = (
            f"https://github.com/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/download/{tag}/{asset_name}"
        )
        status, _ = _gh_request(url, token=None, accept="application/octet-stream",
                                stream_to=dest, timeout=300, max_bytes=_MAX_DOWNLOAD_BYTES)
    if status != 200:
        fatal(f"Download of {asset_name} failed (HTTP {status}).", EXIT_FAIL)
    if not dest.exists() or dest.stat().st_size == 0:
        fatal(f"Download produced empty file: {dest}", EXIT_FAIL)


# ─── SHA256 + minisign verification (S4) ─────────────────────────────────────

def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _parse_sidecar(sidecar: Path, asset_name: str) -> str:
    """Strictly parse `<64 hex>[  <asset name>]` (one line); anything else is EXIT_FAIL."""
    try:
        text = sidecar.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        fatal(f"SHA256 sidecar {sidecar.name} is unreadable.", EXIT_FAIL)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    parts = lines[0].split() if len(lines) == 1 else []
    if len(parts) not in (1, 2) or not _SHA256_RE.fullmatch(parts[0].lower()):
        fatal(f"SHA256 sidecar {sidecar.name} is malformed: expected one line "
              "'<64 hex digits>  <file name>'.", EXIT_FAIL)
    if len(parts) == 2 and parts[1].lstrip("*") != asset_name:
        fatal(f"SHA256 sidecar names {parts[1]!r}, not {asset_name!r}.", EXIT_FAIL)
    return parts[0].lower()


def _verify_sha256(asset: Path, sidecar: Path) -> None:
    expected = _parse_sidecar(sidecar, asset.name)
    actual   = _sha256(asset)
    if actual != expected:
        fatal(
            f"SHA256 mismatch — refusing to extract.\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok("SHA256 checksum verified.")


def _verify_minisign(manifest: Path, sig: Path, pubkey: str, tag: str, digest: str) -> None:
    """Verify the manifest signature with the pinned key (`minisign -V -P KEY`).

    The signed trusted comment must also bind this project, this tag and this exact manifest
    digest (`project=<name> tag=<tag> manifest_sha256=<hex>`), so an old signed release cannot
    be replayed as a new one, nor another project's signed release as this project's.
    """
    cmd = ["minisign", "-V", "-m", str(manifest), "-x", str(sig), "-P", pubkey]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        fatal(
            f"minisign signature verification FAILED for {manifest.name}:\n"
            f"  {result.stderr.strip()}",
            EXIT_FAIL,
        )
    comment = ""
    for line in result.stdout.splitlines():
        if line.startswith("Trusted comment:"):
            comment = line[len("Trusted comment:"):].strip()
    fields = dict(tok.split("=", 1) for tok in comment.split() if "=" in tok)
    if (fields.get("project") != PROJECT_NAME or fields.get("tag") != tag
            or fields.get("manifest_sha256") != digest):
        fatal(
            "minisign trusted comment does not bind this release "
            f"(want project={PROJECT_NAME} tag={tag} manifest_sha256={digest}; "
            f"got {comment!r}).",
            EXIT_FAIL,
        )
    ok("Manifest signature verified (minisign).")


def download_and_verify(
    tag: str,
    workdir: Path,
    token: Optional[str],
    variant: Optional[str] = None,
) -> Path:
    """Download the bundle + sidecar and verify SHA256; return the bundle path.

    ``variant`` (S-REL.6) selects the per-interpreter asset ``<tag>-<variant>{suffix}``;
    ``None`` uses the single-asset name ``<tag>{suffix}``. The signature and manifest
    are verified separately, from the bundle bytes (`_verify_manifest`)."""
    asset_name   = f"{tag}-{variant}{ASSET_SUFFIX}" if variant else f"{tag}{ASSET_SUFFIX}"
    sidecar_name = f"{asset_name}.sha256"
    asset   = workdir / asset_name
    sidecar = workdir / sidecar_name

    info(f"Downloading {asset_name} ...")
    _download_asset(tag, asset_name, asset, token)

    info(f"Downloading {sidecar_name} ...")
    _download_asset(tag, sidecar_name, sidecar, token)

    info("Verifying SHA256 checksum ...")
    _verify_sha256(asset, sidecar)
    return asset


# ─── Bundle reading + the verified manifest (INS-01 / R5) ────────────────────

def _bundle_members(tf: tarfile.TarFile) -> List[Tuple[tarfile.TarInfo, str]]:
    """(member, path relative to the bundle's single top-level directory) for every
    member below it. Anything outside that one directory, or duplicated, is EXIT_FAIL."""
    members = tf.getmembers()
    if len(members) > _MAX_MEMBERS:
        fatal(f"Bundle has {len(members)} members; the limit is {_MAX_MEMBERS}.", EXIT_FAIL)
    declared = sum(m.size for m in members if m.isfile())
    if declared > _MAX_EXTRACT_BYTES:
        fatal(f"Bundle expands to {declared} bytes; the limit is {_MAX_EXTRACT_BYTES}.",
              EXIT_FAIL)
    tops = {Path(m.name).parts[0] for m in members if Path(m.name).parts}
    if len(tops) != 1:
        fatal(f"Bundle must have exactly one top-level directory; found {sorted(tops)}.",
              EXIT_FAIL)
    result: List[Tuple[tarfile.TarInfo, str]] = []
    seen = set()
    for m in members:
        parts = Path(m.name).parts
        if len(parts) < 2:
            if not m.isdir():
                fatal(f"Bundle member {m.name!r} sits outside the top-level directory.",
                      EXIT_FAIL)
            continue
        rel = str(Path(*parts[1:]))
        if rel in seen:
            fatal(f"Bundle contains {rel!r} more than once.", EXIT_FAIL)
        seen.add(rel)
        result.append((m, rel))
    return result


def _read_member(tf: tarfile.TarFile, member: tarfile.TarInfo, what: str) -> bytes:
    if not member.isfile() or member.size > _MAX_MANIFEST_BYTES:
        fatal(f"Bundle {what} is not a regular file of sane size.", EXIT_FAIL)
    handle = tf.extractfile(member)
    if handle is None:
        fatal(f"Bundle {what} is unreadable.", EXIT_FAIL)
    return handle.read()


def _read_bundle_manifest(bundle: Path) -> Tuple[bytes, Optional[bytes]]:
    """The manifest bytes (and signature bytes, if present) read straight from the bundle.
    These in-memory bytes are the ONLY manifest used after verification."""
    with tarfile.open(bundle, "r:xz") as tf:
        by_rel = {rel: m for m, rel in _bundle_members(tf)}
        if MANIFEST_NAME not in by_rel:
            fatal(f"Bundle does not contain {MANIFEST_NAME}; refusing to install.", EXIT_FAIL)
        manifest = _read_member(tf, by_rel[MANIFEST_NAME], MANIFEST_NAME)
        sig = None
        if SIGNATURE_NAME in by_rel:
            sig = _read_member(tf, by_rel[SIGNATURE_NAME], SIGNATURE_NAME)
    return manifest, sig


def _parse_manifest(data: bytes, tag: str) -> dict:
    """Parse + validate the manifest: unparseable / unknown schema / wrong tag => EXIT_FAIL."""
    try:
        manifest = json.loads(data.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        fatal(f"{MANIFEST_NAME} is not valid UTF-8 JSON; refusing to install.", EXIT_FAIL)
    if not isinstance(manifest, dict):
        fatal(f"{MANIFEST_NAME} must be a JSON object.", EXIT_FAIL)
    schema = manifest.get("schema_version")
    if isinstance(schema, bool) or schema != MANIFEST_SCHEMA:
        fatal(f"{MANIFEST_NAME} has unsupported schema_version {schema!r} "
              f"(this installer reads {MANIFEST_SCHEMA}).", EXIT_FAIL)
    if "tag" in manifest and manifest["tag"] != tag:
        fatal(f"{MANIFEST_NAME} is for tag {manifest['tag']!r}, not the requested {tag!r}.",
              EXIT_FAIL)
    bare = tag[len(TAG_PREFIX):]
    if "version" in manifest and manifest["version"] != bare:
        fatal(f"{MANIFEST_NAME} is for version {manifest['version']!r}, not {bare!r}.",
              EXIT_FAIL)
    return manifest


def _verify_manifest(
    manifest_bytes: bytes, sig_bytes: Optional[bytes], tag: str, workdir: Path,
) -> Tuple[dict, str]:
    """Signature (when a key is configured) + parse. Returns (manifest, sha256 hex)."""
    digest = hashlib.sha256(manifest_bytes).hexdigest()
    if MANIFEST_PUBKEY:
        if not sig_bytes:
            fatal(f"Bundle does not contain {SIGNATURE_NAME}; this project's releases "
                  "must be signed.", EXIT_FAIL)
        mpath, spath = workdir / "manifest.verify", workdir / "manifest.verify.minisig"
        mpath.write_bytes(manifest_bytes)
        spath.write_bytes(sig_bytes)
        info(f"Verifying {MANIFEST_NAME} with minisign ...")
        _verify_minisign(mpath, spath, MANIFEST_PUBKEY, tag, digest)
    else:
        info("This release is unsigned (no manifest_pubkey configured): integrity rests "
             "on HTTPS + the SHA256 sidecar + the manifest hashes. The sidecar and the "
             "manifest are served from the same origin as the bundle, so this detects "
             "corruption, NOT a compromised publisher or tampered release assets.")
    return _parse_manifest(manifest_bytes, tag), digest


def _hex_digest(value: object, what: str) -> str:
    if not isinstance(value, str) or not _SHA256_RE.fullmatch(value.lower()):
        fatal(f"{MANIFEST_NAME}: {what} has no valid sha256.", EXIT_FAIL)
    return value.lower()  # type: ignore[union-attr]


def _check_size(entry: dict, actual: int, what: str) -> None:
    if "size" in entry and (isinstance(entry["size"], bool) or entry["size"] != actual):
        fatal(f"{MANIFEST_NAME}: size mismatch for {what} "
              f"(manifest {entry['size']!r}, got {actual}).", EXIT_FAIL)


def _regular_file(path: Path, what: str) -> Path:
    if path.is_symlink() or not path.is_file():
        fatal(f"{what} is missing or not a regular file: {path}", EXIT_FAIL)
    return path


def _manifest_files(manifest: dict) -> dict:
    """The manifest `files` map: {normalised relative path: {sha256, size?}}; anything
    else (non-object, absolute/`..`/un-normalised keys) is EXIT_FAIL."""
    files = manifest.get("files", {})
    if not isinstance(files, dict):
        fatal(f"{MANIFEST_NAME}: 'files' must be an object.", EXIT_FAIL)
    for rel in files:
        if (not isinstance(rel, str) or not rel or rel.startswith("/")
                or posixpath.normpath(rel) != rel or rel in (".", "..")
                or rel.startswith("../") or "\0" in rel or "\\" in rel):
            fatal(f"{MANIFEST_NAME}: files key {rel!r} is not a normalised relative path.",
                  EXIT_FAIL)
    return files


def _preserved_link(tree: Path, root: Path, rel: str) -> bool:
    """True when `rel` is (inside) a PRESERVE_PATHS entry that this installer replaced with
    its own symlink into <root>/shared: the operator's copy, not the bundle's, so the
    manifest hash does not apply to it (R7 / S6.4)."""
    for keep in PRESERVE_PATHS:
        keep = posixpath.normpath(keep)
        if rel == keep or rel.startswith(keep + "/"):
            link = tree / keep
            if link.is_symlink() and Path(os.readlink(link)) == root / "shared" / keep:
                return True
    return False


def _verify_files(tree: Path, manifest: dict, root: Path) -> None:
    """Every manifest `files` entry must exist and match; the adapter MUST be covered.
    Preserved paths that point into <root>/shared are skipped (they are the operator's)."""
    files = _manifest_files(manifest)
    if ENTRYPOINT and ENTRYPOINT not in files:
        fatal(f"Adapter {ENTRYPOINT!r} is not covered by {MANIFEST_NAME} 'files'; "
              "refusing to run unhashed code as root.", EXIT_FAIL)
    for rel, entry in files.items():
        if not isinstance(entry, dict):
            fatal(f"{MANIFEST_NAME}: files[{rel!r}] must be an object.", EXIT_FAIL)
        expected = _hex_digest(entry.get("sha256"), f"files[{rel!r}]")
        if _preserved_link(tree, root, rel):
            continue
        path = _regular_file(tree / rel, f"Manifest file {rel!r}")
        _check_size(entry, path.stat().st_size, f"files[{rel!r}]")
        if _sha256(path) != expected:
            fatal(f"SHA256 mismatch for {rel!r} against {MANIFEST_NAME}.", EXIT_FAIL)


# ─── Extraction safety (S6.3) ─────────────────────────────────────────────────

_UNSAFE_TYPES = {tarfile.BLKTYPE, tarfile.CHRTYPE, tarfile.FIFOTYPE}


def _safe_member(member: tarfile.TarInfo, dest: Path) -> bool:
    """Return False (and warn) if member should be rejected (S6.3 safety rules)."""
    parts = Path(member.name).parts
    if member.name.startswith("/"):
        warn(f"Rejecting absolute path: {member.name}")
        return False
    if ".." in parts:
        warn(f"Rejecting path traversal: {member.name}")
        return False
    try:
        resolved = (dest / member.name).resolve()
        resolved.relative_to(dest.resolve())
    except ValueError:
        warn(f"Rejecting escape path: {member.name}")
        return False
    if member.type in _UNSAFE_TYPES:
        warn(f"Rejecting device/fifo node: {member.name}")
        return False
    if member.issym() or member.islnk():
        link_target = member.linkname or ""
        if link_target.startswith("/"):
            warn(f"Rejecting absolute symlink: {member.name} -> {link_target}")
            return False
        if ".." in Path(link_target).parts:
            warn(f"Rejecting traversal symlink: {member.name} -> {link_target}")
            return False
    return True


def _wheel_listed(rel: str) -> bool:
    """`rel` matches a WHEEL_SPECS glob (same number of path parts, each fnmatch'ed)."""
    parts = rel.split("/")
    for pattern, _dist in WHEEL_SPECS:
        globs = pattern.split("/")
        if len(globs) == len(parts) and all(
                fnmatch.fnmatchcase(p, g) for p, g in zip(parts, globs)):
            return True
    return False


def _link_target_rel(m: tarfile.TarInfo, rel: str, top: str) -> Optional[str]:
    """The bundle-relative path a symlink/hardlink member points at (None if it escapes)."""
    if m.issym():
        target = posixpath.normpath(posixpath.join(posixpath.dirname(rel), m.linkname))
    else:  # hardlink: linkname is a path in the archive, below the top-level dir
        parts = Path(m.linkname).parts
        if not parts or parts[0] != top:
            return None
        target = str(Path(*parts[1:])) if len(parts) > 1 else ""
    if not target or target == "." or target.startswith("../") or target.startswith("/"):
        return None
    return target


def _pre_scan_members(
    tf: tarfile.TarFile, dest: Path, files: Optional[dict] = None,
) -> List[tarfile.TarInfo]:
    """Strip the top-level dir, drop the manifest/signature (kept separately, verified),
    and refuse the whole bundle if any member is unsafe or UNLISTED (fail closed).

    Every non-directory member must be a key of manifest `files` or match a WHEEL_SPECS
    glob (so it is hashed); a symlink/hardlink is only allowed when its target is a listed
    file. `files=None` skips the coverage rule (extension/legacy callers)."""
    import copy as _copy
    members = []
    for member, rel in _bundle_members(tf):
        if rel in (MANIFEST_NAME, SIGNATURE_NAME):
            continue
        m = _copy.copy(member)
        m.name = rel
        if not _safe_member(m, dest):
            fatal(f"Bundle member {member.name!r} is unsafe; refusing to extract.", EXIT_FAIL)
        if files is not None and not m.isdir():
            if m.issym() or m.islnk():
                top = Path(member.name).parts[0]
                target = _link_target_rel(m, rel, top)
                if target is None or target not in files:
                    fatal(f"Bundle link {rel!r} -> {m.linkname!r} does not point at a file "
                          f"listed in {MANIFEST_NAME}; refusing to extract.", EXIT_FAIL)
                if m.islnk():
                    m.linkname = target  # relative to the extraction root, like m.name
            elif not m.isfile():
                fatal(f"Bundle member {rel!r} has an unsupported type; refusing to extract.",
                      EXIT_FAIL)
            elif rel not in files and not _wheel_listed(rel):
                fatal(f"Bundle member {rel!r} is not covered by {MANIFEST_NAME} 'files' "
                      "(and is not a declared wheel); refusing to install unhashed content.",
                      EXIT_FAIL)
        members.append(m)
    return members


def _strip_privileges(m: tarfile.TarInfo) -> tarfile.TarInfo:
    """What `filter='data'` does for the cases that matter to a root install, for Pythons
    that lack it: no setuid/setgid/sticky, no group/other write, the archive's owner and
    group ignored (extracted files belong to the installing user)."""
    m.mode = (m.mode & 0o755)
    m.uid, m.gid = _expected_owner(), os.getegid()
    m.uname = m.gname = ""
    return m


def _extract_bundle(bundle: Path, tree: Path, manifest: Optional[dict] = None) -> None:
    """Extract the bundle into the release tree: coverage + safety pre-scan, then
    `filter='data'` (or the manual equivalent on Pythons without `tarfile.data_filter`)."""
    files = _manifest_files(manifest) if manifest is not None else None
    tree.mkdir(parents=True, exist_ok=True)
    info(f"Extracting to {tree} ...")
    with tarfile.open(bundle, "r:xz") as tf:
        members = _pre_scan_members(tf, tree, files)
        kw: dict = {}
        if hasattr(tarfile, "data_filter"):
            kw["filter"] = "data"
        else:
            members = [_strip_privileges(m) for m in members]
        try:
            tf.extractall(tree, members=members, **kw)
        except (tarfile.TarError, OSError, KeyError) as exc:
            fatal(f"Extraction failed: {exc}", EXIT_FAIL)
    ok("Extraction complete.")


# ─── Wheels: hash-locked, offline install into the release's own venv (R9) ───

def _canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _wheel_order() -> List[Tuple[str, str]]:
    """WHEEL_SPECS with cli-extended first (KI-51), the rest in declared order
    (dependencies before the tool wheels)."""
    first = [s for s in WHEEL_SPECS if _canon(s[1]) == "cli-extended"]
    return first + [s for s in WHEEL_SPECS if _canon(s[1]) != "cli-extended"]


def _wheel_version(wheel: Path) -> str:
    """The version field of a wheel file name; it goes into the hash lock, so it must be a
    plain version string (no spaces, `;`, `@`, newlines or option-looking text)."""
    parts = wheel.name[:-len(".whl")].split("-")
    if len(parts) < 5 or not _WHEEL_VERSION_RE.fullmatch(parts[1]):
        fatal(f"Not a valid wheel file name: {wheel.name}", EXIT_FAIL)
    return parts[1]


def _verify_wheel_sha256(wheel_path: Path, manifest: dict, distribution: str) -> str:
    """Check the wheel against manifest[distribution] (SPEC B Seam-3): a missing entry,
    a missing/invalid sha256, a wrong file name or a size/hash mismatch is EXIT_FAIL.
    Returns the expected sha256."""
    entry = manifest.get(distribution)
    if not isinstance(entry, dict):
        fatal(f"{MANIFEST_NAME} has no entry for distribution {distribution!r}.", EXIT_FAIL)
    expected = _hex_digest(entry.get("sha256"), f"distribution {distribution!r}")
    if "wheel" in entry and entry["wheel"] != wheel_path.name:
        fatal(f"{MANIFEST_NAME} lists wheel {entry['wheel']!r} for {distribution!r}, "
              f"bundle has {wheel_path.name!r}.", EXIT_FAIL)
    _check_size(entry, wheel_path.stat().st_size, f"distribution {distribution!r}")
    actual = _sha256(wheel_path)
    if actual != expected:
        fatal(
            f"Wheel SHA256 mismatch for {wheel_path.name} (distribution: {distribution!r}):\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok(f"Wheel {wheel_path.name} ({distribution}) sha256 verified.")
    return expected


def _check_venv_prereqs() -> None:
    """`python3 -m venv` needs ensurepip (Debian: the python3-venv package)."""
    try:
        import venv  # noqa: F401
        import ensurepip  # noqa: F401
    except ImportError:
        fatal("Python's venv/ensurepip modules are missing. Install the python3-venv "
              "package (Debian/Ubuntu: apt install python3-venv) and re-run.", EXIT_PREREQ)


def _pip_env() -> Dict[str, str]:
    """No `PIP_*` from the caller, and no global/site pip config either: `--isolated` leaves
    pip's "global" scope (/etc/pip.conf, $XDG_CONFIG_DIRS) enabled, `PIP_CONFIG_FILE=os.devnull`
    disables every config file."""
    env = {k: v for k, v in os.environ.items() if not k.startswith("PIP_")}
    env["PIP_CONFIG_FILE"] = os.devnull
    return env


def _run_checked(cmd: List[str], what: str) -> None:
    result = subprocess.run(cmd, env=_pip_env(), capture_output=True, text=True)
    if result.returncode != 0:
        fatal(f"{what} failed (exit {result.returncode}):\n"
              f"{(result.stdout + result.stderr).strip()}", EXIT_FAIL)


def _install_wheels(tree: Path, release: Path, manifest: dict) -> None:
    """Build <release>/venv from <release>/wheelhouse only: verified wheels, a lock of
    `name==version --hash=sha256:...`, `pip install --isolated --no-index --require-hashes`,
    then `pip check`."""
    if not WHEEL_SPECS:
        return
    wheelhouse = release / "wheelhouse"
    wheelhouse.mkdir()
    lock_lines: List[str] = []
    for glob_pat, distribution in _wheel_order():
        matches = sorted(tree.glob(glob_pat))
        if len(matches) != 1:
            fatal(
                f"Expected exactly one wheel in the bundle for {distribution!r} "
                f"(glob: {glob_pat!r}); found {len(matches)}.",
                EXIT_FAIL,
            )
        wheel = _regular_file(matches[0], f"Wheel for {distribution!r}")
        digest = _verify_wheel_sha256(wheel, manifest, distribution)
        shutil.copy2(wheel, wheelhouse / wheel.name)
        lock_lines.append(f"{distribution}=={_wheel_version(wheel)} --hash=sha256:{digest}")
    lock = release / "requirements.lock"
    lock.write_text("\n".join(lock_lines) + "\n", encoding="utf-8")

    venv_dir = release / "venv"
    info(f"Setting up private venv at {venv_dir} ...")
    _run_checked([sys.executable, "-m", "venv", str(venv_dir)], "venv creation")
    py = str(venv_dir / "bin" / "python")
    info("Installing hash-locked wheels (offline, --no-index) ...")
    _run_checked(
        [py, "-m", "pip", "install", "--isolated", "--disable-pip-version-check",
         "--no-index", "--find-links", str(wheelhouse), "--require-hashes", "-r", str(lock)],
        "pip install",
    )
    _run_checked([py, "-m", "pip", "check", "--isolated", "--disable-pip-version-check"],
                 "pip check")
    ok(f"Installed {len(lock_lines)} wheel(s).")


# ─── Atomic file helpers ──────────────────────────────────────────────────────

def _fsync_dir(path: Path) -> None:
    fd = os.open(str(path), os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _atomic_write(path: Path, data: bytes, mode: int = 0o644) -> None:
    """Write `data` to `path` atomically (temp file in the same dir, fsync, rename)."""
    tmp = path.with_name(f".{path.name}.tmp")
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
    fd = os.open(str(tmp), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
    except BaseException:
        tmp.unlink()
        raise
    os.replace(tmp, path)
    _fsync_dir(path.parent)


# ─── Root-directory ownership (root runs code from <root>) ───────────────────

def _expected_owner() -> int:
    """The uid that must own <root> and its subdirectories (the effective uid)."""
    return os.geteuid()


def _check_dir(path: Path, what: str) -> None:
    """As root: `path` must be a real directory (not a symlink), owned by the effective
    uid and not group/world-writable, else EXIT_FAIL. A no-op for unprivileged runs."""
    if os.geteuid() != 0:
        return
    st = os.lstat(path)
    if stat.S_ISLNK(st.st_mode) or not stat.S_ISDIR(st.st_mode):
        fatal(f"{what} {path} is not a real directory (symlink or file); refusing to "
              "install as root through it.", EXIT_FAIL)
    if st.st_uid != _expected_owner():
        fatal(f"{what} {path} is owned by uid {st.st_uid}, not {_expected_owner()}; "
              "refusing to install as root.", EXIT_FAIL)
    if st.st_mode & 0o022:
        fatal(f"{what} {path} is group- or world-writable ({oct(st.st_mode & 0o777)}); "
              "refusing to install as root. chmod go-w it.", EXIT_FAIL)


def _mkdir_secure(path: Path) -> None:
    """Create `path` (0755) if missing and run `_check_dir` on it."""
    try:
        os.mkdir(path, 0o755)
    except FileExistsError:
        pass
    _check_dir(path, "Install directory")


def _check_layout(root: Path) -> None:
    """Re-check <root> and the subdirectories that already exist (before anything is
    written through them)."""
    if os.path.lexists(root):
        _check_dir(root, "Install root")
    for name in ("releases", "shared", "bin"):
        if os.path.lexists(root / name):
            _check_dir(root / name, f"Install subdirectory {name!r}")


# ─── Adapter invocation (Seam 1 — S3.3) ──────────────────────────────────────

def _layout(release: Path, legacy: bool = False) -> Tuple[Path, Path, Path]:
    """(tree, venv_dir, manifest path) of a release directory."""
    if legacy:  # pre-W1 layout: content at the release root, one shared <root>/venv
        return release, release.parent.parent / "venv", release / MANIFEST_NAME
    return release / "tree", release / "venv", release / MANIFEST_NAME


def _python_for(venv_dir: Path) -> str:
    return str(venv_dir / "bin" / "python") if WHEEL_SPECS else sys.executable


def _invoke_adapter(
    action: str,
    release_dir: Path,
    root: Path,
    venv_dir: Path,
    token: Optional[str] = None,
    manifest_path: Optional[Path] = None,
    config_path: Optional[Path] = None,
) -> None:
    """Invoke project adapter; non-zero exit aborts before the current swap (S3.3).

    ``release_dir`` is the content root (the release's ``tree/``)."""
    if not ENTRYPOINT:
        return  # no adapter (tls-edge minimal path)
    adapter = release_dir / ENTRYPOINT
    if not adapter.exists():
        fatal(f"Adapter entrypoint not found: {adapter}", EXIT_FAIL)
    cmd = [
        _python_for(venv_dir), str(adapter), action,
        "--release-root", str(release_dir),
        "--config", str(config_path or root / "shared" / "host.toml"),
        "--manifest", str(manifest_path or release_dir.parent / MANIFEST_NAME),
    ]
    info(f"Invoking adapter: {action} ...")
    # Strip GitHub token from child environment (S5)
    child_env = {
        k: v for k, v in os.environ.items()
        if k not in ("GITHUB_TOKEN", "CMRU_GITHUB_TOKEN", "GITHUB_PUSH_PAT")
    }
    result = subprocess.run(cmd, env=child_env)
    if result.returncode != 0:
        fatal(
            f"Adapter exited {result.returncode} (action={action!r}); "
            "transaction aborted — current release unchanged.",
            EXIT_FAIL,
        )
    ok(f"Adapter {action} succeeded.")


# ─── Preserve / shared config (S3.2) ─────────────────────────────────────────

def _copy_preserve_to_shared(root: Path, src_release: Optional[Path] = None) -> None:
    """Copy preserved paths from the current release tree into <root>/shared/."""
    shared = root / "shared"
    source = src_release
    if source is None:
        state = _read_state(root)
        if state:
            source = _layout(_release_dir(root, state["current"]["name"]),
                             bool(state.get("legacy")))[0]
    if source is None or not source.is_dir():
        return
    for rel in PRESERVE_PATHS:
        src = source / rel
        dest = shared / rel
        if src.exists() and not src.is_symlink():
            _mkdir_secure(shared)
            dest.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(src, dest)
            else:
                shutil.copy2(src, dest)
            ok(f"Preserved: {rel}")


def _restore_preserve_from_shared(root: Path, release_dir: Path) -> None:
    """Symlink preserved paths from shared/ into the new release tree."""
    shared = root / "shared"
    for rel in PRESERVE_PATHS:
        src = shared / rel
        if src.exists():
            dest = release_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.exists() or dest.is_symlink():
                if dest.is_dir() and not dest.is_symlink():
                    shutil.rmtree(dest)
                else:
                    dest.unlink()
            dest.symlink_to(src)
            ok(f"Linked shared/{rel} into release.")


def _install_host_config(root: Path, source: Path) -> None:
    """`--config FILE` => <root>/shared/host.toml, mode 0600, written atomically."""
    shared = root / "shared"
    _mkdir_secure(shared)
    _atomic_write(shared / "host.toml", source.read_bytes(), 0o600)
    ok(f"Host config installed at {shared / 'host.toml'} (0600).")


def _check_config_arg(args: argparse.Namespace) -> Optional[Path]:
    given = getattr(args, "config", None)
    if not given:
        return None
    path = Path(given).expanduser()
    if not path.is_file():
        fatal(f"--config file not found or not a regular file: {path}", EXIT_CONFIG)
    return path


# ─── Scope resolution (S3.2) ─────────────────────────────────────────────────

def _root_dir(scope: str) -> Path:
    if scope == "system":
        return Path(INSTALL_DIR_SYSTEM)
    xdg = os.environ.get("XDG_DATA_HOME", "").strip()
    base = Path(xdg) if xdg else Path.home() / ".local" / "share"
    return base / INSTALL_DIR_USER


# ─── Exclusive lock + SIGINT/SIGTERM handler ─────────────────────────────────

_active_staging: Optional[Path] = None
_lock_fd: Optional[int] = None


def _cleanup_on_signal(sig: int, _frame: object) -> None:
    global _active_staging, _lock_fd
    staging = _active_staging
    if staging and staging.exists():
        # never remove a release that has become `current` (a signal landing around the swap)
        live = staging.parent.parent / "current"
        if not (live.is_symlink() and live.resolve() == staging.resolve()):
            shutil.rmtree(staging, ignore_errors=True)
    if _lock_fd is not None:
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
        except OSError:
            pass
    sys.exit(EXIT_FAIL)


signal.signal(signal.SIGINT, _cleanup_on_signal)
signal.signal(signal.SIGTERM, _cleanup_on_signal)


class _Lock:
    def __init__(self, root: Path) -> None:
        self._path = root / ".lock"

    def __enter__(self) -> "_Lock":
        global _lock_fd
        root = self._path.parent
        root.parent.mkdir(parents=True, exist_ok=True)
        _mkdir_secure(root)
        _check_layout(root)
        try:
            _lock_fd = os.open(str(self._path),
                               os.O_CREAT | os.O_WRONLY | os.O_NOFOLLOW, 0o600)
        except OSError as exc:  # ELOOP: .lock is a symlink
            fatal(f"Cannot open the lock file {self._path} ({exc.strerror}); "
                  "refusing to follow it.", EXIT_FAIL)
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            info("Another installer is running; waiting for lock ...")
            fcntl.flock(_lock_fd, fcntl.LOCK_EX)
        return self

    def __exit__(self, *_: object) -> None:
        global _lock_fd
        if _lock_fd is not None:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
            _lock_fd = None


# ─── Releases, state, rollback (R7) ───────────────────────────────────────────
#
# <root>/releases/<tag>-<manifest12>[-<variant>]/
#     tree/  venv/  wheelhouse/  requirements.lock  manifest.json [manifest.json.minisig]
#     release.json  .complete     (.incomplete while being built; .complete is written last)
# <root>/current  -> releases/<name>            (atomic symlink swap)
# <root>/state.json  {schema, current, previous, history}   (atomic write)
# <root>/bin/<cmd> -> ../current/venv/bin/<cmd>

def _release_dir(root: Path, name: str) -> Path:
    if not isinstance(name, str) or not _NAME_RE.fullmatch(name) or ".." in name:
        fatal(f"state.json names an invalid release {name!r}; refusing.", EXIT_FAIL)
    return root / "releases" / name


def _release_name(tag: str, digest: str, variant: Optional[str]) -> str:
    return f"{tag}-{digest[:12]}" + (f"-{variant}" if variant else "")


def _entry_of(release: Path) -> dict:
    try:
        entry = json.loads((release / "release.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        fatal(f"{release.name}: release.json is missing or invalid.", EXIT_FAIL)
    if not isinstance(entry, dict) or entry.get("name") != release.name:
        fatal(f"{release.name}: release.json does not describe this release.", EXIT_FAIL)
    return entry


def _read_state(root: Path, repair: bool = True) -> Optional[dict]:
    """The install state, or None when nothing is installed.

    * a pre-W1 install (a `current` symlink, no state.json) is returned as a synthetic
      state with `legacy: True` — the next install/update migrates it;
    * a `current` symlink that disagrees with state.json (crash between the swap and
      the state write) is reconciled from the target's own release.json; so is a
      complete new-layout release with no state.json at all (a fresh install that died
      between the swap and the state write);
    * `repair=False` (the read-only `status`) reconciles in memory and writes nothing."""
    state_path = root / "state.json"
    current = root / "current"
    target = current.resolve() if current.is_symlink() else None
    if not state_path.exists():
        if target is not None and target.is_dir():
            if (target / ".complete").is_file() and (target / "release.json").is_file():
                state = {"schema": 1, "current": _entry_of(target), "previous": None,
                         "history": []}
                warn(f"state.json is missing but {current} points at the complete release "
                     f"{target.name}; reconciling.")
                if repair:
                    _write_state(root, state)
                return state
            return {"schema": 1, "legacy": True, "previous": None, "history": [],
                    "current": {"name": target.name, "tag": target.name,
                                "manifest_sha256": None, "variant": _installed_variant(root)}}
        return None
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
        cur = state["current"]
        assert isinstance(cur["name"], str) and isinstance(cur["tag"], str)
        assert isinstance(state.get("history", []), list)
    except (OSError, ValueError, KeyError, TypeError, AssertionError):
        fatal(f"{state_path} is unreadable or malformed; refusing to touch the install.",
              EXIT_FAIL)
    if target is None or not target.is_dir():
        fatal(f"state.json records {cur['name']!r} but {current} is missing or dangling.",
              EXIT_FAIL)
    if target.name != cur["name"]:
        if not (target / ".complete").exists():
            fatal(f"{current} points at {target.name!r}, which is not a complete release.",
                  EXIT_FAIL)
        warn(f"state.json was behind {current} (interrupted run); reconciling to {target.name}.")
        state = {"schema": 1, "current": _entry_of(target), "previous": cur,
                 "history": list(state.get("history", [])) + [cur]}
        if repair:
            _write_state(root, state)
    return state


def _write_state(root: Path, state: dict) -> None:
    state = dict(state, schema=1)
    state["history"] = list(state.get("history", []))[-20:]
    _atomic_write(root / "state.json",
                  (json.dumps(state, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def _current_version(root: Path) -> Optional[str]:
    """The installed release tag, or None."""
    state = _read_state(root)
    return state["current"]["tag"] if state else None


def _atomic_swap_current(root: Path, new_release: Path) -> None:
    """Atomic current swap: tmp symlink + os.replace (S6.3)."""
    current = root / "current"
    tmp_link = root / ".current.tmp"
    if tmp_link.is_symlink():
        tmp_link.unlink()
    os.symlink(os.path.relpath(new_release, root), tmp_link)
    os.replace(tmp_link, current)
    ok(f"current -> {new_release.name}")


def _prune_releases(root: Path, state: Optional[dict]) -> None:
    """Delete every release dir except current and previous (this also cleans `.incomplete`
    and any leftover pre-W1 content); never touches what `current` points at."""
    releases = root / "releases"
    if not releases.is_dir():
        return
    keep = set()
    if state:
        keep.add(state["current"]["name"])
        if state.get("previous"):
            keep.add(state["previous"]["name"])
    cur = root / "current"
    if cur.is_symlink():
        keep.add(cur.resolve().name)
    for entry in sorted(releases.iterdir()):
        if entry.name in keep:
            continue
        info(f"Pruning release: {entry.name}")
        if entry.is_dir() and not entry.is_symlink():
            shutil.rmtree(entry, ignore_errors=True)
        else:
            entry.unlink()
    legacy_venv = root / "venv"
    if state and not state.get("legacy") and legacy_venv.is_dir() and not legacy_venv.is_symlink():
        info("Removing the pre-W1 shared venv.")
        shutil.rmtree(legacy_venv, ignore_errors=True)


def _discard_release(root: Path, release: Path) -> None:
    """Remove a release this run created, and `releases/` itself if that leaves it empty."""
    shutil.rmtree(release, ignore_errors=True)
    try:
        (root / "releases").rmdir()
    except OSError:
        pass


def _write_launchers(root: Path) -> None:
    """<root>/bin/<cmd> -> ../current/venv/bin/<cmd> (atomic per launcher)."""
    if not LAUNCHERS:
        return
    bindir = root / "bin"
    _mkdir_secure(bindir)
    for cmd in LAUNCHERS:
        tmp = bindir / f".{cmd}.tmp"
        if tmp.is_symlink():
            tmp.unlink()
        os.symlink(f"../current/venv/bin/{cmd}", tmp)
        os.replace(tmp, bindir / cmd)
        ok(f"Launcher: {bindir / cmd}")


def _verify_release_intact(root: Path, entry: dict) -> Path:
    """Re-verify a recorded release before it is (re-)used: complete marker, the recorded
    manifest digest, the signature (when a key is configured) and the adapter hash."""
    release = _release_dir(root, entry["name"])
    if not (release / ".complete").is_file():
        fatal(f"Release {entry['name']} is not complete; refusing to use it.", EXIT_FAIL)
    manifest_path = _regular_file(release / MANIFEST_NAME, f"{entry['name']} manifest")
    manifest_bytes = manifest_path.read_bytes()
    digest = hashlib.sha256(manifest_bytes).hexdigest()
    if digest != entry.get("manifest_sha256"):
        fatal(f"Release {entry['name']}: recorded manifest digest does not match "
              "the manifest on disk.", EXIT_FAIL)
    sig_bytes = None
    if MANIFEST_PUBKEY:
        sig_bytes = _regular_file(release / SIGNATURE_NAME, f"{entry['name']} signature").read_bytes()
    with tempfile.TemporaryDirectory() as tmp:
        manifest, _ = _verify_manifest(manifest_bytes, sig_bytes, entry["tag"], Path(tmp))
    _verify_files(release / "tree", manifest, root)
    return release


def _build_release(
    root: Path, release: Path, bundle: Path, manifest_bytes: bytes,
    sig_bytes: Optional[bytes], manifest: dict, entry: dict,
) -> None:
    """Create the release at its final path, `.incomplete` until everything succeeded."""
    release.mkdir(parents=True)
    (release / ".incomplete").write_text("", encoding="utf-8")
    tree = release / "tree"
    _extract_bundle(bundle, tree, manifest)
    _atomic_write(release / MANIFEST_NAME, manifest_bytes)
    if sig_bytes is not None and MANIFEST_PUBKEY:
        _atomic_write(release / SIGNATURE_NAME, sig_bytes)
    _verify_files(tree, manifest, root)
    _restore_preserve_from_shared(root, tree)
    _install_wheels(tree, release, manifest)
    for cmd in LAUNCHERS:
        if not (release / "venv" / "bin" / cmd).exists():
            fatal(f"Launcher {cmd!r} is not provided by this release's venv.", EXIT_FAIL)
    _atomic_write(release / "release.json",
                  (json.dumps(entry, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def _commit_release(
    root: Path, release: Path, state: Optional[dict], entry: dict, action: str,
    token: Optional[str], config_arg: Optional[Path], fresh: bool,
) -> None:
    """Adapter, `.complete`, swap, state. Any failure before the swap removes a release
    that this run created (never a pre-existing, verified one)."""
    global _active_staging
    tree, venv_dir, manifest_path = _layout(release)
    try:
        _invoke_adapter(action, tree, root, venv_dir, token,
                        manifest_path=manifest_path, config_path=config_arg)
        if fresh:
            (release / ".complete").write_text("", encoding="utf-8")
            (release / ".incomplete").unlink()
        # From here the release may become `current`: the signal handler must not rmtree it.
        _active_staging = None
        _atomic_swap_current(root, release)
    except BaseException:
        if fresh:
            _discard_release(root, release)
        _active_staging = None
        raise
    _active_staging = None
    # A pre-W1 (legacy) current has no per-release venv or digest: it is not a rollback
    # target, so it becomes neither `previous` nor history.
    old = state["current"] if state and not state.get("legacy") else None
    history = list(state.get("history", [])) if old else []
    previous = old
    if old and old["name"] == entry["name"]:
        previous = state.get("previous")
    elif old:
        history.append(old)
    _write_state(root, {"current": entry, "previous": previous, "history": history})
    _persist_variant(root, entry.get("variant"))


def _transact(args: argparse.Namespace, token: Optional[str], root: Path, install: bool) -> None:
    """The one install/update transaction (called with the exclusive lock held)."""
    global _active_staging
    state = _read_state(root)
    if install and state is not None:
        warn(f"Existing install found ({state['current']['tag']}). Running update instead.")
    if not install and state is None:
        fatal(f"No install found at {root}. Run 'python3 get.py install' first.", EXIT_FAIL)
    legacy = bool(state and state.get("legacy"))
    if not legacy:
        # crash recovery: `.incomplete` dirs from a dead run. NEVER for a pre-W1 install:
        # its old releases (the old installer's rollback targets) must survive until the
        # new release is live and swapped in; the end-of-transaction prune removes them.
        _prune_releases(root, state)
    config_arg = _check_config_arg(args)

    tag = _resolve_tag(args, token)
    variant = _select_variant(args, root)
    if variant:
        info(f"Variant: {_c('BLD', variant)}")

    if state and not legacy:
        cur = state["current"]
        if cur["tag"] != tag:
            older = _semver_key(tag) < _semver_key(cur["tag"])
            if older and getattr(args, "version", None) is None:
                fatal(f"Refusing to downgrade {cur['tag']} -> {tag} (the latest release "
                      f"is older than the installed one). Pass --version {tag} to do "
                      "it deliberately.", EXIT_FAIL)
            if older:
                warn(f"Downgrade: installing {tag}, older than the installed {cur['tag']}.")
        if cur["tag"] == tag and cur.get("variant") == variant:
            _verify_release_intact(root, cur)
            if config_arg:
                _install_host_config(root, config_arg)
            _write_launchers(root)
            ok(f"Already at {tag}. Nothing to do (recorded manifest re-verified).")
            return
    if legacy:
        warn("Existing install uses the pre-W1 layout; migrating (current is swapped "
             "atomically; the old release dir and shared venv are removed afterwards).")

    with tempfile.TemporaryDirectory() as tmp:
        bundle = download_and_verify(tag, Path(tmp), token, variant)
        manifest_bytes, sig_bytes = _read_bundle_manifest(bundle)
        manifest, digest = _verify_manifest(manifest_bytes, sig_bytes, tag, Path(tmp))
        name = _release_name(tag, digest, variant)
        entry = {"name": name, "tag": tag, "variant": variant, "manifest_sha256": digest}
        release = _release_dir(root, name)
        if state is not None:
            _copy_preserve_to_shared(root)
        fresh = not release.exists()
        if fresh:
            _active_staging = release
            _mkdir_secure(root / "releases")
            try:
                _build_release(root, release, bundle, manifest_bytes, sig_bytes, manifest, entry)
            except BaseException:
                _discard_release(root, release)
                _active_staging = None
                raise
        else:
            info(f"Re-using verified release {name}.")
            _verify_release_intact(root, entry)
        _commit_release(root, release, state, entry, "apply" if state else "bootstrap",
                        token, config_arg, fresh)
    if config_arg:
        _install_host_config(root, config_arg)
    _write_launchers(root)
    _prune_releases(root, _read_state(root))


# ─── Commands ────────────────────────────────────────────────────────────────

def _preflight(root: Path, scope: str, verb: str) -> None:
    """Everything that must hold before any network I/O or state change."""
    if scope == "system" and os.geteuid() != 0:
        fatal(f"system-scope {verb} requires root (sudo).", EXIT_PREREQ)
    if MANIFEST_PUBKEY and not shutil.which("minisign"):
        fatal("This project's releases are signed and `minisign` is not installed. "
              "Install the minisign package (Debian/Ubuntu: apt install minisign) "
              "and re-run.", EXIT_PREREQ)
    if WHEEL_SPECS:
        _check_venv_prereqs()


def do_install(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    hr()
    print(f"  {_c('BLD', 'ciu')}  install  scope={scope}  root={root}")
    hr()

    _preflight(root, scope, "install")
    with _Lock(root):
        _transact(args, token, root, install=True)

    hr()
    ok(f"ciu {_current_version(root)} installed at {root}")
    print()


def do_update(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    _preflight(root, scope, "update")
    with _Lock(root):
        _transact(args, token, root, install=False)

    ok(f"Updated to {_current_version(root)}.")
    print()


def do_rollback(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    _preflight(root, scope, "rollback")
    with _Lock(root):
        state = _read_state(root)
        if state is None:
            fatal(f"No install found at {root}.", EXIT_FAIL)
        if state.get("legacy"):
            fatal("This install uses the pre-W1 layout and has no recorded previous "
                  "release: the pre-migration layout is not a rollback target; run "
                  "'python3 get.py update' once to migrate it (the first update after "
                  "migration creates a rollback target).", EXIT_FAIL)
        wanted = getattr(args, "version", None)
        if wanted is not None:
            tag = _validate_tag(normalize_tag(wanted))
            pool = ([state["previous"]] if state.get("previous") else []) \
                + list(reversed(state.get("history", [])))
            target = next((e for e in pool if e["tag"] == tag
                           and e["name"] != state["current"]["name"]
                           and (_release_dir(root, e["name"]) / ".complete").exists()), None)
            if target is None:
                fatal(f"No complete recorded release for {tag} to roll back to.", EXIT_FAIL)
        else:
            target = state.get("previous")
            if target is None:
                fatal("No previous release to roll back to: the install has only one "
                      "release (a fresh install, or one just migrated from the pre-W1 "
                      "layout). The pre-migration layout is not a rollback target; the "
                      "first update after migration creates one.", EXIT_FAIL)

        info(f"Rolling back to {target['tag']} ({target['name']}) ...")
        release = _verify_release_intact(root, target)
        tree, venv_dir, manifest_path = _layout(release)
        _invoke_adapter("rollback", tree, root, venv_dir, token, manifest_path=manifest_path)
        old = state["current"]
        _atomic_swap_current(root, release)
        _write_state(root, {"current": target, "previous": old,
                            "history": list(state.get("history", [])) + [old]})
        _persist_variant(root, target.get("variant"))
        _write_launchers(root)
        _prune_releases(root, _read_state(root))
    ok(f"Rolled back to {target['tag']}.")


def do_status(args: argparse.Namespace) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    state = _read_state(root, repair=False)  # status never writes
    if state is None:
        print(f"ciu: not installed at {root}")
        return

    cur = state["current"]
    legacy = bool(state.get("legacy"))
    print(f"ciu status  scope={scope}  root={root}")
    print(f"  current:  {cur['tag']}" + ("  (pre-W1 layout; run update to migrate)" if legacy else ""))
    if not legacy:
        print(f"  release:  {cur['name']}  manifest sha256 {cur['manifest_sha256'][:12]}")
        print(f"  signed:   {'yes (minisign)' if MANIFEST_PUBKEY else 'no (SHA256 only)'}")
    if state.get("previous"):
        print(f"  previous: {state['previous']['tag']}")

    if ENTRYPOINT:
        release = _release_dir(root, cur["name"])
        tree, venv_dir, manifest_path = _layout(release, legacy)
        cmd = [
            _python_for(venv_dir), str(tree / ENTRYPOINT), "health",
            "--release-root", str(tree),
            "--config", str(root / "shared" / "host.toml"),
            "--manifest", str(manifest_path),
        ]
        result = subprocess.run(cmd)
        if result.returncode == 0:
            ok("health check passed.")
        else:
            warn(f"health check exited {result.returncode}.")


# --- extension: installer/enroll.py sha256=7259537f95c516887f8f21263ccac47e1c449f7621b96e01d1ca94e6f50c342f ---
# ciu-owned host-enrollment fragment (CIU S14.7 / KI-24).
#
# This file is RENDER INPUT, not an importable module: cmru's `[project.installer]
# extensions` mechanism inlines it verbatim into `ciu/get.py` at the
# `# @@EXTENSIONS@@` marker (cmru W1-CIU-ENROLL, decision O4). It is not shipped
# in the ciu wheel (see ciu/pyproject.toml: only `src/` is a package root).
#
# It may use only the template names listed in the rendered file's
# `EXTENSION_API` tuple plus the standard library; cmru checks that at render
# time. `ciu` is a cmru template placeholder, replaced after
# inlining.
#
# Hardening of this code (KI-49 / KI-50) is tracked as CIU-122 / CIU-123 in
# ciu/KNOWN_ISSUES_TODO_BACKLOG.md; the code below is the pre-move behaviour,
# moved unchanged.
import argparse
import glob as _glob
import grp
import os
import pwd
import re
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional, Tuple


# ─── Host enrollment helpers (CIU S14.7 / cmru KI-24) ────────────────────────
#
# `enroll` turns a bare, untrusted host into one a controller CAN start trusting:
# install + a deploy user + ONE control-generated public key + the host-key
# fingerprints the operator confirms out of band. It deliberately does NOT
# generate keys, call anything back, open a listener, touch sshd_config, run any
# adapter verb, or install system packages — the token/callback/self-hosted
# download backend alternative was withdrawn; everything here is local state.

# Accepted public-key algorithms (KI-24): the two fixed names plus the two
# families. Anything else is a configuration error, not a "try it and see".
_SSH_KEY_TYPE_RE = re.compile(
    r"^(?:ssh-ed25519|ssh-rsa|ecdsa-sha2-[A-Za-z0-9@._-]+|sk-[A-Za-z0-9@._-]+)$"
)
_SSH_KEY_B64_RE = re.compile(r"^[A-Za-z0-9+/]+={0,3}$")

# Printed where the operator must substitute a real value — never guessed.
_ENROLL_NAME_PLACEHOLDER = "<NAME>"
_ENROLL_ADDR_PLACEHOLDER = "<ADDRESS>"


def _is_ssh_key_type(token: str) -> bool:
    return bool(_SSH_KEY_TYPE_RE.match(token))


def _parse_authorized_key(raw: Optional[str]) -> Tuple[str, str, str]:
    """Parse ``<type> <base64>[ <comment>]`` → (type, base64, comment).

    Refuses anything else with EXIT_CONFIG (KI-24 step 1). An options field
    (``from="..."``,``command="..."``) is NOT accepted here: options are this
    subcommand's own business (``--from``), so a key line that already carries
    them is ambiguous about which restriction actually applies.
    """
    text = (raw or "").strip()
    if not text:
        fatal("--authorized-key is empty; pass the control-generated public key line.",
              EXIT_CONFIG)
    if "\n" in text or "\r" in text:
        fatal("--authorized-key must be a SINGLE line; got embedded newline(s).",
              EXIT_CONFIG)
    parts = text.split()
    if len(parts) < 2:
        fatal(
            f"--authorized-key is not a public key line: {text!r}. "
            "Expected '<type> <base64> [comment]'.",
            EXIT_CONFIG,
        )
    ktype, b64 = parts[0], parts[1]
    comment = " ".join(parts[2:])
    if not _is_ssh_key_type(ktype):
        if any(ch in ktype for ch in '=,"'):
            fatal(
                f"--authorized-key starts with an options field ({ktype!r}); pass "
                "the bare '<type> <base64> [comment]' line and express the "
                "restriction with --from instead.",
                EXIT_CONFIG,
            )
        fatal(
            f"Unsupported key type {ktype!r}. Expected one of: ssh-ed25519, "
            "ecdsa-sha2-*, sk-*, ssh-rsa.",
            EXIT_CONFIG,
        )
    if not _SSH_KEY_B64_RE.match(b64):
        fatal(
            f"Key material for {ktype} is not base64: {b64!r}. "
            "Did an options field (from=\"...\") get pasted in? Use --from instead.",
            EXIT_CONFIG,
        )
    return ktype, b64, comment


def _ak_split_line(line: str) -> Optional[Tuple[str, str, str, str]]:
    """Split one authorized_keys line into (options, type, base64, comment).

    Returns None for blank/comment lines and for lines carrying no recognisable
    key type. Splitting is quote-aware because an OpenSSH options field may hold
    whitespace inside double quotes (``from="1.2.3.4",command="a b"``) — a plain
    ``str.split()`` would tear such a line in half and mis-read the key.
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    tokens: List[str] = []
    buf: List[str] = []
    in_quote = False
    escaped = False
    for ch in stripped:
        if escaped:
            buf.append(ch)
            escaped = False
            continue
        if ch == "\\" and in_quote:
            buf.append(ch)
            escaped = True
            continue
        if ch == '"':
            in_quote = not in_quote
            buf.append(ch)
            continue
        if ch.isspace() and not in_quote:
            if buf:
                tokens.append("".join(buf))
                buf = []
            continue
        buf.append(ch)
    if buf:
        tokens.append("".join(buf))
    if not tokens:
        return None
    if _is_ssh_key_type(tokens[0]):
        options, rest = "", tokens
    else:
        options, rest = tokens[0], tokens[1:]
        if not rest or not _is_ssh_key_type(rest[0]):
            # Tolerate the malformed `from="…",<type> <b64>` shape on READ (see
            # _build_key_line): sshd refuses such a line, but if one is already
            # in the file we must still recognise the key material in it — a
            # conflict we cannot see is a conflict we silently append beside.
            head, sep, tail = options.rpartition(",")
            if sep and _is_ssh_key_type(tail) and tokens[1:]:
                options, rest = head, [tail] + tokens[1:]
    if len(rest) < 2 or not _is_ssh_key_type(rest[0]):
        return None
    return options, rest[0], rest[1], " ".join(rest[2:])


def _build_key_line(ktype: str, b64: str, comment: str, from_pattern: Optional[str]) -> str:
    """Render the exact line to append: ``from="P" <type> <b64> <comment>``.

    NOTE (deviation from KI-24's literal text, which spells the restricted form
    ``from="PATTERN",<type> …``): OpenSSH separates the options field from the
    key with WHITESPACE, not a comma. sshd's reader advances past the options to
    the first unquoted whitespace, so a comma-joined line makes ``ssh-ed25519``
    look like a second option name and the key is never read — the entry parses
    as garbage and public-key auth fails. Measured, not reasoned: with
    ``from="*",<key>`` in authorized_keys a real sshd answered "Permission
    denied (publickey)"; with ``from="*" <key>`` the same key authenticated. An
    installer that wrote the comma form would report a successful enrollment and
    leave a host the controller can never log into.
    """
    body = f"{ktype} {b64}" + (f" {comment}" if comment else "")
    if from_pattern:
        return f'from="{from_pattern}" {body}'
    return body


def _find_sshd() -> Optional[str]:
    """Locate an SSH server binary: PATH first, then the usual sbin location."""
    found = shutil.which("sshd")
    if found:
        return found
    fallback = Path("/usr/sbin/sshd")
    return str(fallback) if fallback.exists() else None


def _enroll_check_prerequisites(args: argparse.Namespace) -> Tuple[str, str, str]:
    """KI-24 step 1 — every check that must pass BEFORE any network I/O.

    Linux is already enforced globally in ``main()`` before dispatch. Returns the
    parsed key so the caller never re-parses it.
    """
    if os.geteuid() != 0:
        fatal("enroll must run as root (sudo): it creates a user and writes "
              "into that user's ~/.ssh.", EXIT_PREREQ)

    sshd = _find_sshd()
    if not sshd:
        fatal(
            "No SSH server on this host (sshd is not on PATH and /usr/sbin/sshd "
            "does not exist). Install openssh-server and re-run — this installer "
            "never installs system packages itself.",
            EXIT_PREREQ,
        )
    ok(f"SSH server present: {sshd}")

    parsed = _parse_authorized_key(getattr(args, "authorized_key", None))
    ok(f"Authorized key parsed ({parsed[0]}).")
    return parsed


def _enroll_ensure_user(user: str, want_docker: bool) -> "pwd.struct_passwd":
    """KI-24 step 3 — create the deploy user when absent, never modify it when present."""
    if want_docker:
        # Checked BEFORE useradd so a missing group never leaves a half-enrolled host.
        try:
            grp.getgrnam("docker")
        except KeyError:
            fatal(
                "--docker was requested but this host has no 'docker' group. "
                "Install Docker (which creates it) and re-run; enroll will not "
                "create system groups.",
                EXIT_PREREQ,
            )

    try:
        entry = pwd.getpwnam(user)
    except KeyError:
        entry = None

    if entry is None:
        info(f"Creating deploy user {user} ...")
        result = subprocess.run(
            ["useradd", "--create-home", "--shell", "/bin/bash", user],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            fatal(
                f"useradd {user} failed (exit {result.returncode}): "
                f"{result.stderr.strip() or result.stdout.strip()}",
                EXIT_FAIL,
            )
        try:
            entry = pwd.getpwnam(user)
        except KeyError:
            fatal(f"useradd {user} reported success but the user is still unknown.",
                  EXIT_FAIL)
        ok(f"User {user} created (home {entry.pw_dir}, shell {entry.pw_shell}).")
    else:
        ok(f"User {user} already exists — left untouched "
           f"(home {entry.pw_dir}, shell {entry.pw_shell}).")

    if want_docker:
        result = subprocess.run(
            ["usermod", "--append", "--groups", "docker", user],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            fatal(
                f"Adding {user} to the docker group failed (exit {result.returncode}): "
                f"{result.stderr.strip() or result.stdout.strip()}",
                EXIT_FAIL,
            )
        ok(f"User {user} is in the docker group.")

    return entry


def _enroll_install_key(
    entry: "pwd.struct_passwd",
    parsed: Tuple[str, str, str],
    from_pattern: Optional[str],
) -> Path:
    """KI-24 step 4 — ~USER/.ssh 0700, authorized_keys 0600, key appended ONCE.

    Idempotency is decided on KEY MATERIAL, not on the rendered line: an
    identical entry is reported and not duplicated, while the same key under
    DIFFERENT options (a changed ``from=``, or one with and one without) is a
    real conflict and is refused with EXIT_CONFIG rather than quietly appended
    beside the old one.
    """
    ktype, b64, comment = parsed
    want_options = f'from="{from_pattern}"' if from_pattern else ""
    line = _build_key_line(ktype, b64, comment, from_pattern)

    ssh_dir = Path(entry.pw_dir) / ".ssh"
    ssh_dir.mkdir(parents=True, exist_ok=True)
    os.chmod(ssh_dir, 0o700)
    os.chown(ssh_dir, entry.pw_uid, entry.pw_gid)

    authorized = ssh_dir / "authorized_keys"
    existing = (
        authorized.read_text(encoding="utf-8", errors="replace")
        if authorized.exists() else ""
    )

    already_present = False
    other_key_comments: List[str] = []
    for raw_line in existing.splitlines():
        parsed_line = _ak_split_line(raw_line)
        if parsed_line is None:
            continue
        have_options, have_type, have_b64, have_comment = parsed_line
        if (have_type, have_b64) != (ktype, b64):
            # A DIFFERENT, already-recognized key for this same user — not a
            # conflict (KI-24 never restricts a user to one key), but a
            # genuine key rotation must not silently leave two valid
            # identities with no visibility (adversarial review finding,
            # cmru-ki24): note it so it can be warned about below.
            other_key_comments.append(have_comment or have_type)
            continue
        if have_options != want_options:
            fatal(
                f"{authorized} already carries this key under DIFFERENT options.\n"
                f"  present: {have_options or '(none)'}\n"
                f"  wanted:  {want_options or '(none)'}\n"
                "Refusing to append a second entry for the same key material — "
                "resolve the conflict by hand and re-run.",
                EXIT_CONFIG,
            )
        already_present = True
        if have_comment != comment:
            warn(f"Key already present with a different comment "
                 f"({have_comment!r} vs {comment!r}); leaving it as-is.")

    if already_present:
        ok(f"Key already present in {authorized} — not duplicated.")
    else:
        if other_key_comments:
            warn(
                f"{authorized} already has {len(other_key_comments)} other "
                f"key(s) for this user ({', '.join(other_key_comments)}) — "
                "appending this one ALONGSIDE them, not replacing. If this "
                "was meant to be a rotation, remove the old key by hand."
            )
        with open(authorized, "a", encoding="utf-8") as handle:
            if existing and not existing.endswith("\n"):
                handle.write("\n")
            handle.write(line + "\n")
        ok(f"Key appended to {authorized}.")

    os.chmod(authorized, 0o600)
    os.chown(authorized, entry.pw_uid, entry.pw_gid)
    return authorized


def _host_key_fingerprints() -> List[Tuple[str, str, str]]:
    """(path, full ssh-keygen line, SHA256:… token) for every host public key.

    Shells out to ``ssh-keygen -lf`` — the fingerprint is OpenSSH's to compute,
    never this script's.
    """
    results: List[Tuple[str, str, str]] = []
    for path in sorted(_glob.glob("/etc/ssh/ssh_host_*_key.pub")):
        result = subprocess.run(
            ["ssh-keygen", "-lf", path], capture_output=True, text=True
        )
        if result.returncode != 0:
            warn(f"ssh-keygen -lf {path} failed (exit {result.returncode}): "
                 f"{result.stderr.strip()}")
            continue
        text = result.stdout.strip()
        token = next(
            (tok for tok in text.split() if tok.startswith("SHA256:")), ""
        )
        results.append((path, text, token))
    return results


def _host_addresses() -> List[str]:
    """Addresses from ``hostname -I`` — reported UNCONFIRMED, never chosen for the operator."""
    if not shutil.which("hostname"):
        warn("hostname(1) not found; cannot list this host's addresses.")
        return []
    result = subprocess.run(["hostname", "-I"], capture_output=True, text=True)
    if result.returncode != 0:
        warn(f"hostname -I failed (exit {result.returncode}): {result.stderr.strip()}")
        return []
    return result.stdout.split()


def do_enroll(args: argparse.Namespace, token: Optional[str]) -> None:
    """Enrol this host for a controller (CIU S14.7 / cmru KI-24).

    Strict order, fail-fast, idempotent on re-run:
      1. prerequisites — BEFORE any network I/O;
      2. install (skipped by --no-install);
      3. deploy user;
      4. ~USER/.ssh + authorized_keys;
      5. print the fingerprints, addresses and completion command.
    """
    scope = getattr(args, "scope", "system")
    user = getattr(args, "user", None) or "ciu"
    controller = getattr(args, "controller", "")

    hr()
    print(f"  {_c('BLD', 'ciu')}  enroll  user={user}  "
          f"controller={controller}  scope={scope}")
    hr()

    # 1. Prerequisites — nothing below this line may run before these pass.
    parsed = _enroll_check_prerequisites(args)

    # 2. Install, verbatim: do_install owns the transaction/manifest logic.
    if getattr(args, "no_install", False):
        info("--no-install: skipping the install step.")
    else:
        install_args = argparse.Namespace(
            scope=scope,
            version=getattr(args, "version", None),
            variant=getattr(args, "variant", None),
            manifest_pubkey=getattr(args, "manifest_pubkey", None),
            config=getattr(args, "config", None),
        )
        do_install(install_args, token)

    # 3. Deploy user.
    entry = _enroll_ensure_user(user, bool(getattr(args, "docker", False)))

    # 4. Authorized key.
    authorized = _enroll_install_key(entry, parsed, getattr(args, "from_pattern", None))

    # 5. Report. Nothing here changes state; it is what the operator confirms.
    root = _root_dir(scope)
    installed = _current_version(root) or "(not installed)"
    fingerprints = _host_key_fingerprints()
    addresses = _host_addresses()
    ed25519_fp = next(
        (token_ for path, _text, token_ in fingerprints
         if path.endswith("ssh_host_ed25519_key.pub") and token_),
        "",
    )
    name = getattr(args, "name", None) or _ENROLL_NAME_PLACEHOLDER
    address = addresses[0] if addresses else _ENROLL_ADDR_PLACEHOLDER

    hr()
    print("SSH host key fingerprints (confirm these out of band):")
    if fingerprints:
        for path, text, _token in fingerprints:
            print(f"  {path}: {text}")
    else:
        warn("No /etc/ssh/ssh_host_*_key.pub found — is the SSH server configured?")

    print("Addresses (UNCONFIRMED — this host cannot know which one the "
          "controller reaches it on):")
    if addresses:
        for addr in addresses:
            print(f"  {addr}")
    else:
        print(f"  {_ENROLL_ADDR_PLACEHOLDER}")

    print(f"User:      {user}")
    print(f"Home:      {entry.pw_dir}")
    print(f"Keys:      {authorized}")
    print(f"Installed: {installed}")
    print(f"Controller: {controller}")
    hr()
    print("Finish enrollment on the CONTROL host with:")
    print(f"  ciu host enroll {name} --ssh-host {address} "
          f"--fingerprint {ed25519_fp or 'SHA256:<ed25519 fingerprint>'}")
    if name == _ENROLL_NAME_PLACEHOLDER:
        print(f"  (replace {_ENROLL_NAME_PLACEHOLDER} — enroll does not invent a host name; "
              "pass --name to have it filled in)")
    if address == _ENROLL_ADDR_PLACEHOLDER:
        print(f"  (replace {_ENROLL_ADDR_PLACEHOLDER} with the address the controller "
              "will actually use)")
    hr()
    ok(f"Host enrolled for {controller}.")


def _register_enroll(subparsers):
    """Add the `enroll` subcommand. The flag set is normative: ciu's
    `host enroll` prints the exact one-liner an admin runs on a bare host."""
    p_enroll = subparsers.add_parser(
        "enroll",
        help="Enrol this host: install + deploy user + authorized key + host-key fingerprints",
    )
    p_enroll.add_argument("--authorized-key", metavar="KEY", required=True,
                          help="Control-generated public key line: '<type> <base64> [comment]'")
    p_enroll.add_argument("--controller", metavar="FQDN", required=True,
                          help="FQDN of the controller this host is being enrolled for")
    p_enroll.add_argument("--user", metavar="USER", default="ciu",
                          help="Deploy user to create or confirm (default: ciu)")
    p_enroll.add_argument("--name", metavar="NAME",
                          help="Host name for the printed completion command (default: a placeholder)")
    p_enroll.add_argument("--from", dest="from_pattern", metavar="PATTERN",
                          help='Restrict the key with from="PATTERN" (source-address restriction)')
    p_enroll.add_argument("--docker", action="store_true",
                          help="Add the deploy user to the docker group (refused when absent)")
    p_enroll.add_argument("--no-install", action="store_true",
                          help="Skip the install step (user + key + fingerprints only)")
    p_enroll.add_argument("--scope", choices=["system", "user"], default="system",
                          help="Install scope for the install step (default: system)")
    return {"enroll": do_enroll}


_EXTENSIONS.append(_register_enroll)
# --- end extension: installer/enroll.py ---


# ─── Pre-flight checks (S3.1) ────────────────────────────────────────────────

def check_prerequisites() -> None:
    """Check required commands before any network I/O (S3.1 / S6.5)."""
    missing = [cmd for cmd in REQUIRED_COMMANDS if not shutil.which(cmd)]
    if missing:
        fatal(
            f"Required tools not found: {', '.join(missing)}. "
            "Install them and re-run.",
            EXIT_PREREQ,
        )


# ─── Entry point ─────────────────────────────────────────────────────────────

def main() -> None:
    if platform.system() != "Linux":
        fatal("ciu requires Linux.", EXIT_PREREQ)

    # Check prerequisites BEFORE any network I/O (S3.1)
    check_prerequisites()

    parser = argparse.ArgumentParser(
        prog="get.py",
        description="ciu transactional installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  sudo python3 get.py install [--config HOST.toml]\n"
            "  python3 get.py install --scope user\n"
            "  sudo python3 get.py update [--version TAG]\n"
            "  python3 get.py status\n"
            "  sudo python3 get.py rollback\n"
        ),
    )

    # Auth flags (S5)
    tok_ex = parser.add_mutually_exclusive_group()
    tok_ex.add_argument(
        "--github-token", metavar="TOKEN",
        help="GitHub token (WARN: leaks via shell history/ps; prefer file or env)",
    )
    tok_ex.add_argument("--github-token-file", metavar="FILE",
                        help="File containing the GitHub token (chmod 600)")
    tok_ex.add_argument("--github-token-stdin", action="store_true",
                        help="Read GitHub token from stdin (first line)")

    subparsers = parser.add_subparsers(dest="command", required=True)

    p_install = subparsers.add_parser("install", help="Fresh install")
    p_install.add_argument("--config", metavar="HOST.toml",
                           help="Host config file, installed as <root>/shared/host.toml (0600)")
    p_install.add_argument("--version", metavar="TAG", help="Pin a specific release")
    p_install.add_argument("--scope", choices=["system", "user"], default="system",
                           help="Install scope (default: system)")
    p_install.add_argument("--variant", metavar="NAME",
                           help="Select a per-interpreter variant (multi-variant releases)")

    p_update = subparsers.add_parser("update", help="Update to latest (or --version)")
    p_update.add_argument("--version", metavar="TAG")
    p_update.add_argument("--scope", choices=["system", "user"], default="system")
    p_update.add_argument("--variant", metavar="NAME",
                          help="Override the remembered variant (multi-variant releases)")

    p_status = subparsers.add_parser("status", help="Show current/previous versions + health")
    p_status.add_argument("--scope", choices=["system", "user"], default="system")

    p_rollback = subparsers.add_parser("rollback", help="Re-point current to the previous release")
    p_rollback.add_argument("--version", metavar="TAG", help="Roll back to a specific recorded version")
    p_rollback.add_argument("--scope", choices=["system", "user"], default="system")

    # Project extensions (cmru `[project.installer] extensions`): each registered
    # function adds its own subparsers and returns {command: handler}. A command
    # name that duplicates a core command or another extension's is a render-time
    # contract violation, refused before any argument is parsed.
    extension_handlers: Dict[str, Callable[[argparse.Namespace, Optional[str]], None]] = {}
    for register in _EXTENSIONS:
        known = set(subparsers.choices)
        try:
            handlers = register(subparsers)
        except (argparse.ArgumentError, ValueError) as exc:  # argparse >= 3.11: ValueError
            fatal(f"extension {getattr(register, '__name__', register)!r} "
                  f"registers a duplicate command: {exc}", EXIT_CONFIG)
        for command, handler in handlers.items():
            if command in known or command in extension_handlers:
                fatal(f"extension command {command!r} duplicates an existing command "
                      "(core or another extension).", EXIT_CONFIG)
            if command not in subparsers.choices:
                fatal(f"extension command {command!r} returned a handler but "
                      "registered no subparser of that name.", EXIT_CONFIG)
            extension_handlers[command] = handler

    args = parser.parse_args()
    token = _resolve_token(args)

    if args.command == "install":
        do_install(args, token)
    elif args.command == "update":
        do_update(args, token)
    elif args.command == "status":
        do_status(args)
    elif args.command == "rollback":
        do_rollback(args, token)
    elif args.command in extension_handlers:
        extension_handlers[args.command](args, token)
    else:
        parser.print_help()
        raise SystemExit(EXIT_CONFIG)


if __name__ == "__main__":
    main()
