#!/usr/bin/env python3
"""ciu installer — get.py  (generated by cmru get-py)

Transactional installer: private-repo asset auth, atomic install/update/rollback
with a `current` symlink, system/user scope, bundled wheel install into a private
venv, SHA256 + minisign-signed-manifest verification before extraction.

Usage
-----
Install (system scope, requires root):
    sudo python3 get.py install --config HOST.toml

Install (user scope):
    python3 get.py install --config HOST.toml --scope user

Pin a specific version:
    sudo python3 get.py install --config HOST.toml --version ciu-v0.2.0

Select a variant (multi-variant releases — one asset per interpreter):
    sudo python3 get.py install --config HOST.toml --variant py311

Update:
    sudo python3 get.py update

Status:
    python3 get.py status

Rollback:
    sudo python3 get.py rollback

Enrol a bare host (install + deploy user + control-generated authorized key,
then print the host-key fingerprints the controller pins):
    sudo python3 get.py enroll --authorized-key 'ssh-ed25519 AAAA... ciu@control' \
        --controller control.example.net --name web-01

Requires: python3 (stdlib only); system tools: python3
"""
from __future__ import annotations

import argparse
import fcntl
import glob as _glob
import grp
import hashlib
import json
import os
import platform
import pwd
import re
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import List, Optional, Tuple

# ─── Project constants (injected by cmru get-py) ─────────────────────────────
REPO_OWNER       = "volkb79-2"
REPO_NAME        = "vbpub"
TAG_PREFIX       = "ciu-v"
ASSET_SUFFIX     = ".tar.xz"
MANIFEST_NAME    = "manifest.json"
SIGNATURE_NAME   = "manifest.json.minisig"
ENTRYPOINT       = ""           # "" means no adapter
REQUIRED_COMMANDS: List[str] = ["python3"]
PRESERVE_PATHS: List[str]    = []
WHEEL_SPECS: List[Tuple[str, str]] = [("vendor/ciu-*.whl", "ciu")]  # [(glob, distribution), ...]
# Per-interpreter variants (S-REL.6). [] ⇒ one unambiguous single-asset release.
# When non-empty the release carries one asset per variant, named <tag>-<name><suffix>,
# and the operator MUST select one at install time with --variant NAME (no silent default).
VARIANTS: List[dict] = []  # e.g. [{"name": "py39", "label": "Python 3.9"}, ...]

# Scope directories (injected)
INSTALL_DIR_SYSTEM = "/opt/ciu"
INSTALL_DIR_USER   = "ciu"   # leaf; expanded under XDG_DATA_HOME

RELEASES_API = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases"

# Allowed hosts for HTTPS downloads (transport hardening S5)
_ALLOWED_HOSTS = {
    "api.github.com",
    "github.com",
    "objects.githubusercontent.com",
    "uploads.github.com",
}

# ─── Exit codes (S8 / CIU S10.3) ─────────────────────────────────────────────
EXIT_OK     = 0
EXIT_FAIL   = 1   # download / verify / install / adapter failure
EXIT_CONFIG = 2   # configuration / schema failure
EXIT_PREREQ = 3   # missing prerequisite / required env absent


# ─── ANSI helpers (suppressed when not a TTY) ────────────────────────────────
_NO_COLOUR = not sys.stdout.isatty()
_C = {"RED": "\033[0;31m", "YEL": "\033[0;33m", "GRN": "\033[0;32m",
      "CYN": "\033[0;36m", "BLD": "\033[1m",    "RST": "\033[0m"}


def _c(code: str, text: str) -> str:
    return text if _NO_COLOUR else f"{_C[code]}{text}{_C['RST']}"


def info(msg: str)  -> None: print(f"{_c('CYN', '==>')} {msg}", flush=True)
def ok(msg: str)    -> None: print(f"{_c('GRN', '  ok')} {msg}", flush=True)
def warn(msg: str)  -> None: print(f"{_c('YEL', 'warn')} {msg}", file=sys.stderr, flush=True)
def err(msg: str)   -> None: print(f"{_c('RED', ' err')} {msg}", file=sys.stderr, flush=True)
def hr()            -> None: print("─" * 79)


def fatal(msg: str, code: int = EXIT_FAIL) -> None:
    err(msg)
    raise SystemExit(code)


# ─── Token / auth helpers (S5) ───────────────────────────────────────────────

def _validate_token_file(path: Path) -> None:
    """Reject token files with bad permissions or foreign owner."""
    if not path.exists():
        fatal(f"Token file not found: {path}", EXIT_CONFIG)
    if path.is_symlink():
        real = path.resolve()
        if not real.exists():
            fatal(f"Token file symlink broken: {path}", EXIT_CONFIG)
    st = path.stat()
    if st.st_mode & 0o077:
        fatal(
            f"Token file {path} has loose permissions ({oct(st.st_mode & 0o777)}); "
            "chmod 600 it.", EXIT_CONFIG
        )
    if st.st_uid != os.getuid():
        fatal(
            f"Token file {path} is owned by uid {st.st_uid}, "
            f"not current user {os.getuid()}.",
            EXIT_CONFIG,
        )


def _resolve_token(args: argparse.Namespace) -> Optional[str]:
    """Resolve GitHub token: CLI arg > file/stdin > env (S5).

    Warns when --github-token is used (leaks via ps/shell history).
    Token is never logged in full.
    """
    token: Optional[str] = None

    # Lowest priority: env
    for env_var in ("CMRU_GITHUB_TOKEN", "GITHUB_TOKEN"):
        v = os.environ.get(env_var, "").strip()
        if v:
            token = v
            break

    # stdin
    if getattr(args, "github_token_stdin", False):
        line = sys.stdin.readline().strip()
        if line:
            token = line

    # file
    tok_file = getattr(args, "github_token_file", None)
    if tok_file:
        fp = Path(tok_file).expanduser()
        _validate_token_file(fp)
        line = fp.read_text().strip()
        if line:
            token = line

    # CLI arg (highest priority — warn)
    tok_arg = getattr(args, "github_token", None)
    if tok_arg:
        warn("--github-token leaks via shell history/process list; "
             "prefer --github-token-file or CMRU_GITHUB_TOKEN env var.")
        token = tok_arg

    return token or None


# ─── Transport hardening (S5) ─────────────────────────────────────────────────

def _check_url(url: str) -> None:
    """Reject http:// and unknown hosts."""
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https":
        fatal(f"HTTPS-only: refusing {parsed.scheme}:// URL: {url}", EXIT_FAIL)
    host = parsed.hostname or ""
    allowed = (
        host in _ALLOWED_HOSTS
        or host.endswith(".githubusercontent.com")
        or host.endswith(".github.com")
    )
    if not allowed:
        fatal(f"Host not in allowlist: {host}", EXIT_FAIL)


class _NoRedirectAuth(urllib.request.HTTPRedirectHandler):
    """Strip Authorization header before following cross-origin redirects (S5)."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # type: ignore[override]
        new_req = super().redirect_request(req, fp, code, msg, headers, newurl)
        if new_req is not None:
            new_req.remove_header("Authorization")
            new_req.remove_header("authorization")
        return new_req


def _gh_request(
    url: str,
    *,
    token: Optional[str] = None,
    accept: str = "application/vnd.github+json",
    stream_to: Optional[Path] = None,
    timeout: int = 30,
) -> Tuple[int, bytes]:
    """Low-level GitHub request.

    Per S5 / release.py invariant: only sends Authorization when token is present.
    An empty 'Bearer ' header causes GitHub to 401 even on public repos.
    """
    _check_url(url)
    headers: dict = {"Accept": accept, "User-Agent": "ciu/get.py"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    opener = urllib.request.build_opener(_NoRedirectAuth)
    try:
        with opener.open(req, timeout=timeout) as resp:
            if stream_to:
                with open(stream_to, "wb") as fh:
                    shutil.copyfileobj(resp, fh)
                return resp.status, b""
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        body = exc.read() if exc.fp else b""
        return exc.code, body
    except urllib.error.URLError as exc:
        fatal(f"Network error fetching {url}: {exc}", EXIT_FAIL)
        return 0, b""  # unreachable


def _gh_json(url: str, token: Optional[str] = None) -> object:
    status, body = _gh_request(url, token=token)
    if status in (401, 403):
        hint = " (token may be missing or expired)" if not token else ""
        fatal(f"GitHub API {status}{hint}: {url}", EXIT_FAIL)
    if status >= 400:
        fatal(
            f"GitHub API {status}: {url}\n"
            f"  {body.decode('utf-8', errors='replace')}",
            EXIT_FAIL,
        )
    return json.loads(body)


# ─── Tag / release resolution ─────────────────────────────────────────────────

def _semver_key(tag: str) -> tuple:
    ver = tag[len(TAG_PREFIX):]
    tokens: list = []
    for chunk in ver.replace("-", ".").split("."):
        for run in re.findall(r"\d+|\D+", chunk):
            tokens.append((0, int(run), "") if run.isdigit() else (1, 0, run))
    return tuple(tokens)


def resolve_latest_tag(token: Optional[str] = None) -> str:
    """Return the highest-semver ciu-v* release tag."""
    releases = _gh_json(f"{RELEASES_API}?per_page=100", token=token)
    assert isinstance(releases, list)
    candidates = [
        r["tag_name"] for r in releases
        if isinstance(r, dict)
        and r.get("tag_name", "").startswith(TAG_PREFIX)
        and not r.get("draft")
        and not r.get("prerelease")
    ]
    if not candidates:
        fatal(
            f"No ciu releases found (prefix: {TAG_PREFIX!r}). "
            "Check network access or pass --version.",
            EXIT_FAIL,
        )
    return max(candidates, key=_semver_key)


def normalize_tag(version_arg: str) -> str:
    if version_arg.startswith(TAG_PREFIX):
        return version_arg
    # Drop a single leading "v" prefix only — NOT str.lstrip('v'), which strips a
    # whole leading run of 'v' chars (so "v1.0.0" is fine but a hypothetical multi-'v'
    # or 'v'-initial token would be corrupted). Prefix-strip, not charset-strip.
    bare = version_arg[1:] if version_arg.startswith("v") else version_arg
    return f"{TAG_PREFIX}{bare}"


def _find_asset_by_name(assets: list, name: str) -> Optional[dict]:
    for a in assets:
        if a.get("name") == name:
            return a
    return None


# ─── Variant selection (S-REL.6 / S6.12) ──────────────────────────────────────

def _variant_names() -> List[str]:
    return [v["name"] for v in VARIANTS]


def _format_variants() -> str:
    lines = []
    for v in VARIANTS:
        label = v.get("label")
        lines.append(f"  - {v['name']}" + (f"  ({label})" if label else ""))
    return "\n".join(lines)


def _variant_marker_path(root: Path) -> Path:
    """Where the selected variant is remembered so `update` keeps the host's choice."""
    return root / "shared" / ".variant"


def _persist_variant(root: Path, variant: Optional[str]) -> None:
    if not variant:
        return
    marker = _variant_marker_path(root)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text(variant + "\n", encoding="utf-8")


def _installed_variant(root: Path) -> Optional[str]:
    """The variant recorded by the last install/update (None if single-asset / unset)."""
    marker = _variant_marker_path(root)
    if marker.exists():
        return marker.read_text(encoding="utf-8").strip() or None
    return None


def _select_variant(args: argparse.Namespace, root: Path) -> Optional[str]:
    """Resolve which per-interpreter variant to install/update (S6.12).

    Returns None for a single-asset release (VARIANTS empty). Otherwise, in priority order:
    an explicit --variant (validated); a variant
    remembered from a prior install (so `update` stays on the same interpreter); an
    interactive prompt on a TTY; else a fatal error listing the choices. No silent default.
    """
    if not VARIANTS:
        return None
    names = _variant_names()
    chosen = getattr(args, "variant", None)
    if chosen:
        if chosen not in names:
            fatal(f"Unknown --variant {chosen!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
        return chosen
    marker = _variant_marker_path(root)
    if marker.exists():
        prev = marker.read_text(encoding="utf-8").strip()
        if prev in names:
            info(f"Using previously selected variant: {_c('BLD', prev)}")
            return prev
    if sys.stdin.isatty():
        info("This release ships multiple variants — choose one:")
        for i, v in enumerate(VARIANTS, 1):
            label = v.get("label")
            print(f"  {i}) {v['name']}" + (f"  ({label})" if label else ""))
        raw = input("Variant [name or number]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(VARIANTS):
            return VARIANTS[int(raw) - 1]["name"]
        if raw in names:
            return raw
        fatal(f"Invalid selection {raw!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
    fatal(
        "This release ships multiple per-interpreter variants; none was selected.\n"
        f"Re-run with --variant NAME. Available variants:\n{_format_variants()}",
        EXIT_CONFIG,
    )
    return None  # unreachable (fatal raises)


# ─── Download (public or private) (S5) ────────────────────────────────────────

def _download_asset(tag: str, asset_name: str, dest: Path, token: Optional[str]) -> None:
    """Download a release asset — private path if token present, public URL otherwise."""
    if token:
        # Private path: resolve release → list assets → find by name → download by ID
        status, body = _gh_request(
            f"{RELEASES_API}/tags/{tag}", token=token
        )
        if status >= 400:
            fatal(f"Could not fetch release {tag} (HTTP {status})", EXIT_FAIL)
        rel = json.loads(body)
        assets = rel.get("assets", [])
        asset = _find_asset_by_name(assets, asset_name)
        if asset is None:
            fatal(
                f"Asset {asset_name!r} not found in release {tag}. "
                f"Available: {[a.get('name') for a in assets]}",
                EXIT_FAIL,
            )
        # Download by asset ID — strip auth before the redirect (S5)
        asset_url = (
            f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/assets/{asset['id']}"
        )
        _gh_request(asset_url, token=token, accept="application/octet-stream",
                    stream_to=dest, timeout=300)
    else:
        url = (
            f"https://github.com/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/download/{tag}/{asset_name}"
        )
        _gh_request(url, token=None, accept="application/octet-stream",
                    stream_to=dest, timeout=300)
    if not dest.exists() or dest.stat().st_size == 0:
        fatal(f"Download produced empty file: {dest}", EXIT_FAIL)


# ─── SHA256 + minisign verification (S4) ─────────────────────────────────────

def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _verify_sha256(asset: Path, sidecar: Path) -> None:
    expected = sidecar.read_text().split()[0]
    actual   = _sha256(asset)
    if actual != expected:
        fatal(
            f"SHA256 mismatch — refusing to extract.\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok("SHA256 checksum verified.")


def _verify_minisign(manifest: Path, sig: Path, pubkey_arg: str) -> None:
    """Verify manifest.json.minisig with minisign (S4) before extraction."""
    if pubkey_arg.startswith("/") or pubkey_arg.startswith("./") or pubkey_arg.endswith(".pub"):
        cmd = ["minisign", "-Vm", str(manifest), "-p", pubkey_arg]
    else:
        cmd = ["minisign", "-Vm", str(manifest), "-P", pubkey_arg]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        fatal(
            f"minisign signature verification FAILED for {manifest.name}:\n"
            f"  {result.stderr.strip()}",
            EXIT_FAIL,
        )
    ok("Manifest signature verified (minisign).")


def _extract_manifest_for_verify(bundle: Path, workdir: Path) -> Tuple[Path, Path]:
    """Extract only manifest + sig from bundle for pre-extraction verification."""
    import copy as _copy
    manifest_out = workdir / MANIFEST_NAME
    sig_out = workdir / SIGNATURE_NAME
    with tarfile.open(bundle, "r:xz") as tf:
        for member in tf.getmembers():
            parts = Path(member.name).parts
            rel = str(Path(*parts[1:])) if len(parts) >= 2 else member.name
            if rel in (MANIFEST_NAME, SIGNATURE_NAME):
                m = _copy.copy(member)
                m.name = rel
                kw: dict = {}
                if sys.version_info >= (3, 12):
                    kw["filter"] = "data"
                tf.extract(m, path=workdir, **kw)
    if not manifest_out.exists():
        fatal(
            f"Bundle does not contain {MANIFEST_NAME}; cannot verify signature.",
            EXIT_FAIL,
        )
    if not sig_out.exists():
        fatal(
            f"Bundle does not contain {SIGNATURE_NAME}; cannot verify signature.",
            EXIT_FAIL,
        )
    return manifest_out, sig_out


def download_and_verify(
    tag: str,
    workdir: Path,
    token: Optional[str],
    pubkey_arg: Optional[str],
    variant: Optional[str] = None,
) -> Path:
    """Download the bundle + sidecar; verify SHA256 + minisign; return bundle path.

    ``variant`` (S-REL.6) selects the per-interpreter asset ``<tag>-<variant>{suffix}``;
    ``None`` uses the single-asset name ``<tag>{suffix}``."""
    asset_name   = f"{tag}-{variant}{ASSET_SUFFIX}" if variant else f"{tag}{ASSET_SUFFIX}"
    sidecar_name = f"{asset_name}.sha256"
    asset   = workdir / asset_name
    sidecar = workdir / sidecar_name

    info(f"Downloading {asset_name} ...")
    _download_asset(tag, asset_name, asset, token)

    info(f"Downloading {sidecar_name} ...")
    _download_asset(tag, sidecar_name, sidecar, token)

    info("Verifying SHA256 checksum ...")
    _verify_sha256(asset, sidecar)

    if pubkey_arg and MANIFEST_NAME:
        info(f"Extracting {MANIFEST_NAME} for signature verification ...")
        manifest_path, sig_path = _extract_manifest_for_verify(asset, workdir)
        info(f"Verifying {MANIFEST_NAME} with minisign ...")
        _verify_minisign(manifest_path, sig_path, pubkey_arg)
    elif MANIFEST_NAME and not pubkey_arg:
        warn(
            "No --manifest-pubkey provided; skipping minisign verification. "
            "Supply --manifest-pubkey for full chain-of-trust."
        )

    return asset


# ─── Extraction safety (S6.3) ─────────────────────────────────────────────────

_UNSAFE_TYPES = {tarfile.BLKTYPE, tarfile.CHRTYPE, tarfile.FIFOTYPE}


def _safe_member(member: tarfile.TarInfo, dest: Path) -> bool:
    """Return False (and warn) if member should be rejected (S6.3 safety rules)."""
    parts = Path(member.name).parts
    if member.name.startswith("/"):
        warn(f"Skipping absolute path: {member.name}")
        return False
    if ".." in parts:
        warn(f"Skipping path traversal: {member.name}")
        return False
    try:
        resolved = (dest / member.name).resolve()
        resolved.relative_to(dest.resolve())
    except ValueError:
        warn(f"Skipping escape path: {member.name}")
        return False
    if member.type in _UNSAFE_TYPES:
        warn(f"Skipping device/fifo node: {member.name}")
        return False
    if member.issym() or member.islnk():
        link_target = member.linkname or ""
        if link_target.startswith("/"):
            warn(f"Skipping absolute symlink: {member.name} -> {link_target}")
            return False
        if ".." in Path(link_target).parts:
            warn(f"Skipping traversal symlink: {member.name} -> {link_target}")
            return False
    return True


def _pre_scan_members(tf: tarfile.TarFile, dest: Path) -> List[tarfile.TarInfo]:
    """Pre-scan members, strip top-level dir component, reject unsafe entries."""
    import copy as _copy
    members = []
    for member in tf.getmembers():
        parts = Path(member.name).parts
        if len(parts) < 2:
            continue  # skip the top-level dir itself
        m = _copy.copy(member)
        m.name = str(Path(*parts[1:]))
        if _safe_member(m, dest):
            members.append(m)
    return members


def _extract_bundle(bundle: Path, staging: Path) -> None:
    """Extract bundle into staging dir with safety pre-scan + filter='data' (py>=3.12)."""
    staging.mkdir(parents=True, exist_ok=True)
    info(f"Extracting to {staging} ...")
    with tarfile.open(bundle, "r:xz") as tf:
        members = _pre_scan_members(tf, staging)
        kw: dict = {}
        if sys.version_info >= (3, 12):
            kw["filter"] = "data"
        tf.extractall(staging, members=members, **kw)
    ok("Extraction complete.")


# ─── Wheel verification + venv install (S4, S6.3) ────────────────────────────

def _verify_wheel_sha256(wheel_path: Path, manifest: dict, distribution: str) -> None:
    """Check wheel sha256 against manifest (S4 step 3) before pip install.

    Reads sha256 from the per-distribution entry in the manifest
    (manifest[distribution]['sha256']), matching SPEC B's Seam-3 schema.
    Distribution is the canonical package name (e.g. 'cmru', 'ciu').
    """
    dist_entry = manifest.get(distribution) or {}
    expected = dist_entry.get("sha256")
    if not expected:
        warn(f"No sha256 for distribution {distribution!r} in manifest; skipping wheel hash check.")
        return
    actual = _sha256(wheel_path)
    if actual != expected:
        fatal(
            f"Wheel SHA256 mismatch for {wheel_path.name} (distribution: {distribution!r}):\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok(f"Wheel {wheel_path.name} ({distribution}) sha256 verified.")


def _install_wheels(staging: Path, venv_dir: Path, manifest: dict) -> None:
    """Create/update private venv and install bundled wheels (no-index)."""
    if not WHEEL_SPECS:
        return
    info(f"Setting up private venv at {venv_dir} ...")
    subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True)
    pip = venv_dir / "bin" / "pip"
    for glob_pat, distribution in WHEEL_SPECS:
        matches = sorted(staging.glob(glob_pat))
        if not matches:
            fatal(
                f"No wheel found in bundle for {distribution!r} (glob: {glob_pat!r})",
                EXIT_FAIL,
            )
        wheel_path = matches[-1]
        _verify_wheel_sha256(wheel_path, manifest, distribution)
        info(f"Installing {wheel_path.name} into venv ...")
        subprocess.run([str(pip), "install", "--no-index", str(wheel_path)], check=True)
        ok(f"Installed {distribution} from {wheel_path.name}.")


# ─── Adapter invocation (Seam 1 — S3.3) ──────────────────────────────────────

def _invoke_adapter(
    action: str,
    release_dir: Path,
    root: Path,
    venv_dir: Path,
    token: Optional[str] = None,
) -> None:
    """Invoke project adapter; non-zero exit aborts before the current swap (S3.3)."""
    if not ENTRYPOINT:
        return  # no adapter (tls-edge minimal path)
    adapter = release_dir / ENTRYPOINT
    if not adapter.exists():
        fatal(f"Adapter entrypoint not found: {adapter}", EXIT_FAIL)
    venv_python = venv_dir / "bin" / "python"
    config_path = root / "shared" / "host.toml"
    manifest_path = release_dir / MANIFEST_NAME
    cmd = [
        str(venv_python), str(adapter), action,
        "--release-root", str(release_dir),
        "--config", str(config_path),
        "--manifest", str(manifest_path),
    ]
    info(f"Invoking adapter: {action} ...")
    # Strip GitHub token from child environment (S5)
    child_env = {
        k: v for k, v in os.environ.items()
        if k not in ("GITHUB_TOKEN", "CMRU_GITHUB_TOKEN", "GITHUB_PUSH_PAT")
    }
    result = subprocess.run(cmd, env=child_env)
    if result.returncode != 0:
        fatal(
            f"Adapter exited {result.returncode} (action={action!r}); "
            "transaction aborted — current release unchanged.",
            EXIT_FAIL,
        )
    ok(f"Adapter {action} succeeded.")


# ─── Preserve / shared config (S3.2) ─────────────────────────────────────────

def _copy_preserve_to_shared(root: Path, src_release: Optional[Path] = None) -> None:
    """Copy preserved paths from current release into <root>/shared/."""
    shared = root / "shared"
    current = root / "current"
    source = src_release or (current.resolve() if current.exists() else None)
    if source is None or not source.is_dir():
        return
    for rel in PRESERVE_PATHS:
        src = source / rel
        dest = shared / rel
        if src.exists() and not src.is_symlink():
            dest.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(src, dest)
            else:
                shutil.copy2(src, dest)
            ok(f"Preserved: {rel}")


def _restore_preserve_from_shared(root: Path, release_dir: Path) -> None:
    """Symlink preserved paths from shared/ into the new release dir."""
    shared = root / "shared"
    for rel in PRESERVE_PATHS:
        src = shared / rel
        if src.exists():
            dest = release_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.exists() or dest.is_symlink():
                if dest.is_dir() and not dest.is_symlink():
                    shutil.rmtree(dest)
                else:
                    dest.unlink()
            dest.symlink_to(src)
            ok(f"Linked shared/{rel} into release.")


# ─── Scope resolution (S3.2) ─────────────────────────────────────────────────

def _root_dir(scope: str) -> Path:
    if scope == "system":
        return Path(INSTALL_DIR_SYSTEM)
    xdg = os.environ.get("XDG_DATA_HOME", "").strip()
    base = Path(xdg) if xdg else Path.home() / ".local" / "share"
    return base / INSTALL_DIR_USER


# ─── Exclusive lock + SIGINT/SIGTERM handler ─────────────────────────────────

_active_staging: Optional[Path] = None
_lock_fd: Optional[int] = None


def _cleanup_on_signal(sig: int, _frame: object) -> None:
    global _active_staging, _lock_fd
    if _active_staging and _active_staging.exists():
        shutil.rmtree(_active_staging, ignore_errors=True)
    if _lock_fd is not None:
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
        except OSError:
            pass
    sys.exit(EXIT_FAIL)


signal.signal(signal.SIGINT, _cleanup_on_signal)
signal.signal(signal.SIGTERM, _cleanup_on_signal)


class _Lock:
    def __init__(self, root: Path) -> None:
        self._path = root / ".lock"

    def __enter__(self) -> "_Lock":
        global _lock_fd
        self._path.parent.mkdir(parents=True, exist_ok=True)
        _lock_fd = os.open(str(self._path), os.O_CREAT | os.O_WRONLY, 0o600)
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            info("Another installer is running; waiting for lock ...")
            fcntl.flock(_lock_fd, fcntl.LOCK_EX)
        return self

    def __exit__(self, *_: object) -> None:
        global _lock_fd
        if _lock_fd is not None:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
            _lock_fd = None


# ─── Release management helpers ───────────────────────────────────────────────

def _current_version(root: Path) -> Optional[str]:
    cur = root / "current"
    if cur.is_symlink() and cur.exists():
        return cur.resolve().name
    return None


def _prune_old_releases(releases_dir: Path, keep: int = 2) -> None:
    """Keep the N most-recent release dirs; prune older ones."""
    entries = sorted(
        [d for d in releases_dir.iterdir()
         if d.is_dir() and not d.name.endswith(".staging")],
        key=lambda d: d.stat().st_mtime,
    )
    for old in entries[:-keep]:
        info(f"Pruning old release: {old.name}")
        shutil.rmtree(old, ignore_errors=True)


def _atomic_swap_current(root: Path, new_release: Path) -> None:
    """Atomic current swap: tmp symlink + os.replace (S6.3)."""
    current = root / "current"
    tmp_link = root / ".current.tmp"
    if tmp_link.is_symlink():
        tmp_link.unlink()
    os.symlink(new_release, tmp_link)
    os.replace(tmp_link, current)
    ok(f"current -> {new_release.name}")


def _finalize_staging(staging: Path, releases_dir: Path, tag: str) -> Path:
    final = releases_dir / tag
    if final.exists():
        shutil.rmtree(final)
    staging.rename(final)
    return final


def _load_manifest(release_dir: Path) -> dict:
    mf = release_dir / MANIFEST_NAME
    if MANIFEST_NAME and mf.exists():
        try:
            return json.loads(mf.read_text())
        except Exception:
            pass
    return {}


# ─── Host enrollment helpers (CIU S14.7 / cmru KI-24) ────────────────────────
#
# `enroll` turns a bare, untrusted host into one a controller CAN start trusting:
# install + a deploy user + ONE control-generated public key + the host-key
# fingerprints the operator confirms out of band. It deliberately does NOT
# generate keys, call anything back, open a listener, touch sshd_config, run any
# adapter verb, or install system packages — the token/callback/self-hosted
# download backend alternative was withdrawn; everything here is local state.

# Accepted public-key algorithms (KI-24): the two fixed names plus the two
# families. Anything else is a configuration error, not a "try it and see".
_SSH_KEY_TYPE_RE = re.compile(
    r"^(?:ssh-ed25519|ssh-rsa|ecdsa-sha2-[A-Za-z0-9@._-]+|sk-[A-Za-z0-9@._-]+)$"
)
_SSH_KEY_B64_RE = re.compile(r"^[A-Za-z0-9+/]+={0,3}$")

# Printed where the operator must substitute a real value — never guessed.
_ENROLL_NAME_PLACEHOLDER = "<NAME>"
_ENROLL_ADDR_PLACEHOLDER = "<ADDRESS>"


def _is_ssh_key_type(token: str) -> bool:
    return bool(_SSH_KEY_TYPE_RE.match(token))


def _parse_authorized_key(raw: Optional[str]) -> Tuple[str, str, str]:
    """Parse ``<type> <base64>[ <comment>]`` → (type, base64, comment).

    Refuses anything else with EXIT_CONFIG (KI-24 step 1). An options field
    (``from="..."``,``command="..."``) is NOT accepted here: options are this
    subcommand's own business (``--from``), so a key line that already carries
    them is ambiguous about which restriction actually applies.
    """
    text = (raw or "").strip()
    if not text:
        fatal("--authorized-key is empty; pass the control-generated public key line.",
              EXIT_CONFIG)
    if "\n" in text or "\r" in text:
        fatal("--authorized-key must be a SINGLE line; got embedded newline(s).",
              EXIT_CONFIG)
    parts = text.split()
    if len(parts) < 2:
        fatal(
            f"--authorized-key is not a public key line: {text!r}. "
            "Expected '<type> <base64> [comment]'.",
            EXIT_CONFIG,
        )
    ktype, b64 = parts[0], parts[1]
    comment = " ".join(parts[2:])
    if not _is_ssh_key_type(ktype):
        if any(ch in ktype for ch in '=,"'):
            fatal(
                f"--authorized-key starts with an options field ({ktype!r}); pass "
                "the bare '<type> <base64> [comment]' line and express the "
                "restriction with --from instead.",
                EXIT_CONFIG,
            )
        fatal(
            f"Unsupported key type {ktype!r}. Expected one of: ssh-ed25519, "
            "ecdsa-sha2-*, sk-*, ssh-rsa.",
            EXIT_CONFIG,
        )
    if not _SSH_KEY_B64_RE.match(b64):
        fatal(
            f"Key material for {ktype} is not base64: {b64!r}. "
            "Did an options field (from=\"...\") get pasted in? Use --from instead.",
            EXIT_CONFIG,
        )
    return ktype, b64, comment


def _ak_split_line(line: str) -> Optional[Tuple[str, str, str, str]]:
    """Split one authorized_keys line into (options, type, base64, comment).

    Returns None for blank/comment lines and for lines carrying no recognisable
    key type. Splitting is quote-aware because an OpenSSH options field may hold
    whitespace inside double quotes (``from="1.2.3.4",command="a b"``) — a plain
    ``str.split()`` would tear such a line in half and mis-read the key.
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return None
    tokens: List[str] = []
    buf: List[str] = []
    in_quote = False
    escaped = False
    for ch in stripped:
        if escaped:
            buf.append(ch)
            escaped = False
            continue
        if ch == "\\" and in_quote:
            buf.append(ch)
            escaped = True
            continue
        if ch == '"':
            in_quote = not in_quote
            buf.append(ch)
            continue
        if ch.isspace() and not in_quote:
            if buf:
                tokens.append("".join(buf))
                buf = []
            continue
        buf.append(ch)
    if buf:
        tokens.append("".join(buf))
    if not tokens:
        return None
    if _is_ssh_key_type(tokens[0]):
        options, rest = "", tokens
    else:
        options, rest = tokens[0], tokens[1:]
        if not rest or not _is_ssh_key_type(rest[0]):
            # Tolerate the malformed `from="…",<type> <b64>` shape on READ (see
            # _build_key_line): sshd refuses such a line, but if one is already
            # in the file we must still recognise the key material in it — a
            # conflict we cannot see is a conflict we silently append beside.
            head, sep, tail = options.rpartition(",")
            if sep and _is_ssh_key_type(tail) and tokens[1:]:
                options, rest = head, [tail] + tokens[1:]
    if len(rest) < 2 or not _is_ssh_key_type(rest[0]):
        return None
    return options, rest[0], rest[1], " ".join(rest[2:])


def _build_key_line(ktype: str, b64: str, comment: str, from_pattern: Optional[str]) -> str:
    """Render the exact line to append: ``from="P" <type> <b64> <comment>``.

    NOTE (deviation from KI-24's literal text, which spells the restricted form
    ``from="PATTERN",<type> …``): OpenSSH separates the options field from the
    key with WHITESPACE, not a comma. sshd's reader advances past the options to
    the first unquoted whitespace, so a comma-joined line makes ``ssh-ed25519``
    look like a second option name and the key is never read — the entry parses
    as garbage and public-key auth fails. Measured, not reasoned: with
    ``from="*",<key>`` in authorized_keys a real sshd answered "Permission
    denied (publickey)"; with ``from="*" <key>`` the same key authenticated. An
    installer that wrote the comma form would report a successful enrollment and
    leave a host the controller can never log into.
    """
    body = f"{ktype} {b64}" + (f" {comment}" if comment else "")
    if from_pattern:
        return f'from="{from_pattern}" {body}'
    return body


def _find_sshd() -> Optional[str]:
    """Locate an SSH server binary: PATH first, then the usual sbin location."""
    found = shutil.which("sshd")
    if found:
        return found
    fallback = Path("/usr/sbin/sshd")
    return str(fallback) if fallback.exists() else None


def _enroll_check_prerequisites(args: argparse.Namespace) -> Tuple[str, str, str]:
    """KI-24 step 1 — every check that must pass BEFORE any network I/O.

    Linux is already enforced globally in ``main()`` before dispatch. Returns the
    parsed key so the caller never re-parses it.
    """
    if os.geteuid() != 0:
        fatal("enroll must run as root (sudo): it creates a user and writes "
              "into that user's ~/.ssh.", EXIT_PREREQ)

    sshd = _find_sshd()
    if not sshd:
        fatal(
            "No SSH server on this host (sshd is not on PATH and /usr/sbin/sshd "
            "does not exist). Install openssh-server and re-run — this installer "
            "never installs system packages itself.",
            EXIT_PREREQ,
        )
    ok(f"SSH server present: {sshd}")

    parsed = _parse_authorized_key(getattr(args, "authorized_key", None))
    ok(f"Authorized key parsed ({parsed[0]}).")
    return parsed


def _enroll_ensure_user(user: str, want_docker: bool) -> "pwd.struct_passwd":
    """KI-24 step 3 — create the deploy user when absent, never modify it when present."""
    if want_docker:
        # Checked BEFORE useradd so a missing group never leaves a half-enrolled host.
        try:
            grp.getgrnam("docker")
        except KeyError:
            fatal(
                "--docker was requested but this host has no 'docker' group. "
                "Install Docker (which creates it) and re-run; enroll will not "
                "create system groups.",
                EXIT_PREREQ,
            )

    try:
        entry = pwd.getpwnam(user)
    except KeyError:
        entry = None

    if entry is None:
        info(f"Creating deploy user {user} ...")
        result = subprocess.run(
            ["useradd", "--create-home", "--shell", "/bin/bash", user],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            fatal(
                f"useradd {user} failed (exit {result.returncode}): "
                f"{result.stderr.strip() or result.stdout.strip()}",
                EXIT_FAIL,
            )
        try:
            entry = pwd.getpwnam(user)
        except KeyError:
            fatal(f"useradd {user} reported success but the user is still unknown.",
                  EXIT_FAIL)
        ok(f"User {user} created (home {entry.pw_dir}, shell {entry.pw_shell}).")
    else:
        ok(f"User {user} already exists — left untouched "
           f"(home {entry.pw_dir}, shell {entry.pw_shell}).")

    if want_docker:
        result = subprocess.run(
            ["usermod", "--append", "--groups", "docker", user],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            fatal(
                f"Adding {user} to the docker group failed (exit {result.returncode}): "
                f"{result.stderr.strip() or result.stdout.strip()}",
                EXIT_FAIL,
            )
        ok(f"User {user} is in the docker group.")

    return entry


def _enroll_install_key(
    entry: "pwd.struct_passwd",
    parsed: Tuple[str, str, str],
    from_pattern: Optional[str],
) -> Path:
    """KI-24 step 4 — ~USER/.ssh 0700, authorized_keys 0600, key appended ONCE.

    Idempotency is decided on KEY MATERIAL, not on the rendered line: an
    identical entry is reported and not duplicated, while the same key under
    DIFFERENT options (a changed ``from=``, or one with and one without) is a
    real conflict and is refused with EXIT_CONFIG rather than quietly appended
    beside the old one.
    """
    ktype, b64, comment = parsed
    want_options = f'from="{from_pattern}"' if from_pattern else ""
    line = _build_key_line(ktype, b64, comment, from_pattern)

    ssh_dir = Path(entry.pw_dir) / ".ssh"
    ssh_dir.mkdir(parents=True, exist_ok=True)
    os.chmod(ssh_dir, 0o700)
    os.chown(ssh_dir, entry.pw_uid, entry.pw_gid)

    authorized = ssh_dir / "authorized_keys"
    existing = (
        authorized.read_text(encoding="utf-8", errors="replace")
        if authorized.exists() else ""
    )

    already_present = False
    other_key_comments: List[str] = []
    for raw_line in existing.splitlines():
        parsed_line = _ak_split_line(raw_line)
        if parsed_line is None:
            continue
        have_options, have_type, have_b64, have_comment = parsed_line
        if (have_type, have_b64) != (ktype, b64):
            # A DIFFERENT, already-recognized key for this same user — not a
            # conflict (KI-24 never restricts a user to one key), but a
            # genuine key rotation must not silently leave two valid
            # identities with no visibility (adversarial review finding,
            # cmru-ki24): note it so it can be warned about below.
            other_key_comments.append(have_comment or have_type)
            continue
        if have_options != want_options:
            fatal(
                f"{authorized} already carries this key under DIFFERENT options.\n"
                f"  present: {have_options or '(none)'}\n"
                f"  wanted:  {want_options or '(none)'}\n"
                "Refusing to append a second entry for the same key material — "
                "resolve the conflict by hand and re-run.",
                EXIT_CONFIG,
            )
        already_present = True
        if have_comment != comment:
            warn(f"Key already present with a different comment "
                 f"({have_comment!r} vs {comment!r}); leaving it as-is.")

    if already_present:
        ok(f"Key already present in {authorized} — not duplicated.")
    else:
        if other_key_comments:
            warn(
                f"{authorized} already has {len(other_key_comments)} other "
                f"key(s) for this user ({', '.join(other_key_comments)}) — "
                "appending this one ALONGSIDE them, not replacing. If this "
                "was meant to be a rotation, remove the old key by hand."
            )
        with open(authorized, "a", encoding="utf-8") as handle:
            if existing and not existing.endswith("\n"):
                handle.write("\n")
            handle.write(line + "\n")
        ok(f"Key appended to {authorized}.")

    os.chmod(authorized, 0o600)
    os.chown(authorized, entry.pw_uid, entry.pw_gid)
    return authorized


def _host_key_fingerprints() -> List[Tuple[str, str, str]]:
    """(path, full ssh-keygen line, SHA256:… token) for every host public key.

    Shells out to ``ssh-keygen -lf`` — the fingerprint is OpenSSH's to compute,
    never this script's.
    """
    results: List[Tuple[str, str, str]] = []
    for path in sorted(_glob.glob("/etc/ssh/ssh_host_*_key.pub")):
        result = subprocess.run(
            ["ssh-keygen", "-lf", path], capture_output=True, text=True
        )
        if result.returncode != 0:
            warn(f"ssh-keygen -lf {path} failed (exit {result.returncode}): "
                 f"{result.stderr.strip()}")
            continue
        text = result.stdout.strip()
        token = next(
            (tok for tok in text.split() if tok.startswith("SHA256:")), ""
        )
        results.append((path, text, token))
    return results


def _host_addresses() -> List[str]:
    """Addresses from ``hostname -I`` — reported UNCONFIRMED, never chosen for the operator."""
    if not shutil.which("hostname"):
        warn("hostname(1) not found; cannot list this host's addresses.")
        return []
    result = subprocess.run(["hostname", "-I"], capture_output=True, text=True)
    if result.returncode != 0:
        warn(f"hostname -I failed (exit {result.returncode}): {result.stderr.strip()}")
        return []
    return result.stdout.split()


# ─── Commands ────────────────────────────────────────────────────────────────

def do_install(args: argparse.Namespace, token: Optional[str]) -> None:
    global _active_staging
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)
    releases_dir = root / "releases"
    venv_dir = root / "venv"
    shared_dir = root / "shared"

    hr()
    print(f"  {_c('BLD', 'ciu')}  install  scope={scope}  root={root}")
    hr()

    if scope == "system" and os.geteuid() != 0:
        fatal("system-scope install requires root (sudo).", EXIT_PREREQ)

    current_ver = _current_version(root)
    if current_ver:
        warn(f"Existing install found ({current_ver}). Running update instead.")
        do_update(args, token)
        return

    if args.version:
        tag = normalize_tag(args.version)
        info(f"Pinned version: {_c('BLD', tag)}")
    else:
        info("Resolving latest release ...")
        tag = resolve_latest_tag(token)
        info(f"Latest: {_c('BLD', tag)}")

    variant = _select_variant(args, root)
    if variant:
        info(f"Variant: {_c('BLD', variant)}")

    shared_dir.mkdir(parents=True, exist_ok=True)
    releases_dir.mkdir(parents=True, exist_ok=True)
    _persist_variant(root, variant)

    with _Lock(root):
        staging = releases_dir / f"{tag}.staging"
        _active_staging = staging

        with tempfile.TemporaryDirectory() as tmp:
            bundle = download_and_verify(
                tag, Path(tmp), token, getattr(args, "manifest_pubkey", None), variant
            )
            _extract_bundle(bundle, staging)

        manifest = _load_manifest(staging)
        _install_wheels(staging, venv_dir, manifest)
        _restore_preserve_from_shared(root, staging)

        if ENTRYPOINT:
            _invoke_adapter("bootstrap", staging, root, venv_dir, token)

        release_dir = _finalize_staging(staging, releases_dir, tag)
        _active_staging = None
        _atomic_swap_current(root, release_dir)
        _prune_old_releases(releases_dir)

    hr()
    ok(f"ciu {tag} installed at {root}")
    print()


def do_update(args: argparse.Namespace, token: Optional[str]) -> None:
    global _active_staging
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)
    releases_dir = root / "releases"
    venv_dir = root / "venv"

    if scope == "system" and os.geteuid() != 0:
        fatal("system-scope update requires root (sudo).", EXIT_PREREQ)

    current_ver = _current_version(root)
    if not current_ver:
        fatal(
            f"No install found at {root}. Run 'python3 get.py install' first.",
            EXIT_FAIL,
        )

    if args.version:
        tag = normalize_tag(args.version)
        info(f"Pinned version: {_c('BLD', tag)}")
    else:
        info("Resolving latest release ...")
        tag = resolve_latest_tag(token)
        info(f"Latest: {_c('BLD', tag)}")

    variant = _select_variant(args, root)
    if variant:
        info(f"Variant: {_c('BLD', variant)}")

    # Nothing to do only when BOTH the version AND the selected variant already match
    # what is installed — otherwise `update --variant OTHER` at the current version must
    # re-install the other variant (S6.12), not be silently short-circuited.
    if tag == current_ver and variant == _installed_variant(root):
        ok(f"Already at {tag}. Nothing to do.")
        return

    info(f"Updating {current_ver} -> {tag} ...")
    _copy_preserve_to_shared(root)

    releases_dir.mkdir(parents=True, exist_ok=True)
    _persist_variant(root, variant)

    with _Lock(root):
        staging = releases_dir / f"{tag}.staging"
        _active_staging = staging

        with tempfile.TemporaryDirectory() as tmp:
            bundle = download_and_verify(
                tag, Path(tmp), token, getattr(args, "manifest_pubkey", None), variant
            )
            _extract_bundle(bundle, staging)

        manifest = _load_manifest(staging)
        _install_wheels(staging, venv_dir, manifest)
        _restore_preserve_from_shared(root, staging)

        if ENTRYPOINT:
            _invoke_adapter("apply", staging, root, venv_dir, token)

        release_dir = _finalize_staging(staging, releases_dir, tag)
        _active_staging = None
        _atomic_swap_current(root, release_dir)
        _prune_old_releases(releases_dir)

    ok(f"Updated to {tag}.")
    print()


def do_rollback(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)
    releases_dir = root / "releases"
    venv_dir = root / "venv"

    if scope == "system" and os.geteuid() != 0:
        fatal("system-scope rollback requires root (sudo).", EXIT_PREREQ)

    current_ver = _current_version(root)

    if getattr(args, "version", None):
        target_tag = normalize_tag(args.version)
    else:
        if not releases_dir.exists():
            fatal("No releases directory found.", EXIT_FAIL)
        entries = sorted(
            [d for d in releases_dir.iterdir()
             if d.is_dir() and not d.name.endswith(".staging")],
            key=lambda d: d.stat().st_mtime,
        )
        prev = next((e for e in reversed(entries) if e.name != current_ver), None)
        if prev is None:
            fatal("No previous release to roll back to.", EXIT_FAIL)
        target_tag = prev.name

    target_dir = releases_dir / target_tag
    if not target_dir.exists():
        fatal(f"Release {target_tag} not found at {target_dir}.", EXIT_FAIL)

    info(f"Rolling back to {target_tag} ...")

    if ENTRYPOINT:
        _invoke_adapter("rollback", target_dir, root, venv_dir, token)

    _atomic_swap_current(root, target_dir)
    ok(f"Rolled back to {target_tag}.")


def do_status(args: argparse.Namespace) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)
    releases_dir = root / "releases"

    current_ver = _current_version(root)
    if not current_ver:
        print(f"ciu: not installed at {root}")
        return

    print(f"ciu status  scope={scope}  root={root}")
    print(f"  current:  {current_ver}")

    if releases_dir.exists():
        entries = sorted(
            [d for d in releases_dir.iterdir()
             if d.is_dir() and not d.name.endswith(".staging")],
            key=lambda d: d.stat().st_mtime,
            reverse=True,
        )
        previous = [e.name for e in entries if e.name != current_ver]
        if previous:
            print(f"  previous: {', '.join(previous[:3])}")

    if ENTRYPOINT:
        venv_python = root / "venv" / "bin" / "python"
        current_dir = root / "current"
        cmd = [
            str(venv_python), str(current_dir / ENTRYPOINT), "health",
            "--release-root", str(current_dir),
            "--config", str(root / "shared" / "host.toml"),
            "--manifest", str(current_dir / MANIFEST_NAME),
        ]
        result = subprocess.run(cmd)
        if result.returncode == 0:
            ok("health check passed.")
        else:
            warn(f"health check exited {result.returncode}.")


def do_enroll(args: argparse.Namespace, token: Optional[str]) -> None:
    """Enrol this host for a controller (CIU S14.7 / cmru KI-24).

    Strict order, fail-fast, idempotent on re-run:
      1. prerequisites — BEFORE any network I/O;
      2. install (skipped by --no-install);
      3. deploy user;
      4. ~USER/.ssh + authorized_keys;
      5. print the fingerprints, addresses and completion command.
    """
    scope = getattr(args, "scope", "system")
    user = getattr(args, "user", None) or "ciu"
    controller = getattr(args, "controller", "")

    hr()
    print(f"  {_c('BLD', 'ciu')}  enroll  user={user}  "
          f"controller={controller}  scope={scope}")
    hr()

    # 1. Prerequisites — nothing below this line may run before these pass.
    parsed = _enroll_check_prerequisites(args)

    # 2. Install, verbatim: do_install owns the transaction/manifest logic.
    if getattr(args, "no_install", False):
        info("--no-install: skipping the install step.")
    else:
        install_args = argparse.Namespace(
            scope=scope,
            version=getattr(args, "version", None),
            variant=getattr(args, "variant", None),
            manifest_pubkey=getattr(args, "manifest_pubkey", None),
            config=getattr(args, "config", None),
        )
        do_install(install_args, token)

    # 3. Deploy user.
    entry = _enroll_ensure_user(user, bool(getattr(args, "docker", False)))

    # 4. Authorized key.
    authorized = _enroll_install_key(entry, parsed, getattr(args, "from_pattern", None))

    # 5. Report. Nothing here changes state; it is what the operator confirms.
    root = _root_dir(scope)
    installed = _current_version(root) or "(not installed)"
    fingerprints = _host_key_fingerprints()
    addresses = _host_addresses()
    ed25519_fp = next(
        (token_ for path, _text, token_ in fingerprints
         if path.endswith("ssh_host_ed25519_key.pub") and token_),
        "",
    )
    name = getattr(args, "name", None) or _ENROLL_NAME_PLACEHOLDER
    address = addresses[0] if addresses else _ENROLL_ADDR_PLACEHOLDER

    hr()
    print("SSH host key fingerprints (confirm these out of band):")
    if fingerprints:
        for path, text, _token in fingerprints:
            print(f"  {path}: {text}")
    else:
        warn("No /etc/ssh/ssh_host_*_key.pub found — is the SSH server configured?")

    print("Addresses (UNCONFIRMED — this host cannot know which one the "
          "controller reaches it on):")
    if addresses:
        for addr in addresses:
            print(f"  {addr}")
    else:
        print(f"  {_ENROLL_ADDR_PLACEHOLDER}")

    print(f"User:      {user}")
    print(f"Home:      {entry.pw_dir}")
    print(f"Keys:      {authorized}")
    print(f"Installed: {installed}")
    print(f"Controller: {controller}")
    hr()
    print("Finish enrollment on the CONTROL host with:")
    print(f"  ciu host enroll {name} --ssh-host {address} "
          f"--fingerprint {ed25519_fp or 'SHA256:<ed25519 fingerprint>'}")
    if name == _ENROLL_NAME_PLACEHOLDER:
        print(f"  (replace {_ENROLL_NAME_PLACEHOLDER} — enroll does not invent a host name; "
              "pass --name to have it filled in)")
    if address == _ENROLL_ADDR_PLACEHOLDER:
        print(f"  (replace {_ENROLL_ADDR_PLACEHOLDER} with the address the controller "
              "will actually use)")
    hr()
    ok(f"Host enrolled for {controller}.")


# ─── Pre-flight checks (S3.1) ────────────────────────────────────────────────

def check_prerequisites() -> None:
    """Check required commands before any network I/O (S3.1 / S6.5)."""
    missing = [cmd for cmd in REQUIRED_COMMANDS if not shutil.which(cmd)]
    if missing:
        fatal(
            f"Required tools not found: {', '.join(missing)}. "
            "Install them and re-run.",
            EXIT_PREREQ,
        )


# ─── Entry point ─────────────────────────────────────────────────────────────

def main() -> None:
    if platform.system() != "Linux":
        fatal("ciu requires Linux.", EXIT_PREREQ)

    # Check prerequisites BEFORE any network I/O (S3.1)
    check_prerequisites()

    parser = argparse.ArgumentParser(
        prog="get.py",
        description="ciu transactional installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  sudo python3 get.py install --config HOST.toml\n"
            "  python3 get.py install --config HOST.toml --scope user\n"
            "  sudo python3 get.py update\n"
            "  python3 get.py status\n"
            "  sudo python3 get.py rollback\n"
            "  sudo python3 get.py enroll --authorized-key 'ssh-ed25519 AAAA... ciu@control'"
            " --controller control.example.net\n"
        ),
    )

    # Auth flags (S5)
    tok_ex = parser.add_mutually_exclusive_group()
    tok_ex.add_argument(
        "--github-token", metavar="TOKEN",
        help="GitHub token (WARN: leaks via shell history/ps; prefer file or env)",
    )
    tok_ex.add_argument("--github-token-file", metavar="FILE",
                        help="File containing the GitHub token (chmod 600)")
    tok_ex.add_argument("--github-token-stdin", action="store_true",
                        help="Read GitHub token from stdin (first line)")
    parser.add_argument(
        "--manifest-pubkey", metavar="KEY_OR_FILE",
        help="minisign public key (base64) or path to .pub file for manifest verification",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    p_install = subparsers.add_parser("install", help="Fresh install")
    p_install.add_argument("--config", metavar="HOST.toml", help="Host config file")
    p_install.add_argument("--version", metavar="TAG", help="Pin a specific release")
    p_install.add_argument("--scope", choices=["system", "user"], default="system",
                           help="Install scope (default: system)")
    p_install.add_argument("--variant", metavar="NAME",
                           help="Select a per-interpreter variant (multi-variant releases)")

    p_update = subparsers.add_parser("update", help="Update to latest (or --version)")
    p_update.add_argument("--version", metavar="TAG")
    p_update.add_argument("--scope", choices=["system", "user"], default="system")
    p_update.add_argument("--variant", metavar="NAME",
                          help="Override the remembered variant (multi-variant releases)")

    p_status = subparsers.add_parser("status", help="Show current/previous versions + health")
    p_status.add_argument("--scope", choices=["system", "user"], default="system")

    p_rollback = subparsers.add_parser("rollback", help="Re-point current to a previous release")
    p_rollback.add_argument("--version", metavar="TAG", help="Roll back to specific version")
    p_rollback.add_argument("--scope", choices=["system", "user"], default="system")

    # Host enrollment (CIU S14.7 / cmru KI-24). The flag set here is normative:
    # ciu's `host enroll` prints the exact one-liner an admin runs on a bare host.
    p_enroll = subparsers.add_parser(
        "enroll",
        help="Enrol this host: install + deploy user + authorized key + host-key fingerprints",
    )
    p_enroll.add_argument("--authorized-key", metavar="KEY", required=True,
                          help="Control-generated public key line: '<type> <base64> [comment]'")
    p_enroll.add_argument("--controller", metavar="FQDN", required=True,
                          help="FQDN of the controller this host is being enrolled for")
    p_enroll.add_argument("--user", metavar="USER", default="ciu",
                          help="Deploy user to create or confirm (default: ciu)")
    p_enroll.add_argument("--name", metavar="NAME",
                          help="Host name for the printed completion command (default: a placeholder)")
    p_enroll.add_argument("--from", dest="from_pattern", metavar="PATTERN",
                          help='Restrict the key with from="PATTERN" (source-address restriction)')
    p_enroll.add_argument("--docker", action="store_true",
                          help="Add the deploy user to the docker group (refused when absent)")
    p_enroll.add_argument("--no-install", action="store_true",
                          help="Skip the install step (user + key + fingerprints only)")
    p_enroll.add_argument("--scope", choices=["system", "user"], default="system",
                          help="Install scope for the install step (default: system)")

    args = parser.parse_args()
    token = _resolve_token(args)

    if args.command == "install":
        do_install(args, token)
    elif args.command == "update":
        do_update(args, token)
    elif args.command == "status":
        do_status(args)
    elif args.command == "rollback":
        do_rollback(args, token)
    elif args.command == "enroll":
        do_enroll(args, token)
    else:
        parser.print_help()
        raise SystemExit(EXIT_CONFIG)


if __name__ == "__main__":
    main()
