#!/usr/bin/env python3
"""tls-edge installer — get.py  (generated by cmru get-py)

Transactional, fail-closed installer: private-repo asset auth, per-release
directories (own venv each) with an atomic `current` symlink, state + rollback,
system/user scope, offline hash-locked wheel install, SHA256 verification of the
bundle and a verified manifest that covers everything that runs, and an optional
minisign signature over that manifest (verified whenever a key is configured).

Usage
-----
Install (system scope, requires root):
    sudo python3 get.py install [--config HOST.toml]

Install (user scope):
    python3 get.py install --scope user

Pin a specific version (installs exactly that tag):
    sudo python3 get.py install --version tls-edge-v0.2.0

Select a variant (multi-variant releases — one asset per interpreter):
    sudo python3 get.py install --variant py311

Update (latest, or --version X):
    sudo python3 get.py update

Status:
    python3 get.py status

Rollback (to the recorded previous release):
    sudo python3 get.py rollback

Requires: python3 (stdlib only); system tools: python3, docker
"""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import platform
import re
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

# ─── Project constants (injected by cmru get-py) ─────────────────────────────
REPO_OWNER       = "volkb79-2"
REPO_NAME        = "vbpub"
TAG_PREFIX       = "tls-edge-v"
ASSET_SUFFIX     = ".tar.xz"
MANIFEST_NAME    = "manifest.json"
SIGNATURE_NAME   = "manifest.json.minisig"
ENTRYPOINT       = ""           # "" means no adapter
# minisign public key (base64). "" => the release is unsigned (SHA256 only).
MANIFEST_PUBKEY  = ""
REQUIRED_COMMANDS: List[str] = ["python3", "docker"]
PRESERVE_PATHS: List[str]    = ["ciu-stack/ciu.toml.j2", "edge-proxy/.env"]
# [(glob, distribution), ...] in install order (cli-extended is hoisted first at install).
WHEEL_SPECS: List[Tuple[str, str]] = []
# Commands exposed as <root>/bin/<cmd> -> ../current/venv/bin/<cmd>.
LAUNCHERS: List[str] = []
# Per-interpreter variants (S-REL.6). [] ⇒ one unambiguous single-asset release.
# When non-empty the release carries one asset per variant, named <tag>-<name><suffix>,
# and the operator MUST select one at install time with --variant NAME (no silent default).
VARIANTS: List[dict] = []  # e.g. [{"name": "py39", "label": "Python 3.9"}, ...]

# Scope directories (injected)
INSTALL_DIR_SYSTEM = "/opt/tls-edge"
INSTALL_DIR_USER   = "tls-edge"   # leaf; expanded under XDG_DATA_HOME

RELEASES_API = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases"

# Allowed hosts for HTTPS downloads (transport hardening S5)
_ALLOWED_HOSTS = {
    "api.github.com",
    "github.com",
    "objects.githubusercontent.com",
    "uploads.github.com",
}

MANIFEST_SCHEMA = 1
_MAX_MANIFEST_BYTES = 8 * 1024 * 1024
_SHA256_RE = re.compile(r"[0-9a-f]{64}")
_TAG_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+-]*")
_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+-]*")

# ─── Exit codes (S8 / CIU S10.3) ─────────────────────────────────────────────
EXIT_OK     = 0
EXIT_FAIL   = 1   # download / verify / install / adapter failure
EXIT_CONFIG = 2   # configuration / schema failure
EXIT_PREREQ = 3   # missing prerequisite / required env absent


# ─── ANSI helpers (suppressed when not a TTY) ────────────────────────────────
_NO_COLOUR = not sys.stdout.isatty()
_C = {"RED": "\033[0;31m", "YEL": "\033[0;33m", "GRN": "\033[0;32m",
      "CYN": "\033[0;36m", "BLD": "\033[1m",    "RST": "\033[0m"}


def _c(code: str, text: str) -> str:
    return text if _NO_COLOUR else f"{_C[code]}{text}{_C['RST']}"


def info(msg: str)  -> None: print(f"{_c('CYN', '==>')} {msg}", flush=True)
def ok(msg: str)    -> None: print(f"{_c('GRN', '  ok')} {msg}", flush=True)
def warn(msg: str)  -> None: print(f"{_c('YEL', 'warn')} {msg}", file=sys.stderr, flush=True)
def err(msg: str)   -> None: print(f"{_c('RED', ' err')} {msg}", file=sys.stderr, flush=True)
def hr()            -> None: print("─" * 79)


def fatal(msg: str, code: int = EXIT_FAIL) -> None:
    err(msg)
    raise SystemExit(code)


# ─── Project extensions (cmru `[project.installer] extensions`) ──────────────
# A fragment inlined by cmru at the extensions marker (below) registers itself with a
# top-level `_EXTENSIONS.append(register)`; `main()` calls each registered
# function with the subparsers action and expects {command: handler} back.
# Handlers are called as handler(args, token).
_EXTENSIONS: List[Callable[[argparse._SubParsersAction],
                           Dict[str, Callable[[argparse.Namespace, Optional[str]], None]]]] = []

# STABILITY CONTRACT. These are the ONLY template top-level names an extension
# fragment may reference (cmru checks this at render time; anything else is a
# render error). Renaming, changing the signature of, or removing a name here
# requires updating every in-repo fragment in the same change. Names are only
# ever added deliberately, with the fragment that needs them.
#
# Semantics fragments may rely on:
#   do_install(args, token)  args needs .scope, .version, .variant, .config (all
#                            optional via getattr); installs/updates and returns,
#                            or raises SystemExit on failure.
#   _current_version(root)   the installed release TAG (str) or None.
#   _root_dir(scope)         the install root Path for "system" or "user".
EXTENSION_API = (
    "EXIT_CONFIG",
    "EXIT_FAIL",
    "EXIT_PREREQ",
    "_EXTENSIONS",
    "_c",
    "_current_version",
    "_root_dir",
    "do_install",
    "fatal",
    "hr",
    "info",
    "ok",
    "warn",
)


# ─── Token / auth helpers (S5) ───────────────────────────────────────────────

def _validate_token_file(path: Path) -> None:
    """Reject token files with bad permissions or foreign owner."""
    if not path.exists():
        fatal(f"Token file not found: {path}", EXIT_CONFIG)
    if path.is_symlink():
        real = path.resolve()
        if not real.exists():
            fatal(f"Token file symlink broken: {path}", EXIT_CONFIG)
    st = path.stat()
    if st.st_mode & 0o077:
        fatal(
            f"Token file {path} has loose permissions ({oct(st.st_mode & 0o777)}); "
            "chmod 600 it.", EXIT_CONFIG
        )
    if st.st_uid != os.getuid():
        fatal(
            f"Token file {path} is owned by uid {st.st_uid}, "
            f"not current user {os.getuid()}.",
            EXIT_CONFIG,
        )


def _resolve_token(args: argparse.Namespace) -> Optional[str]:
    """Resolve GitHub token: CLI arg > file/stdin > env (S5).

    Warns when --github-token is used (leaks via ps/shell history).
    Token is never logged in full. An empty --github-token-stdin is a
    configuration error, never a silent "no token".
    """
    token: Optional[str] = None

    # Lowest priority: env
    for env_var in ("CMRU_GITHUB_TOKEN", "GITHUB_TOKEN"):
        v = os.environ.get(env_var, "").strip()
        if v:
            token = v
            break

    # stdin
    if getattr(args, "github_token_stdin", False):
        line = sys.stdin.readline().strip()
        if not line:
            fatal(
                "--github-token-stdin was given but stdin is empty. Under "
                "`curl ... | python3 -` stdin is the script itself; use "
                "--github-token-file or the CMRU_GITHUB_TOKEN environment variable.",
                EXIT_CONFIG,
            )
        token = line

    # file
    tok_file = getattr(args, "github_token_file", None)
    if tok_file:
        fp = Path(tok_file).expanduser()
        _validate_token_file(fp)
        line = fp.read_text().strip()
        if line:
            token = line

    # CLI arg (highest priority — warn)
    tok_arg = getattr(args, "github_token", None)
    if tok_arg:
        warn("--github-token leaks via shell history/process list; "
             "prefer --github-token-file or CMRU_GITHUB_TOKEN env var.")
        token = tok_arg

    return token or None


# ─── Transport hardening (S5) ─────────────────────────────────────────────────

def _check_url(url: str) -> None:
    """Reject http:// and unknown hosts (applied to the request AND every redirect hop)."""
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https":
        fatal(f"HTTPS-only: refusing {parsed.scheme}:// URL: {url}", EXIT_FAIL)
    host = parsed.hostname or ""
    allowed = (
        host in _ALLOWED_HOSTS
        or host.endswith(".githubusercontent.com")
        or host.endswith(".github.com")
    )
    if not allowed:
        fatal(f"Host not in allowlist: {host}", EXIT_FAIL)


class _RedirectGuard(urllib.request.HTTPRedirectHandler):
    """Every redirect hop is re-checked (HTTPS + allowlist) and NEVER carries the token (S5)."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # type: ignore[override]
        _check_url(newurl)
        new_req = super().redirect_request(req, fp, code, msg, headers, newurl)
        if new_req is not None:
            new_req.remove_header("Authorization")
            new_req.remove_header("authorization")
        return new_req


def _gh_request(
    url: str,
    *,
    token: Optional[str] = None,
    accept: str = "application/vnd.github+json",
    stream_to: Optional[Path] = None,
    timeout: int = 30,
) -> Tuple[int, bytes]:
    """Low-level GitHub request.

    Per S5 / release.py invariant: only sends Authorization when token is present.
    An empty 'Bearer ' header causes GitHub to 401 even on public repos.
    """
    _check_url(url)
    headers: dict = {"Accept": accept, "User-Agent": "tls-edge/get.py"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    opener = urllib.request.build_opener(_RedirectGuard)
    try:
        with opener.open(req, timeout=timeout) as resp:
            if stream_to:
                with open(stream_to, "wb") as fh:
                    shutil.copyfileobj(resp, fh)
                return resp.status, b""
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        body = exc.read() if exc.fp else b""
        return exc.code, body
    except urllib.error.URLError as exc:
        fatal(f"Network error fetching {url}: {exc}", EXIT_FAIL)
        return 0, b""  # unreachable


def _gh_json(url: str, token: Optional[str] = None) -> object:
    status, body = _gh_request(url, token=token)
    if status in (401, 403):
        hint = " (token may be missing or expired)" if not token else ""
        fatal(f"GitHub API {status}{hint}: {url}", EXIT_FAIL)
    if status >= 400:
        fatal(
            f"GitHub API {status}: {url}\n"
            f"  {body.decode('utf-8', errors='replace')}",
            EXIT_FAIL,
        )
    try:
        return json.loads(body)
    except ValueError:
        fatal(f"GitHub API returned invalid JSON: {url}", EXIT_FAIL)
        return None  # unreachable


# ─── Tag / release resolution ─────────────────────────────────────────────────

def _semver_key(tag: str) -> tuple:
    ver = tag[len(TAG_PREFIX):]
    tokens: list = []
    for chunk in ver.replace("-", ".").split("."):
        for run in re.findall(r"\d+|\D+", chunk):
            tokens.append((0, int(run), "") if run.isdigit() else (1, 0, run))
    return tuple(tokens)


def resolve_latest_tag(token: Optional[str] = None) -> str:
    """Return the highest-semver tls-edge-v* release tag."""
    releases = _gh_json(f"{RELEASES_API}?per_page=100", token=token)
    if not isinstance(releases, list):
        fatal("GitHub releases listing has an unexpected shape.", EXIT_FAIL)
    candidates = [
        r["tag_name"] for r in releases
        if isinstance(r, dict)
        and isinstance(r.get("tag_name"), str)
        and r["tag_name"].startswith(TAG_PREFIX)
        and not r.get("draft")
        and not r.get("prerelease")
    ]
    if not candidates:
        fatal(
            f"No tls-edge releases found (prefix: {TAG_PREFIX!r}). "
            "Check network access or pass --version.",
            EXIT_FAIL,
        )
    return max(candidates, key=_semver_key)


def normalize_tag(version_arg: str) -> str:
    if version_arg.startswith(TAG_PREFIX):
        return version_arg
    # Drop a single leading "v" prefix only — NOT str.lstrip('v'), which strips a
    # whole leading run of 'v' chars (so "v1.0.0" is fine but a hypothetical multi-'v'
    # or 'v'-initial token would be corrupted). Prefix-strip, not charset-strip.
    bare = version_arg[1:] if version_arg.startswith("v") else version_arg
    return f"{TAG_PREFIX}{bare}"


def _validate_tag(tag: str) -> str:
    """A tag becomes a URL component and a directory name: refuse anything odd."""
    if not tag.startswith(TAG_PREFIX) or not _TAG_RE.fullmatch(tag) or ".." in tag:
        fatal(f"Refusing release tag {tag!r}: expected {TAG_PREFIX}<version> "
              "(letters, digits, '.', '_', '+', '-').", EXIT_CONFIG)
    return tag


def _resolve_tag(args: argparse.Namespace, token: Optional[str]) -> str:
    """`--version X` installs exactly X; without it, resolve the latest and print it."""
    version = getattr(args, "version", None)
    if version:
        tag = _validate_tag(normalize_tag(version))
        info(f"Pinned version: {_c('BLD', tag)}")
        return tag
    info("Resolving latest release ...")
    tag = _validate_tag(resolve_latest_tag(token))
    info(f"Latest: {_c('BLD', tag)}  (resolved; pass --version {tag} to pin it)")
    return tag


def _find_asset_by_name(assets: list, name: str) -> Optional[dict]:
    for a in assets:
        if a.get("name") == name:
            return a
    return None


# ─── Variant selection (S-REL.6 / S6.12) ──────────────────────────────────────

def _variant_names() -> List[str]:
    return [v["name"] for v in VARIANTS]


def _format_variants() -> str:
    lines = []
    for v in VARIANTS:
        label = v.get("label")
        lines.append(f"  - {v['name']}" + (f"  ({label})" if label else ""))
    return "\n".join(lines)


def _variant_marker_path(root: Path) -> Path:
    """Where the selected variant is remembered so `update` keeps the host's choice."""
    return root / "shared" / ".variant"


def _persist_variant(root: Path, variant: Optional[str]) -> None:
    if not variant:
        return
    marker = _variant_marker_path(root)
    marker.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(marker, (variant + "\n").encode("utf-8"), 0o644)


def _installed_variant(root: Path) -> Optional[str]:
    """The variant recorded by the last install/update (None if single-asset / unset)."""
    marker = _variant_marker_path(root)
    if marker.exists():
        return marker.read_text(encoding="utf-8").strip() or None
    return None


def _select_variant(args: argparse.Namespace, root: Path) -> Optional[str]:
    """Resolve which per-interpreter variant to install/update (S6.12).

    Returns None for a single-asset release (VARIANTS empty). Otherwise, in priority order:
    an explicit --variant (validated); a variant
    remembered from a prior install (so `update` stays on the same interpreter); an
    interactive prompt on a TTY; else a fatal error listing the choices. No silent default.
    """
    if not VARIANTS:
        return None
    names = _variant_names()
    chosen = getattr(args, "variant", None)
    if chosen:
        if chosen not in names:
            fatal(f"Unknown --variant {chosen!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
        return chosen
    marker = _variant_marker_path(root)
    if marker.exists():
        prev = marker.read_text(encoding="utf-8").strip()
        if prev in names:
            info(f"Using previously selected variant: {_c('BLD', prev)}")
            return prev
    if sys.stdin.isatty():
        info("This release ships multiple variants — choose one:")
        for i, v in enumerate(VARIANTS, 1):
            label = v.get("label")
            print(f"  {i}) {v['name']}" + (f"  ({label})" if label else ""))
        raw = input("Variant [name or number]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(VARIANTS):
            return VARIANTS[int(raw) - 1]["name"]
        if raw in names:
            return raw
        fatal(f"Invalid selection {raw!r}. Available:\n{_format_variants()}", EXIT_CONFIG)
    fatal(
        "This release ships multiple per-interpreter variants; none was selected.\n"
        f"Re-run with --variant NAME. Available variants:\n{_format_variants()}",
        EXIT_CONFIG,
    )
    return None  # unreachable (fatal raises)


# ─── Download (public or private) (S5) ────────────────────────────────────────

def _download_asset(tag: str, asset_name: str, dest: Path, token: Optional[str]) -> None:
    """Download a release asset — private path if token present, public URL otherwise."""
    if token:
        # Private path: resolve release → list assets → find by name → download by ID
        status, body = _gh_request(
            f"{RELEASES_API}/tags/{tag}", token=token
        )
        if status >= 400:
            fatal(f"Could not fetch release {tag} (HTTP {status})", EXIT_FAIL)
        try:
            rel = json.loads(body)
        except ValueError:
            fatal(f"Release {tag}: GitHub returned invalid JSON.", EXIT_FAIL)
        assets = rel.get("assets", []) if isinstance(rel, dict) else []
        asset = _find_asset_by_name(assets, asset_name)
        if asset is None:
            fatal(
                f"Asset {asset_name!r} not found in release {tag}. "
                f"Available: {[a.get('name') for a in assets]}",
                EXIT_FAIL,
            )
        # Download by asset ID — the token is never forwarded across the redirect (S5)
        asset_url = (
            f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/assets/{asset['id']}"
        )
        status, _ = _gh_request(asset_url, token=token, accept="application/octet-stream",
                                stream_to=dest, timeout=300)
    else:
        url = (
            f"https://github.com/{REPO_OWNER}/{REPO_NAME}"
            f"/releases/download/{tag}/{asset_name}"
        )
        status, _ = _gh_request(url, token=None, accept="application/octet-stream",
                                stream_to=dest, timeout=300)
    if status != 200:
        fatal(f"Download of {asset_name} failed (HTTP {status}).", EXIT_FAIL)
    if not dest.exists() or dest.stat().st_size == 0:
        fatal(f"Download produced empty file: {dest}", EXIT_FAIL)


# ─── SHA256 + minisign verification (S4) ─────────────────────────────────────

def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _parse_sidecar(sidecar: Path, asset_name: str) -> str:
    """Strictly parse `<64 hex>[  <asset name>]` (one line); anything else is EXIT_FAIL."""
    try:
        text = sidecar.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        fatal(f"SHA256 sidecar {sidecar.name} is unreadable.", EXIT_FAIL)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    parts = lines[0].split() if len(lines) == 1 else []
    if len(parts) not in (1, 2) or not _SHA256_RE.fullmatch(parts[0].lower()):
        fatal(f"SHA256 sidecar {sidecar.name} is malformed: expected one line "
              "'<64 hex digits>  <file name>'.", EXIT_FAIL)
    if len(parts) == 2 and parts[1].lstrip("*") != asset_name:
        fatal(f"SHA256 sidecar names {parts[1]!r}, not {asset_name!r}.", EXIT_FAIL)
    return parts[0].lower()


def _verify_sha256(asset: Path, sidecar: Path) -> None:
    expected = _parse_sidecar(sidecar, asset.name)
    actual   = _sha256(asset)
    if actual != expected:
        fatal(
            f"SHA256 mismatch — refusing to extract.\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok("SHA256 checksum verified.")


def _verify_minisign(manifest: Path, sig: Path, pubkey: str, tag: str, digest: str) -> None:
    """Verify the manifest signature with the pinned key (`minisign -V -P KEY`).

    The signed trusted comment must also bind this tag and this exact manifest digest
    (`project=<name> tag=<tag> manifest_sha256=<hex>`), so an old signed release cannot be
    replayed as a new one.
    """
    cmd = ["minisign", "-V", "-m", str(manifest), "-x", str(sig), "-P", pubkey]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        fatal(
            f"minisign signature verification FAILED for {manifest.name}:\n"
            f"  {result.stderr.strip()}",
            EXIT_FAIL,
        )
    comment = ""
    for line in result.stdout.splitlines():
        if line.startswith("Trusted comment:"):
            comment = line[len("Trusted comment:"):].strip()
    fields = dict(tok.split("=", 1) for tok in comment.split() if "=" in tok)
    if fields.get("tag") != tag or fields.get("manifest_sha256") != digest:
        fatal(
            "minisign trusted comment does not bind this release "
            f"(want tag={tag} manifest_sha256={digest}; got {comment!r}).",
            EXIT_FAIL,
        )
    ok("Manifest signature verified (minisign).")


def download_and_verify(
    tag: str,
    workdir: Path,
    token: Optional[str],
    variant: Optional[str] = None,
) -> Path:
    """Download the bundle + sidecar and verify SHA256; return the bundle path.

    ``variant`` (S-REL.6) selects the per-interpreter asset ``<tag>-<variant>{suffix}``;
    ``None`` uses the single-asset name ``<tag>{suffix}``. The signature and manifest
    are verified separately, from the bundle bytes (`_verify_manifest`)."""
    asset_name   = f"{tag}-{variant}{ASSET_SUFFIX}" if variant else f"{tag}{ASSET_SUFFIX}"
    sidecar_name = f"{asset_name}.sha256"
    asset   = workdir / asset_name
    sidecar = workdir / sidecar_name

    info(f"Downloading {asset_name} ...")
    _download_asset(tag, asset_name, asset, token)

    info(f"Downloading {sidecar_name} ...")
    _download_asset(tag, sidecar_name, sidecar, token)

    info("Verifying SHA256 checksum ...")
    _verify_sha256(asset, sidecar)
    return asset


# ─── Bundle reading + the verified manifest (INS-01 / R5) ────────────────────

def _bundle_members(tf: tarfile.TarFile) -> List[Tuple[tarfile.TarInfo, str]]:
    """(member, path relative to the bundle's single top-level directory) for every
    member below it. Anything outside that one directory, or duplicated, is EXIT_FAIL."""
    members = tf.getmembers()
    tops = {Path(m.name).parts[0] for m in members if Path(m.name).parts}
    if len(tops) != 1:
        fatal(f"Bundle must have exactly one top-level directory; found {sorted(tops)}.",
              EXIT_FAIL)
    result: List[Tuple[tarfile.TarInfo, str]] = []
    seen = set()
    for m in members:
        parts = Path(m.name).parts
        if len(parts) < 2:
            if not m.isdir():
                fatal(f"Bundle member {m.name!r} sits outside the top-level directory.",
                      EXIT_FAIL)
            continue
        rel = str(Path(*parts[1:]))
        if rel in seen:
            fatal(f"Bundle contains {rel!r} more than once.", EXIT_FAIL)
        seen.add(rel)
        result.append((m, rel))
    return result


def _read_member(tf: tarfile.TarFile, member: tarfile.TarInfo, what: str) -> bytes:
    if not member.isfile() or member.size > _MAX_MANIFEST_BYTES:
        fatal(f"Bundle {what} is not a regular file of sane size.", EXIT_FAIL)
    handle = tf.extractfile(member)
    if handle is None:
        fatal(f"Bundle {what} is unreadable.", EXIT_FAIL)
    return handle.read()


def _read_bundle_manifest(bundle: Path) -> Tuple[bytes, Optional[bytes]]:
    """The manifest bytes (and signature bytes, if present) read straight from the bundle.
    These in-memory bytes are the ONLY manifest used after verification."""
    with tarfile.open(bundle, "r:xz") as tf:
        by_rel = {rel: m for m, rel in _bundle_members(tf)}
        if MANIFEST_NAME not in by_rel:
            fatal(f"Bundle does not contain {MANIFEST_NAME}; refusing to install.", EXIT_FAIL)
        manifest = _read_member(tf, by_rel[MANIFEST_NAME], MANIFEST_NAME)
        sig = None
        if SIGNATURE_NAME in by_rel:
            sig = _read_member(tf, by_rel[SIGNATURE_NAME], SIGNATURE_NAME)
    return manifest, sig


def _parse_manifest(data: bytes, tag: str) -> dict:
    """Parse + validate the manifest: unparseable / unknown schema / wrong tag => EXIT_FAIL."""
    try:
        manifest = json.loads(data.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        fatal(f"{MANIFEST_NAME} is not valid UTF-8 JSON; refusing to install.", EXIT_FAIL)
    if not isinstance(manifest, dict):
        fatal(f"{MANIFEST_NAME} must be a JSON object.", EXIT_FAIL)
    schema = manifest.get("schema_version")
    if isinstance(schema, bool) or schema != MANIFEST_SCHEMA:
        fatal(f"{MANIFEST_NAME} has unsupported schema_version {schema!r} "
              f"(this installer reads {MANIFEST_SCHEMA}).", EXIT_FAIL)
    if "tag" in manifest and manifest["tag"] != tag:
        fatal(f"{MANIFEST_NAME} is for tag {manifest['tag']!r}, not the requested {tag!r}.",
              EXIT_FAIL)
    bare = tag[len(TAG_PREFIX):]
    if "version" in manifest and manifest["version"] != bare:
        fatal(f"{MANIFEST_NAME} is for version {manifest['version']!r}, not {bare!r}.",
              EXIT_FAIL)
    return manifest


def _verify_manifest(
    manifest_bytes: bytes, sig_bytes: Optional[bytes], tag: str, workdir: Path,
) -> Tuple[dict, str]:
    """Signature (when a key is configured) + parse. Returns (manifest, sha256 hex)."""
    digest = hashlib.sha256(manifest_bytes).hexdigest()
    if MANIFEST_PUBKEY:
        if not sig_bytes:
            fatal(f"Bundle does not contain {SIGNATURE_NAME}; this project's releases "
                  "must be signed.", EXIT_FAIL)
        mpath, spath = workdir / "manifest.verify", workdir / "manifest.verify.minisig"
        mpath.write_bytes(manifest_bytes)
        spath.write_bytes(sig_bytes)
        info(f"Verifying {MANIFEST_NAME} with minisign ...")
        _verify_minisign(mpath, spath, MANIFEST_PUBKEY, tag, digest)
    else:
        info("This release is unsigned (no manifest_pubkey configured): integrity rests "
             "on HTTPS + the SHA256 sidecar + the manifest hashes.")
    return _parse_manifest(manifest_bytes, tag), digest


def _hex_digest(value: object, what: str) -> str:
    if not isinstance(value, str) or not _SHA256_RE.fullmatch(value.lower()):
        fatal(f"{MANIFEST_NAME}: {what} has no valid sha256.", EXIT_FAIL)
    return value.lower()  # type: ignore[union-attr]


def _check_size(entry: dict, actual: int, what: str) -> None:
    if "size" in entry and (isinstance(entry["size"], bool) or entry["size"] != actual):
        fatal(f"{MANIFEST_NAME}: size mismatch for {what} "
              f"(manifest {entry['size']!r}, got {actual}).", EXIT_FAIL)


def _regular_file(path: Path, what: str) -> Path:
    if path.is_symlink() or not path.is_file():
        fatal(f"{what} is missing or not a regular file: {path}", EXIT_FAIL)
    return path


def _verify_files(tree: Path, manifest: dict) -> None:
    """Every manifest `files` entry must exist and match; the adapter MUST be covered."""
    files = manifest.get("files", {})
    if not isinstance(files, dict):
        fatal(f"{MANIFEST_NAME}: 'files' must be an object.", EXIT_FAIL)
    if ENTRYPOINT and ENTRYPOINT not in files:
        fatal(f"Adapter {ENTRYPOINT!r} is not covered by {MANIFEST_NAME} 'files'; "
              "refusing to run unhashed code as root.", EXIT_FAIL)
    for rel, entry in files.items():
        if not isinstance(entry, dict):
            fatal(f"{MANIFEST_NAME}: files[{rel!r}] must be an object.", EXIT_FAIL)
        expected = _hex_digest(entry.get("sha256"), f"files[{rel!r}]")
        path = _regular_file(tree / rel, f"Manifest file {rel!r}")
        _check_size(entry, path.stat().st_size, f"files[{rel!r}]")
        if _sha256(path) != expected:
            fatal(f"SHA256 mismatch for {rel!r} against {MANIFEST_NAME}.", EXIT_FAIL)


# ─── Extraction safety (S6.3) ─────────────────────────────────────────────────

_UNSAFE_TYPES = {tarfile.BLKTYPE, tarfile.CHRTYPE, tarfile.FIFOTYPE}


def _safe_member(member: tarfile.TarInfo, dest: Path) -> bool:
    """Return False (and warn) if member should be rejected (S6.3 safety rules)."""
    parts = Path(member.name).parts
    if member.name.startswith("/"):
        warn(f"Rejecting absolute path: {member.name}")
        return False
    if ".." in parts:
        warn(f"Rejecting path traversal: {member.name}")
        return False
    try:
        resolved = (dest / member.name).resolve()
        resolved.relative_to(dest.resolve())
    except ValueError:
        warn(f"Rejecting escape path: {member.name}")
        return False
    if member.type in _UNSAFE_TYPES:
        warn(f"Rejecting device/fifo node: {member.name}")
        return False
    if member.issym() or member.islnk():
        link_target = member.linkname or ""
        if link_target.startswith("/"):
            warn(f"Rejecting absolute symlink: {member.name} -> {link_target}")
            return False
        if ".." in Path(link_target).parts:
            warn(f"Rejecting traversal symlink: {member.name} -> {link_target}")
            return False
    return True


def _pre_scan_members(tf: tarfile.TarFile, dest: Path) -> List[tarfile.TarInfo]:
    """Strip the top-level dir, drop the manifest/signature (kept separately, verified),
    and refuse the whole bundle if any member is unsafe (fail closed)."""
    import copy as _copy
    members = []
    for member, rel in _bundle_members(tf):
        if rel in (MANIFEST_NAME, SIGNATURE_NAME):
            continue
        m = _copy.copy(member)
        m.name = rel
        if not _safe_member(m, dest):
            fatal(f"Bundle member {member.name!r} is unsafe; refusing to extract.", EXIT_FAIL)
        members.append(m)
    return members


def _extract_bundle(bundle: Path, tree: Path) -> None:
    """Extract bundle into the release tree with safety pre-scan + filter='data' (py>=3.12)."""
    tree.mkdir(parents=True, exist_ok=True)
    info(f"Extracting to {tree} ...")
    with tarfile.open(bundle, "r:xz") as tf:
        members = _pre_scan_members(tf, tree)
        kw: dict = {}
        if sys.version_info >= (3, 12):
            kw["filter"] = "data"
        tf.extractall(tree, members=members, **kw)
    ok("Extraction complete.")


# ─── Wheels: hash-locked, offline install into the release's own venv (R9) ───

def _canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _wheel_order() -> List[Tuple[str, str]]:
    """WHEEL_SPECS with cli-extended first (KI-51), the rest in declared order
    (dependencies before the tool wheels)."""
    first = [s for s in WHEEL_SPECS if _canon(s[1]) == "cli-extended"]
    return first + [s for s in WHEEL_SPECS if _canon(s[1]) != "cli-extended"]


def _wheel_version(wheel: Path) -> str:
    parts = wheel.name[:-len(".whl")].split("-")
    if len(parts) < 5 or not parts[1]:
        fatal(f"Not a valid wheel file name: {wheel.name}", EXIT_FAIL)
    return parts[1]


def _verify_wheel_sha256(wheel_path: Path, manifest: dict, distribution: str) -> str:
    """Check the wheel against manifest[distribution] (SPEC B Seam-3): a missing entry,
    a missing/invalid sha256, a wrong file name or a size/hash mismatch is EXIT_FAIL.
    Returns the expected sha256."""
    entry = manifest.get(distribution)
    if not isinstance(entry, dict):
        fatal(f"{MANIFEST_NAME} has no entry for distribution {distribution!r}.", EXIT_FAIL)
    expected = _hex_digest(entry.get("sha256"), f"distribution {distribution!r}")
    if "wheel" in entry and entry["wheel"] != wheel_path.name:
        fatal(f"{MANIFEST_NAME} lists wheel {entry['wheel']!r} for {distribution!r}, "
              f"bundle has {wheel_path.name!r}.", EXIT_FAIL)
    _check_size(entry, wheel_path.stat().st_size, f"distribution {distribution!r}")
    actual = _sha256(wheel_path)
    if actual != expected:
        fatal(
            f"Wheel SHA256 mismatch for {wheel_path.name} (distribution: {distribution!r}):\n"
            f"  expected: {expected}\n"
            f"  got:      {actual}",
            EXIT_FAIL,
        )
    ok(f"Wheel {wheel_path.name} ({distribution}) sha256 verified.")
    return expected


def _check_venv_prereqs() -> None:
    """`python3 -m venv` needs ensurepip (Debian: the python3-venv package)."""
    try:
        import venv  # noqa: F401
        import ensurepip  # noqa: F401
    except ImportError:
        fatal("Python's venv/ensurepip modules are missing. Install the python3-venv "
              "package (Debian/Ubuntu: apt install python3-venv) and re-run.", EXIT_PREREQ)


def _pip_env() -> Dict[str, str]:
    return {k: v for k, v in os.environ.items() if not k.startswith("PIP_")}


def _run_checked(cmd: List[str], what: str) -> None:
    result = subprocess.run(cmd, env=_pip_env(), capture_output=True, text=True)
    if result.returncode != 0:
        fatal(f"{what} failed (exit {result.returncode}):\n"
              f"{(result.stdout + result.stderr).strip()}", EXIT_FAIL)


def _install_wheels(tree: Path, release: Path, manifest: dict) -> None:
    """Build <release>/venv from <release>/wheelhouse only: verified wheels, a lock of
    `name==version --hash=sha256:...`, `pip install --isolated --no-index --require-hashes`,
    then `pip check`."""
    if not WHEEL_SPECS:
        return
    wheelhouse = release / "wheelhouse"
    wheelhouse.mkdir()
    lock_lines: List[str] = []
    for glob_pat, distribution in _wheel_order():
        matches = sorted(tree.glob(glob_pat))
        if len(matches) != 1:
            fatal(
                f"Expected exactly one wheel in the bundle for {distribution!r} "
                f"(glob: {glob_pat!r}); found {len(matches)}.",
                EXIT_FAIL,
            )
        wheel = _regular_file(matches[0], f"Wheel for {distribution!r}")
        digest = _verify_wheel_sha256(wheel, manifest, distribution)
        shutil.copy2(wheel, wheelhouse / wheel.name)
        lock_lines.append(f"{distribution}=={_wheel_version(wheel)} --hash=sha256:{digest}")
    lock = release / "requirements.lock"
    lock.write_text("\n".join(lock_lines) + "\n", encoding="utf-8")

    venv_dir = release / "venv"
    info(f"Setting up private venv at {venv_dir} ...")
    _run_checked([sys.executable, "-m", "venv", str(venv_dir)], "venv creation")
    py = str(venv_dir / "bin" / "python")
    info("Installing hash-locked wheels (offline, --no-index) ...")
    _run_checked(
        [py, "-m", "pip", "install", "--isolated", "--disable-pip-version-check",
         "--no-index", "--find-links", str(wheelhouse), "--require-hashes", "-r", str(lock)],
        "pip install",
    )
    _run_checked([py, "-m", "pip", "check", "--isolated", "--disable-pip-version-check"],
                 "pip check")
    ok(f"Installed {len(lock_lines)} wheel(s).")


# ─── Atomic file helpers ──────────────────────────────────────────────────────

def _fsync_dir(path: Path) -> None:
    fd = os.open(str(path), os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _atomic_write(path: Path, data: bytes, mode: int = 0o644) -> None:
    """Write `data` to `path` atomically (temp file in the same dir, fsync, rename)."""
    tmp = path.with_name(f".{path.name}.tmp")
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
    fd = os.open(str(tmp), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
    except BaseException:
        tmp.unlink()
        raise
    os.replace(tmp, path)
    _fsync_dir(path.parent)


# ─── Adapter invocation (Seam 1 — S3.3) ──────────────────────────────────────

def _layout(release: Path, legacy: bool = False) -> Tuple[Path, Path, Path]:
    """(tree, venv_dir, manifest path) of a release directory."""
    if legacy:  # pre-W1 layout: content at the release root, one shared <root>/venv
        return release, release.parent.parent / "venv", release / MANIFEST_NAME
    return release / "tree", release / "venv", release / MANIFEST_NAME


def _python_for(venv_dir: Path) -> str:
    return str(venv_dir / "bin" / "python") if WHEEL_SPECS else sys.executable


def _invoke_adapter(
    action: str,
    release_dir: Path,
    root: Path,
    venv_dir: Path,
    token: Optional[str] = None,
    manifest_path: Optional[Path] = None,
    config_path: Optional[Path] = None,
) -> None:
    """Invoke project adapter; non-zero exit aborts before the current swap (S3.3).

    ``release_dir`` is the content root (the release's ``tree/``)."""
    if not ENTRYPOINT:
        return  # no adapter (tls-edge minimal path)
    adapter = release_dir / ENTRYPOINT
    if not adapter.exists():
        fatal(f"Adapter entrypoint not found: {adapter}", EXIT_FAIL)
    cmd = [
        _python_for(venv_dir), str(adapter), action,
        "--release-root", str(release_dir),
        "--config", str(config_path or root / "shared" / "host.toml"),
        "--manifest", str(manifest_path or release_dir.parent / MANIFEST_NAME),
    ]
    info(f"Invoking adapter: {action} ...")
    # Strip GitHub token from child environment (S5)
    child_env = {
        k: v for k, v in os.environ.items()
        if k not in ("GITHUB_TOKEN", "CMRU_GITHUB_TOKEN", "GITHUB_PUSH_PAT")
    }
    result = subprocess.run(cmd, env=child_env)
    if result.returncode != 0:
        fatal(
            f"Adapter exited {result.returncode} (action={action!r}); "
            "transaction aborted — current release unchanged.",
            EXIT_FAIL,
        )
    ok(f"Adapter {action} succeeded.")


# ─── Preserve / shared config (S3.2) ─────────────────────────────────────────

def _copy_preserve_to_shared(root: Path, src_release: Optional[Path] = None) -> None:
    """Copy preserved paths from the current release tree into <root>/shared/."""
    shared = root / "shared"
    source = src_release
    if source is None:
        state = _read_state(root)
        if state:
            source = _layout(_release_dir(root, state["current"]["name"]),
                             bool(state.get("legacy")))[0]
    if source is None or not source.is_dir():
        return
    for rel in PRESERVE_PATHS:
        src = source / rel
        dest = shared / rel
        if src.exists() and not src.is_symlink():
            dest.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(src, dest)
            else:
                shutil.copy2(src, dest)
            ok(f"Preserved: {rel}")


def _restore_preserve_from_shared(root: Path, release_dir: Path) -> None:
    """Symlink preserved paths from shared/ into the new release tree."""
    shared = root / "shared"
    for rel in PRESERVE_PATHS:
        src = shared / rel
        if src.exists():
            dest = release_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.exists() or dest.is_symlink():
                if dest.is_dir() and not dest.is_symlink():
                    shutil.rmtree(dest)
                else:
                    dest.unlink()
            dest.symlink_to(src)
            ok(f"Linked shared/{rel} into release.")


def _install_host_config(root: Path, source: Path) -> None:
    """`--config FILE` => <root>/shared/host.toml, mode 0600, written atomically."""
    shared = root / "shared"
    shared.mkdir(parents=True, exist_ok=True)
    _atomic_write(shared / "host.toml", source.read_bytes(), 0o600)
    ok(f"Host config installed at {shared / 'host.toml'} (0600).")


def _check_config_arg(args: argparse.Namespace) -> Optional[Path]:
    given = getattr(args, "config", None)
    if not given:
        return None
    path = Path(given).expanduser()
    if not path.is_file():
        fatal(f"--config file not found or not a regular file: {path}", EXIT_CONFIG)
    return path


# ─── Scope resolution (S3.2) ─────────────────────────────────────────────────

def _root_dir(scope: str) -> Path:
    if scope == "system":
        return Path(INSTALL_DIR_SYSTEM)
    xdg = os.environ.get("XDG_DATA_HOME", "").strip()
    base = Path(xdg) if xdg else Path.home() / ".local" / "share"
    return base / INSTALL_DIR_USER


# ─── Exclusive lock + SIGINT/SIGTERM handler ─────────────────────────────────

_active_staging: Optional[Path] = None
_lock_fd: Optional[int] = None


def _cleanup_on_signal(sig: int, _frame: object) -> None:
    global _active_staging, _lock_fd
    if _active_staging and _active_staging.exists():
        shutil.rmtree(_active_staging, ignore_errors=True)
    if _lock_fd is not None:
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
        except OSError:
            pass
    sys.exit(EXIT_FAIL)


signal.signal(signal.SIGINT, _cleanup_on_signal)
signal.signal(signal.SIGTERM, _cleanup_on_signal)


class _Lock:
    def __init__(self, root: Path) -> None:
        self._path = root / ".lock"

    def __enter__(self) -> "_Lock":
        global _lock_fd
        self._path.parent.mkdir(parents=True, exist_ok=True)
        _lock_fd = os.open(str(self._path), os.O_CREAT | os.O_WRONLY, 0o600)
        try:
            fcntl.flock(_lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            info("Another installer is running; waiting for lock ...")
            fcntl.flock(_lock_fd, fcntl.LOCK_EX)
        return self

    def __exit__(self, *_: object) -> None:
        global _lock_fd
        if _lock_fd is not None:
            fcntl.flock(_lock_fd, fcntl.LOCK_UN)
            os.close(_lock_fd)
            _lock_fd = None


# ─── Releases, state, rollback (R7) ───────────────────────────────────────────
#
# <root>/releases/<tag>-<manifest12>[-<variant>]/
#     tree/  venv/  wheelhouse/  requirements.lock  manifest.json [manifest.json.minisig]
#     release.json  .complete     (.incomplete while being built; .complete is written last)
# <root>/current  -> releases/<name>            (atomic symlink swap)
# <root>/state.json  {schema, current, previous, history}   (atomic write)
# <root>/bin/<cmd> -> ../current/venv/bin/<cmd>

def _release_dir(root: Path, name: str) -> Path:
    if not isinstance(name, str) or not _NAME_RE.fullmatch(name) or ".." in name:
        fatal(f"state.json names an invalid release {name!r}; refusing.", EXIT_FAIL)
    return root / "releases" / name


def _release_name(tag: str, digest: str, variant: Optional[str]) -> str:
    return f"{tag}-{digest[:12]}" + (f"-{variant}" if variant else "")


def _entry_of(release: Path) -> dict:
    try:
        entry = json.loads((release / "release.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        fatal(f"{release.name}: release.json is missing or invalid.", EXIT_FAIL)
    if not isinstance(entry, dict) or entry.get("name") != release.name:
        fatal(f"{release.name}: release.json does not describe this release.", EXIT_FAIL)
    return entry


def _read_state(root: Path) -> Optional[dict]:
    """The install state, or None when nothing is installed.

    * a pre-W1 install (a `current` symlink, no state.json) is returned as a synthetic
      state with `legacy: True` — the next install/update migrates it;
    * a `current` symlink that disagrees with state.json (crash between the swap and
      the state write) is reconciled from the target's own release.json."""
    state_path = root / "state.json"
    current = root / "current"
    target = current.resolve() if current.is_symlink() else None
    if not state_path.exists():
        if target is not None and target.is_dir():
            return {"schema": 1, "legacy": True, "previous": None, "history": [],
                    "current": {"name": target.name, "tag": target.name,
                                "manifest_sha256": None, "variant": _installed_variant(root)}}
        return None
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
        cur = state["current"]
        assert isinstance(cur["name"], str) and isinstance(cur["tag"], str)
        assert isinstance(state.get("history", []), list)
    except (OSError, ValueError, KeyError, TypeError, AssertionError):
        fatal(f"{state_path} is unreadable or malformed; refusing to touch the install.",
              EXIT_FAIL)
    if target is None or not target.is_dir():
        fatal(f"state.json records {cur['name']!r} but {current} is missing or dangling.",
              EXIT_FAIL)
    if target.name != cur["name"]:
        if not (target / ".complete").exists():
            fatal(f"{current} points at {target.name!r}, which is not a complete release.",
                  EXIT_FAIL)
        warn(f"state.json was behind {current} (interrupted run); reconciling to {target.name}.")
        state = {"schema": 1, "current": _entry_of(target), "previous": cur,
                 "history": list(state.get("history", [])) + [cur]}
        _write_state(root, state)
    return state


def _write_state(root: Path, state: dict) -> None:
    state = dict(state, schema=1)
    state["history"] = list(state.get("history", []))[-20:]
    _atomic_write(root / "state.json",
                  (json.dumps(state, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def _current_version(root: Path) -> Optional[str]:
    """The installed release tag, or None."""
    state = _read_state(root)
    return state["current"]["tag"] if state else None


def _atomic_swap_current(root: Path, new_release: Path) -> None:
    """Atomic current swap: tmp symlink + os.replace (S6.3)."""
    current = root / "current"
    tmp_link = root / ".current.tmp"
    if tmp_link.is_symlink():
        tmp_link.unlink()
    os.symlink(os.path.relpath(new_release, root), tmp_link)
    os.replace(tmp_link, current)
    ok(f"current -> {new_release.name}")


def _prune_releases(root: Path, state: Optional[dict]) -> None:
    """Delete every release dir except current and previous (this also cleans `.incomplete`
    and any leftover pre-W1 content); never touches what `current` points at."""
    releases = root / "releases"
    if not releases.is_dir():
        return
    keep = set()
    if state:
        keep.add(state["current"]["name"])
        if state.get("previous"):
            keep.add(state["previous"]["name"])
    cur = root / "current"
    if cur.is_symlink():
        keep.add(cur.resolve().name)
    for entry in sorted(releases.iterdir()):
        if entry.name in keep:
            continue
        info(f"Pruning release: {entry.name}")
        if entry.is_dir() and not entry.is_symlink():
            shutil.rmtree(entry, ignore_errors=True)
        else:
            entry.unlink()
    legacy_venv = root / "venv"
    if state and not state.get("legacy") and legacy_venv.is_dir() and not legacy_venv.is_symlink():
        info("Removing the pre-W1 shared venv.")
        shutil.rmtree(legacy_venv, ignore_errors=True)


def _discard_release(root: Path, release: Path) -> None:
    """Remove a release this run created, and `releases/` itself if that leaves it empty."""
    shutil.rmtree(release, ignore_errors=True)
    try:
        (root / "releases").rmdir()
    except OSError:
        pass


def _write_launchers(root: Path) -> None:
    """<root>/bin/<cmd> -> ../current/venv/bin/<cmd> (atomic per launcher)."""
    if not LAUNCHERS:
        return
    bindir = root / "bin"
    bindir.mkdir(parents=True, exist_ok=True)
    for cmd in LAUNCHERS:
        tmp = bindir / f".{cmd}.tmp"
        if tmp.is_symlink():
            tmp.unlink()
        os.symlink(f"../current/venv/bin/{cmd}", tmp)
        os.replace(tmp, bindir / cmd)
        ok(f"Launcher: {bindir / cmd}")


def _verify_release_intact(root: Path, entry: dict) -> Path:
    """Re-verify a recorded release before it is (re-)used: complete marker, the recorded
    manifest digest, the signature (when a key is configured) and the adapter hash."""
    release = _release_dir(root, entry["name"])
    if not (release / ".complete").is_file():
        fatal(f"Release {entry['name']} is not complete; refusing to use it.", EXIT_FAIL)
    manifest_path = _regular_file(release / MANIFEST_NAME, f"{entry['name']} manifest")
    manifest_bytes = manifest_path.read_bytes()
    digest = hashlib.sha256(manifest_bytes).hexdigest()
    if digest != entry.get("manifest_sha256"):
        fatal(f"Release {entry['name']}: recorded manifest digest does not match "
              "the manifest on disk.", EXIT_FAIL)
    sig_bytes = None
    if MANIFEST_PUBKEY:
        sig_bytes = _regular_file(release / SIGNATURE_NAME, f"{entry['name']} signature").read_bytes()
    with tempfile.TemporaryDirectory() as tmp:
        manifest, _ = _verify_manifest(manifest_bytes, sig_bytes, entry["tag"], Path(tmp))
    _verify_files(release / "tree", manifest)
    return release


def _build_release(
    root: Path, release: Path, bundle: Path, manifest_bytes: bytes,
    sig_bytes: Optional[bytes], manifest: dict, entry: dict,
) -> None:
    """Create the release at its final path, `.incomplete` until everything succeeded."""
    release.mkdir(parents=True)
    (release / ".incomplete").write_text("", encoding="utf-8")
    tree = release / "tree"
    _extract_bundle(bundle, tree)
    _atomic_write(release / MANIFEST_NAME, manifest_bytes)
    if sig_bytes is not None and MANIFEST_PUBKEY:
        _atomic_write(release / SIGNATURE_NAME, sig_bytes)
    _verify_files(tree, manifest)
    _restore_preserve_from_shared(root, tree)
    _install_wheels(tree, release, manifest)
    for cmd in LAUNCHERS:
        if not (release / "venv" / "bin" / cmd).exists():
            fatal(f"Launcher {cmd!r} is not provided by this release's venv.", EXIT_FAIL)
    _atomic_write(release / "release.json",
                  (json.dumps(entry, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def _commit_release(
    root: Path, release: Path, state: Optional[dict], entry: dict, action: str,
    token: Optional[str], config_arg: Optional[Path], fresh: bool,
) -> None:
    """Adapter, `.complete`, swap, state. Any failure before the swap removes a release
    that this run created (never a pre-existing, verified one)."""
    global _active_staging
    tree, venv_dir, manifest_path = _layout(release)
    try:
        _invoke_adapter(action, tree, root, venv_dir, token,
                        manifest_path=manifest_path, config_path=config_arg)
        if fresh:
            (release / ".complete").write_text("", encoding="utf-8")
            (release / ".incomplete").unlink()
        _atomic_swap_current(root, release)
    except BaseException:
        if fresh:
            _discard_release(root, release)
        _active_staging = None
        raise
    _active_staging = None
    # A pre-W1 (legacy) current has no per-release venv or digest: it is not a rollback
    # target, so it becomes neither `previous` nor history.
    old = state["current"] if state and not state.get("legacy") else None
    history = list(state.get("history", [])) if old else []
    previous = old
    if old and old["name"] == entry["name"]:
        previous = state.get("previous")
    elif old:
        history.append(old)
    _write_state(root, {"current": entry, "previous": previous, "history": history})
    _persist_variant(root, entry.get("variant"))


def _transact(args: argparse.Namespace, token: Optional[str], root: Path, install: bool) -> None:
    """The one install/update transaction (called with the exclusive lock held)."""
    global _active_staging
    state = _read_state(root)
    if install and state is not None:
        warn(f"Existing install found ({state['current']['tag']}). Running update instead.")
    if not install and state is None:
        fatal(f"No install found at {root}. Run 'python3 get.py install' first.", EXIT_FAIL)
    _prune_releases(root, state)  # crash recovery: `.incomplete` dirs from a dead run
    config_arg = _check_config_arg(args)

    tag = _resolve_tag(args, token)
    variant = _select_variant(args, root)
    if variant:
        info(f"Variant: {_c('BLD', variant)}")

    legacy = bool(state and state.get("legacy"))
    if state and not legacy:
        cur = state["current"]
        if cur["tag"] == tag and cur.get("variant") == variant:
            _verify_release_intact(root, cur)
            ok(f"Already at {tag}. Nothing to do (recorded manifest re-verified).")
            return
    if legacy:
        warn("Existing install uses the pre-W1 layout; migrating (current is swapped "
             "atomically; the old release dir and shared venv are removed afterwards).")

    with tempfile.TemporaryDirectory() as tmp:
        bundle = download_and_verify(tag, Path(tmp), token, variant)
        manifest_bytes, sig_bytes = _read_bundle_manifest(bundle)
        manifest, digest = _verify_manifest(manifest_bytes, sig_bytes, tag, Path(tmp))
        name = _release_name(tag, digest, variant)
        entry = {"name": name, "tag": tag, "variant": variant, "manifest_sha256": digest}
        release = _release_dir(root, name)
        if state is not None:
            _copy_preserve_to_shared(root)
        fresh = not release.exists()
        if fresh:
            _active_staging = release
            (root / "releases").mkdir(parents=True, exist_ok=True)
            try:
                _build_release(root, release, bundle, manifest_bytes, sig_bytes, manifest, entry)
            except BaseException:
                _discard_release(root, release)
                _active_staging = None
                raise
        else:
            info(f"Re-using verified release {name}.")
            _verify_release_intact(root, entry)
        _commit_release(root, release, state, entry, "apply" if state else "bootstrap",
                        token, config_arg, fresh)
    if config_arg:
        _install_host_config(root, config_arg)
    _write_launchers(root)
    _prune_releases(root, _read_state(root))


# ─── Commands ────────────────────────────────────────────────────────────────

def _preflight(root: Path, scope: str, verb: str) -> None:
    """Everything that must hold before any network I/O or state change."""
    if scope == "system" and os.geteuid() != 0:
        fatal(f"system-scope {verb} requires root (sudo).", EXIT_PREREQ)
    if MANIFEST_PUBKEY and not shutil.which("minisign"):
        fatal("This project's releases are signed and `minisign` is not installed. "
              "Install the minisign package (Debian/Ubuntu: apt install minisign) "
              "and re-run.", EXIT_PREREQ)
    if WHEEL_SPECS:
        _check_venv_prereqs()


def do_install(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    hr()
    print(f"  {_c('BLD', 'tls-edge')}  install  scope={scope}  root={root}")
    hr()

    _preflight(root, scope, "install")
    with _Lock(root):
        _transact(args, token, root, install=True)

    hr()
    ok(f"tls-edge {_current_version(root)} installed at {root}")
    print()


def do_update(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    _preflight(root, scope, "update")
    with _Lock(root):
        _transact(args, token, root, install=False)

    ok(f"Updated to {_current_version(root)}.")
    print()


def do_rollback(args: argparse.Namespace, token: Optional[str]) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    _preflight(root, scope, "rollback")
    with _Lock(root):
        state = _read_state(root)
        if state is None:
            fatal(f"No install found at {root}.", EXIT_FAIL)
        if state.get("legacy"):
            fatal("This install uses the pre-W1 layout and has no recorded previous "
                  "release; run 'python3 get.py update' once to migrate it.", EXIT_FAIL)
        wanted = getattr(args, "version", None)
        if wanted:
            tag = normalize_tag(wanted)
            pool = ([state["previous"]] if state.get("previous") else []) \
                + list(reversed(state.get("history", [])))
            target = next((e for e in pool if e["tag"] == tag
                           and e["name"] != state["current"]["name"]
                           and (_release_dir(root, e["name"]) / ".complete").exists()), None)
            if target is None:
                fatal(f"No complete recorded release for {tag} to roll back to.", EXIT_FAIL)
        else:
            target = state.get("previous")
            if target is None:
                fatal("No previous release to roll back to.", EXIT_FAIL)

        info(f"Rolling back to {target['tag']} ({target['name']}) ...")
        release = _verify_release_intact(root, target)
        tree, venv_dir, manifest_path = _layout(release)
        _invoke_adapter("rollback", tree, root, venv_dir, token, manifest_path=manifest_path)
        old = state["current"]
        _atomic_swap_current(root, release)
        _write_state(root, {"current": target, "previous": old,
                            "history": list(state.get("history", [])) + [old]})
        _persist_variant(root, target.get("variant"))
        _write_launchers(root)
        _prune_releases(root, _read_state(root))
    ok(f"Rolled back to {target['tag']}.")


def do_status(args: argparse.Namespace) -> None:
    scope = getattr(args, "scope", "system")
    root = _root_dir(scope)

    state = _read_state(root)
    if state is None:
        print(f"tls-edge: not installed at {root}")
        return

    cur = state["current"]
    legacy = bool(state.get("legacy"))
    print(f"tls-edge status  scope={scope}  root={root}")
    print(f"  current:  {cur['tag']}" + ("  (pre-W1 layout; run update to migrate)" if legacy else ""))
    if not legacy:
        print(f"  release:  {cur['name']}  manifest sha256 {cur['manifest_sha256'][:12]}")
        print(f"  signed:   {'yes (minisign)' if MANIFEST_PUBKEY else 'no (SHA256 only)'}")
    if state.get("previous"):
        print(f"  previous: {state['previous']['tag']}")

    if ENTRYPOINT:
        release = _release_dir(root, cur["name"])
        tree, venv_dir, manifest_path = _layout(release, legacy)
        cmd = [
            _python_for(venv_dir), str(tree / ENTRYPOINT), "health",
            "--release-root", str(tree),
            "--config", str(root / "shared" / "host.toml"),
            "--manifest", str(manifest_path),
        ]
        result = subprocess.run(cmd)
        if result.returncode == 0:
            ok("health check passed.")
        else:
            warn(f"health check exited {result.returncode}.")


# ─── Pre-flight checks (S3.1) ────────────────────────────────────────────────

def check_prerequisites() -> None:
    """Check required commands before any network I/O (S3.1 / S6.5)."""
    missing = [cmd for cmd in REQUIRED_COMMANDS if not shutil.which(cmd)]
    if missing:
        fatal(
            f"Required tools not found: {', '.join(missing)}. "
            "Install them and re-run.",
            EXIT_PREREQ,
        )


# ─── Entry point ─────────────────────────────────────────────────────────────

def main() -> None:
    if platform.system() != "Linux":
        fatal("tls-edge requires Linux.", EXIT_PREREQ)

    # Check prerequisites BEFORE any network I/O (S3.1)
    check_prerequisites()

    parser = argparse.ArgumentParser(
        prog="get.py",
        description="tls-edge transactional installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  sudo python3 get.py install [--config HOST.toml]\n"
            "  python3 get.py install --scope user\n"
            "  sudo python3 get.py update [--version TAG]\n"
            "  python3 get.py status\n"
            "  sudo python3 get.py rollback\n"
        ),
    )

    # Auth flags (S5)
    tok_ex = parser.add_mutually_exclusive_group()
    tok_ex.add_argument(
        "--github-token", metavar="TOKEN",
        help="GitHub token (WARN: leaks via shell history/ps; prefer file or env)",
    )
    tok_ex.add_argument("--github-token-file", metavar="FILE",
                        help="File containing the GitHub token (chmod 600)")
    tok_ex.add_argument("--github-token-stdin", action="store_true",
                        help="Read GitHub token from stdin (first line)")

    subparsers = parser.add_subparsers(dest="command", required=True)

    p_install = subparsers.add_parser("install", help="Fresh install")
    p_install.add_argument("--config", metavar="HOST.toml",
                           help="Host config file, installed as <root>/shared/host.toml (0600)")
    p_install.add_argument("--version", metavar="TAG", help="Pin a specific release")
    p_install.add_argument("--scope", choices=["system", "user"], default="system",
                           help="Install scope (default: system)")
    p_install.add_argument("--variant", metavar="NAME",
                           help="Select a per-interpreter variant (multi-variant releases)")

    p_update = subparsers.add_parser("update", help="Update to latest (or --version)")
    p_update.add_argument("--version", metavar="TAG")
    p_update.add_argument("--scope", choices=["system", "user"], default="system")
    p_update.add_argument("--variant", metavar="NAME",
                          help="Override the remembered variant (multi-variant releases)")

    p_status = subparsers.add_parser("status", help="Show current/previous versions + health")
    p_status.add_argument("--scope", choices=["system", "user"], default="system")

    p_rollback = subparsers.add_parser("rollback", help="Re-point current to the previous release")
    p_rollback.add_argument("--version", metavar="TAG", help="Roll back to a specific recorded version")
    p_rollback.add_argument("--scope", choices=["system", "user"], default="system")

    # Project extensions (cmru `[project.installer] extensions`): each registered
    # function adds its own subparsers and returns {command: handler}. A command
    # name that duplicates a core command or another extension's is a render-time
    # contract violation, refused before any argument is parsed.
    extension_handlers: Dict[str, Callable[[argparse.Namespace, Optional[str]], None]] = {}
    for register in _EXTENSIONS:
        known = set(subparsers.choices)
        try:
            handlers = register(subparsers)
        except (argparse.ArgumentError, ValueError) as exc:  # argparse >= 3.11: ValueError
            fatal(f"extension {getattr(register, '__name__', register)!r} "
                  f"registers a duplicate command: {exc}", EXIT_CONFIG)
        for command, handler in handlers.items():
            if command in known or command in extension_handlers:
                fatal(f"extension command {command!r} duplicates an existing command "
                      "(core or another extension).", EXIT_CONFIG)
            if command not in subparsers.choices:
                fatal(f"extension command {command!r} returned a handler but "
                      "registered no subparser of that name.", EXIT_CONFIG)
            extension_handlers[command] = handler

    args = parser.parse_args()
    token = _resolve_token(args)

    if args.command == "install":
        do_install(args, token)
    elif args.command == "update":
        do_update(args, token)
    elif args.command == "status":
        do_status(args)
    elif args.command == "rollback":
        do_rollback(args, token)
    elif args.command in extension_handlers:
        extension_handlers[args.command](args, token)
    else:
        parser.print_help()
        raise SystemExit(EXIT_CONFIG)


if __name__ == "__main__":
    main()
