"""O1 — ``PythonAdapter.has_executable_code``, the one place this adapter
classifies file CONTENT (consulted by ``evaluate.py`` only for a considered,
non-test source file absent from the coverage artifact entirely — srdm's
NoCode distinction).

Each construct family A-098 names for P06 (decorators, async/compound
statements, docstrings, comments, pragma tokens) gets its own dedicated,
committed literal snippet and an INDEPENDENTLY reasoned expected boolean —
never a value generated by calling this adapter and trusting the result.
Every construct below resolves from its own SINGLE reported line (a
decorator line, an async-def header, a compound-statement header, a
docstring line, a comment line, a pragma-carrying line) — genuine
multi-line statement interior-line attribution is out of scope (A-098,
P07's future ``statement_spans``).

The negative this defends (verbatim, O1): *replacing AST/token
classification with nonblank-line counting, or omitting one construct,
changes a literal expected set.* ``test_a_multiline_docstring_alone_...``
below is the fixture engineered specifically to catch exactly that
substitution: several nonblank lines, zero real code.
"""

from __future__ import annotations

from assay.adapters.python import PythonAdapter

ADAPTER = PythonAdapter()

# --- decorators ---


def test_a_decorated_function_has_executable_code():
    source = "@staticmethod\ndef helper():\n    return 1\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


# --- async / compound statements ---


def test_an_async_function_definition_has_executable_code():
    source = "async def fetch():\n    return 1\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_an_if_statement_header_has_executable_code():
    source = "if True:\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_a_for_statement_header_has_executable_code():
    source = "for _ in range(1):\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_a_with_statement_header_has_executable_code():
    source = "with open('x') as f:\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_a_try_statement_header_has_executable_code():
    source = "try:\n    pass\nexcept Exception:\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_a_class_definition_has_executable_code():
    source = "class Thing:\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


# --- docstrings ---


def test_a_module_docstring_alone_has_no_executable_code():
    source = '"""Just a module docstring, nothing else."""\n'
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is False


def test_a_multiline_docstring_alone_would_fool_a_nonblank_line_counter():
    """The key negative-detecting fixture: five nonblank lines, all of them
    inside ONE bare-string statement -- a naive nonblank-line-count
    heuristic reports True (5 > 0); the correct AST-based classification
    reports False, because coverage.py never traces a docstring at all."""
    source = (
        '"""\n'
        "This is a long module-level docstring,\n"
        "spanning several physical lines,\n"
        "with no real executable statement\n"
        "anywhere in this file at all.\n"
        '"""\n'
    )
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is False


# --- comments ---


def test_comments_alone_have_no_executable_code():
    source = "# a top-level comment\n# and another one\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is False


# --- pragma tokens ---


def test_a_pragma_token_alone_has_no_executable_code():
    """A bare pragma comment with nothing else is still just a comment --
    it does not, by itself, create any code for this method to find."""
    source = "# pragma: no cover\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is False


def test_a_real_statement_carrying_a_pragma_still_has_executable_code():
    """The pragma token does not erase the statement it decorates -- that
    line's EXCLUSION from coverage is the coverage artifact's own concern
    (its ``excluded_lines``), never this method's; a file whose only
    statement happens to carry ``# pragma: no cover`` still genuinely has
    code, and this method must say so."""
    source = "x = 1  # pragma: no cover\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


# --- combined non-code fixture (docstring + comment + pragma together) ---


def test_docstring_comment_and_pragma_together_still_have_no_code():
    source = (
        '"""Module docstring."""\n'
        "# a comment\n"
        "# pragma: no cover\n"
    )
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is False


# --- edges: empty file, unparseable file ---


def test_an_empty_file_has_no_executable_code():
    assert ADAPTER.has_executable_code("pkg/mod.py", "") is False


def test_unparseable_source_is_treated_as_having_code():
    """Fail CLOSED (srdm's asymmetry): a real SyntaxError is never a silent
    excuse -- the worst case is a visible false failure, never a
    measurement gap this method quietly waves through."""
    source = "def broken(:\n    pass\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True


def test_source_with_an_embedded_null_byte_is_treated_as_having_code():
    """A NUL byte is unparseable too (confirmed live on this interpreter,
    Python 3.14: ``ast.parse`` raises ``SyntaxError`` for it, not
    ``ValueError`` -- both exception types are still caught by this method,
    which is why both are named in its ``except`` clause, matching
    dstdns's own ``statement_spans`` defensive pairing) -- it must fail
    closed the same way as any other unparseable source."""
    source = "x = 1\x00\n"
    assert ADAPTER.has_executable_code("pkg/mod.py", source) is True
