"""O1/O4 -- ``GoAdapter.has_executable_code``, the narrow deterministic
Go lexer/parser (A-087): does *text* contain a top-level function
declaration with a real body?

The four base fixtures are PORTED LITERALLY (not invented) from
``shared-ramdisk-depot-manager/tools/covergate/hascode_test.go`` -- the
exact comment-only, declarations-only, function-body-present, and
bodyless-declaration cases the handoff names by id. Everything past that is
A-104's own explicit hazard list, each given its own committed fixture and
independently reasoned expected boolean -- never a value generated by
calling this adapter and trusting the result.

The negative this defends (verbatim, O1): *regex-only func matching
misclassifies comments, strings, declarations, or malformed input in the
paired fixtures.* Several fixtures below are engineered specifically to
catch exactly that: a real ``func`` word buried inside a comment or string
that a substring search would wrongly find, and a real function body that a
naive scanner blind to brace-depth or bracket-depth would wrongly miss or
wrongly refuse.
"""

from __future__ import annotations

from assay.adapters.go import GoAdapter

ADAPTER = GoAdapter()

# --- ported literally from hascode_test.go ---


def test_a_comment_only_file_has_no_executable_code():
    """srdm's own motivating incident (hascode_test.go's own comment): a
    doc.go with nothing but a package clause and a long comment produces no
    cover blocks at all."""
    source = (
        "// Package expose will own the exposure drivers.\n"
        "//\n"
        "// Empty until P03.\n"
        "package expose\n"
    )
    assert ADAPTER.has_executable_code("expose/doc.go", source) is False


def test_a_declarations_only_file_has_no_executable_code():
    """go test -cover instruments function bodies and nothing else, so
    types, constants and package-level vars yield no blocks. Also exercises
    a real, terminated interpreted-string literal (``"nope"``) as ordinary
    content, not a hazard."""
    source = (
        "package x\n"
        "\n"
        'import "errors"\n'
        "\n"
        "type Kind string\n"
        "\n"
        "const (\n"
        '\tKindA Kind = "a"\n'
        '\tKindB Kind = "b"\n'
        ")\n"
        "\n"
        'var ErrNope = errors.New("nope")\n'
    )
    assert ADAPTER.has_executable_code("x/types.go", source) is False


def test_a_file_with_a_function_body_has_executable_code():
    source = "package x\n\nfunc Add(a, b int) int { return a + b }\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_bodiless_declaration_is_not_executable_code():
    """An assembly or cgo stub has no Go statements to instrument."""
    source = "package x\n\nfunc fastPath(x uint64) uint64\n"
    assert ADAPTER.has_executable_code("x/asm.go", source) is False


# --- A-104: comments and literals must be stripped before `func` search ---


def test_a_line_comment_containing_func_and_braces_is_not_misclassified():
    source = "package x\n\n// func Fake() { not real }\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_a_block_comment_containing_func_and_braces_is_not_misclassified():
    source = "package x\n\n/* func Fake() { not real } */\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_a_line_comment_running_to_end_of_file_with_no_trailing_newline():
    """The file simply ends inside the comment -- no ``\\n`` to find."""
    source = "package x\n\n// trailing comment, no newline after it"
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_a_block_comment_spanning_multiple_lines_is_stripped_correctly():
    source = "package x\n\n/*\nfunc Fake() {\n\tnot real\n}\n*/\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_an_unterminated_block_comment_is_treated_as_malformed():
    """The comment swallows the rest of the file, including a real `func`
    later in it -- correctly refused (True) rather than guessed at."""
    source = "package x\n\n/* never closed\nfunc F() {\n\treturn\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_string_literal_containing_func_and_braces_is_not_misclassified():
    """Also exercises backslash-escaped quotes inside the string: the
    escaped quotes must not end the literal early and expose the `func`
    text they surround."""
    source = 'package x\n\nvar s = "func Fake() { say \\"hi\\" }"\n'
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_an_escaped_quote_inside_a_string_does_not_end_it_early():
    source = 'package x\n\nvar s = "a quote: \\" still inside"\n\nfunc F() {\n\treturn\n}\n'
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_unterminated_string_literal_is_treated_as_malformed():
    """Go interpreted strings may never contain a bare newline -- the
    literal ends the file's trustworthiness right there, even though a
    real `func` follows later."""
    source = 'package x\n\nvar s = "never closed\nfunc F() {\n\treturn\n}\n'
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_unterminated_string_literal_that_runs_to_end_of_file_is_malformed():
    """The OTHER way a quoted literal can be unterminated: no closing quote
    and no bare newline either -- the file simply ends inside it."""
    source = 'package x\n\nvar s = "never closed'
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_raw_string_literal_spanning_multiple_lines_is_not_misclassified():
    source = "package x\n\nvar s = `func Fake() {\n\tnot real\n}`\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is False


def test_an_unterminated_raw_string_literal_is_treated_as_malformed():
    source = "package x\n\nvar s = `never closed\n\nfunc F() {\n\treturn\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_rune_literal_containing_a_brace_character_does_not_corrupt_brace_depth():
    """The sharpest form of the negative: `'{'` is a single-character rune
    literal, not a real brace. If it were not recognised as a rune literal
    at all, its own `{` would wrongly increment brace depth and the REAL
    top-level `func F() {}` below would then be (wrongly) seen as nested
    inside a nonexistent enclosing brace and never even considered."""
    source = "package x\n\nvar r = '{'\n\nfunc F() {\n\treturn\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_escaped_quote_rune_literal_is_skipped_correctly():
    source = "package x\n\nvar r = '\\''\n\nfunc F() {\n\treturn\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_unterminated_rune_literal_is_treated_as_malformed():
    source = "package x\n\nvar r = 'x\nfunc F() {\n\treturn\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


# --- A-104: generics type-parameter brackets ---


def test_a_generics_function_with_a_body_has_executable_code():
    """Real syntax already present in this estate's own
    ``covergate/profile_test.go:137`` (``func keysOf[T any](...)``). The
    generics bracket `[T any]` and the parameter list `(m map[string]T)`
    (itself containing a NESTED bracket) must both be tracked and neither
    mistaken for the body-opening brace."""
    source = (
        "package x\n\n"
        "func keysOf[T any](m map[string]T) []string {\n"
        "\tout := make([]string, 0, len(m))\n"
        "\treturn out\n"
        "}\n"
    )
    assert ADAPTER.has_executable_code("x/f.go", source) is True


# --- word-boundary safety (the O1 negative's "regex-only func matching"
# case, reproduced without any regex at all) ---


def test_a_word_merely_containing_func_before_the_boundary_is_not_misclassified():
    source = "package x\n\nvar myfunction = 1\n"
    assert ADAPTER.has_executable_code("x/v.go", source) is False


def test_a_word_merely_starting_with_func_is_not_misclassified():
    source = "package x\n\nvar funcName = 1\n"
    assert ADAPTER.has_executable_code("x/v.go", source) is False


# --- top-level-only walk (matches PythonAdapter's own tree.body-only
# convention, A-104) ---


def test_a_struct_field_of_function_type_is_not_mistaken_for_a_top_level_func():
    """`Handler func() int` is a FIELD, nested inside the struct's own
    body -- never a top-level declaration. Without brace-depth gating, a
    scanner would find `func` here, then find the struct's own closing
    `}` before any body-opening `{`, and (per this module's own
    stray-closer rule) wrongly conclude the file is malformed/True."""
    source = "package x\n\ntype Config struct {\n\tHandler func() int\n}\n"
    assert ADAPTER.has_executable_code("x/types.go", source) is False


# --- structurally unknown / malformed input renders True (A-087, O4) ---


def test_an_embedded_null_byte_is_treated_as_malformed():
    source = "package x\x00\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_stray_top_level_closing_brace_is_treated_as_malformed():
    source = "package x\n}\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_a_stray_closing_brace_inside_a_signature_is_treated_as_malformed():
    source = "package x\n\nfunc F() }\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_unmatched_closing_paren_inside_a_signature_is_treated_as_malformed():
    """A different unbalanced closer than the stray-brace case above: one
    extra ``)`` with no matching opener, inside the signature's own paren/
    bracket nesting counter (never reaching the brace check at all)."""
    source = "package x\n\nfunc F())\n"
    assert ADAPTER.has_executable_code("x/f.go", source) is True


def test_an_incomplete_signature_reaching_end_of_file_is_treated_as_malformed():
    """Ported literally from hascode_test.go's own ``broken.go``."""
    source = "package x\n\nfunc (((\n"
    assert ADAPTER.has_executable_code("x/broken.go", source) is True


# --- scanning continues correctly past an earlier bodiless declaration ---


def test_a_second_top_level_function_is_found_after_an_earlier_bodiless_one():
    source = (
        "package x\n\n"
        "func fastPath(x uint64) uint64\n\n"
        "func Real() int {\n\treturn 1\n}\n"
    )
    assert ADAPTER.has_executable_code("x/mixed.go", source) is True


def test_two_bodiless_declarations_in_a_row_have_no_executable_code():
    source = (
        "package x\n\n"
        "func fastPath(x uint64) uint64\n\n"
        "func slowPath(x uint64) uint64\n"
    )
    assert ADAPTER.has_executable_code("x/mixed.go", source) is False


# --- edges: empty file ---


def test_an_empty_file_has_no_executable_code():
    assert ADAPTER.has_executable_code("x/empty.go", "") is False
