"""``assay.adapters.sql_lex`` -- the stdlib-only, two-level bounded DDL
lexer (P34/W1, carve ``W3-CARVE-P34-sql-adapter.md`` §3.1, A-281/A-283).

Every construct-level test below is a small, independently-reasoned inline
fixture (never generated by calling :func:`lex_sql` first and trusting its
own output -- A-041/A-080's own "independent oracle" discipline): each
asserts the exact expected mask bytes, built by hand from the fixture's own
text, never merely "does not crash". The real-DDL oracle at the bottom is
the one committed asset (``tests/fixtures/mutation/sql/
dstdns-21-create-workflow-corpus.sql``, pinned dstdns blob ``e188053a``,
tree ``820d4c3c``, revision ``151cda0d``) -- the one place a REAL,
producer-emitted file is the input, matching wave-1 lesson 5.
"""

from __future__ import annotations

from conftest import PROJECT_ROOT

from assay.adapters.sql_lex import lex_sql
from assay.mutation import MutationDiscoveryError

import pytest

FIXTURE_PATH = (
    PROJECT_ROOT
    / "tests"
    / "fixtures"
    / "mutation"
    / "sql"
    / "dstdns-21-create-workflow-corpus.sql"
)


def _line_span(source: bytes, lineno: int) -> tuple[int, int]:
    """The ``(start, end)`` byte offsets of 1-based physical line *lineno*
    in *source* (excluding its own trailing ``\\n``) -- an independent,
    from-scratch line locator built only from ``bytes.split``, never from
    anything :mod:`assay.mutation`/:mod:`assay.adapters.sql_lex` computes,
    so it cannot share a bug with the code under test."""
    lines = source.split(b"\n")
    offset = 0
    for line in lines[: lineno - 1]:
        offset += len(line) + 1
    return offset, offset + len(lines[lineno - 1])


# --- construct 1: -- line comment -------------------------------------------


def test_line_comment_is_masked_to_next_newline():
    source = b"SELECT 1; -- drop everything\nSELECT 2;"
    result = lex_sql(source)
    assert result.mask == b"SELECT 1; " + b" " * len(b"-- drop everything") + b"\nSELECT 2;"


def test_line_comment_at_eof_with_no_trailing_newline_is_masked_to_end():
    source = b"SELECT 1; -- trailing, no newline"
    result = lex_sql(source)
    assert result.mask == b"SELECT 1; " + b" " * len(b"-- trailing, no newline")


# --- construct 2: /* block comment */ (nests) -------------------------------


def test_block_comment_is_masked():
    source = b"A /* comment */ B"
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b"/* comment */") + b" B"


def test_nested_block_comment_is_masked_as_one_construct():
    """PostgreSQL nests ``/* */``, unlike SQL-92: the FIRST ``*/`` does not
    close the comment, only the one matching the outermost ``/*`` does."""
    source = b"A /* outer /* inner */ still-comment */ B"
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b"/* outer /* inner */ still-comment */") + b" B"


def test_unterminated_block_comment_raises_mutation_discovery_error():
    with pytest.raises(MutationDiscoveryError):
        lex_sql(b"A /* never closed")


def test_control_a_terminated_block_comment_does_not_raise():
    """Paired must-succeed control for the unterminated-block-comment probe
    above: the identical construct, properly closed, lexes cleanly."""
    lex_sql(b"A /* closed */ B")


# --- construct 3: '...' string literal --------------------------------------


def test_string_literal_with_embedded_doubled_quote_is_masked_whole():
    source = b"A 'it''s fine' B"
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b"'it''s fine'") + b" B"


def test_unterminated_string_literal_raises_mutation_discovery_error():
    with pytest.raises(MutationDiscoveryError):
        lex_sql(b"A 'never closed")


def test_control_a_terminated_string_literal_does_not_raise():
    lex_sql(b"A 'closed' B")


def test_backslash_is_not_an_escape_in_a_plain_string():
    """standard_conforming_strings = on (measured, carve §9 M22): a bare
    backslash inside a plain ``'...'`` string is an ordinary character, so
    the string terminates at the very next quote regardless of what
    precedes it."""
    source = b"A 'ends\\' B"
    result = lex_sql(source)
    # The string is `'ends\'` (terminates at the quote right after the
    # backslash); ` B` is real code, unmasked.
    assert result.mask == b"A " + b" " * len(b"'ends\\'") + b" B"


# --- construct 4: "..." quoted identifier -----------------------------------


def test_quoted_identifier_with_embedded_doubled_quote_is_masked_whole():
    source = b'A "weird""name" B'
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b'"weird""name"') + b" B"


def test_unterminated_quoted_identifier_raises_mutation_discovery_error():
    with pytest.raises(MutationDiscoveryError):
        lex_sql(b'A "never closed')


def test_control_a_terminated_quoted_identifier_does_not_raise():
    lex_sql(b'A "closed" B')


# --- construct 5: $tag$...$tag$ dollar quote ---------------------------------


def test_bare_dollar_quote_delimiters_are_masked_but_plain_body_is_recovered_as_code():
    """The delimiters (``$$``) are never code and stay masked; the BODY, once
    phase 2 recurses into it, is a plain word sequence with no comment or
    string of its own, so it is recovered as real code, unchanged."""
    source = b"A $$ body text $$ B"
    result = lex_sql(source)
    assert result.dollar_bodies == ((4, 15),)
    assert source[4:15] == b" body text "
    expected = bytearray(source)
    expected[2:4] = b"  "  # opening "$$"
    expected[15:17] = b"  "  # closing "$$"
    assert result.mask == bytes(expected)


def test_named_tag_dollar_quote_delimiters_are_masked_body_recovered_as_code():
    source = b"A $tag$ body text $tag$ B"
    result = lex_sql(source)
    assert result.dollar_bodies == ((7, 18),)
    assert source[7:18] == b" body text "
    expected = bytearray(source)
    expected[2:7] = b"     "  # opening "$tag$"
    expected[18:23] = b"     "  # closing "$tag$"
    assert result.mask == bytes(expected)


def test_dollar_quote_body_containing_the_other_tag_is_not_mistaken_closed():
    """The real hazard this construct exists to defend against: the OUTER
    tag's own closing scan must not stop early at an unrelated dollar-quote
    delimiter appearing inside the body. The body here contains a complete,
    SELF-CLOSING ``$other$ ... $other$`` construct -- phase 1's outer scan
    must skip straight past both occurrences of ``$other$`` and land on the
    real trailing ``$$``, and phase 2's one-level recursion then masks the
    nested construct (its own interior, ``" nested "``, is a body-inside-a-
    body and stays invisible -- the same one-level limit proven directly by
    ``test_a_body_inside_a_body_is_not_recursed_into`` below)."""
    source = b"$$ has $other$ nested $other$ text $$"
    result = lex_sql(source)
    assert result.dollar_bodies == ((2, 35),)
    assert source[2:35] == b" has $other$ nested $other$ text "
    # the outer delimiters are masked
    assert result.mask[0:2] == b"  "
    assert result.mask[35:37] == b"  "
    # code either side of the nested construct is recovered
    assert result.mask[2:7] == source[2:7] == b" has "
    assert result.mask[29:35] == source[29:35] == b" text "
    # the nested "$other$ ... $other$" construct, INCLUDING its own body, is
    # entirely blanked -- a body inside a body is never recursed into
    assert result.mask[7:29] == b" " * 22
    assert b"nested" not in result.mask


def test_positional_parameter_is_not_mistaken_for_a_dollar_quote_opener():
    """``$1`` (a positional parameter) must not open a dollar quote: a
    digit is never a valid dollar-quote tag START byte."""
    source = b"SELECT $1, $2"
    result = lex_sql(source)
    assert result.mask == source
    assert result.dollar_bodies == ()


def test_trailing_bare_dollar_at_eof_is_ordinary_code():
    source = b"SELECT $"
    result = lex_sql(source)
    assert result.mask == source
    assert result.dollar_bodies == ()


def test_tag_broken_by_whitespace_before_its_closing_dollar_is_not_an_opener():
    """``$foo bar$`` -- the identifier scan consumes ``foo``, then hits a
    space (not a valid tag byte) before ever seeing a closing ``$``, so this
    is not a dollar-quote opener at all, and no exception is raised."""
    source = b"A $foo bar$ B"
    result = lex_sql(source)
    assert result.mask == source
    assert result.dollar_bodies == ()


def test_tag_with_no_closing_dollar_anywhere_is_not_an_opener_and_does_not_raise():
    """``$foo`` with no second ``$`` anywhere in the file never even opens a
    tag (the tag-recognition scan itself fails), which is a DIFFERENT case
    from a recognised tag whose BODY never closes (that one raises, tested
    below)."""
    source = b"A $foo"
    result = lex_sql(source)
    assert result.mask == source
    assert result.dollar_bodies == ()


def test_unterminated_dollar_quote_raises_mutation_discovery_error():
    """Unlike the case above, ``$foo$`` IS a recognised, validly-formed
    opening tag; when the identical closing tag never appears anywhere
    later in the file, the construct is genuinely unterminated."""
    with pytest.raises(MutationDiscoveryError):
        lex_sql(b"A $foo$ never closed")


def test_control_a_terminated_named_tag_dollar_quote_does_not_raise():
    lex_sql(b"A $foo$ closed $foo$ B")


# --- construct 6: E'...' escape string --------------------------------------


def test_escape_string_backslash_quote_does_not_terminate():
    source = b"A E'a\\'b' C"
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b"E'a\\'b'") + b" C"


def test_escape_string_recognised_at_start_of_source():
    source = b"E'x' rest"
    result = lex_sql(source)
    assert result.mask == b" " * len(b"E'x'") + b" rest"


def test_escape_string_recognised_after_non_word_byte():
    source = b"A E'x' B"
    result = lex_sql(source)
    assert result.mask == b"A " + b" " * len(b"E'x'") + b" B"


def test_control_identifier_ending_in_e_before_a_quote_is_not_an_escape_string():
    """The word-boundary guard's own must-succeed control: ``WHERE'x'`` has
    an 'E' immediately before the quote, but it is the tail of the word
    ``WHERE``, not a standalone escape-string prefix, so this is an
    ordinary plain string, and the plain-string rule (no backslash escapes)
    applies -- proven by the trailing `\\` NOT escaping the closing quote,
    which would still be inside an escape string but ends a plain one."""
    source = b"WHERE'x\\'"
    result = lex_sql(source)
    # "WHERE" is code; the plain string is `'x\'` (terminates at the quote
    # right after the backslash, because backslash is not an escape here).
    assert result.mask == b"WHERE" + b" " * len(b"'x\\'")


def test_unterminated_escape_string_raises_mutation_discovery_error():
    with pytest.raises(MutationDiscoveryError):
        lex_sql(b"A E'never closed")


def test_control_a_terminated_escape_string_does_not_raise():
    lex_sql(b"A E'closed' B")


def test_u_ampersand_string_lexes_as_a_plain_string_with_no_special_case():
    """``U&'...'`` needs no dedicated recognition: ``U`` and ``&`` are two
    ordinary code bytes, and the plain-string rule catches the ``'...'``
    that follows -- exactly the carve's own claim (§3.1)."""
    source = b"A U&'d\\1234' B"
    result = lex_sql(source)
    assert result.mask == b"A U&" + b" " * len(b"'d\\1234'") + b" B"


# --- phase 2: exactly one level of recursion --------------------------------


def test_code_inside_a_dollar_body_is_recovered_by_one_level_of_recursion():
    source = b"$$ SELECT 1; -- comment\nSELECT 2; $$"
    result = lex_sql(source)
    body_start, body_end = result.dollar_bodies[0]
    inner_mask = result.mask[body_start:body_end]
    inner_source = source[body_start:body_end]
    assert inner_mask == b" SELECT 1; " + b" " * len(b"-- comment") + b"\nSELECT 2; "
    # The comment's own bytes are gone from the mask but the code around it
    # survives verbatim -- confirms recursion actually re-lexed the body
    # rather than merely leaving it as the all-blank phase-1 default.
    assert inner_source != inner_mask


def test_a_body_inside_a_body_is_not_recursed_into():
    """A dollar-quoted construct APPEARING inside a level-1 body is still
    recognised and masked by the recursive re-lex (phase 1 runs identically
    at any depth) -- but its own interior is never given a SECOND level of
    recursion, so code that would only be reachable two levels deep stays
    masked."""
    source = (
        b"$$ SELECT 1; $inner$ CREATE TRIGGER never_seen $inner$ SELECT 2; $$"
    )
    result = lex_sql(source)
    assert len(result.dollar_bodies) == 1  # only the OUTER body is recorded
    body_start, body_end = result.dollar_bodies[0]
    inner_mask = result.mask[body_start:body_end]
    inner_source = source[body_start:body_end]
    # "SELECT 1;" and "SELECT 2;" are real code, one recursion level deep.
    assert b"SELECT 1;" in inner_mask
    assert b"SELECT 2;" in inner_mask
    # The $inner$ delimiters AND its body are blanked -- masked as a plain
    # (non-recursed) dollar-quote by the one-level-deep re-lex.
    inner_tag_start = inner_source.index(b"$inner$")
    inner_tag_end = inner_source.rindex(b"$inner$") + len(b"$inner$")
    assert inner_mask[inner_tag_start:inner_tag_end] == b" " * (
        inner_tag_end - inner_tag_start
    )
    assert b"CREATE TRIGGER never_seen" not in inner_mask


# --- mask shape invariants ---------------------------------------------------


def test_mask_length_always_equals_source_length():
    source = b"CREATE TABLE t (a INT NOT NULL); -- x\n$$ body $$ 'lit' \"id\""
    result = lex_sql(source)
    assert len(result.mask) == len(source)


def test_newlines_survive_inside_a_masked_multiline_construct():
    source = b"A /* line one\nline two */ B"
    result = lex_sql(source)
    newline_index = source.index(b"\n")
    assert result.mask[newline_index : newline_index + 1] == b"\n"
    # every OTHER byte of the comment is blanked
    assert result.mask[2:newline_index] == b" " * (newline_index - 2)


def test_unrecognised_bytes_are_left_untouched_as_ordinary_code():
    source = b"SELECT * FROM t WHERE a = 1;"
    result = lex_sql(source)
    assert result.mask == source
    assert result.dollar_bodies == ()


# --- the real, producer-emitted oracle --------------------------------------


def test_real_dstdns_fixture_recovers_the_do_block_guarded_foreign_keys():
    """The carve's own central measurement (§9 M3/M4), against the real
    pinned dstdns file (``151cda0d``,
    ``infra/db-init/init-scripts/21-create-workflow-corpus.sql``, tree
    ``820d4c3c``): line 99's ``ON DELETE RESTRICT`` sits inside a ``--``
    comment and must be masked; lines 327 and 332 are the corpus's only two
    REAL ``ON DELETE RESTRICT`` foreign keys, both inside a
    ``DO $$ ... $$`` idempotency guard, and phase-2 recursion must recover
    them as real code."""
    source = FIXTURE_PATH.read_bytes()
    result = lex_sql(source)
    assert len(result.mask) == len(source)

    comment_start, comment_end = _line_span(source, 99)
    comment_line = source[comment_start:comment_end]
    assert b"ON DELETE RESTRICT" in comment_line
    needle_offset = comment_start + comment_line.index(b"ON DELETE RESTRICT")
    needle_len = len(b"ON DELETE RESTRICT")
    assert result.mask[needle_offset : needle_offset + needle_len] == b" " * needle_len

    for lineno in (327, 332):
        line_start, line_end = _line_span(source, lineno)
        line_text = source[line_start:line_end]
        assert b"ON DELETE RESTRICT" in line_text
        code_offset = line_start + line_text.index(b"ON DELETE RESTRICT")
        assert (
            result.mask[code_offset : code_offset + needle_len]
            == source[code_offset : code_offset + needle_len]
        )

    # The `DO $$ ... $$` block starting near line 322 is one of several
    # top-level dollar bodies this file carries (six `$$ LANGUAGE plpgsql`
    # function bodies plus this one guard) -- find it by its own line range
    # rather than assuming it is the only one.
    do_block_bodies = [
        (start, end)
        for start, end in result.dollar_bodies
        if 322 <= source.count(b"\n", 0, start) + 1 <= 323
    ]
    assert len(do_block_bodies) == 1
    body_start, body_end = do_block_bodies[0]
    assert b"FOREIGN KEY" in source[body_start:body_end]
