DEFAULT_SERVICE_NAME = "pwmcp-server"
DEFAULT_WS_HOST = "0.0.0.0"
DEFAULT_WS_PORT = 3000
DEFAULT_MCP_HOST = "0.0.0.0"
DEFAULT_MCP_PORT = 8765
DEFAULT_HEALTH_PORT = 8081
DEFAULT_MCP_SERVER_NAME = "pwmcp-server"

ENV_WS_HOST = "WS_HOST"
ENV_WS_PORT = "WS_PORT"
ENV_MCP_PORT = "MCP_PORT"
ENV_MCP_SERVER_NAME = "MCP_SERVER_NAME"
ENV_HEALTH_PORT = "HEALTH_PORT"
ENV_ACCESS_TOKEN = "ACCESS_TOKEN"
ENV_WS_AUTH_TOKEN = "WS_AUTH_TOKEN"
ENV_MCP_AUTH_TOKEN = "MCP_AUTH_TOKEN"
ENV_AUTH_REQUIRED = "AUTH_REQUIRED"
