#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

PATTERNS = [
    re.compile(r"\{[^{}]+\}"),
    re.compile(r"</?[A-Za-z][A-Za-z0-9]*(?:=[^<>\n]*)?>"),
    re.compile(r"\[(?:/?[bicuv]|c|-)\]"),
    re.compile(r"\[[0-9A-Fa-f]{6}\]"),
    re.compile(r"@\w+\d*"),
    re.compile(r"\\n"),
]

LEAK_PLACEHOLDER_PATTERN = re.compile(r"__(?:PH|BPH)_\d+__")
LEAK_TRANSPORT_PATTERN = re.compile(r"\(?(?:TKB?PH\d+(?:LR|L|R)?TK)\)?")


def extract_tokens(value: str) -> list[str]:
    out: list[str] = []
    for pattern in PATTERNS:
        out.extend(match.group(0) for match in pattern.finditer(value or ""))
    return out


def extract_leak_tokens(value: str) -> list[str]:
    out: list[str] = []
    out.extend(match.group(0) for match in LEAK_PLACEHOLDER_PATTERN.finditer(value or ""))
    out.extend(match.group(0) for match in LEAK_TRANSPORT_PATTERN.finditer(value or ""))
    return sorted(set(out))


def _load_changed_rows(path: Path | None) -> dict[str, set[int]]:
    if path is None:
        return {}
    changed: dict[str, set[int]] = {}
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            file_name = (row.get("file") or "").strip()
            row_text = (row.get("row") or "").strip()
            if not file_name or not row_text:
                continue
            try:
                row_index = int(row_text)
            except ValueError:
                continue
            changed.setdefault(file_name, set()).add(row_index)
    return changed


def validate_file(path: Path, only_rows: set[int] | None) -> tuple[int, int]:
    issues = 0
    total = 0
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row_idx, row in enumerate(reader, start=2):
            if only_rows is not None and row_idx not in only_rows:
                continue
            english = row.get("English") or ""
            deutsch = row.get("Deutsch") or ""
            if not english.strip() or not deutsch.strip():
                continue
            total += 1
            src = set(extract_tokens(english))
            dst = set(extract_tokens(deutsch))
            missing = sorted(src - dst)
            extra = sorted(dst - src)
            if missing or extra:
                issues += 1
                print(f"[ERROR] {path.name}:{row_idx} KEY={row.get('KEY','')} missing={missing} extra={extra}")
    return total, issues


def _map_output_name_to_source(path: Path) -> str:
    name = path.name
    if name.endswith('.de.completed.csv'):
        return name.replace('.de.completed.csv', '.csv')
    return name


def _load_export_id_map(path: Path | None) -> dict[tuple[str, int, str], str]:
    if path is None or not path.exists():
        return {}

    id_map: dict[tuple[str, int, str], str] = {}
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue

            file_name = str(row.get("file") or "").strip()
            key = str(row.get("key") or "").strip()
            row_number = row.get("row")
            export_id = str(row.get("id") or "").strip()
            if not file_name or not key or not export_id:
                continue
            if not isinstance(row_number, int):
                continue
            id_map[(file_name, row_number, key)] = export_id

    return id_map


def _build_failures_markdown(failures: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Step 5 Token Parity QA Failures")
    lines.append("")
    lines.append("This report is generated by `qa_validate_tokens.py` after apply (`run-full-workflow.sh` Step 5).")
    lines.append("")
    lines.append("## How this differs from MT failures")
    lines.append("")
    lines.append("- **MT failures report (`translation-failures.md`)**: failures from MT transport/provider and placeholder-sequence QA inside `translate-mt`.")
    lines.append("- **Step 5 token parity failures (this section/report)**: post-apply English-vs-Deutsch token-set parity mismatches in final CSV output.")
    lines.append("- A row can pass MT placeholder QA and still fail Step 5 if game-side token patterns diverge after restoration/application.")
    lines.append("")
    lines.append(f"## Summary")
    lines.append("")
    lines.append(f"- Step 5 failures: **{len(failures)}**")
    lines.append("")

    if not failures:
        lines.append("No Step 5 token parity failures detected.")
        lines.append("")
        return "\n".join(lines)

    lines.append("## Failures")
    lines.append("")
    for index, failure in enumerate(failures, start=1):
        lines.append(f"### {index}. {failure['id']}")
        lines.append("")
        lines.append(f"- file: `{failure['file']}`")
        lines.append(f"- row: `{failure['row']}`")
        lines.append(f"- key: `{failure['key']}`")
        lines.append(f"- missing_tokens: `{failure['missing_tokens']}`")
        lines.append(f"- extra_tokens: `{failure['extra_tokens']}`")
        lines.append(f"- leak_tokens: `{failure.get('leak_tokens', [])}`")
        lines.append("")
        lines.append("**English**")
        lines.append("")
        lines.append("```text")
        lines.append(failure["english"])
        lines.append("```")
        lines.append("")
        lines.append("**Deutsch**")
        lines.append("")
        lines.append("```text")
        lines.append(failure["deutsch"])
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate token parity between English and German columns")
    parser.add_argument("files", nargs="+", help="CSV files to validate")
    parser.add_argument(
        "--changes-csv",
        help="Optional applied_changes.csv path. If provided, only changed rows are validated.",
    )
    parser.add_argument(
        "--full-file",
        action="store_true",
        help="Validate all rows (includes pre-existing mismatches).",
    )
    parser.add_argument(
        "--export-file",
        help="Optional export JSONL to map rows to full export IDs.",
    )
    parser.add_argument(
        "--failures-output-jsonl",
        help="Optional JSONL output path for Step 5 token parity failures.",
    )
    parser.add_argument(
        "--failures-output-md",
        help="Optional markdown output path for Step 5 token parity failures.",
    )
    parser.add_argument(
        "--promote-failures-as-ok",
        action="store_true",
        help="Do not fail exit code on Step 5 issues; keep reporting and return success.",
    )
    args = parser.parse_args()

    changed_rows = _load_changed_rows(Path(args.changes_csv)) if args.changes_csv else {}
    export_id_map = _load_export_id_map(Path(args.export_file)) if args.export_file else {}

    grand_total = 0
    grand_issues = 0
    failures: list[dict] = []
    for file_name in args.files:
        path = Path(file_name)
        only_rows = None
        if not args.full_file and changed_rows:
            source_name = _map_output_name_to_source(path)
            only_rows = changed_rows.get(source_name, set())
        issues = 0
        total = 0

        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row_idx, row in enumerate(reader, start=2):
                if only_rows is not None and row_idx not in only_rows:
                    continue
                english = row.get("English") or ""
                deutsch = row.get("Deutsch") or ""
                if not english.strip() or not deutsch.strip():
                    continue
                total += 1
                src = set(extract_tokens(english))
                dst = set(extract_tokens(deutsch))
                missing = sorted(src - dst)
                extra = sorted(dst - src)
                leaks = extract_leak_tokens(deutsch)
                if missing or extra or leaks:
                    issues += 1
                    key = str(row.get("KEY") or "").strip()
                    source_name = _map_output_name_to_source(path)
                    export_id = export_id_map.get((source_name, row_idx, key), f"{source_name}:{row_idx}:{key}")
                    failures.append(
                        {
                            "phase": "step5_token_parity",
                            "id": export_id,
                            "file": source_name,
                            "row": row_idx,
                            "key": key,
                            "missing_tokens": missing,
                            "extra_tokens": extra,
                            "leak_tokens": leaks,
                            "english": english,
                            "deutsch": deutsch,
                        }
                    )
                    print(
                        f"[ERROR] {path.name}:{row_idx} KEY={row.get('KEY','')} "
                        f"missing={missing} extra={extra} leaks={leaks}"
                    )

        grand_total += total
        grand_issues += issues
        scope = "full" if only_rows is None else f"changed_rows={len(only_rows)}"
        print(f"[INFO] {file_name}: checked={total} issues={issues} scope={scope}")

    if args.failures_output_jsonl:
        output_path = Path(args.failures_output_jsonl)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as handle:
            for failure in failures:
                handle.write(json.dumps(failure, ensure_ascii=False) + "\n")
        print(f"[INFO] Wrote Step 5 failures JSONL: {output_path} ({len(failures)} rows)")

    if args.failures_output_md:
        output_path = Path(args.failures_output_md)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(_build_failures_markdown(failures), encoding="utf-8")
        print(f"[INFO] Wrote Step 5 failures markdown: {output_path} ({len(failures)} rows)")

    if grand_issues:
        if args.promote_failures_as_ok:
            print(f"[WARN] Step 5 failures promoted as OK: {grand_issues}")
            return
        raise SystemExit(1)


if __name__ == "__main__":
    main()
