"""Managed per-entry backlog: one issue/feature record per file.
docs/backlog-entries-spec.md. The single-file inbox machinery stays in
backlog_items.py (P28, untouched); this module is the PARALLEL per-file
subsystem behind nyxloom.toml's optional [backlog_entries] table.

A project adopts entries by declaring:

    [backlog_entries]
    dir       = "nyxloom-trove/backlog"   # trove-relative; this default
    id_prefix = "CIU"                     # required; the project's sequence

Omitting the section means the project does not use entries: resolve_dir()
returns None and every lint rule / CLI verb stays silent or refuses -- never
a shadow path to a hardcoded location (estate defaults rule).

Entry file contract (spec §Entry file contract):

- filename `<ID>-<slug>.md`, stem minus `-<slug>` == frontmatter `id`;
- YAML frontmatter validated against schemas/backlog-entry.schema.json
  (kind=backlog-entry, schema_version=1, closed status vocabulary
  open|carved|merged|fixed|withdrawn|obsolete);
- markdown body is human narrative the machine never parses for
  correctness; `## Updates` receives dated appends via note().

INTERFACE CONTRACT:

- Entry dataclass: id, title, status, path, line (1-based first body line),
  plus the optional schema fields (type, severity, priority, component,
  context_estimate, folds_into, filed_by, filed_date, provenance,
  spec_owner, decisions, carved_handoff, merge_commit, promoted_from,
  closed_date, closed_reason) and raw (the parsed frontmatter dict).
- resolve_dir(cfg) -> Path | None: cfg.backlog_entries_dir resolved against
  cfg.root, defaulting to <root>/nyxloom-trove/backlog when the section is
  present without dir; None when the section is absent.
- parse_entry(path) -> Entry; raises HandoffParseError on malformed
  frontmatter (fail-closed, mirrors spine S4).
- load_entries(cfg) -> list[Entry]: every *.md in dir except INDEX.md,
  sorted by (status order, numeric id).
- validate_dir(cfg) -> list[LintFinding], rule BLG2: frontmatter schema,
  stem-minus-slug == id, id grammar + configured-prefix match, uniqueness,
  closed_* iff terminal (merged carries merge_commit instead).
- index_findings(cfg) -> list[LintFinding], rule BLG3: committed INDEX.md
  must byte-equal render_index(load_entries(cfg)) -- regenerate-and-diff,
  so tracker drift is uncommittable rather than discouraged.
- allocate_id(entries, prefix) -> str: max existing numeric suffix of ANY
  matching-prefix entry (legacy dash-less shapes included) + 1, in the
  project's dashed form `<PREFIX>-<N>`.
- create_entry(...) -> Path: scaffold + write + reindex.
- promote(cfg, inbox_id) -> Path: spine-inbox item OR plain P28 bullet ->
  managed entry; the inbox edit is a SURGICAL line-range deletion (never a
  YAML re-dump -- PyYAML round-trips destroy comments), mirroring
  tick_merged's byte-preserving discipline.
- note(cfg, entry_id, text) -> Path: dated paragraph under `## Updates`.
- set_status(cfg, entry_id, status, reason=None) -> Path: typed transition;
  fixed|withdrawn|obsolete REQUIRE reason and stamp closed_date/closed_reason;
  merged is refused here (merge auto-tick is the only writer);
  reopen clears closed_*.
- tick_merged_entries(cfg, task_id, commit) -> bool: set status=merged +
  merge_commit on the entry whose carved_handoff == task_id. Rewrites ONLY
  those frontmatter tokens (line surgery). No match -> no write, False.
"""

from __future__ import annotations

import importlib.resources
import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import jsonschema

from . import backlog_items
from .config import ProjectConfig
from .frontmatter import HandoffParseError, split_frontmatter
from .log import get_logger
from .types import LintFinding

log = get_logger("backlog_entries")

DEFAULT_DIR_RELPATH = "nyxloom-trove/backlog"
INDEX_NAME = "INDEX.md"
INDEX_BANNER = "<!-- GENERATED by `nyxloom backlog index` -- do not edit; regenerate. -->"

STATUSES = ("open", "carved", "merged", "fixed", "withdrawn", "obsolete")
TERMINAL_STATUSES = ("fixed", "withdrawn", "obsolete")
# Index grouping: open first, then carved, then terminal statuses.
_STATUS_ORDER = {s: i for i, s in enumerate(STATUSES)}

# Non-greedy prefix so a legacy dash-less padded id (B001) parses as
# prefix "B" + num 1, not prefix "B00" + num 1.
_ID_RE = re.compile(r"^(?P<prefix>[A-Z][A-Z0-9]*?)-?(?P<num>[0-9]+)$")
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")

BODY_TEMPLATE = """\
## Observed mechanism and reproduction

## Why {project} owns it

## Proposed contract

## Oracles

## SPEC ownership

## Updates
"""


@dataclass
class Entry:
    id: str
    title: str
    status: str
    path: Path
    line: int                      # 1-based first body line
    raw: dict = field(default_factory=dict)
    type: str | None = None
    severity: str | None = None
    priority: int | None = None
    component: str | None = None
    context_estimate: str | None = None
    folds_into: str | None = None
    filed_by: str | None = None
    filed_date: str | None = None
    provenance: str | None = None
    spec_owner: str | None = None
    decisions: list[str] = field(default_factory=list)
    carved_handoff: str | None = None
    merge_commit: str | None = None
    promoted_from: str | None = None
    closed_date: str | None = None
    closed_reason: str | None = None

    @property
    def num(self) -> int:
        return int(_ID_RE.match(self.id).group("num"))


def today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def resolve_dir(cfg: ProjectConfig) -> Path | None:
    """The entries dir, or None when the project has not adopted entries."""
    if cfg.backlog_id_prefix is None:
        return None
    rel = cfg.backlog_entries_dir or DEFAULT_DIR_RELPATH
    return cfg.root / rel


def _load_schema() -> dict:
    text = importlib.resources.files("nyxloom.schemas").joinpath(
        "backlog-entry.schema.json"
    ).read_text(encoding="utf-8")
    return json.loads(text)


def parse_entry(path: Path) -> Entry:
    """Parse one entry file. Raises HandoffParseError on malformed
    frontmatter (fail-closed -- never a silent skip, spine-S4 shape)."""
    fm, body, body_start = split_frontmatter(path.read_text(encoding="utf-8"))
    optional = (
        "type", "severity", "priority", "component", "context_estimate",
        "folds_into", "filed_by", "filed_date", "provenance", "spec_owner",
        "carved_handoff", "merge_commit", "promoted_from", "closed_date",
        "closed_reason",
    )
    kwargs = {k: fm[k] for k in optional if k in fm}
    if "decisions" in fm:
        kwargs["decisions"] = list(fm["decisions"])
    return Entry(
        id=fm["id"], title=fm["title"], status=fm["status"],
        path=path, line=body_start, raw=fm, **kwargs,
    )


def _status_key(e: Entry) -> tuple[int, int]:
    # Unknown statuses sort last (after every known group), never crash the
    # sort -- BLG2 reports them.
    return (_STATUS_ORDER.get(e.status, len(STATUSES)), e.num)


def load_entries(cfg: ProjectConfig) -> list[Entry]:
    """Every entry in the dir (INDEX.md excluded), spec-sorted."""
    d = resolve_dir(cfg)
    if d is None or not d.is_dir():
        return []
    entries = [parse_entry(p) for p in sorted(d.glob("*.md"))
               if p.name != INDEX_NAME]
    return sorted(entries, key=_status_key)


# ----- BLG2: entry validity -----

def validate_dir(cfg: ProjectConfig) -> list[LintFinding]:
    d = resolve_dir(cfg)
    if d is None or not d.is_dir():
        return []
    findings: list[LintFinding] = []
    validator = jsonschema.Draft202012Validator(_load_schema())
    seen: dict[str, Path] = {}

    for p in sorted(d.glob("*.md")):
        if p.name == INDEX_NAME:
            continue
        rel = str(p.relative_to(cfg.root))
        try:
            fm, _body, _line = split_frontmatter(p.read_text(encoding="utf-8"))
        except HandoffParseError as e:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"unparsable frontmatter: {e.errors}", path=rel,
            ))
            continue

        for error in sorted(validator.iter_errors(fm),
                            key=lambda e: list(e.absolute_path)):
            jp = ".".join(str(x) for x in error.absolute_path) or "$"
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"{jp}: {error.message}", path=rel,
            ))
        if not all(k in fm for k in ("id", "status")):
            continue  # schema errors already reported; further checks need these

        entry_id = fm["id"]
        m = _ID_RE.match(entry_id)
        if m is None:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"{entry_id}: id does not match ^[A-Z][A-Z0-9]*-?[0-9]+$",
                path=rel,
            ))
        elif m.group("prefix") != cfg.backlog_id_prefix:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=(f"{entry_id}: id prefix {m.group('prefix')!r} != "
                         f"configured id_prefix {cfg.backlog_id_prefix!r}"),
                path=rel,
            ))

        stem = p.stem
        slug = stem[len(entry_id):].lstrip("-") if stem.startswith(entry_id) else ""
        if (not stem.startswith(entry_id) or not slug
                or not _SLUG_RE.match(slug)):
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=(f"filename stem {stem!r} must be "
                         f"<id>-<slug> with kebab slug (id {entry_id!r})"),
                path=rel,
            ))

        if entry_id in seen:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"duplicate id {entry_id} (also {seen[entry_id].name})",
                path=rel,
            ))
        else:
            seen[entry_id] = p

        status = fm["status"]
        has_closed = bool(fm.get("closed_reason"))
        if status in TERMINAL_STATUSES and not has_closed:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"{entry_id}: terminal status {status} requires closed_reason",
                path=rel,
            ))
        if status not in TERMINAL_STATUSES and has_closed:
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"{entry_id}: closed_reason present but status is {status}",
                path=rel,
            ))
        if status == "merged" and not fm.get("merge_commit"):
            findings.append(LintFinding(
                rule="BLG2", severity="error",
                message=f"{entry_id}: merged requires merge_commit (auto-tick stamps it)",
                path=rel,
            ))

    log.debug("entries validated", count=len(seen), finding_count=len(findings))
    return findings


# ----- INDEX.md (BLG3) -----

def _cell(text: object) -> str:
    return str(text or "").replace("|", "\\|").replace("\n", " ")


def render_index(entries: list[Entry]) -> str:
    lines = [
        INDEX_BANNER,
        "",
        "# Backlog entries",
        "",
        "| ID | Title | Status | Type | Priority | Provenance |",
        "|---|---|---|---|---|---|",
    ]
    for e in entries:
        lines.append(
            f"| [{e.id}]({e.path.name}) | {_cell(e.title)} | {e.status} "
            f"| {_cell(e.type)} | {_cell(e.priority)} | {_cell(e.provenance)} |"
        )
    return "\n".join(lines) + "\n"


def write_index(cfg: ProjectConfig) -> Path:
    d = resolve_dir(cfg)
    assert d is not None
    d.mkdir(parents=True, exist_ok=True)
    out = d / INDEX_NAME
    out.write_text(render_index(load_entries(cfg)), encoding="utf-8")
    log.info("index written", path=str(out))
    return out


def index_findings(cfg: ProjectConfig) -> list[LintFinding]:
    """BLG3: the committed INDEX.md must byte-equal a fresh regeneration."""
    d = resolve_dir(cfg)
    if d is None or not d.is_dir():
        return []
    expected = render_index(load_entries(cfg))
    index_path = d / INDEX_NAME
    actual = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
    if actual == expected:
        return []
    return [LintFinding(
        rule="BLG3", severity="error",
        message="INDEX.md is stale (regenerate: `nyxloom backlog index`)",
        path=str(index_path.relative_to(cfg.root)),
    )]


# ----- allocation / creation -----

def allocate_id(entries: list[Entry], prefix: str) -> str:
    """Next id in the project's dashed form: max existing numeric suffix of
    ANY matching-prefix entry (legacy dash-less shapes included) + 1."""
    nums = [e.num for e in entries
            if _ID_RE.match(e.id) and _ID_RE.match(e.id).group("prefix") == prefix]
    return f"{prefix}-{max(nums, default=0) + 1}"


def create_entry(
    cfg: ProjectConfig,
    title: str,
    *,
    type: str | None = None,
    severity: str | None = None,
    priority: int | None = None,
    component: str | None = None,
    context_estimate: str | None = None,
    folds_into: str | None = None,
    provenance: str | None = None,
    filed_by: str | None = None,
    spec_owner: str | None = None,
    body: str | None = None,
    promoted_from: str | None = None,
) -> Path:
    d = resolve_dir(cfg)
    assert d is not None
    entries = load_entries(cfg)
    entry_id = allocate_id(entries, cfg.backlog_id_prefix)
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:63].strip("-") or "entry"

    fm_lines = ["---", "kind: backlog-entry", "schema_version: 1",
                f"id: {entry_id}",
                f"title: {json.dumps(title, ensure_ascii=False)}",
                "status: open"]
    for key, value in (("type", type), ("severity", severity),
                       ("component", component),
                       ("context_estimate", context_estimate),
                       ("folds_into", folds_into),
                       ("provenance", provenance),
                       ("filed_by", filed_by), ("spec_owner", spec_owner)):
        if value is not None:
            fm_lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    if priority is not None:
        fm_lines.append(f"priority: {priority}")
    if promoted_from is not None:
        fm_lines.append(f"promoted_from: {promoted_from}")
    fm_lines.append(f'filed_date: "{today()}"')
    fm_lines.append("---")

    if body is None:
        body = BODY_TEMPLATE.format(project=cfg.project_id)
    text = "\n".join(fm_lines) + "\n\n" + body.strip() + "\n"

    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{entry_id}-{slug}.md"
    path.write_text(text, encoding="utf-8")
    write_index(cfg)
    log.info("entry created", id=entry_id, path=str(path))
    return path


# ----- surgical frontmatter token edit (tick/set-status shared) -----

_FM_TOKEN_RES = {
    key: re.compile(rf"^{key}:.*$", re.M)
    for key in ("status", "merge_commit", "closed_date", "closed_reason")
}
# The delete variant consumes the line's newline too, so removal never
# leaves a blank line mid-frontmatter; the SET variant must NOT eat it
# (the replacement would otherwise join the next line).
_FM_DEL_RES = {
    key: re.compile(rf"^{key}:.*\n?", re.M)
    for key in ("status", "merge_commit", "closed_date", "closed_reason")
}


def _set_fm_token(text: str, key: str, value: str | None) -> str:
    """Set (or delete, value=None) one scalar frontmatter token, touching no
    other byte. Absent-means-insert before the closing '---'."""
    if value is None:
        return _FM_DEL_RES[key].sub("", text, count=1)
    pattern = _FM_TOKEN_RES[key]
    replacement = f"{key}: {value}"
    if pattern.search(text):
        # lambda: `value` is data, never a backreference template.
        return pattern.sub(lambda _: replacement, text, count=1)
    closing = text.index("\n---", text.index("---") + 3)
    return text[:closing + 1] + replacement + "\n" + text[closing + 1:]


# ----- promotion from the idea inbox -----

_SPINE_ITEM_RE = re.compile(r"^- id: ")


def _read_spine_inbox(cfg: ProjectConfig) -> tuple[Path, list[dict], list[tuple[int, int]]] | None:
    """The spine inbox (cfg.backlog): path, parsed items, and each item's
    [start, end) LINE range within the file (0-based, end-exclusive) so
    promotion can delete surgically instead of YAML-re-dumping.

    Returns None ONLY for genuine absence (key unset / file missing) -- the
    two conditions the plain-inbox fallback may legitimately handle. A
    PRESENT but unparsable doc or a block-scan mismatch RAISES
    HandoffParseError: corruption must fail loudly, never masquerade as
    'no inbox' (a failed comparison must not be folded into an absence)."""
    if not cfg.backlog:
        return None
    path = cfg.root / cfg.backlog
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    fm, _body, _start = split_frontmatter(text)
    items = fm.get("items") or []
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for i, line in enumerate(lines):
        if _SPINE_ITEM_RE.match(line):
            if start is not None:
                ranges.append((start, i))
            start = i
    if start is not None:
        ranges.append((start, len(lines)))
    if len(ranges) != len(items):
        raise HandoffParseError(
            str(path), [f"item block scan found {len(ranges)} blocks for "
                        f"{len(items)} frontmatter items; refusing to edit"])
    return path, items, ranges


def promote(cfg: ProjectConfig, inbox_id: str) -> Path:
    """Inbox item -> managed entry. Spine inbox wins when both exist (it is
    the adopted form). Carries over title/type/component/context_estimate/
    folds_into; stamps promoted_from; removes the item surgically."""
    spine = _read_spine_inbox(cfg)  # None only on genuine absence; corrupt raises

    if spine is not None:
        path, items, ranges = spine
        for item, rng in zip(items, ranges):
            if str(item.get("id")) == inbox_id:
                entry_path = create_entry(
                    cfg,
                    str(item["title"]),
                    type=item.get("type"),
                    component=item.get("component"),
                    context_estimate=item.get("context_estimate"),
                    folds_into=item.get("folds_into"),
                    promoted_from=inbox_id,
                )
                lines = path.read_text(encoding="utf-8").split("\n")
                del lines[rng[0]:rng[1]]
                path.write_text("\n".join(lines), encoding="utf-8")
                write_index(cfg)
                return entry_path
        raise KeyError(f"no inbox item {inbox_id} in {path}")

    plain_path = backlog_items.resolve_path(cfg)
    if plain_path.exists():
        text = plain_path.read_text(encoding="utf-8")
        bullets = backlog_items.parse(plain_path)
        target = next((it for it in bullets if it.id == inbox_id), None)
        if target is None:
            raise KeyError(f"no inbox item {inbox_id} in {plain_path}")
        title = target.detail.split("\n")[0].strip(" .") or inbox_id
        entry_path = create_entry(cfg, title, promoted_from=inbox_id)
        lines = text.split("\n")
        start = target.line - 1
        end = len(lines)
        for i in range(start + 1, len(lines)):
            if backlog_items._ITEM_RE.match(lines[i]):
                end = i
                break
        # Pop trailing blank lines (never the bullet: it is non-blank by
        # _ITEM_RE, so no lower bound guard is needed -- and a numeric guard
        # here would carry an unreachable arm that mutation testing can only
        # classify as an equivalent mutant).
        item_lines = lines[start:end]
        while item_lines and item_lines[-1] == "":
            item_lines.pop()
        del lines[start:start + len(item_lines)]
        plain_path.write_text("\n".join(lines), encoding="utf-8")
        write_index(cfg)
        return entry_path

    raise FileNotFoundError("no idea inbox found (spine or plain backlog.md)")


# ----- note / set-status / auto-tick -----

def _find(cfg: ProjectConfig, entry_id: str) -> Entry:
    for e in load_entries(cfg):
        if e.id == entry_id:
            return e
    raise KeyError(f"no entry {entry_id}")


def note(cfg: ProjectConfig, entry_id: str, text: str) -> Path:
    """Append a dated paragraph under `## Updates` -- the ONLY sanctioned
    way to file follow-up evidence (second reproductions, priority bumps)."""
    e = _find(cfg, entry_id)
    content = e.path.read_text(encoding="utf-8")
    stamp = f"**{today()}** — {text.strip()}"
    if re.search(r"^## Updates\s*$", content, re.M):
        content = content.rstrip("\n") + f"\n\n{stamp}\n"
    else:
        content = content.rstrip("\n") + f"\n\n## Updates\n\n{stamp}\n"
    e.path.write_text(content, encoding="utf-8")
    write_index(cfg)
    return e.path


def set_status(cfg: ProjectConfig, entry_id: str, status: str,
               reason: str | None = None) -> Path:
    if status not in STATUSES:
        raise ValueError(f"unknown status {status!r}; valid: {', '.join(STATUSES)}")
    if status == "merged":
        raise ValueError("merged is written only by the merge auto-tick")
    if status in TERMINAL_STATUSES and not (reason or "").strip():
        raise ValueError(f"--reason is required for terminal status {status}")
    e = _find(cfg, entry_id)
    content = e.path.read_text(encoding="utf-8")
    content = _set_fm_token(content, "status", status)
    if status in TERMINAL_STATUSES:
        content = _set_fm_token(content, "closed_date", f'"{today()}"')
        content = _set_fm_token(
            content, "closed_reason", json.dumps(reason.strip(), ensure_ascii=False))
    else:  # reopen: clear the closed_* pair
        content = _set_fm_token(content, "closed_date", None)
        content = _set_fm_token(content, "closed_reason", None)
    e.path.write_text(content, encoding="utf-8")
    write_index(cfg)
    log.info("entry status set", id=entry_id, status=status)
    return e.path


def tick_merged_entries(cfg: ProjectConfig, task_id: str, commit: str) -> bool:
    """Merge auto-tick for entries: set status=merged + merge_commit on the
    entry whose carved_handoff == task_id. ONLY those two tokens change."""
    d = resolve_dir(cfg)
    if d is None or not d.is_dir():
        return False
    for e in load_entries(cfg):
        if e.carved_handoff != task_id:
            continue
        content = e.path.read_text(encoding="utf-8")
        content = _set_fm_token(content, "status", "merged")
        content = _set_fm_token(content, "merge_commit", commit)
        e.path.write_text(content, encoding="utf-8")
        write_index(cfg)
        log.info("entry ticked merged", id=e.id, task_id=task_id, commit=commit)
        return True
    log.debug("entry tick: no linked entry", task_id=task_id)
    return False
