"""CIU host enrollment — ``ciu host enroll`` (SPEC S14.7, CIU-93).

The step BEFORE S14.1-S14.6: from a bare host with nothing but Python 3 and an
SSH server to a working ``[deploy.hosts.<name>]`` row. Two steps, one verb, no
token, no callback, no listener:

* **Step 1** (``ciu host enroll <name>``) generates an ed25519 key pair into the
  S14.3a host-secret namespace with the platform's own ``ssh-keygen``, and
  PRINTS — writing no inventory row — the one command the target's admin runs.
* **Step 2** (``ciu host enroll <name> --ssh-host ADDR --fingerprint SHA256:…``)
  keyscans the address, refuses unless a scanned key matches the fingerprint the
  admin read on the console, proves the login by running ``ciu version`` on the
  target with that key pinned for one connection, and only then writes the row.

Security envelope (S14.7d, on top of S14.4a-c): the private half is generated
where it is used and is never printed, logged or transmitted; the installer URL
is always pinned to the control host's own ciu version; ``CIU_SSH_INSECURE_TOFU``
is never set here under any flag combination — this flow is the secure
alternative to that escape hatch, not a way around it.

This module owns the flow; the inventory WRITE lives in ``hosts.py`` beside the
reader it must round-trip against, and the connection itself goes through
``transport_ssh.ssh_exec`` so the pinning/temp-file/cleanup envelope is the one
every other transport verb already uses.
"""
from __future__ import annotations

import os
import shlex
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

from .hosts import load_hosts, resolve_hosts_file, write_host_row
from .secrets.materialize import host_secret_store

#: ciu's own release coordinates — the SAME values as this repo's `cmru.toml`
#: `[github]` / `[project].prefix`, which is what cmru bakes into the rendered
#: `get.py`. They are constants OF the ciu package, deliberately not read from
#: whatever `cmru.toml` happens to sit in the consumer's checkout (that file
#: describes the CONSUMER's project, e.g. dstdns, not ciu). A test pins them
#: against ciu's own cmru.toml so the two can never drift apart silently.
INSTALLER_REPO_OWNER = "volkb79-2"
INSTALLER_REPO_NAME = "vbpub"
INSTALLER_TAG_PREFIX = "ciu-v"

#: The scanned host-key types, in the order `ssh-keyscan` is asked for them.
KEYSCAN_TYPES = "ed25519,ecdsa,rsa"

#: Private key file name inside `<repo>/.ciu/secrets/hosts/<name>/` (S14.3a).
KEY_ENTRY = "ssh_key"


class EnrollError(ValueError):
    """A tagged ``[S14.7]`` refusal. Nothing is written when one is raised."""


def key_paths(repo_root: Path, name: str) -> tuple[Path, Path]:
    """``(private, public)`` key paths for a host, in the S14.3a namespace.

    ``host_secret_store`` is reused verbatim rather than re-deriving
    ``<repo>/.ciu/secrets/hosts/<name>/`` here — the enrollment key IS a
    host-scoped local secret, it just happens to be generated by ``ssh-keygen``
    instead of by a ``GEN_LOCAL`` directive.
    """
    private = host_secret_store(repo_root, name, KEY_ENTRY)
    return private, private.with_name(private.name + ".pub")


def installer_url(version: str) -> str:
    """The version-pinned ``get.py`` release-asset URL (S14.7d).

    Never ``latest``: control and target must run the same ciu. A control host
    running an UNRELEASED build (a setuptools-scm ``.dev``/local version) has no
    corresponding release asset, so this refuses rather than printing a URL that
    404s — ``--installer-url`` is the documented way through.
    """
    if ".dev" in version or "+" in version or version == "unknown":
        raise EnrollError(
            f"[S14.7] this control host runs an unreleased ciu ({version}), which "
            f"has no 'get.py' release asset to pin. Pass --installer-url with a "
            f"mirror or a commit-pinned URL, or run enrollment from a released ciu."
        )
    return (
        f"https://github.com/{INSTALLER_REPO_OWNER}/{INSTALLER_REPO_NAME}"
        f"/releases/download/{INSTALLER_TAG_PREFIX}{version}/get.py"
    )


def resolve_controller(controller: str | None, config: dict) -> str:
    """``--controller``, else ``topology.external.public_fqdn``, else refuse.

    S14.7a is explicit that a missing value on BOTH sides is a refusal — this
    codebase never substitutes a guessed or defaulted hostname for information
    it was not given (AGENTS.md, "defaults are hazards").
    """
    if controller:
        return controller
    topology = config.get("topology")
    external = topology.get("external") if isinstance(topology, dict) else None
    declared = external.get("public_fqdn") if isinstance(external, dict) else None
    if isinstance(declared, str) and declared.strip():
        return declared.strip()
    raise EnrollError(
        "[S14.7] no controller name: pass --controller <FQDN>, or declare "
        "topology.external.public_fqdn in the global config. CIU does not guess "
        "a controller hostname."
    )


def _run(argv: list[str], **kwargs) -> subprocess.CompletedProcess:
    """``subprocess.run`` with captured text output (never shell=True)."""
    return subprocess.run(argv, capture_output=True, text=True, **kwargs)


def generate_key_pair(repo_root: Path, name: str, comment: str) -> tuple[Path, Path]:
    """``ssh-keygen -t ed25519 -N ""`` into the host namespace (S14.7a).

    The real ``ssh-keygen``, never a hand-rolled generator. The empty passphrase
    is deliberate and matches every other host key in this namespace: the key is
    for unattended ``ciu ssh`` / ``ciu up --host`` use, so a passphrase would
    only move the secret to an agent CIU does not manage.
    """
    private, public = key_paths(repo_root, name)
    private.parent.mkdir(parents=True, exist_ok=True)
    os.chmod(private.parent, stat.S_IRWXU)  # 0700
    for stale in (private, public):
        if stale.exists():
            stale.unlink()
    result = _run([
        "ssh-keygen", "-t", "ed25519", "-f", str(private), "-C", comment, "-N", "",
    ])
    if result.returncode != 0:
        raise EnrollError(
            f"[S14.7] ssh-keygen failed for host '{name}' (exit "
            f"{result.returncode}): {result.stderr.strip() or 'no output'}"
        )
    os.chmod(private, stat.S_IRUSR | stat.S_IWUSR)  # 0600
    os.chmod(public, 0o644)  # world-readable: it is printed and pasted around
    return private, public


def _one_liner(
    url: str, public_key: str, controller: str, name: str,
    user: str, from_pattern: str | None, docker: bool,
) -> str:
    """The command the TARGET's admin runs (S14.7a / proposal §4)."""
    args = [
        "enroll",
        "--authorized-key", public_key,
        "--controller", controller,
        "--user", user,
        "--name", name,
    ]
    if from_pattern:
        args += ["--from", from_pattern]
    if docker:
        args.append("--docker")
    return (
        f"curl -fsSL {url} \\\n"
        f"  | sudo python3 - {shlex.join(args)}"
    )


def enroll_step1(
    repo_root: Path,
    name: str,
    *,
    config: dict,
    version: str,
    user: str = "ciu",
    port: int = 22,
    controller: str | None = None,
    from_pattern: str | None = None,
    docker: bool = False,
    installer_url_override: str | None = None,
    replace: bool = False,
    out=print,
) -> int:
    """Step 1 (S14.7a): generate the key pair and print; write NO inventory row."""
    hosts = load_hosts(repo_root)
    if name in hosts and not replace:
        raise EnrollError(
            f"[S14.7] host '{name}' is already enrolled in "
            f"{resolve_hosts_file(repo_root)}. Re-run with --replace to rotate its "
            f"key (the row's ssh_key/known_host are overwritten at step 2), or "
            f"pick another name."
        )
    controller_name = resolve_controller(controller, config)
    url = installer_url_override or installer_url(version)
    project = str(config.get("deploy", {}).get("project_name") or "ciu")

    private, public = generate_key_pair(
        repo_root, name, f"ciu@{controller_name}:{project}"
    )
    public_key = public.read_text(encoding="utf-8").strip()

    completion = ["ciu", "host", "enroll", name, "--ssh-host", "<address>",
                  "--fingerprint", "SHA256:<as printed by the target>"]
    if user != "ciu":
        completion += ["--user", user]
    if port != 22:
        completion += ["--port", str(port)]
    if replace:
        completion.append("--replace")

    out(f"[S14.7a] host '{name}': key pair generated, nothing written to the inventory yet.")
    out("")
    out(f"  private key : {private}   (never printed, never leaves this host)")
    out(f"  public key  : {public}")
    out("")
    out(public_key)
    out("")
    out("Step 1 — the target's admin runs ONE command on the bare host:")
    out("")
    out(_one_liner(url, public_key, controller_name, name, user, from_pattern, docker))
    out("")
    out("Step 2 — then, back here, with the fingerprint the admin read on the console:")
    out("")
    out(f"  {shlex.join(completion)}")
    out("")
    out(f"Nothing is polling: run step 2 whenever the admin is done. "
        f"'ciu host enroll {name} --abort' removes this key pair instead.")
    return 0


def enroll_abort(repo_root: Path, name: str, *, out=print) -> int:
    """``--abort`` (S14.7a): remove a PENDING (step-1-only) key pair."""
    if name in load_hosts(repo_root):
        raise EnrollError(
            f"[S14.7] host '{name}' has an inventory row, so it is not a pending "
            f"enrollment. --abort only removes a step-1 key pair that will not be "
            f"completed; remove the row by hand to un-enroll a live host."
        )
    private, public = key_paths(repo_root, name)
    removed = []
    for path in (private, public):
        if path.exists():
            path.unlink()
            removed.append(str(path))
    if not removed:
        raise EnrollError(
            f"[S14.7] host '{name}' has no pending enrollment key pair under "
            f"{private.parent} — nothing to abort."
        )
    if private.parent.is_dir() and not any(private.parent.iterdir()):
        private.parent.rmdir()
    for path in removed:
        out(f"[S14.7a] removed {path}")
    return 0


def keyscan(ssh_host: str, port: int) -> list[tuple[str, str]]:
    """``ssh-keyscan`` the target; return ``[(algo, base64), …]`` (S14.7c).

    Comment/error lines (``ssh-keyscan`` writes those to stderr, but a defensive
    filter costs nothing) and malformed rows are dropped rather than pinned.
    """
    result = _run([
        "ssh-keyscan", "-p", str(port), "-t", KEYSCAN_TYPES, ssh_host,
    ])
    keys: list[tuple[str, str]] = []
    for line in result.stdout.splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        keys.append((parts[1], parts[2]))
    if not keys:
        raise EnrollError(
            f"[S14.7] ssh-keyscan returned no host key for {ssh_host}:{port} "
            f"({result.stderr.strip() or 'no output'}). Is the host reachable and "
            f"is sshd listening on that port?"
        )
    return keys


def fingerprint_of(algo: str, blob: str) -> str:
    """The SHA256 fingerprint of one scanned key, via ``ssh-keygen -lf``.

    OpenSSH's own hashing, not a re-implementation — the value has to equal
    exactly what the target printed from its own ``ssh-keygen -lf``.
    """
    fd, tmp_path = tempfile.mkstemp(prefix="ciu_hostkey_", suffix=".pub")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(f"{algo} {blob}\n")
        result = _run(["ssh-keygen", "-lf", tmp_path])
    finally:
        os.unlink(tmp_path)  # mkstemp created it; nothing here can remove it
    if result.returncode != 0:
        raise EnrollError(
            f"[S14.7] could not fingerprint the scanned {algo} host key: "
            f"{result.stderr.strip() or 'ssh-keygen failed'}"
        )
    for token in result.stdout.split():
        if token.startswith("SHA256:"):
            return token
    raise EnrollError(
        f"[S14.7] ssh-keygen -lf printed no SHA256 fingerprint for the scanned "
        f"{algo} host key."
    )


def _confirm_interactively(
    ssh_host: str, scanned: list[tuple[str, str, str]], out, input_fn
) -> tuple[str, str]:
    """TTY confirmation when ``--fingerprint`` was not given (S14.7c).

    A non-TTY run without the flag is a refusal — never a silent TOFU accept,
    which is exactly the behaviour ``CIU_SSH_INSECURE_TOFU`` exists to gate.
    """
    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        raise EnrollError(
            f"[S14.7] --fingerprint is required for a non-interactive enrollment of "
            f"{ssh_host}. Pass the SHA256 fingerprint the target printed on its "
            f"console; CIU never pins a scanned key it has not been asked to trust."
        )
    out(f"Host keys scanned from {ssh_host}:")
    for algo, _blob, fp in scanned:
        out(f"  {algo}  {fp}")
    answer = input_fn(
        "Does one of these match the fingerprint the admin read on the target's "
        "console? Type the fingerprint to pin it: "
    ).strip()
    for algo, blob, fp in scanned:
        if answer == fp:
            return algo, blob
    raise EnrollError(
        f"[S14.7] '{answer or '(nothing)'}' does not match any key scanned from "
        f"{ssh_host}; refusing to pin."
    )


def select_host_key(
    ssh_host: str,
    scanned: list[tuple[str, str, str]],
    fingerprint: str | None,
    *,
    out=print,
    input_fn=input,
) -> tuple[str, str]:
    """Pick the scanned key to pin, or refuse naming BOTH fingerprints (S14.7c)."""
    if fingerprint is None:
        return _confirm_interactively(ssh_host, scanned, out, input_fn)
    for algo, blob, fp in scanned:
        if fp == fingerprint:
            return algo, blob
    presented = ", ".join(f"{algo} {fp}" for algo, _blob, fp in scanned)
    raise EnrollError(
        f"[S14.7] {ssh_host} presents {presented}; expected {fingerprint} — not "
        f"the host the admin enrolled, or a man in the middle. Nothing written."
    )


def prove_login(
    host_cfg: dict, *, config: dict, repo_root: Path, name: str, exec_fn=None
) -> None:
    """Run ``ciu version`` on the target with the new key + the just-confirmed
    host key pinned for THIS connection only (S14.7c).

    The pin is passed through ``host_cfg``'s own ``known_host``, so
    ``transport_ssh``'s existing temp-known-hosts mechanism (and its S14.4c
    ``[ADDR]:N`` port form) is what enforces it — this module never writes a
    known-hosts file of its own, and the REAL inventory row is not written until
    after this call returns.
    """
    if exec_fn is None:
        from .transport_ssh import ssh_exec

        exec_fn = ssh_exec
    code = exec_fn(host_cfg, ["ciu", "version"], config=config, repo_root=repo_root)
    if code == 0:
        return
    if code == 127:
        raise EnrollError(
            f"[S14.7] {name}: key accepted but ciu is not installed; run get.py "
            f"enroll again without --no-install. Nothing written."
        )
    raise EnrollError(
        f"[S14.7] {name}: could not run 'ciu version' over the new key (ssh exit "
        f"{code}). The key may not have been installed for user "
        f"'{host_cfg.get('ssh_user')}', or the pinned host key was rejected. "
        f"Nothing written."
    )


def enroll_step2(
    repo_root: Path,
    name: str,
    *,
    config: dict,
    ssh_host: str,
    port: int = 22,
    user: str = "ciu",
    fingerprint: str | None = None,
    replace: bool = False,
    out=print,
    input_fn=input,
    exec_fn=None,
) -> int:
    """Step 2 (S14.7c): confirm, prove, then write the row — in that order."""
    private, _public = key_paths(repo_root, name)
    if not private.exists():
        raise EnrollError(
            f"[S14.7] no enrollment key for host '{name}' at {private}. Run "
            f"'ciu host enroll {name}' (step 1) first."
        )
    hosts_path = resolve_hosts_file(repo_root)
    if name in load_hosts(repo_root) and not replace:
        raise EnrollError(
            f"[S14.7] host '{name}' already has a row in {hosts_path}. Re-run with "
            f"--replace to overwrite its ssh_key and known_host."
        )

    scanned = [(algo, blob, fingerprint_of(algo, blob))
               for algo, blob in keyscan(ssh_host, port)]
    algo, blob = select_host_key(
        ssh_host, scanned, fingerprint, out=out, input_fn=input_fn
    )

    row: dict = {"ssh_host": ssh_host, "ssh_user": user}
    if port != 22:
        row["ssh_port"] = port
    row["ssh_key"] = str(private)
    row["known_host"] = f"{algo} {blob}"
    # The row is only ever S14.7c's own keys — bundle_dir, docker_optional,
    # activate, admin and secrets stay the operator's (ENROLL_ROW_KEYS is the
    # single statement of that set, and hosts.py's writer enforces it on edit).

    prove_login(dict(row), config=config, repo_root=repo_root, name=name,
                exec_fn=exec_fn)

    rendered = write_host_row(hosts_path, name, row, replace=replace)
    out(f"[S14.7c] host '{name}' enrolled — written to {hosts_path}:")
    out("")
    out(rendered.rstrip("\n"))
    out("")
    out(f"Verify: ciu ssh {name} -- ciu version")
    return 0
