"""`ciu init` — guided scaffolding of a CIU-enabled repository (S10.1 verb).

Mechanical, validation-first: the generated global defaults are rendered
through the real S3.2 pipeline order (Jinja2 -> TOML parse) and the stack
defaults through the real shape validator BEFORE anything is written; an
existing target file is never overwritten. Templates ship inside the wheel
(`ciu/templates/`) so a plain `pip install ciu` carries them.
"""

from __future__ import annotations

import re
import sys
from importlib import resources
from pathlib import Path

_PROJECT_NAME_RE = re.compile(r"[a-z][a-z0-9-]*")
# (entry, why-it-is-ignored) — written into the consumer's .gitignore with
# the comment attached, so the file explains itself (S2.7 / S3.1 / S8.1).
_GITIGNORE_ENTRIES = (
    ("ciu.env", "machine identity layer (S2.7) — regenerated by `ciu env generate`"),
    ("ciu.global.toml", "rendered global config — track the .j2 source, not its output"),
    ("**/.ciu/", "per-stack machine dirs: rendered ciu.toml, secrets, overlays"),
    ("**/ciu.compose.yml", "CIU's rendered compose output for .j2 templates (S8.1)"),
)
_TEMPLATE_DIR = "templates"
# ciu-P20 (CIU-QOL-13) — `ciu init --hooks NAME1,NAME2` (docs/SPEC.md S19.1).
_HOOK_TEMPLATE_PACKAGE = "ciu.hook_templates"
# The exact copy-time stamp format, documented in docs/SPEC.md S19.1 so a
# future revision-comparison feature has a stable format to parse back out.
_HOOK_STAMP_FORMAT = "# ciu-hook-template: {filename} rev={revision}\n"


def _template(name: str) -> str:
    return (
        resources.files("ciu").joinpath(f"{_TEMPLATE_DIR}/{name}").read_text(
            encoding="utf-8"
        )
    )


def _available_hook_templates() -> dict[str, str]:
    """Return ``{template_name: filename}`` for every shipped hook template.

    Discovered dynamically from ``ciu.hook_templates`` (P20) so a future
    template lands here just by adding a module — no name list to keep in
    sync. ``template_name`` is the file stem, so ``ciu init --hooks NAME``
    maps 1:1 onto ``hook_templates/<NAME>.py``.
    """
    pkg = resources.files(_HOOK_TEMPLATE_PACKAGE)
    return {
        entry.name[: -len(".py")]: entry.name
        for entry in pkg.iterdir()
        if entry.name.endswith(".py") and entry.name != "__init__.py"
    }


def _hook_template_source(filename: str) -> str:
    """Verbatim source text of one shipped hook template file."""
    return resources.files(_HOOK_TEMPLATE_PACKAGE).joinpath(filename).read_text(
        encoding="utf-8"
    )


def _hook_template_revision(name: str) -> int:
    """The CURRENT ``template_revision`` of shipped hook template *name*.

    Imported (not regex-scraped) so this always matches the real value the
    module carries — the same file `_hook_template_source` copies verbatim.
    """
    import importlib

    module = importlib.import_module(f"{_HOOK_TEMPLATE_PACKAGE}.{name}")
    return module.template_revision


def _prompt(message: str, default: str) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{message}{suffix}: ").strip()
    except EOFError:
        answer = ""   # non-interactive stdin: take the default / skip
    return answer or default


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return _PROJECT_NAME_RE.match(slug) and slug or "my-project"


def _render_jinja(text: str, variables: dict) -> str:
    """Render a template with Jinja2, ``keep_trailing_newline=True`` matching
    S3.2 step 1's newline handling.

    CIU-81: uses ``StrictUndefined``, the same construction
    ``config_model.render_jinja2_text`` (the real S3.2 step 1, since CIU-74)
    uses — a mistyped or missing leaf key raises ``jinja2.UndefinedError``
    instead of silently rendering as the empty string. Verified 2026-08-31
    against every shipped scaffold template (``src/ciu/templates/*.j2``):
    none legitimately reference a name that would be undefined at
    scaffold-render time, so this closes the gap CIU-74 left open rather
    than papering over a real lenient-default need.
    """
    from jinja2 import Environment, StrictUndefined

    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    return env.from_string(text).render(**variables)


def collect_plan(argv: list[str], root: Path) -> dict:
    interactive = not any(a.startswith("--") for a in argv)

    def flag(name: str) -> str | None:
        for i, a in enumerate(argv):
            if a == name and i + 1 < len(argv):
                return argv[i + 1]
            if a.startswith(name + "="):
                return a.split("=", 1)[1]
        return None

    project_name = flag("--project-name")
    if not project_name:
        project_name = _slug(root.name)
    elif not _PROJECT_NAME_RE.fullmatch(project_name):
        raise SystemExit(f"init: --project-name must match {_PROJECT_NAME_RE.pattern}")
    if interactive:
        project_name = _prompt("Project name (lowercase slug)", project_name)
    environment_tag = flag("--environment-tag") or (
        _prompt("Environment tag", "dev") if interactive else "dev"
    )
    if not environment_tag.strip() or any(c in environment_tag for c in '"\n#'):
        raise SystemExit(
            f"init: --environment-tag {environment_tag!r} must be a plain TOML "
            "string value (no quotes/newlines/#)."
        )
    stacks_raw = flag("--stacks")
    stacks = [s for s in (stacks_raw or "").split(",") if s.strip()]
    if interactive and not stacks:
        raw = _prompt("First stack name to scaffold (blank = skip)", "")
        stacks = [s.strip() for s in raw.split(",") if s.strip()]

    parsed_stacks: list[dict] = []
    for raw_name in stacks:
        name = _slug(raw_name.replace("_", "-"))
        if name != raw_name:
            print(f"[INFO] stacking '{raw_name}' as directory/name {name!r}")

        root_key = name.replace("-", "_")
        parsed_stacks.append({
            "dir": f"applications/{name}",
            "root_key": root_key,
            "stack_name": name,
            "image": flag("--image") or "python:3.12-alpine",
            "port": 8080,
        })

    # ciu-P20 (CIU-QOL-13, S19.1) — `--hooks NAME1,NAME2` copies shipped hook
    # templates into every stack scaffolded THIS run. Validated here (before
    # any file is written, same discipline as --project-name/--environment-tag
    # above): an unknown name, or --hooks with no stack to copy into, is a
    # configuration error (exit 2 — S10.3), never a partial/silent scaffold.
    hooks_raw = flag("--hooks")
    # De-duplicated, order-preserving: a repeated name would otherwise queue
    # the identical (path, content) pair twice in build_files.
    hooks = list(dict.fromkeys(
        h.strip() for h in (hooks_raw or "").split(",") if h.strip()
    ))
    if hooks:
        available = _available_hook_templates()
        unknown = [h for h in hooks if h not in available]
        if unknown:
            print(
                "ciu init: unknown --hooks template(s): "
                + ", ".join(unknown)
                + " (available: "
                + (", ".join(sorted(available)) or "none")
                + ")",
                file=sys.stderr,
            )
            raise SystemExit(2)
        if not parsed_stacks:
            print(
                "ciu init: --hooks requires at least one --stacks target "
                "to copy into",
                file=sys.stderr,
            )
            raise SystemExit(2)

    return {
        "project_name": project_name,
        "environment_tag": environment_tag,
        "stacks": parsed_stacks,
        "hooks": hooks,
    }


def build_files(plan: dict, root: Path) -> list[tuple[Path, str]]:
    generated_by = "`ciu init`"
    base_vars = {
        "deploy": {
            "project_name": plan["project_name"],
            "environment_tag": plan["environment_tag"],
            "health": {"interval": "5s", "timeout": "3s", "retries": 3,
                        "start_period": "5s"},
            "env": {"defaults": {"TZ": "UTC", "PYTHONUNBUFFERED": "1"}},
        },
    }
    phase_services = "\n".join(
        f"[[deploy.phases.phase_1.services]]\n"
        f'path = "{s["dir"]}"\nname = "{s["stack_name"]}"'
        for s in plan["stacks"]
    ) or "# (no stacks scaffolded — add [deploy.phases.*] entries as you go)"
    files: list[tuple[Path, str]] = [
        (
            root / "ciu.global.defaults.toml.j2",
            _template("global.defaults.toml.j2").replace(
                "@@PROJECT_NAME@@", plan["project_name"]
            ).replace("@@ENVIRONMENT_TAG@@", plan["environment_tag"]).replace(
                "@@GENERATED_BY@@", generated_by
            ).replace("@@PHASE_SERVICES@@", phase_services),
        ),
    ]
    for stack in plan["stacks"]:
        vars_stack = {
            **base_vars,
            stack["root_key"]: {
                "app": {"image_name": stack["image"].rsplit(":", 1)[0],
                         "image_tag": stack["image"].rsplit(":", 1)[-1],
                         "internal_port": stack["port"],
                         "hostdir": {"data": ""}},
                "secrets": {"api_key": "GEN_LOCAL:x"},
            },
            **{k: v for k, v in stack.items() if isinstance(k, str)},
        }
        files.append((
            root / stack["dir"] / "ciu.defaults.toml.j2",
            _template("stack.defaults.toml.j2")
            .replace("@@ROOT_KEY@@", stack["root_key"])
            .replace("@@STACK_NAME@@", stack["stack_name"])
            .replace("@@STACK_DIR@@", stack["dir"])
            .replace("@@IMAGE_NAME@@", stack["image"].rsplit(":", 1)[0])
            .replace("@@IMAGE_TAG@@", stack["image"].rsplit(":", 1)[-1])
            .replace("@@PORT@@", str(stack["port"]))
            .replace("@@GENERATED_BY@@", generated_by),
        ))
        files.append((
            root / stack["dir"] / "ciu.compose.yml.j2",
            # validate-by-render happens below; store the RENDERED form? No —
            # ship the template verbatim; validation renders it separately.
            _template("stack.compose.yml.j2")
            .replace("@@ROOT_KEY@@", stack["root_key"])
            .replace("@@STACK_NAME@@", stack["stack_name"])
            .replace("@@STACK_DIR@@", stack["dir"])
            .replace("@@GENERATED_BY@@", generated_by),
        ))
        # ciu-P20 (CIU-QOL-13, S19.1) — copy each requested hook template
        # into THIS stack, verbatim plus a stamp comment naming the template
        # and the template_revision it was copied at. Destination is
        # `<stack_dir>/hooks/<name>.py` (S9.1's "script paths relative to the
        # stack dir" convention — a hook so declared would be
        # `./hooks/<name>.py` in `[<root>.hooks]`). Queued into the SAME
        # `files` list as everything else, so the existing-file-refusal
        # check below (and init_main's generic write loop) covers it for
        # free — no special-casing a hook file into a silent overwrite.
        for hook_name in plan.get("hooks", []):
            filename = _available_hook_templates()[hook_name]
            stamp = _HOOK_STAMP_FORMAT.format(
                filename=filename,
                revision=_hook_template_revision(hook_name),
            )
            files.append((
                root / stack["dir"] / "hooks" / filename,
                stamp + _hook_template_source(filename),
            ))
    # ---- validation-first: render + parse everything before writing -------
    # CIU-81: renders with StrictUndefined now, matching the real S3.2 render
    # path (config_model.render_jinja2_text, since CIU-74) exactly, so this
    # preflight has genuine fidelity to production instead of certifying a
    # scaffold template under weaker semantics than what actually consumes
    # it — a scaffold template's leaf typo is now caught HERE, not at the
    # first real `ciu up`. Verified against every shipped scaffold template
    # (src/ciu/templates/*.j2) before adopting: none legitimately reference
    # a name that would be undefined at scaffold-render time.
    from jinja2 import Environment, StrictUndefined, TemplateError

    jenv = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    import tomllib

    global_text = next(c for pth, c in files if pth.name == "ciu.global.defaults.toml.j2")
    try:
        rendered_global = jenv.from_string(global_text).render(**base_vars)
    except TemplateError as exc:
        raise SystemExit(
            f"init: ciu.global.defaults.toml.j2 failed to render: {exc} — template bug."
        ) from exc
    parsed_global = tomllib.loads(rendered_global)  # S3.2 step 3 equivalent

    # Review-blocker guard: the pipeline needs [deploy.env.shared] with the
    # ownership vars — parseability alone once shipped a repo that died at
    # step 7. Assert the FACTS the deploy actually consumes.
    shared = parsed_global.get("deploy", {}).get("env", {}).get("shared", {})
    for required in ("CONTAINER_UID", "DOCKER_GID", "REPO_ROOT", "PHYSICAL_REPO_ROOT"):
        if required not in shared:
            raise SystemExit(
                f"init: generated global template lacks deploy.env.shared.{required} "
                "(hostdir/secret ownership would fail at deploy) — template bug."
            )

    from ciu import config_model

    for stack in plan["stacks"]:
        entry = next((c for pth, c in files if pth.name == "ciu.defaults.toml.j2"
                      and stack["dir"] in str(pth)))
        try:
            rendered = jenv.from_string(entry).render(**vars_stack)
        except TemplateError as exc:
            raise SystemExit(
                f"init: {stack['dir']}/ciu.defaults.toml.j2 failed to render: "
                f"{exc} — template bug."
            ) from exc
        tomllib.loads(rendered)
        # Real shape validator (S3.5/S3.7) on the RENDERED defaults:
        config_model.validate_stack_shape(tomllib.loads(rendered))
    existing = [str(path.relative_to(root)) for path, _ in files
                if path.name != ".gitignore-additions.txt" and path.exists()]
    if existing:
        raise SystemExit(
            "init: refusing to overwrite existing file(s): " + ", ".join(existing)
            + " — move them aside first."
        )
    return files


def init_main(argv: list[str]) -> int:
    root = Path.cwd()
    plan = collect_plan(list(argv), root)
    files = build_files(plan, root)
    for path, content in files:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(root)}")
    gitignore = root / ".gitignore"
    raw_lines = (gitignore.read_text().splitlines()
                 if gitignore.exists() else [])
    # Normalize: an entry may carry a trailing "  # why" comment from a prior
    # init — compare on the ENTRY portion only, or reruns duplicate.
    existing_entries = {ln.split("  # ")[0].strip() for ln in raw_lines
                        if ln.strip()}
    missing = [entry for entry in _GITIGNORE_ENTRIES
               if entry[0] not in existing_entries]
    if missing:
        with gitignore.open("a", encoding="utf-8") as fh:
            fh.write("\n# --- CIU generated artifacts (added by `ciu init`) ---\n")
            for entry, why in missing:
                # git .gitignore has NO trailing-comment syntax — everything
                # after the pattern to EOL is PART of the pattern. Entry and
                # explanation must be separate lines.
                fh.write(f"# {why}\n{entry}\n")
        print(f"updated .gitignore (+{len(missing)} entries)")
    print(
        "\nNext steps:\n"
        "  1. Review the placeholders in ciu.global.defaults.toml.j2.\n"
        "  2. Run `ciu env generate` FROM THIS DIRECTORY. It ignores inherited\n"
        "     identity from other checkouts' sourced ciu.env (S2.7), so this\n"
        "     repo gets its own network/instance identity — never another\n"
        "     checkout's. Needs docker for the network ensure; safe to rerun.\n"
        "  3. Bring the first stack up: `ciu up --dir <stack-dir>`.\n"
    )
    return 0
