"""`ciu init` — guided scaffolding of a CIU-enabled repository (S10.1 verb).

Mechanical, validation-first: the generated global defaults are rendered
through the real S3.2 pipeline order (Jinja2 -> TOML parse) and the stack
defaults through the real shape validator BEFORE anything is written; an
existing target file is never overwritten. Templates ship inside the wheel
(`ciu/templates/`) so a plain `pip install ciu` carries them.
"""

from __future__ import annotations

import re
from importlib import resources
from pathlib import Path

_PROJECT_NAME_RE = re.compile(r"[a-z][a-z0-9-]*")
# (entry, why-it-is-ignored) — written into the consumer's .gitignore with
# the comment attached, so the file explains itself (S2.7 / S3.1 / S8.1).
_GITIGNORE_ENTRIES = (
    ("ciu.env", "machine identity layer (S2.7) — regenerated by `ciu env generate`"),
    ("ciu.global.toml", "rendered global config — track the .j2 source, not its output"),
    ("**/.ciu/", "per-stack machine dirs: rendered ciu.toml, secrets, overlays"),
    ("**/ciu.compose.yml", "CIU's rendered compose output for .j2 templates (S8.1)"),
)
_TEMPLATE_DIR = "templates"


def _template(name: str) -> str:
    return (
        resources.files("ciu").joinpath(f"{_TEMPLATE_DIR}/{name}").read_text(
            encoding="utf-8"
        )
    )


def _prompt(message: str, default: str) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{message}{suffix}: ").strip()
    except EOFError:
        answer = ""   # non-interactive stdin: take the default / skip
    return answer or default


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return _PROJECT_NAME_RE.match(slug) and slug or "my-project"


def _render_jinja(text: str, variables: dict) -> str:
    """Render a template with the SAME engine production uses (S3.2 step 1)."""
    from jinja2 import Environment

    env = Environment(keep_trailing_newline=True)
    return env.from_string(text).render(**variables)


def collect_plan(argv: list[str], root: Path) -> dict:
    interactive = not any(a.startswith("--") for a in argv)

    def flag(name: str) -> str | None:
        for i, a in enumerate(argv):
            if a == name and i + 1 < len(argv):
                return argv[i + 1]
            if a.startswith(name + "="):
                return a.split("=", 1)[1]
        return None

    project_name = flag("--project-name")
    if not project_name:
        project_name = _slug(root.name)
    elif not _PROJECT_NAME_RE.fullmatch(project_name):
        raise SystemExit(f"init: --project-name must match {_PROJECT_NAME_RE.pattern}")
    if interactive:
        project_name = _prompt("Project name (lowercase slug)", project_name)
    environment_tag = flag("--environment-tag") or (
        _prompt("Environment tag", "dev") if interactive else "dev"
    )
    if not environment_tag.strip() or any(c in environment_tag for c in '"\n#'):
        raise SystemExit(
            f"init: --environment-tag {environment_tag!r} must be a plain TOML "
            "string value (no quotes/newlines/#)."
        )
    stacks_raw = flag("--stacks")
    stacks = [s for s in (stacks_raw or "").split(",") if s.strip()]
    if interactive and not stacks:
        raw = _prompt("First stack name to scaffold (blank = skip)", "")
        stacks = [s.strip() for s in raw.split(",") if s.strip()]

    parsed_stacks: list[dict] = []
    for raw_name in stacks:
        name = _slug(raw_name.replace("_", "-"))
        if name != raw_name:
            print(f"[INFO] stacking '{raw_name}' as directory/name {name!r}")

        root_key = name.replace("-", "_")
        parsed_stacks.append({
            "dir": f"applications/{name}",
            "root_key": root_key,
            "stack_name": name,
            "image": flag("--image") or "python:3.12-alpine",
            "port": 8080,
        })
    return {
        "project_name": project_name,
        "environment_tag": environment_tag,
        "stacks": parsed_stacks,
    }


def build_files(plan: dict, root: Path) -> list[tuple[Path, str]]:
    generated_by = "`ciu init`"
    base_vars = {
        "deploy": {
            "project_name": plan["project_name"],
            "environment_tag": plan["environment_tag"],
            "health": {"interval": "5s", "timeout": "3s", "retries": 3,
                        "start_period": "5s"},
            "env": {"defaults": {"TZ": "UTC", "PYTHONUNBUFFERED": "1"}},
        },
    }
    phase_services = "\n".join(
        f"[[deploy.phases.phase_1.services]]\n"
        f'path = "{s["dir"]}"\nname = "{s["stack_name"]}"'
        for s in plan["stacks"]
    ) or "# (no stacks scaffolded — add [deploy.phases.*] entries as you go)"
    files: list[tuple[Path, str]] = [
        (
            root / "ciu.global.defaults.toml.j2",
            _template("global.defaults.toml.j2").replace(
                "@@PROJECT_NAME@@", plan["project_name"]
            ).replace("@@ENVIRONMENT_TAG@@", plan["environment_tag"]).replace(
                "@@GENERATED_BY@@", generated_by
            ).replace("@@PHASE_SERVICES@@", phase_services),
        ),
    ]
    for stack in plan["stacks"]:
        vars_stack = {
            **base_vars,
            stack["root_key"]: {
                "app": {"image_name": stack["image"].rsplit(":", 1)[0],
                         "image_tag": stack["image"].rsplit(":", 1)[-1],
                         "internal_port": stack["port"],
                         "hostdir": {"data": ""}},
                "secrets": {"api_key": "GEN_LOCAL:x"},
            },
            **{k: v for k, v in stack.items() if isinstance(k, str)},
        }
        files.append((
            root / stack["dir"] / "ciu.defaults.toml.j2",
            _template("stack.defaults.toml.j2")
            .replace("@@ROOT_KEY@@", stack["root_key"])
            .replace("@@STACK_NAME@@", stack["stack_name"])
            .replace("@@STACK_DIR@@", stack["dir"])
            .replace("@@IMAGE_NAME@@", stack["image"].rsplit(":", 1)[0])
            .replace("@@IMAGE_TAG@@", stack["image"].rsplit(":", 1)[-1])
            .replace("@@PORT@@", str(stack["port"]))
            .replace("@@GENERATED_BY@@", generated_by),
        ))
        files.append((
            root / stack["dir"] / "ciu.compose.yml.j2",
            # validate-by-render happens below; store the RENDERED form? No —
            # ship the template verbatim; validation renders it separately.
            _template("stack.compose.yml.j2")
            .replace("@@ROOT_KEY@@", stack["root_key"])
            .replace("@@STACK_NAME@@", stack["stack_name"])
            .replace("@@STACK_DIR@@", stack["dir"])
            .replace("@@GENERATED_BY@@", generated_by),
        ))
    # ---- validation-first: render + parse everything before writing -------
    from jinja2 import Environment

    jenv = Environment(keep_trailing_newline=True)
    import tomllib

    global_text = next(c for pth, c in files if pth.name == "ciu.global.defaults.toml.j2")
    rendered_global = jenv.from_string(global_text).render(**base_vars)
    parsed_global = tomllib.loads(rendered_global)  # S3.2 step 3 equivalent

    # Review-blocker guard: the pipeline needs [deploy.env.shared] with the
    # ownership vars — parseability alone once shipped a repo that died at
    # step 7. Assert the FACTS the deploy actually consumes.
    shared = parsed_global.get("deploy", {}).get("env", {}).get("shared", {})
    for required in ("CONTAINER_UID", "DOCKER_GID", "REPO_ROOT", "PHYSICAL_REPO_ROOT"):
        if required not in shared:
            raise SystemExit(
                f"init: generated global template lacks deploy.env.shared.{required} "
                "(hostdir/secret ownership would fail at deploy) — template bug."
            )

    from ciu import config_model

    for stack in plan["stacks"]:
        entry = next((c for pth, c in files if pth.name == "ciu.defaults.toml.j2"
                      and stack["dir"] in str(pth)))
        rendered = jenv.from_string(entry).render(**vars_stack)
        tomllib.loads(rendered)
        # Real shape validator (S3.5/S3.7) on the RENDERED defaults:
        config_model.validate_stack_shape(tomllib.loads(rendered))
    existing = [str(path.relative_to(root)) for path, _ in files
                if path.name != ".gitignore-additions.txt" and path.exists()]
    if existing:
        raise SystemExit(
            "init: refusing to overwrite existing file(s): " + ", ".join(existing)
            + " — move them aside first."
        )
    return files


def init_main(argv: list[str]) -> int:
    root = Path.cwd()
    plan = collect_plan(list(argv), root)
    files = build_files(plan, root)
    for path, content in files:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(root)}")
    gitignore = root / ".gitignore"
    raw_lines = (gitignore.read_text().splitlines()
                 if gitignore.exists() else [])
    # Normalize: an entry may carry a trailing "  # why" comment from a prior
    # init — compare on the ENTRY portion only, or reruns duplicate.
    existing_entries = {ln.split("  # ")[0].strip() for ln in raw_lines
                        if ln.strip()}
    missing = [entry for entry in _GITIGNORE_ENTRIES
               if entry[0] not in existing_entries]
    if missing:
        with gitignore.open("a", encoding="utf-8") as fh:
            fh.write("\n# --- CIU generated artifacts (added by `ciu init`) ---\n")
            for entry, why in missing:
                # git .gitignore has NO trailing-comment syntax — everything
                # after the pattern to EOL is PART of the pattern. Entry and
                # explanation must be separate lines.
                fh.write(f"# {why}\n{entry}\n")
        print(f"updated .gitignore (+{len(missing)} entries)")
    print(
        "\nNext steps:\n"
        "  1. Review the placeholders in ciu.global.defaults.toml.j2.\n"
        "  2. Run `ciu env generate` FROM THIS DIRECTORY. It ignores inherited\n"
        "     identity from other checkouts' sourced ciu.env (S2.7), so this\n"
        "     repo gets its own network/instance identity — never another\n"
        "     checkout's. Needs docker for the network ensure; safe to rerun.\n"
        "  3. Bring the first stack up: `ciu up --dir <stack-dir>`.\n"
    )
    return 0
