#!/usr/bin/env python3
"""
Workspace environment loader for CIU.

This module reads ciu.env files generated by ciu --generate-env
and exposes the values as process environment variables.
"""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import shutil
import socket
import stat
import subprocess
import sys
import tomllib
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, Iterable, Mapping, Optional

import re

from . import governance as governance_mod
from .config_constants import (
    GLOBAL_CONFIG_DEFAULTS,
    GLOBAL_CONFIG_RENDERED,
    GLOBAL_CONFIG_WORKTREE_OVERRIDES,
    WORKSPACE_ENV,
)

STANDALONE_ROOT_PATTERN = re.compile(
    r"^\s*standalone_root\s*=\s*true\s*$",
    re.IGNORECASE | re.MULTILINE,
)


ENV_FILE_NAME = WORKSPACE_ENV

# The derived identity tuple (S2.7 / CIU-41). After a generate in the same
# run, these keys from the freshly written ciu.env outrank any inherited
# ambient value: the record was computed for THIS repo root moments ago and
# is by construction fresher than shell state sourced from another checkout.
# PUBLIC_FQDN joins with CIU-47: generate derives it from THIS workspace's
# own inputs, so the written record outranks an inherited ambient value here
# too (read-path precedence of already-generated workspaces is unchanged).
GENERATED_IDENTITY_KEYS = (
    "REPO_NAME",
    "INSTANCE_ID",
    "DOCKER_NETWORK_INTERNAL",
    "PUBLIC_FQDN",
)

# S2.2 — required keys always present in ciu.env
REQUIRED_KEYS_CORE: tuple[str, ...] = (
    "REPO_ROOT",
    "PHYSICAL_REPO_ROOT",
    "DOCKER_NETWORK_INTERNAL",
    "CONTAINER_UID",
    "DOCKER_GID",
)

# S3.1b (CIU-60) — the CIU-owned table `ciu env generate` upserts into this
# checkout's `ciu.global.worktree.toml.j2`, so the identity facts a TEMPLATE
# needs reach it through the ordinary merged-config chain instead of through
# ambient `os.environ` (S3.2's `env` context is still raw process environment;
# hooks got the safe treatment in S9.3, templates never did).
#
# The key names are snake_case to match this file's existing key-naming
# convention (`ref_path`, `network`, `ref_projects`), NOT the SCREAMING_CASE
# shell-env names they are derived from.
GENERATED_FACTS_TABLE = "ciu.instance.generated"
GENERATED_FACTS_HEADER = f"[{GENERATED_FACTS_TABLE}]"
GENERATED_FACTS_KEYS: tuple[str, ...] = (
    "repo_name",
    "instance_id",
    "network",
    "physical_repo_root",
    "repo_root",
    "public_fqdn",
)

# S3.1c (CIU-75) — the ONE translation table between the overlay's snake_case
# fact names (above) and the legacy SCREAMING_CASE `ciu.env` key names. It
# exists because a CHILD ciu process and a template's `$VAR` expansion still
# speak shell-env names; nothing inside CIU reads the `ciu.env` FILE any more.
# Keep it exhaustive over GENERATED_FACTS_KEYS — a fact with no env name would
# silently vanish from every child environment built from it.
GENERATED_FACT_ENV_KEYS: dict[str, str] = {
    "repo_name": "REPO_NAME",
    "instance_id": "INSTANCE_ID",
    "network": "DOCKER_NETWORK_INTERNAL",
    "physical_repo_root": "PHYSICAL_REPO_ROOT",
    "repo_root": "REPO_ROOT",
    "public_fqdn": "PUBLIC_FQDN",
}

# The same six names as a set: the keys `ciu.env` still CARRIES but that CIU
# never takes FROM it (S3.1c clause 2). The distinction matters because
# `ciu.env` also carries MACHINE facts (`CONTAINER_UID`, `DOCKER_GID`,
# `ENV_TYPE`, `PUBLIC_IP`, `PUBLIC_TLS_*`, `PYTHON_EXECUTABLE`, `HOST_MDT_TMP`
# …) which are properties of the host, not of the instance, and which S3.1c
# clause 7 leaves on live derivation. Deriving this from the mapping above
# rather than listing it again is deliberate: a fact added to one and not the
# other is exactly the drift this table exists to prevent.
LEGACY_IDENTITY_ENV_KEYS: frozenset[str] = frozenset(GENERATED_FACT_ENV_KEYS.values())

# Written once, at the top of a file this function had to create from nothing.
# Mirrors `worktree._worktree_overlay_text`'s own header-comment style so a
# CIU-created overlay looks the same whichever code path created it.
_OVERLAY_FRESH_HEADER: tuple[str, ...] = (
    "# Worktree-local sparse global override (S3.1b / S16).",
    "# Durable configuration: preserved by `ciu clean` and `ciu env generate`.",
)

# These live INSIDE the owned block (below the table header, above the keys)
# rather than above the header on purpose: the upsert owns exactly the region
# from the header line to the next table, so a comment placed above the header
# would survive the replace and be re-emitted on every run, growing a duplicate
# banner per `env generate`. Below it, the block is byte-idempotent.
_GENERATED_FACTS_BANNER: tuple[str, ...] = (
    "# CIU-owned (S3.1b): rewritten in full by every `ciu env generate`.",
    "# Do NOT hand-edit keys in THIS table — edits here are silently",
    "# overwritten. Every OTHER byte of this file is yours and is preserved.",
)


# S3.1c (CIU-75) — the single wording of the one-release deprecation notice, so
# the `ciu env generate` write path and the `ciu env` read path cannot drift
# into two different stories about what changed. `{path}` is the ciu.env whose
# consumer is being nudged.
LEGACY_ENV_EXPORT_WARNING = (
    "[S3.1c] {path} is a LEGACY WRITE-ONLY export as of ciu 7.7.0: CIU itself "
    "no longer reads it — instance identity now comes only from the "
    f"[{GENERATED_FACTS_TABLE}] table in {GLOBAL_CONFIG_WORKTREE_OVERRIDES}. "
    "The key set is unchanged, so a shell or tool that `source`s it still "
    "works this release; switch it to `eval \"$(ciu env print)\"` — a future "
    "release stops writing the file."
)


class WorkspaceEnvError(ValueError):
    """Raised when workspace environment file is missing or invalid."""


def _log_info(message: str) -> None:
    print(f"[INFO] {message}", flush=True)


def _log_warn(message: str, *, stream=None) -> None:
    """A `[WARN]` line, on stdout by default.

    ``stream`` exists for S3.1c clause 3 (CIU-75 review): a notice raised by a
    verb the operator typed may go to stdout, but the SAME notice raised from
    the STEP-1 bootstrap of `ciu check --json` must not — it would land ahead
    of the JSON document and break every machine consumer's parse. ``None``
    means "stdout at call time", which is what `print` already does, so no
    existing caller changes behavior.
    """
    print(f"[WARN] {message}", file=stream, flush=True)


def resolve_env_root(start_dir: Path, define_root: Optional[Path], defaults_filename: str) -> Path:
    """Resolve the workspace env root directory.

    Order:
    1. Explicit --define-root
    2. Walk up from start_dir until defaults_filename is found
    3. Fallback to start_dir
    """
    if define_root:
        root = define_root.resolve()
        if not root.exists():
            raise WorkspaceEnvError(f"Repository root does not exist: {root}")
        return root

    current = start_dir.resolve()
    while True:
        if (current / defaults_filename).exists():
            return current
        if current == current.parent:
            break
        current = current.parent

    return start_dir.resolve()


def find_workspace_env(start_dir: Path) -> Path:
    """Find ciu.env by walking up from start_dir.

    Priority:
    1. REPO_ROOT environment variable (if set)
    2. Walk up directory tree from start_dir
    """
    repo_root = os.environ.get("REPO_ROOT")
    if repo_root:
        candidate = Path(repo_root).resolve() / ENV_FILE_NAME
        if candidate.exists():
            return candidate

    current = start_dir.resolve()
    while True:
        candidate = current / ENV_FILE_NAME
        if candidate.exists():
            return candidate
        if current == current.parent:
            break
        current = current.parent

    raise WorkspaceEnvError(
        f"Workspace environment file {ENV_FILE_NAME} not found. "
        "Run: ciu env generate"
    )


def parse_workspace_env(path: Path) -> Dict[str, str]:
    """Parse ciu.env into a dict of key/value pairs."""
    values: Dict[str, str] = {}

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()

        lexer = shlex.shlex(line, posix=True)
        lexer.whitespace_split = True
        lexer.commenters = "#"
        try:
            tokens = list(lexer)
        except ValueError as exc:
            raise WorkspaceEnvError(
                f"Invalid {ENV_FILE_NAME} entry: {raw_line!r}"
            ) from exc
        if not tokens:
            continue
        if len(tokens) != 1 or "=" not in tokens[0]:
            raise WorkspaceEnvError(
                f"Invalid {ENV_FILE_NAME} entry: {raw_line!r}"
            )

        key, value = tokens[0].split("=", 1)
        key = key.strip()
        if not key:
            raise WorkspaceEnvError(
                f"Invalid {ENV_FILE_NAME} entry (empty key): {raw_line!r}"
            )
        values[key] = value

    return values


def load_workspace_env(start_dir: Path, override: bool = False) -> Dict[str, str]:
    """Load ciu.env and populate os.environ.

    **Not for identity, and not for CIU's own bootstrap (S3.1c).** Two reasons,
    both of which cost real bugs before CIU-75: it seeds the six identity keys
    from the LEGACY export, which since 7.7.0 is not where identity lives; and
    it locates the file through :func:`find_workspace_env`, which honors an
    ambient ``REPO_ROOT`` and can therefore load a DIFFERENT checkout's file
    entirely. `bootstrap_workspace_env` uses :func:`_load_legacy_machine_env`
    (exact path, machine facts only) plus :func:`seed_identity_env`. This
    function remains for consumers of the legacy export itself.

    Args:
        start_dir: Directory to begin searching for ciu.env
        override: If True, overwrite existing os.environ values

    Returns:
        Dict of loaded values (from file)
    """
    env_path = find_workspace_env(start_dir)
    values = parse_workspace_env(env_path)

    for key, value in values.items():
        if override or key not in os.environ:
            os.environ[key] = value

    return values


def ensure_workspace_env(required_keys: Iterable[str]) -> None:
    """Ensure required environment variables are present.

    Raises WorkspaceEnvError if any are missing or empty.
    S2.5: 0 is a valid value — check is None / == "" not truthiness.
    """
    missing = [key for key in required_keys if os.environ.get(key) is None or os.environ.get(key) == ""]
    if missing:
        missing_str = ", ".join(missing)
        raise WorkspaceEnvError(
            "Missing required workspace environment variables: "
            f"{missing_str}. "
            'Run: ciu env generate (then, for a shell: eval "$(ciu env print)")'
        )


def detect_standalone_root(start_dir: Path) -> Optional[Path]:
    """Detect a standalone CIU root based on ciu.global.defaults.toml.j2.

    Returns the nearest parent directory whose ciu.global.defaults.toml.j2
    contains 'standalone_root = true'.
    """
    current = start_dir.resolve()
    while True:
        candidate = current / GLOBAL_CONFIG_DEFAULTS
        if candidate.exists():
            try:
                content = candidate.read_text(encoding="utf-8")
            except OSError:
                content = ""
            if STANDALONE_ROOT_PATTERN.search(content):
                return current
        if current == current.parent:
            break
        current = current.parent
    return None


def enforce_standalone_root(start_dir: Path) -> None:
    """Enforce the S1.2 standalone-root guard from an INVOCATION directory.

    If ``start_dir`` sits inside a standalone CIU root (a directory whose
    ``ciu.global.defaults.toml.j2`` sets ``standalone_root = true``), then
    ``$REPO_ROOT`` MUST resolve to that same directory, else ``WorkspaceEnvError``.

    ``start_dir`` MUST be the directory the command was invoked from (cwd, or the
    ``--dir`` target), NOT an already-resolved ``repo_root``. The guard exists
    precisely to catch a contaminated / stale ``$REPO_ROOT`` — e.g. a sibling
    repo's ``ciu.env`` auto-sourced by the shell (``~/.bashrc`` sourcing
    ``${REPO_ROOT}/ciu.env``). Walking up from the *resolved* root would inspect
    the wrong repo's marker and silently pass — which is exactly the bug this
    helper fixes: ``ciu render`` used ``detect_standalone_root(repo_root)`` while
    ``ciu up`` used the invocation dir, so the two paths disagreed and ``render``
    would proceed against the wrong repo. Both call this with their invocation
    directory now, so they cannot diverge again.
    """
    standalone_root = detect_standalone_root(start_dir)
    if standalone_root is None:
        return
    env_repo_root_raw = os.environ.get("REPO_ROOT", "")
    if not env_repo_root_raw:
        # Nothing to compare against; resolve_repo_root / bootstrap raise their
        # own "REPO_ROOT not set" error for the unset case.
        return
    env_repo_root = Path(env_repo_root_raw).resolve()
    if env_repo_root != standalone_root:
        raise WorkspaceEnvError(
            "[S1.2] standalone_root is true but REPO_ROOT does not match. "
            f"Expected: {standalone_root}, got: {env_repo_root}. "
            "Regenerate ciu.env from the standalone root (or run from it)."
        )


def _detect_env_type() -> Dict[str, str]:
    """Detect ENV_TYPE: devcontainer | native | github-actions (S2.7).

    v1's 'bare-metal' is renamed 'native' per S2.7 / Appendix C.
    IS_NATIVE replaces IS_BARE_METAL; IS_DEVCONTAINER and IS_GITHUB_ACTIONS
    are retained.
    """
    env_type = os.environ.get("ENV_TYPE")
    if not env_type:
        if os.environ.get("GITHUB_ACTIONS"):
            env_type = "github-actions"
        elif os.environ.get("REMOTE_CONTAINERS") or os.environ.get("WORKSPACE_DIR") or Path("/.dockerenv").exists():
            env_type = "devcontainer"
        else:
            env_type = "native"

    return {
        "ENV_TYPE": env_type,
        "IS_DEVCONTAINER": "1" if env_type == "devcontainer" else "0",
        "IS_GITHUB_ACTIONS": "1" if env_type == "github-actions" else "0",
        "IS_NATIVE": "1" if env_type == "native" else "0",
    }


def _detect_public_fqdn(repo_root: Path, require_fqdn: bool) -> Dict[str, str]:
    """Detect PUBLIC_FQDN/PUBLIC_IP with S2.7 refined precedence (CIU-47).

    ``env generate`` is the identity-computation verb: PUBLIC_FQDN is derived
    from THIS workspace's own inputs — the rendered global config's
    ``infrastructure.public_fqdn`` first, else reverse DNS of the detected
    public IP — and an ambient ``PUBLIC_FQDN`` (a shell that sourced another
    checkout's ``ciu.env`` carries that checkout's value) is adopted only
    when CONSISTENT with what this workspace derives. On a real mismatch the
    derived value wins and a stderr warning names the ignored ambient value
    — the same refined precedence S2.7 applies to ``PHYSICAL_REPO_ROOT`` and
    the identity tuple (CIU-41).

    One deliberate exception, mirroring the mountinfo precedent: when the
    detection path yields NO independently sourced value (no config entry,
    and reverse DNS produced nothing — e.g. an offline host), there is no
    basis to override an explicit pre-set value, so the ambient FQDN is kept
    silently. It remains the legitimate manual-override mechanism there.
    The bare ``os.environ.get("PUBLIC_FQDN", ...)`` fallback this replaces
    adopted the ambient value unconditionally, with no consistency check —
    a main checkout's sourced ``ciu.env`` leaked its FQDN into a fresh
    worktree's generated record (CIU-47).

    ``PUBLIC_IP`` and the TLS paths keep the plain S2.7 pre-set-wins reads;
    they are not part of the filed CIU-47 scope.
    """
    ambient_fqdn = os.environ.get("PUBLIC_FQDN") or ""
    public_ip = os.environ.get("PUBLIC_IP", "")

    # -- Derive from THIS workspace's own inputs first (CIU-47) ------------
    # `derived` is None until a value with a real source behind it exists.
    derived: Optional[str] = None

    ciu_global = repo_root / GLOBAL_CONFIG_RENDERED
    if ciu_global.exists():
        try:
            import tomllib

            with ciu_global.open("rb") as f:
                config = tomllib.load(f)
            configured = config.get("infrastructure", {}).get("public_fqdn", "")
            if isinstance(configured, str) and configured:
                derived = configured
        except (tomllib.TOMLDecodeError, OSError, KeyError, AttributeError, TypeError) as exc:
            _log_warn(f"Could not parse {ciu_global}: {exc}")

    if not public_ip:
        try:
            with urllib.request.urlopen("https://api.ipify.org", timeout=10) as resp:
                public_ip = resp.read().decode("utf-8").strip()
        except (urllib.error.URLError, TimeoutError):
            public_ip = ""

    if derived is None and public_ip:
        try:
            derived = socket.gethostbyaddr(public_ip)[0]
        except (socket.herror, socket.gaierror):
            derived = None

    # -- Reconcile with the ambient value (S2.7 refined precedence) --------
    if ambient_fqdn:
        if derived is not None and derived != ambient_fqdn:
            print(
                f"ciu: ignoring pre-set PUBLIC_FQDN={ambient_fqdn!r} during "
                f"env generate — inconsistent with the value derived for "
                f"this workspace ({derived!r}). The derived value is written "
                "to ciu.env (the pre-set env is likely stale/cross-workspace "
                "shell state, e.g. inherited from another checkout's sourced "
                "ciu.env).",
                file=sys.stderr,
            )
            public_fqdn = derived
        else:
            # Consistent, or no independently derived value to compare
            # against — the pre-set value stands (manual override).
            public_fqdn = ambient_fqdn
    else:
        public_fqdn = derived or ""

    if not public_fqdn:
        if require_fqdn:
            raise WorkspaceEnvError("Failed to detect PUBLIC_FQDN. Set PUBLIC_FQDN in the environment.")
        public_fqdn = public_ip or "localhost"

    return {
        "PUBLIC_IP": public_ip,
        "PUBLIC_FQDN": public_fqdn,
        "PUBLIC_TLS_CRT_PEM": os.environ.get("PUBLIC_TLS_CRT_PEM", ""),
        "PUBLIC_TLS_KEY_PEM": os.environ.get("PUBLIC_TLS_KEY_PEM", ""),
    }


def _detect_docker_gid() -> str:
    docker_gid = os.environ.get("DOCKER_GID", "")
    # S2.5: '0' is a valid value — do not reject on falsy check
    if docker_gid is not None and docker_gid != "":
        return docker_gid

    for socket_path in ("/var/run/docker-host.sock", "/var/run/docker.sock"):
        if Path(socket_path).exists():
            return str(Path(socket_path).stat().st_gid)

    try:
        import grp

        return str(grp.getgrnam("docker").gr_gid)
    except KeyError:
        raise WorkspaceEnvError("DOCKER_GID not found. Ensure docker group exists or set DOCKER_GID.")


def _detect_governance_read_iops() -> tuple[str, str]:
    """S15.6 — derive ``CIU_GOV_READ_IOPS`` for the ``ciu env generate`` phase.

    A pre-set environment value always wins (S2.7 — every ciu.env key is
    autodetected, but an already-set value is never overridden). Otherwise
    delegates to :func:`ciu.governance.derive_read_iops` with ``configured=0``
    (always "derive" here — ciu.env is the machine-identity layer, S2.7; the
    per-stack ``read_iops``/``baseline_path`` overrides are handled directly
    by the overlay generator, which re-derives independently so governance
    still works without an env regen). Derivation follows the S15.4 baseline
    search order: env ``CIU_GOV_BASELINE_PATH`` →
    ``/var/lib/ciu/io-baseline.env`` → mdt host-setup's
    ``/var/lib/mdt/io-baseline.env``; first existing file wins.

    Returns ``(value_str, source_note)`` — the note is folded into the emitted
    comment so ``ciu.env`` documents where the number came from.
    """
    preset = os.environ.get("CIU_GOV_READ_IOPS")
    if preset is not None and preset != "":
        return preset, "explicit (pre-set in environment)"
    value, note = governance_mod.derive_read_iops(0)
    return str(value), note


# Contract 1 (P-physical-root-mount-table): this process's own mount table.
# Overridable per-call for tests; referenced as a bare module global (not a
# function-default) inside _physical_root_from_mountinfo so monkeypatching
# `ciu.workspace_env._MOUNTINFO_PATH` takes effect without needing to thread
# the path through every caller.
_MOUNTINFO_PATH = Path("/proc/self/mountinfo")


def _unescape_mountinfo_path(value: str) -> str:
    """Decode the pathname escapes mandated by ``proc(5)`` mountinfo.

    The mount table separates fields on spaces, so its path fields encode a
    literal space, tab, newline, and backslash as octal escapes.  Treating the
    encoded spelling as a ``Path`` makes a bind mount below a directory with a
    space invisible to the longest-prefix lookup, and CIU then falls back to a
    potentially unrelated devcontainer label.  Decode exactly one mountinfo
    escape level; a literal ``\\040`` in a path must not be decoded twice.
    """
    escapes = {"040": " ", "011": "\t", "012": "\n", "134": "\\"}
    return re.sub(r"\\(040|011|012|134)", lambda match: escapes[match.group(1)], value)


def _parse_mountinfo(text: str) -> list[tuple[Path, Path]]:
    """Parse ``/proc/self/mountinfo`` into ``(mount_point, mount_root)`` pairs.

    Format (``man 5 proc``): each line's fixed fields before the literal
    ``" - "`` separator are ``mount_id parent_id major:minor root mount_point
    mount_opts``, followed by zero or more optional ``tag:value`` fields.
    ``root`` and ``mount_point`` sit at fixed indices (3, 4) regardless of how
    many optional fields trail them, so this is safe without locating the
    separator for those two fields.

    For a bind mount, ``root`` is the sub-path of the underlying filesystem
    exposed at ``mount_point`` — e.g. a devcontainer bind-mounting
    ``/home/vb/volkb79-2/vbpub`` (host) at ``/workspaces/vbpub`` (container)
    reports ``root=/home/vb/volkb79-2/vbpub mount_point=/workspaces/vbpub``.
    That ``root`` value is exactly the physical (host) path we want.

    The root mount itself (``mount_point == "/"``) is skipped: it carries no
    per-repo bind-mount signal (its ``root`` is meaningless overlay/rootfs
    plumbing, not a host path), so it must never win a longest-match contest.
    """
    entries: list[tuple[Path, Path]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if " - " not in line:
            continue
        left = line.split(" - ", 1)[0]
        fields = left.split()
        if len(fields) < 5:
            continue
        mount_root = _unescape_mountinfo_path(fields[3])
        mount_point = _unescape_mountinfo_path(fields[4])
        if mount_point == "/":
            continue
        entries.append((Path(mount_point), Path(mount_root)))
    return entries


def _physical_root_from_mountinfo(repo_root: Path) -> Optional[Path]:
    """Contract 1 — longest mount-destination-prefix match via mountinfo.

    Ports the longest-match algorithm from tls-edge's ``physical_path()``
    (``tls-edge/scripts/render_standalone.py``): for *repo_root*, find the
    mount whose destination is the LONGEST prefix of ``repo_root.resolve()``
    and map through its source. The port reads THIS process's own mount table
    (``/proc/self/mountinfo``) instead of shelling out to ``docker inspect``
    for another container's Mounts — tls-edge inspects a named sibling
    container; here we only ever need our own view.

    Returns ``None`` when mountinfo is unreadable or yields no match, so the
    caller can fall through to the next candidate (Contract 2).
    """
    try:
        text = _MOUNTINFO_PATH.read_text(encoding="utf-8")
    except OSError:
        return None

    resolved = repo_root.resolve()
    best_dest: Optional[Path] = None
    best_root: Optional[Path] = None
    for dest, root in _parse_mountinfo(text):
        if (dest == resolved or dest in resolved.parents) and (
            best_dest is None or len(dest.parts) > len(best_dest.parts)
        ):
            best_dest, best_root = dest, root

    if best_dest is None or best_root is None:
        return None
    return best_root / resolved.relative_to(best_dest)


def _detect_physical_repo_root(repo_root: Path) -> Path:
    """Contract precedence (SPEC.md S2.7): pre-set env (when consistent) ->
    mountinfo -> docker-ps devcontainer-origin label -> identity.

    A pre-set ``PHYSICAL_REPO_ROOT`` is a legitimate manual-override
    mechanism (native host, mountinfo unreadable, deliberate remap) — but it
    is ALSO an inherited-shell-state contamination vector: a devcontainer's
    login shell may `source` one repo's ``ciu.env`` (e.g. via a
    ``REPO_ROOT``-triggered ``.bashrc`` hook for the devcontainer's primary
    workspace) and leave a stale ``PHYSICAL_REPO_ROOT`` in the environment
    when the same shell later operates on an unrelated, nested repo (2026-07
    live bug: dstdns's ``PHYSICAL_REPO_ROOT`` leaking into a
    ``ciu env generate`` run for ``vbpub/nyxloom``, corrupting its
    ``PHYSICAL_REPO_ROOT`` / ``REPO_NAME`` / network identity).

    Refined contract: the pre-set value wins ONLY when it is CONSISTENT with
    this process's own mountinfo-derived physical root for *repo_root* (or
    when mountinfo yields nothing to check against — mountinfo is our only
    independent signal, so absent it we have no basis to override the
    explicit env). When mountinfo yields a DIFFERENT physical root, that
    mountinfo value is trusted instead (it reflects an actual bind mount for
    THIS repo_root, not inherited shell state) and a warning is emitted.
    """
    physical_root = os.environ.get("PHYSICAL_REPO_ROOT")
    preset_path = Path(physical_root).resolve() if physical_root else None

    via_mountinfo = _physical_root_from_mountinfo(repo_root)

    if preset_path is not None:
        if via_mountinfo is None or via_mountinfo == preset_path:
            return preset_path
        print(
            f"ciu: ignoring pre-set PHYSICAL_REPO_ROOT={preset_path} for "
            f"repo_root={repo_root} — inconsistent with the mountinfo-derived "
            f"physical root {via_mountinfo}. Using the mountinfo-derived value "
            "(the pre-set env is likely stale/cross-repo shell state, e.g. "
            "inherited from a different repo's sourced ciu.env). Unset "
            "PHYSICAL_REPO_ROOT or update it if this override is intentional.",
            file=sys.stderr,
        )
        return via_mountinfo

    if via_mountinfo is not None:
        return via_mountinfo

    # Contract 2 fallback (mountinfo yielded nothing): existing
    # devcontainer-origin behavior. NOTE: this label reflects the CONTAINER's
    # own origin, not necessarily repo_root — it is a same-value-for-every-
    # repo_root fallback, kept only for parity with pre-existing behavior
    # when mountinfo is unavailable (e.g. not readable, non-Linux).
    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Label \"devcontainer.local_folder\"}}"],
            capture_output=True,
            text=True,
            check=False,
        )
        # A failed ``docker ps`` cannot establish a physical-root identity.
        # Docker may still put diagnostics (or incomplete template output) on
        # stdout when its daemon/socket is unavailable; treating that as a
        # bind-mount source would make a transient daemon failure select an
        # unrelated repository path.
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                candidate = line.strip()
                if candidate:
                    return Path(candidate).resolve()
    except FileNotFoundError:
        pass

    # Contract 2 final fallback / S1.9: on native host PHYSICAL_REPO_ROOT == REPO_ROOT
    return repo_root.resolve()


def _detect_host_mdt_tmp() -> str:
    """Host path of the persisted /tmp bind mount (mdt devcontainer convention).

    Sibling containers launched on the host Docker daemon (e.g. the test-runner) must bind the SAME
    host dir the devcontainer mounts at /tmp, so /tmp-based git worktrees are visible to them.
    Autodetected like PHYSICAL_REPO_ROOT: an explicit env override wins; otherwise inspect THIS
    container's own /tmp bind-mount source. Empty when /tmp is not a host bind mount (e.g. native host).
    """
    explicit = os.environ.get("HOST_MDT_TMP")
    if explicit:
        return explicit
    container = os.environ.get("DEVCONTAINER_NAME") or os.environ.get("HOSTNAME", "")
    if container:
        try:
            result = subprocess.run(
                ["docker", "inspect", container, "--format",
                 '{{ range .Mounts }}{{ if eq .Destination "/tmp" }}{{ .Source }}{{ end }}{{ end }}'],
                capture_output=True,
                text=True,
                check=False,
            )
            # An inspect failure has no trustworthy mount value, even if a
            # wrapper happened to emit text on stdout.
            if result.returncode == 0:
                src = result.stdout.strip()
                if src:
                    return src
        except FileNotFoundError:
            pass
    return ""


def _compute_network_name(physical_root: Path) -> Dict[str, str]:
    """Derive the identity tuple for THIS physical root (S2.7, CIU-41).

    Every value is derived from *physical_root* alone. Ambient environment
    values are NEVER adopted: ``env generate`` is the identity-computation
    verb, and its output (ciu.env) is the record every later ciu command
    trusts — an inherited ``DOCKER_NETWORK_INTERNAL`` from a shell that
    sourced a DIFFERENT checkout's ciu.env would silently point this
    workspace at that checkout's network (the masked-default defect behind
    dstdns P111 F2). The same refined precedence S2.7 applies to
    PHYSICAL_REPO_ROOT is mirrored here for the whole tuple: a pre-set value
    wins only when CONSISTENT with the derived one; on mismatch the derived
    value is used and a warning names the ignored ambient value.
    """
    repo_name = physical_root.name.lower()
    instance_id = hashlib.sha256(str(physical_root).encode("utf-8")).hexdigest()[:6]
    network_name = f"{repo_name}-{instance_id}-network"
    derived = {
        "REPO_NAME": repo_name,
        "INSTANCE_ID": instance_id,
        "DOCKER_NETWORK_INTERNAL": network_name,
    }
    _warn_inconsistent_ambient("REPO_NAME", repo_name)
    _warn_inconsistent_ambient("INSTANCE_ID", instance_id)
    _warn_inconsistent_ambient(
        "DOCKER_NETWORK_INTERNAL",
        network_name,
        remedy=(
            "To reuse another instance's running infra, use "
            "`ciu worktree add --shared-infra` (SPEC S16.1) instead of "
            "inheriting its network name."
        ),
    )
    return derived


def _warn_inconsistent_ambient(key: str, derived: str, *, remedy: str = "") -> None:
    """Warn when an ambient identity value disagrees with the derived one.

    A consistent pre-set value is silent (it changes nothing); a mismatched
    one is reported and IGNORED — never adopted (CIU-41 / S2.7 refined
    precedence extended to the derived identity tuple).
    """
    ambient = os.environ.get(key)
    if not ambient or ambient == derived:
        return
    message = (
        f"ciu: ignoring pre-set {key}={ambient!r} during env generate — "
        f"inconsistent with the value derived for this repo root ({derived!r}). "
        "The derived value is written to ciu.env (the pre-set env is likely "
        "stale/cross-workspace shell state, e.g. inherited from another "
        "checkout's sourced ciu.env)."
    )
    if remedy:
        message += f" {remedy}"
    print(message, file=sys.stderr)


# `adopt_file_identity` lived here until CIU-75 (ciu 7.7.0). It overwrote the
# ambient identity tuple from a JUST-GENERATED ciu.env, which made it useless
# on the far commoner path where nothing was generated this run — the reason a
# sibling checkout's sourced identity could survive into a render at all. Its
# CIU-41 rule ("the record computed for THIS repo root outranks inherited shell
# state") is kept, unconditionally and from the overlay, in `seed_identity_env`.


def _docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    result = subprocess.run(
        ["docker", "info"],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def _ensure_network_exists(network_name: str) -> None:
    if not network_name:
        raise WorkspaceEnvError("DOCKER_NETWORK_INTERNAL is missing or empty.")

    if not _docker_available():
        raise WorkspaceEnvError("Docker not available; cannot create network.")

    inspect = subprocess.run(
        ["docker", "network", "inspect", network_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if inspect.returncode == 0:
        return

    _log_info(f"Creating docker network: {network_name}")
    create = subprocess.run(
        ["docker", "network", "create", network_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if create.returncode != 0:
        raise WorkspaceEnvError(
            f"Failed to create docker network {network_name}: {create.stderr.strip()}"
        )


def _connect_devcontainer_to_network(network_name: str) -> None:
    """Attach the devcontainer to the named network.

    S1.9: MUST no-op cleanly when ENV_TYPE != devcontainer.
    """
    env_type = os.environ.get("ENV_TYPE", "").lower()
    if env_type != "devcontainer":
        return

    container_name = os.environ.get("DEVCONTAINER_NAME") or os.environ.get("HOSTNAME", "")
    if not container_name:
        _log_warn("Devcontainer name not detected; skipping network attach.")
        return

    if not _docker_available():
        _log_warn("Docker not available; skipping devcontainer network attach.")
        return

    inspect = subprocess.run(
        ["docker", "network", "inspect", network_name, "--format", "{{range .Containers}}{{.Name}} {{end}}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if inspect.returncode == 0 and container_name in inspect.stdout.split():
        return

    _log_info(f"Connecting devcontainer {container_name} to {network_name}")
    connect = subprocess.run(
        ["docker", "network", "connect", network_name, container_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if connect.returncode != 0:
        _log_warn(
            f"Failed to connect devcontainer to {network_name}: {connect.stderr.strip()}"
        )


def _check_tls_access() -> None:
    """TLS accessibility probe.

    S1.9 / S2.8: only runs when PUBLIC_TLS_* are set; degrades to warn on
    non-devcontainer or when docker is unavailable.
    """
    cert_path = os.environ.get("PUBLIC_TLS_CRT_PEM", "")
    key_path = os.environ.get("PUBLIC_TLS_KEY_PEM", "")
    if not cert_path or not key_path:
        return

    if not _docker_available():
        _log_warn("Docker not available; skipping TLS accessibility checks.")
        return

    user_uid = os.environ.get("USER_UID", str(os.getuid()))
    docker_gid = os.environ.get("DOCKER_GID") or os.environ.get("CONTAINER_GID", "")
    if not docker_gid:
        _log_warn("DOCKER_GID not set; skipping TLS accessibility checks.")
        return

    for label, path in (("certificate", cert_path), ("private key", key_path)):
        test = subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "-v",
                "/etc/letsencrypt:/etc/letsencrypt:ro",
                "--user",
                f"{user_uid}:{docker_gid}",
                "alpine:latest",
                "sh",
                "-c",
                f"test -r {shlex.quote(path)}",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if test.returncode != 0:
            _log_warn(f"TLS {label} not accessible to Docker: {path}")


def validate_required_certs(env: Optional[Dict[str, str]] = None) -> None:
    """Validate TLS cert/key files as given in env (S2.4).

    Reads PUBLIC_TLS_CRT_PEM and PUBLIC_TLS_KEY_PEM from *env* (defaults to
    os.environ).  For each path that is set, checks:
      - the file exists and is readable by the calling process, AND
      - is readable by DOCKER_GID: group-readable when st_gid == DOCKER_GID,
        or other-readable (st_mode & 0o004).

    Raises WorkspaceEnvError naming the exact failing path.
    ABSOLUTELY NO path re-derivation — the path is validated exactly as given
    (kills the v1 live/live bug A10 by design).

    S2.5: DOCKER_GID '0' is a valid GID; falsy-safe int parse.
    """
    source = env if env is not None else dict(os.environ)

    cert_path = source.get("PUBLIC_TLS_CRT_PEM", "")
    key_path = source.get("PUBLIC_TLS_KEY_PEM", "")

    if not cert_path and not key_path:
        return

    # S2.5: parse DOCKER_GID with falsy-safe check: '' or absent means unknown
    raw_gid = source.get("DOCKER_GID", "")
    docker_gid: Optional[int]
    if raw_gid is None or raw_gid == "":
        docker_gid = None
    else:
        try:
            docker_gid = int(raw_gid)
        except ValueError:
            docker_gid = None

    for path_str in (cert_path, key_path):
        if not path_str:
            continue
        p = Path(path_str)
        if not p.exists():
            raise WorkspaceEnvError(
                f"TLS file does not exist: {path_str}"
            )
        try:
            st = p.stat()
        except OSError as exc:
            raise WorkspaceEnvError(
                f"TLS file not readable: {path_str}: {exc}"
            ) from exc

        mode = st.st_mode
        # other-readable — accessible regardless of GID
        other_readable = bool(mode & stat.S_IROTH)
        # group-readable by DOCKER_GID
        group_readable_by_docker = (
            docker_gid is not None
            and st.st_gid == docker_gid
            and bool(mode & stat.S_IRGRP)
        )
        if not other_readable and not group_readable_by_docker:
            raise WorkspaceEnvError(
                f"TLS file not readable by DOCKER_GID ({docker_gid}): {path_str}"
            )


def ensure_workspace_network(
    network_name: Optional[str] = None,
    auto_connect: bool = True,
) -> None:
    """Ensure the shared Docker network exists and attach devcontainer if enabled."""
    resolved = network_name or os.environ.get("DOCKER_NETWORK_INTERNAL", "")
    _ensure_network_exists(resolved)
    if auto_connect:
        _connect_devcontainer_to_network(resolved)


def render_generated_facts_block(facts: Mapping[str, str]) -> list[str]:
    """Render the `[ciu.instance.generated]` block as a list of TOML lines.

    Values are emitted with ``json.dumps`` exactly as
    ``worktree._worktree_overlay_text`` already does for its own tables — TOML
    basic strings and JSON strings share an escape grammar for the characters
    a filesystem path or a hostname can contain.

    Key ORDER is :data:`GENERATED_FACTS_KEYS`, never ``facts``' iteration
    order, so the rendered block is byte-identical across runs regardless of
    how the caller built the mapping.
    """
    missing = [key for key in GENERATED_FACTS_KEYS if key not in facts]
    if missing:
        raise WorkspaceEnvError(
            f"[S3.1b] generated identity facts incomplete: missing {missing}"
        )
    lines = [GENERATED_FACTS_HEADER, *_GENERATED_FACTS_BANNER]
    lines.extend(f"{key} = {json.dumps(facts[key])}" for key in GENERATED_FACTS_KEYS)
    return lines


def upsert_generated_facts(repo_root: Path, facts: Mapping[str, str]) -> Path:
    """S3.1b (CIU-60) — write *facts* into ``ciu.global.worktree.toml.j2``.

    This is a TEXT-LEVEL surgical block replace, deliberately NOT a
    ``tomllib`` parse + ``tomli_w`` dump round-trip. The overlay is documented
    operator-editable (S3.1b): a full-file round-trip would round-trip every
    VALUE correctly while silently discarding every comment and reformatting
    every table an operator hand-authored.

    **The bytes CIU owns**, stated exactly, because the boundary is narrower
    than "up to the next table" and the narrowness is the safety property:
    from the ``[ciu.instance.generated]`` header line, up to and including the
    last line this writer itself emits — its own banner comments and its own
    ``key = value`` lines. The scan finds the next line beginning a table at
    column 0 and then walks BACK over that region's trailing run of blank and
    comment lines, which is never ours (the last line rendered is always a
    ``key = value``) and which in TOML's ordinary reading introduces the
    FOLLOWING table. That run is carried across untouched. So a comment
    written immediately below the generated block survives, exactly like one
    written above it. Nothing outside those owned lines is read, rewritten, or
    reordered.

    Behaviour:

    * file absent → created, carrying the same header comment
      ``worktree._worktree_overlay_text`` writes, then the block;
    * table absent → block appended at EOF, one blank line after whatever was
      already there;
    * table present → its owned lines replaced in place, with the trailing
      blank/comment run preserved verbatim (and a single blank separator
      manufactured only when the region carried none at all), so a second run
      over an unchanged workspace produces a byte-identical file.

    Unlike ``worktree._write_worktree_overlay`` — which correctly REFUSES an
    existing file, because its only call site is worktree creation on day zero
    — this runs on every ``ciu env generate``, possibly the tenth one over a
    file the operator has since added their own tables and comments to. Hence
    upsert, not refuse-if-exists and not blind append. That refusal is left
    exactly as it is; its other callers still need it.

    Known and accepted limit of text scanning: a line reading exactly
    ``[ciu.instance.generated]`` *inside a multi-line TOML string elsewhere in
    the file* would be mistaken for the table header. That construct cannot
    occur in a sparse override of the shape S3.1b describes, and the
    alternative (a full-file round-trip) fails the far more likely case of an
    operator comment.

    Returns the overlay path.
    """
    path = Path(repo_root) / GLOBAL_CONFIG_WORKTREE_OVERRIDES
    block = render_generated_facts_block(facts)

    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = ""
    except OSError as exc:
        raise WorkspaceEnvError(f"[S3.1b] could not read {path}: {exc}") from exc

    if existing:
        lines = existing.splitlines()
    else:
        lines = list(_OVERLAY_FRESH_HEADER)

    start = next(
        (i for i, line in enumerate(lines) if line.strip() == GENERATED_FACTS_HEADER),
        None,
    )
    if start is None:
        if lines and lines[-1].strip():
            lines.append("")
        lines.extend(block)
    else:
        end = next(
            (i for i in range(start + 1, len(lines)) if lines[i].startswith("[")),
            len(lines),
        )
        # The region's TRAILING run of blank/comment lines is never ours — the
        # last line this writer emits is always a `key = value` — so it is
        # either the blank separator before the next table or, in TOML's
        # ordinary reading, a hand-authored comment that belongs to that next
        # table. Carrying it across keeps O2's promise for a comment written
        # immediately BELOW the generated block, and is idempotent: the same
        # run is re-detected and re-emitted unchanged on every later run.
        keep = end
        while keep > start + 1 and (
            not lines[keep - 1].strip() or lines[keep - 1].lstrip().startswith("#")
        ):
            keep -= 1
        tail = lines[keep:end]
        # Only manufacture a separator when the region carried none at all.
        if not tail and end < len(lines):
            tail = [""]
        lines[start:end] = [*block, *tail]

    _atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def _atomic_write_text(path: Path, payload: str) -> None:
    """Temp-file + fsync + ``os.replace`` (S16 durability), as
    ``worktree._write_worktree_overlay`` does.

    Uses ``"w"`` rather than that function's ``"x"``: this writer runs on every
    `env generate`, so a temp file left behind by a crash under the same PID
    must not wedge every future generate.
    """
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        with tmp.open("w", encoding="utf-8") as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except OSError as exc:
        try:
            tmp.unlink()
        except OSError:
            pass
        raise WorkspaceEnvError(f"[S3.1b] could not write {path}: {exc}") from exc


def has_generated_facts(ciu_root: Path) -> bool:
    """S3.1c (CIU-75) — does *ciu_root*'s overlay CARRY the CIU-owned table?

    PRESENCE, never readability: the header line exists or it does not. A
    present-but-corrupt table answers ``True`` here on purpose, so the caller's
    own read (:func:`read_generated_facts`) refuses loudly instead of this
    predicate silently downgrading indeterminacy to "not a CIU instance"
    (AGENTS.md's absence-for-emptiness anti-pattern).

    This is the post-cutover replacement for the ``ciu.env`` ``.is_file()``
    readiness signal: what makes a checkout able to act as a CIU instance is
    now the generated table, because that is what every internal fact read
    consults.
    """
    path = Path(ciu_root) / GLOBAL_CONFIG_WORKTREE_OVERRIDES
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        # Unreadable is not "absent" — but a boolean cannot say so. The one
        # honest answer a *presence* predicate can give for a file that exists
        # and cannot be read is "treat it as present": the caller's real read
        # then raises with the actual cause. `FileNotFoundError` (a genuine
        # absence) is the only OSError that must answer False.
        return path.exists()
    return any(line.strip() == GENERATED_FACTS_HEADER for line in text.splitlines())


def read_generated_facts(ciu_root: Path) -> dict[str, str]:
    """S3.1c (CIU-75) — the ``[ciu.instance.generated]`` facts for *ciu_root*.

    The READ side of S3.1b, and since CIU-75 the ONLY source CIU itself
    consults for instance identity: ``ciu.env`` is a write-only legacy export
    (contract item 2) and is never read back by any CIU internal.

    Deliberately a text-level scan of the CIU-owned block, exactly mirroring
    :func:`upsert_generated_facts`'s own ownership boundary — NOT a
    :func:`config_model.render_global_chain` of the whole checkout. Three
    reasons, each of which the chain render fails:

    * the overlay is a Jinja **template**; rendering it needs the merged
      config it is itself a layer of, and (CIU-74) an undefined name is now a
      hard error — but the CIU-owned block is plain TOML by construction
      (``json.dumps``'d strings), so it can be read without any context;
    * the sites this replaces (a reap survey, a shared-infra reference, a
      budget candidate) read a checkout that is NOT this process's own repo
      root and whose committed config chain may be absent or broken; the
      ``ciu.env`` read they used had no such dependency and neither may this;
    * the block is merged LAST in the chain and written by CIU alone, so its
      own bytes ARE the merged value — reading the chain could only agree.

    Returns ``{}`` when the overlay, or the table, is absent — the exact
    counterpart of the pre-cutover "no ``ciu.env`` here" case. Raises
    :class:`WorkspaceEnvError` when the file is present and cannot be read
    (``OSError``), is not UTF-8, is not parseable TOML, or carries a
    non-string value: all four are indeterminacy, never emptiness.
    """
    path = Path(ciu_root) / GLOBAL_CONFIG_WORKTREE_OVERRIDES
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return {}
    except (OSError, UnicodeDecodeError) as exc:
        raise WorkspaceEnvError(f"[S3.1c] could not read {path}: {exc}") from exc

    lines = text.splitlines()
    start = next(
        (i for i, line in enumerate(lines) if line.strip() == GENERATED_FACTS_HEADER),
        None,
    )
    if start is None:
        return {}
    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i].startswith("[")),
        len(lines),
    )
    try:
        parsed = tomllib.loads("\n".join(lines[start:end]))
    except tomllib.TOMLDecodeError as exc:
        raise WorkspaceEnvError(
            f"[S3.1c] {path} has a malformed {GENERATED_FACTS_HEADER} table: {exc}"
        ) from exc

    # The slice STARTS at the table header and stops before the next line
    # beginning a table, so the parse can only ever be this one nested table —
    # no `.get(..., {})` defaulting is warranted, and inventing one would hide
    # a slicing bug behind an empty result.
    table: dict = parsed
    for part in GENERATED_FACTS_TABLE.split("."):
        table = table[part]
    facts: dict[str, str] = {}
    for key, value in table.items():
        if not isinstance(value, str):
            raise WorkspaceEnvError(
                f"[S3.1c] {path} {GENERATED_FACTS_HEADER}.{key} is "
                f"{type(value).__name__}, not a string"
            )
        facts[key] = value
    return facts


def identity_env_from_facts(facts: Mapping[str, str]) -> dict[str, str]:
    """Translate ``[ciu.instance.generated]`` facts to legacy env KEY names.

    The single place :data:`GENERATED_FACT_ENV_KEYS` is applied, so a child
    process's environment and a candidate render's ``environ`` can never
    disagree about which facts cross that boundary. A fact with no env name
    (an operator-added key) is dropped rather than exported under a guessed
    name; a fact CIU never derived (an empty ``public_fqdn``) is carried
    through as the empty string it is, exactly as ``ciu.env`` carried it.
    """
    return {
        GENERATED_FACT_ENV_KEYS[key]: value
        for key, value in facts.items()
        if key in GENERATED_FACT_ENV_KEYS
    }


def read_instance_identity_env(ciu_root: Path) -> dict[str, str]:
    """:func:`read_generated_facts` under the legacy ``ciu.env`` KEY names.

    The SCREAMING_CASE shell names a CHILD ciu process (or a rendered
    template's ``$VAR`` expansion) still speaks. Empty facts → empty dict.
    """
    return identity_env_from_facts(read_generated_facts(ciu_root))


def seed_identity_env(ciu_root: Path) -> dict[str, str]:
    """Put *ciu_root*'s overlay identity into ``os.environ``, OVERRIDING it.

    S3.1c clause 2a, and the fix for the gap the CIU-75 review found: moving
    the twelve per-checkout fact READS onto the overlay left the PROCESS
    ENVIRONMENT still seeded from `ciu.env`, and ~26 internal sites read
    `REPO_ROOT` / `PHYSICAL_REPO_ROOT` / `DOCKER_NETWORK_INTERNAL` /
    `PUBLIC_FQDN` straight out of `os.environ` (a rendered
    ``network_name = "$DOCKER_NETWORK_INTERNAL"`` among them). With the seed
    coming from a file that skipped keys already present, a shell that had
    sourced a SIBLING checkout's `ciu.env` won the render — the exact CIU-41
    hazard, arriving through the one door the cutover had not closed.

    **Override, never skip-if-present.** This is `adopt_file_identity`'s old
    CIU-41 rule with a better source: the overlay was written for THIS repo
    root and outranks inherited shell state by construction. Skip-if-present
    would re-open the hazard for every already-exported key, which is all of
    them in the case that actually bites.

    Returns what it applied (empty when this checkout has no generated table).
    """
    identity = read_instance_identity_env(ciu_root)
    for key, value in identity.items():
        os.environ[key] = value
    return identity


def _load_legacy_machine_env(env_path: Path, *, override: bool) -> dict[str, str]:
    """Seed ``os.environ`` with the NON-identity half of `ciu.env`.

    S3.1c clause 2: `ciu.env` remains the transport for MACHINE facts at
    process start — a cache of live derivation, regenerated when absent — and
    is never a source of instance identity. The identity keys it still carries
    are skipped here and seeded from the overlay by
    :func:`seed_identity_env`; that is belt and braces (the caller seeds
    identity afterwards regardless), and it is what makes "no identity fact is
    ever read from `ciu.env`" true of the code rather than of the ordering.

    Read failure is a WARN and an empty dict, not a traceback. Pre-CIU-75 this
    was a bare `read_text` at the first statement of every verb, so a non-UTF-8
    byte in a file CIU calls write-only crashed `ciu up` with a raw
    `UnicodeDecodeError` — CIU-62's three unrelated failure types
    (`OSError`, `UnicodeDecodeError`, `WorkspaceEnvError`) reaching one more
    reader that had never been given them. Missing machine facts still refuse
    loudly, one step later and with a remedy, in :func:`ensure_workspace_env`.
    """
    try:
        values = parse_workspace_env(env_path)
    except (OSError, UnicodeDecodeError, WorkspaceEnvError) as exc:
        _log_warn(
            f"[S3.1c] could not read {env_path}: {exc}. Machine facts "
            "(CONTAINER_UID, DOCKER_GID, ENV_TYPE, PUBLIC_TLS_*, …) fall back "
            "to this process's own environment; instance identity is "
            f"unaffected — since 7.7.0 it comes from "
            f"{GLOBAL_CONFIG_WORKTREE_OVERRIDES}, not from this file. "
            "Repair with: ciu env generate",
            stream=sys.stderr,
        )
        return {}
    applied: dict[str, str] = {}
    for key, value in values.items():
        if key in LEGACY_IDENTITY_ENV_KEYS:
            continue
        if override or key not in os.environ:
            os.environ[key] = value
            applied[key] = value
    return applied


def _seed_identity_or_repair(ciu_root: Path, *, generated: bool) -> dict[str, str]:
    """:func:`seed_identity_env`, repairing a checkout that has no table yet.

    A 7.6.x checkout upgrading in place has a `ciu.env` and — since CIU-60
    (7.5.0) — usually an overlay table too, but not necessarily: the overlay is
    gitignored, so a fresh clone, a lost worktree-local file or a
    pre-CIU-60 record leaves nothing to read. The record CIU reads is the
    record CIU repairs, which is the same self-healing `ciu.env` has always had
    when absent — and it keeps the upgrade from being "your next `ciu up`
    refuses until you run a command it did not tell you about".

    Repairing is skipped when this run already generated (the generate wrote
    the table itself; a second one would only be slower). A PRESENT but
    unreadable table is not repaired either — :func:`read_generated_facts`
    raises, and S3.1c clause 4 wants that loud rather than overwritten.
    """
    identity = seed_identity_env(ciu_root)
    if identity or generated:
        return identity
    _log_warn(
        f"[S3.1c] {ciu_root / GLOBAL_CONFIG_WORKTREE_OVERRIDES} carries no "
        f"{GENERATED_FACTS_HEADER} table — regenerating this workspace's "
        "identity record (since 7.7.0 it is the only one CIU reads)",
        stream=sys.stderr,
    )
    generate_ciu_env(ciu_root, notice_stream=sys.stderr)
    return seed_identity_env(ciu_root)


def generate_ciu_env(
    repo_root: Path,
    output_path: Optional[Path] = None,
    *,
    notice_stream=None,
) -> Path:
    """Generate ciu.env with autodetected values.

    ``notice_stream`` routes the one-release deprecation notice (S3.1c clause
    3). It defaults to stdout, which is right for the verb an operator typed;
    the STEP-1 bootstrap passes ``sys.stderr``, because that same notice on
    stdout lands ahead of `ciu check --json`'s document and breaks the parse of
    every machine consumer that followed the migration advice.

    Side-effects: writes the ciu.env file, and upserts the identity facts it
    just derived into this checkout's `ciu.global.worktree.toml.j2` under
    `[ciu.instance.generated]` (S3.1b / CIU-60) so TEMPLATES can read them from
    the merged config chain instead of ambient `os.environ`. Both writes come
    from the SAME in-memory values — the facts are never re-derived, and
    `ciu.env` is never re-read to produce them. Network/TLS steps still belong
    in bootstrap_env_init so tests stay simple (S2.8).

    The overlay write is NOT gated on an S16 worktree instance record: the
    primary/main checkout reads the same file through the same unconditional
    `render_global_chain` step, and gating would leave exactly that checkout
    on the old ambient-env path.

    Returns the path to the generated ciu.env file.
    """
    repo_root = repo_root.resolve()
    output_path = output_path or repo_root / ENV_FILE_NAME

    env_flags = _detect_env_type()
    docker_gid = _detect_docker_gid()
    physical_root = _detect_physical_repo_root(repo_root)
    host_mdt_tmp = _detect_host_mdt_tmp()
    network_values = _compute_network_name(physical_root)
    public_values = _detect_public_fqdn(repo_root, require_fqdn=False)

    user_name = os.environ.get("USER_NAME", os.environ.get("USER", ""))
    user_uid = os.environ.get("USER_UID", str(os.getuid()))
    user_gid = os.environ.get("USER_GID", str(os.getgid()))
    docker_uid = os.environ.get("DOCKER_UID", user_uid)

    container_uid = os.environ.get("CONTAINER_UID", user_uid)
    container_gid = os.environ.get("CONTAINER_GID", docker_gid)

    python_exec = os.environ.get("PYTHON_EXECUTABLE", sys.executable)
    pip_exec = os.environ.get("PIP_EXECUTABLE") or shutil.which("pip") or ""

    gov_read_iops, gov_read_iops_note = _detect_governance_read_iops()

    def _emit_section(title: str, entries: list[tuple[str, str, str]]) -> list[str]:
        block: list[str] = [f"# {title}"]
        for key, value, comment in entries:
            block.append(f"# {comment}")
            block.append(f"export {key}=\"{value}\"")
        return block

    lines = [
        "# CIU Workspace Environment (Auto-generated)",
        "# Do not edit manually - regenerated by ciu --generate-env",
        "",
    ]

    lines.extend(_emit_section(
        "Environment type flags",
        [
            ("ENV_TYPE", env_flags["ENV_TYPE"], "Runtime environment: devcontainer | native | github-actions"),
            ("IS_DEVCONTAINER", env_flags["IS_DEVCONTAINER"], "1 when running inside a devcontainer"),
            ("IS_GITHUB_ACTIONS", env_flags["IS_GITHUB_ACTIONS"], "1 when running in GitHub Actions"),
            ("IS_NATIVE", env_flags["IS_NATIVE"], "1 when running on a native host"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "User identity",
        [
            ("USER_NAME", user_name, "Current user name"),
            ("USER_UID", user_uid, "Current user ID"),
            ("USER_GID", user_gid, "Current user primary group ID"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Container identity",
        [
            ("CONTAINER_UID", container_uid, "UID used for container user mapping"),
            ("CONTAINER_GID", container_gid, "GID used for container user mapping"),
            ("DOCKER_UID", docker_uid, "UID for Docker socket access (defaults to USER_UID)"),
            ("DOCKER_GID", docker_gid, "Docker group GID for host volume permissions"),
            ("DEVCONTAINER_NAME", os.environ.get("DEVCONTAINER_NAME", os.environ.get("HOSTNAME", "")), "Detected devcontainer name (if applicable)"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Repository paths",
        [
            ("REPO_ROOT", str(repo_root), "Repo root path inside the current environment"),
            ("PHYSICAL_REPO_ROOT", str(physical_root), "Host-visible repo root for Docker bind mounts"),
            ("HOST_MDT_TMP", host_mdt_tmp, "Host path of the persisted /tmp bind mount, so sibling containers (e.g. the test-runner) can bind the same /tmp; empty on native host"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Docker network identity",
        [
            ("REPO_NAME", network_values["REPO_NAME"], "Lowercase repository name for network naming"),
            ("INSTANCE_ID", network_values["INSTANCE_ID"], "Deterministic instance ID from repo path"),
            ("DOCKER_NETWORK_INTERNAL", network_values["DOCKER_NETWORK_INTERNAL"], "Internal Docker network name"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Public endpoint detection",
        [
            ("PUBLIC_IP", public_values["PUBLIC_IP"], "Detected public IP address (may be empty)"),
            ("PUBLIC_FQDN", public_values["PUBLIC_FQDN"], "Detected or configured public FQDN"),
            ("PUBLIC_TLS_CRT_PEM", public_values["PUBLIC_TLS_CRT_PEM"], "TLS certificate PEM path (S2.3: required only when require_certs=true)"),
            ("PUBLIC_TLS_KEY_PEM", public_values["PUBLIC_TLS_KEY_PEM"], "TLS private key PEM path (S2.3: required only when require_certs=true)"),
        ],
    ))
    lines.append("")

    # Seam 4: CIU_SERVICES_PROFILE placeholder — ordered profile list for this host
    lines.append("# Service profiles (Seam 4 / S7.5)")
    lines.append('# export CIU_SERVICES_PROFILE="core,db,worker-io"  # ordered profile list for this host')
    lines.append("")

    # S15.6: stack-wide resource governance — the overlay generator re-derives
    # this independently from the baseline file (works without an env regen);
    # this copy is a convenience for shell/template consumption.
    lines.extend(_emit_section(
        "Resource governance (S15)",
        [
            (
                "CIU_GOV_READ_IOPS",
                gov_read_iops,
                f"Derived read-IOPS governance cap ({gov_read_iops_note})",
            ),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Python tooling",
        [
            ("PYTHON_EXECUTABLE", python_exec, "Python interpreter for CIU subprocesses"),
            ("PIP_EXECUTABLE", pip_exec, "pip executable resolved on PATH"),
        ],
    ))

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # S3.1c (CIU-75) — the one-release deprecation WARN, in the shape this
    # codebase already uses for a deprecated-but-still-working path
    # (provisioning.py's `stack:<x>:healthy` exit-0 fallback): always-on, names
    # the forward path, names what a future release does. It is a WARN and not
    # a refusal on purpose — the key set below is byte-identical to 7.6.x, so
    # every `source ciu.env` consumer keeps working THIS release.
    _log_warn(
        LEGACY_ENV_EXPORT_WARNING.format(path=output_path),
        stream=notice_stream,
    )

    # S3.1b (CIU-60). Same values, same invocation, second destination: the
    # merged-config chain, which is what a Jinja TEMPLATE can actually see.
    # Deriving them a second time (or reading them back out of ciu.env) would
    # admit a disagreement between the two records that nothing would catch.
    upsert_generated_facts(
        repo_root,
        {
            "repo_name": network_values["REPO_NAME"],
            "instance_id": network_values["INSTANCE_ID"],
            "network": network_values["DOCKER_NETWORK_INTERNAL"],
            "physical_repo_root": str(physical_root),
            "repo_root": str(repo_root),
            "public_fqdn": public_values["PUBLIC_FQDN"],
        },
    )
    return output_path


def bootstrap_env_init(repo_root: Path) -> Path:
    """Single bootstrap entry point for --generate-env (S2.8).

    Performs the full S2.8 duty order:
      1. generate_ciu_env  — detect + write ciu.env
      2. ensure_workspace_network — create DOCKER_NETWORK_INTERNAL
      3. devcontainer self-attach  — no-op when ENV_TYPE != devcontainer (S1.9)
      4. TLS probe (_check_tls_access) — only when PUBLIC_TLS_* set (S1.9)

    generate_ciu_env is kept side-effect-light (write file only) so tests
    remain simple; this function composes the duties.

    Returns the path to the generated ciu.env file.
    """
    env_path = generate_ciu_env(repo_root)

    # Seed os.environ so the steps below see this workspace's values. Two
    # sources, on purpose (S3.1c clause 2): the MACHINE facts come from the
    # file just written, and the IDENTITY comes from the overlay table the
    # same generate wrote — always overriding ambient, because the network
    # step below must act on THIS workspace's network and not on a stale
    # DOCKER_NETWORK_INTERNAL inherited from another checkout's sourced
    # ciu.env (CIU-41).
    _load_legacy_machine_env(env_path, override=False)
    _seed_identity_or_repair(repo_root, generated=True)

    # Step 2+3: network + devcontainer attach (devcontainer attach is a no-op
    # on native/CI per _connect_devcontainer_to_network's ENV_TYPE guard)
    network_name = os.environ.get("DOCKER_NETWORK_INTERNAL", "")
    if network_name:
        try:
            ensure_workspace_network(network_name)
        except WorkspaceEnvError as exc:
            _log_warn(f"Network setup skipped: {exc}")

    # Step 4: TLS probe (no-op when paths not set; degrades to warn on native)
    _check_tls_access()

    return env_path


def bootstrap_workspace_env(
    start_dir: Path,
    define_root: Optional[Path],
    defaults_filename: str,
    generate_env: bool,
    update_cert_permission: bool,
    required_keys: Iterable[str],
) -> Path:
    """Prepare this process's environment for a verb, and validate it.

    STEP 1 of `ciu up` / `check` / `render` / `graph`. Since 7.7.0 it seeds
    from TWO records, and which one owns what is the whole of S3.1c:

    * **identity** — `[ciu.instance.generated]` in this checkout's overlay,
      always, and always OVERRIDING whatever the ambient environment claims;
    * **machine facts** — `ciu.env`, a cache of live derivation, applied only
      where the ambient environment has nothing to say (unless `--define-root`
      pins the root, which has always overridden).

    Returns the resolved env root directory.
    """
    env_root = resolve_env_root(start_dir, define_root, defaults_filename)
    env_path = env_root / ENV_FILE_NAME

    generated = False
    if generate_env or not env_path.exists():
        # The notice goes to stderr here: this regeneration is a side effect of
        # a verb the operator ran for another reason, and `ciu check --json`
        # writes its document to stdout (S3.1c clause 3).
        generate_ciu_env(env_root, notice_stream=sys.stderr)
        generated = True

    # By EXACT path in both cases. `load_workspace_env` walks via
    # `find_workspace_env`, which honors an ambient REPO_ROOT and can therefore
    # hand back ANOTHER checkout's ciu.env — the same cross-workspace leak the
    # identity seed below exists to close, and there is no reason to leave it
    # open for machine facts either now that the root is already resolved.
    _load_legacy_machine_env(env_path, override=bool(define_root))
    # S3.1c clause 2a — identity last, from the overlay, unconditionally
    # overriding. Ordering is not what makes this safe (the loader above skips
    # identity keys outright); it is here so a reader sees the precedence.
    _seed_identity_or_repair(env_root, generated=generated)

    if generated:
        # Run post-generate bootstrap steps (network + TLS probe).
        # These degrade to warn/no-op on native host per S1.9.
        network_name = os.environ.get("DOCKER_NETWORK_INTERNAL", "")
        if network_name:
            try:
                ensure_workspace_network(network_name)
            except WorkspaceEnvError as exc:
                _log_warn(f"Network setup skipped: {exc}")
        _check_tls_access()

    if update_cert_permission:
        public_fqdn = os.environ.get("PUBLIC_FQDN")
        update_cert_permissions(env_root, public_fqdn)

    ensure_workspace_env(required_keys)
    return env_root


def update_cert_permissions(repo_root: Path, public_fqdn: Optional[str] = None) -> None:
    """Run setup-letsencrypt-permissions.sh (requires root)."""
    if os.geteuid() != 0:
        raise WorkspaceEnvError(
            "--update-cert-permission requires root. "
            "Run: sudo ciu --update-cert-permission"
        )

    script_path = repo_root / "scripts" / "setup-letsencrypt-permissions.sh"
    if not script_path.exists():
        raise WorkspaceEnvError(
            f"Certificate permission script not found: {script_path}"
        )

    args = ["bash", str(script_path)]
    if public_fqdn:
        args.append(public_fqdn)

    subprocess.run(args, check=True)
