#!/usr/bin/env python3
"""
Workspace environment loader for CIU.

This module reads ciu.env files generated by ciu --generate-env
and exposes the values as process environment variables.
"""

from __future__ import annotations

import hashlib
import os
import shlex
import shutil
import socket
import stat
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, Iterable, Optional

import re

from .config_constants import (
    GLOBAL_CONFIG_DEFAULTS,
    GLOBAL_CONFIG_RENDERED,
    WORKSPACE_ENV,
)

STANDALONE_ROOT_PATTERN = re.compile(
    r"^\s*standalone_root\s*=\s*true\s*$",
    re.IGNORECASE | re.MULTILINE,
)


ENV_FILE_NAME = WORKSPACE_ENV

# S2.2 — required keys always present in ciu.env
REQUIRED_KEYS_CORE: tuple[str, ...] = (
    "REPO_ROOT",
    "PHYSICAL_REPO_ROOT",
    "DOCKER_NETWORK_INTERNAL",
    "CONTAINER_UID",
    "DOCKER_GID",
)


class WorkspaceEnvError(ValueError):
    """Raised when workspace environment file is missing or invalid."""


def _log_info(message: str) -> None:
    print(f"[INFO] {message}", flush=True)


def _log_warn(message: str) -> None:
    print(f"[WARN] {message}", flush=True)


def _log_error(message: str) -> None:
    print(f"[ERROR] {message}", flush=True)


def resolve_env_root(start_dir: Path, define_root: Optional[Path], defaults_filename: str) -> Path:
    """Resolve the workspace env root directory.

    Order:
    1. Explicit --define-root
    2. Walk up from start_dir until defaults_filename is found
    3. Fallback to start_dir
    """
    if define_root:
        root = define_root.resolve()
        if not root.exists():
            raise WorkspaceEnvError(f"Repository root does not exist: {root}")
        return root

    current = start_dir.resolve()
    while True:
        if (current / defaults_filename).exists():
            return current
        if current == current.parent:
            break
        current = current.parent

    return start_dir.resolve()


def find_workspace_env(start_dir: Path) -> Path:
    """Find ciu.env by walking up from start_dir.

    Priority:
    1. REPO_ROOT environment variable (if set)
    2. Walk up directory tree from start_dir
    """
    repo_root = os.environ.get("REPO_ROOT")
    if repo_root:
        candidate = Path(repo_root).resolve() / ENV_FILE_NAME
        if candidate.exists():
            return candidate

    current = start_dir.resolve()
    while True:
        candidate = current / ENV_FILE_NAME
        if candidate.exists():
            return candidate
        if current == current.parent:
            break
        current = current.parent

    raise WorkspaceEnvError(
        f"Workspace environment file {ENV_FILE_NAME} not found. "
        "Run: ciu --generate-env (or ciu-deploy --generate-env)."
    )


def parse_workspace_env(path: Path) -> Dict[str, str]:
    """Parse ciu.env into a dict of key/value pairs."""
    values: Dict[str, str] = {}

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()

        lexer = shlex.shlex(line, posix=True)
        lexer.whitespace_split = True
        lexer.commenters = "#"
        tokens = list(lexer)
        if not tokens:
            continue
        if len(tokens) != 1 or "=" not in tokens[0]:
            raise WorkspaceEnvError(
                f"Invalid {ENV_FILE_NAME} entry: {raw_line!r}"
            )

        key, value = tokens[0].split("=", 1)
        key = key.strip()
        if not key:
            raise WorkspaceEnvError(
                f"Invalid {ENV_FILE_NAME} entry (empty key): {raw_line!r}"
            )
        values[key] = value

    return values


def load_workspace_env(start_dir: Path, override: bool = False) -> Dict[str, str]:
    """Load ciu.env and populate os.environ.

    Args:
        start_dir: Directory to begin searching for ciu.env
        override: If True, overwrite existing os.environ values

    Returns:
        Dict of loaded values (from file)
    """
    env_path = find_workspace_env(start_dir)
    values = parse_workspace_env(env_path)

    for key, value in values.items():
        if override or key not in os.environ:
            os.environ[key] = value

    return values


def ensure_workspace_env(required_keys: Iterable[str]) -> None:
    """Ensure required environment variables are present.

    Raises WorkspaceEnvError if any are missing or empty.
    S2.5: 0 is a valid value — check is None / == "" not truthiness.
    """
    missing = [key for key in required_keys if os.environ.get(key) is None or os.environ.get(key) == ""]
    if missing:
        missing_str = ", ".join(missing)
        raise WorkspaceEnvError(
            "Missing required workspace environment variables: "
            f"{missing_str}. "
            "Run: ciu --generate-env and source ciu.env."
        )


def detect_standalone_root(start_dir: Path) -> Optional[Path]:
    """Detect a standalone CIU root based on ciu.global.defaults.toml.j2.

    Returns the nearest parent directory whose ciu.global.defaults.toml.j2
    contains 'standalone_root = true'.
    """
    current = start_dir.resolve()
    while True:
        candidate = current / GLOBAL_CONFIG_DEFAULTS
        if candidate.exists():
            try:
                content = candidate.read_text(encoding="utf-8")
            except OSError:
                content = ""
            if STANDALONE_ROOT_PATTERN.search(content):
                return current
        if current == current.parent:
            break
        current = current.parent
    return None


def _detect_env_type() -> Dict[str, str]:
    """Detect ENV_TYPE: devcontainer | native | github-actions (S2.7).

    v1's 'bare-metal' is renamed 'native' per S2.7 / Appendix C.
    IS_NATIVE replaces IS_BARE_METAL; IS_DEVCONTAINER and IS_GITHUB_ACTIONS
    are retained.
    """
    env_type = os.environ.get("ENV_TYPE")
    if not env_type:
        if os.environ.get("GITHUB_ACTIONS"):
            env_type = "github-actions"
        elif os.environ.get("REMOTE_CONTAINERS") or os.environ.get("WORKSPACE_DIR") or Path("/.dockerenv").exists():
            env_type = "devcontainer"
        else:
            env_type = "native"

    return {
        "ENV_TYPE": env_type,
        "IS_DEVCONTAINER": "1" if env_type == "devcontainer" else "0",
        "IS_GITHUB_ACTIONS": "1" if env_type == "github-actions" else "0",
        "IS_NATIVE": "1" if env_type == "native" else "0",
    }


def _detect_public_fqdn(repo_root: Path, require_fqdn: bool) -> Dict[str, str]:
    public_fqdn = os.environ.get("PUBLIC_FQDN", "")
    public_ip = os.environ.get("PUBLIC_IP", "")

    if not public_fqdn:
        ciu_global = repo_root / GLOBAL_CONFIG_RENDERED
        if ciu_global.exists():
            try:
                import tomllib

                with ciu_global.open("rb") as f:
                    config = tomllib.load(f)
                public_fqdn = config.get("infrastructure", {}).get("public_fqdn", "")
            except (tomllib.TOMLDecodeError, OSError, KeyError) as exc:
                _log_warn(f"Could not parse {ciu_global}: {exc}")
                public_fqdn = ""

    if not public_ip:
        try:
            with urllib.request.urlopen("https://api.ipify.org", timeout=10) as resp:
                public_ip = resp.read().decode("utf-8").strip()
        except (urllib.error.URLError, TimeoutError):
            public_ip = ""

    if not public_fqdn and public_ip:
        try:
            public_fqdn = socket.gethostbyaddr(public_ip)[0]
        except (socket.herror, socket.gaierror):
            public_fqdn = ""

    if not public_fqdn:
        if require_fqdn:
            raise WorkspaceEnvError("Failed to detect PUBLIC_FQDN. Set PUBLIC_FQDN in the environment.")
        public_fqdn = public_ip or "localhost"

    return {
        "PUBLIC_IP": public_ip,
        "PUBLIC_FQDN": public_fqdn,
        "PUBLIC_TLS_CRT_PEM": os.environ.get("PUBLIC_TLS_CRT_PEM", ""),
        "PUBLIC_TLS_KEY_PEM": os.environ.get("PUBLIC_TLS_KEY_PEM", ""),
    }


def _detect_docker_gid() -> str:
    docker_gid = os.environ.get("DOCKER_GID", "")
    # S2.5: '0' is a valid value — do not reject on falsy check
    if docker_gid is not None and docker_gid != "":
        return docker_gid

    for socket_path in ("/var/run/docker-host.sock", "/var/run/docker.sock"):
        if Path(socket_path).exists():
            return str(Path(socket_path).stat().st_gid)

    try:
        import grp

        return str(grp.getgrnam("docker").gr_gid)
    except KeyError:
        raise WorkspaceEnvError("DOCKER_GID not found. Ensure docker group exists or set DOCKER_GID.")


def _detect_physical_repo_root(repo_root: Path) -> Path:
    physical_root = os.environ.get("PHYSICAL_REPO_ROOT")
    if physical_root:
        return Path(physical_root).resolve()

    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Label \"devcontainer.local_folder\"}}"],
            capture_output=True,
            text=True,
            check=False,
        )
        for line in result.stdout.splitlines():
            candidate = line.strip()
            if candidate:
                return Path(candidate).resolve()
    except FileNotFoundError:
        pass

    # S1.9: on native host PHYSICAL_REPO_ROOT == REPO_ROOT
    return repo_root.resolve()


def _compute_network_name(physical_root: Path) -> Dict[str, str]:
    repo_name = physical_root.name.lower()
    instance_id = hashlib.sha256(str(physical_root).encode("utf-8")).hexdigest()[:6]
    network_name = f"{repo_name}-{instance_id}-network"
    return {
        "REPO_NAME": repo_name,
        "INSTANCE_ID": instance_id,
        "DOCKER_NETWORK_INTERNAL": os.environ.get("DOCKER_NETWORK_INTERNAL", network_name),
    }


def _docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    result = subprocess.run(
        ["docker", "info"],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def _ensure_network_exists(network_name: str) -> None:
    if not network_name:
        raise WorkspaceEnvError("DOCKER_NETWORK_INTERNAL is missing or empty.")

    if not _docker_available():
        raise WorkspaceEnvError("Docker not available; cannot create network.")

    inspect = subprocess.run(
        ["docker", "network", "inspect", network_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if inspect.returncode == 0:
        return

    _log_info(f"Creating docker network: {network_name}")
    create = subprocess.run(
        ["docker", "network", "create", network_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if create.returncode != 0:
        raise WorkspaceEnvError(
            f"Failed to create docker network {network_name}: {create.stderr.strip()}"
        )


def _connect_devcontainer_to_network(network_name: str) -> None:
    """Attach the devcontainer to the named network.

    S1.9: MUST no-op cleanly when ENV_TYPE != devcontainer.
    """
    env_type = os.environ.get("ENV_TYPE", "").lower()
    if env_type != "devcontainer":
        return

    container_name = os.environ.get("DEVCONTAINER_NAME") or os.environ.get("HOSTNAME", "")
    if not container_name:
        _log_warn("Devcontainer name not detected; skipping network attach.")
        return

    if not _docker_available():
        _log_warn("Docker not available; skipping devcontainer network attach.")
        return

    inspect = subprocess.run(
        ["docker", "network", "inspect", network_name, "--format", "{{range .Containers}}{{.Name}} {{end}}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if inspect.returncode == 0 and container_name in inspect.stdout.split():
        return

    _log_info(f"Connecting devcontainer {container_name} to {network_name}")
    connect = subprocess.run(
        ["docker", "network", "connect", network_name, container_name],
        capture_output=True,
        text=True,
        check=False,
    )
    if connect.returncode != 0:
        _log_warn(
            f"Failed to connect devcontainer to {network_name}: {connect.stderr.strip()}"
        )


def _check_tls_access() -> None:
    """TLS accessibility probe.

    S1.9 / S2.8: only runs when PUBLIC_TLS_* are set; degrades to warn on
    non-devcontainer or when docker is unavailable.
    """
    cert_path = os.environ.get("PUBLIC_TLS_CRT_PEM", "")
    key_path = os.environ.get("PUBLIC_TLS_KEY_PEM", "")
    if not cert_path or not key_path:
        return

    if not _docker_available():
        _log_warn("Docker not available; skipping TLS accessibility checks.")
        return

    user_uid = os.environ.get("USER_UID", str(os.getuid()))
    docker_gid = os.environ.get("DOCKER_GID") or os.environ.get("CONTAINER_GID", "")
    if not docker_gid:
        _log_warn("DOCKER_GID not set; skipping TLS accessibility checks.")
        return

    for label, path in (("certificate", cert_path), ("private key", key_path)):
        test = subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "-v",
                "/etc/letsencrypt:/etc/letsencrypt:ro",
                "--user",
                f"{user_uid}:{docker_gid}",
                "alpine:latest",
                "sh",
                "-c",
                f"test -r '{path}'",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if test.returncode != 0:
            _log_warn(f"TLS {label} not accessible to Docker: {path}")


def validate_required_certs(env: Optional[Dict[str, str]] = None) -> None:
    """Validate TLS cert/key files as given in env (S2.4).

    Reads PUBLIC_TLS_CRT_PEM and PUBLIC_TLS_KEY_PEM from *env* (defaults to
    os.environ).  For each path that is set, checks:
      - the file exists and is readable by the calling process, AND
      - is readable by DOCKER_GID: group-readable when st_gid == DOCKER_GID,
        or other-readable (st_mode & 0o004).

    Raises WorkspaceEnvError naming the exact failing path.
    ABSOLUTELY NO path re-derivation — the path is validated exactly as given
    (kills the v1 live/live bug A10 by design).

    S2.5: DOCKER_GID '0' is a valid GID; falsy-safe int parse.
    """
    source = env if env is not None else dict(os.environ)

    cert_path = source.get("PUBLIC_TLS_CRT_PEM", "")
    key_path = source.get("PUBLIC_TLS_KEY_PEM", "")

    if not cert_path and not key_path:
        return

    # S2.5: parse DOCKER_GID with falsy-safe check: '' or absent means unknown
    raw_gid = source.get("DOCKER_GID", "")
    docker_gid: Optional[int]
    if raw_gid is None or raw_gid == "":
        docker_gid = None
    else:
        try:
            docker_gid = int(raw_gid)
        except ValueError:
            docker_gid = None

    for path_str in (cert_path, key_path):
        if not path_str:
            continue
        p = Path(path_str)
        if not p.exists():
            raise WorkspaceEnvError(
                f"TLS file does not exist: {path_str}"
            )
        try:
            st = p.stat()
        except OSError as exc:
            raise WorkspaceEnvError(
                f"TLS file not readable: {path_str}: {exc}"
            ) from exc

        mode = st.st_mode
        # other-readable — accessible regardless of GID
        other_readable = bool(mode & stat.S_IROTH)
        # group-readable by DOCKER_GID
        group_readable_by_docker = (
            docker_gid is not None
            and st.st_gid == docker_gid
            and bool(mode & stat.S_IRGRP)
        )
        if not other_readable and not group_readable_by_docker:
            raise WorkspaceEnvError(
                f"TLS file not readable by DOCKER_GID ({docker_gid}): {path_str}"
            )


def ensure_workspace_network(
    network_name: Optional[str] = None,
    auto_connect: bool = True,
) -> None:
    """Ensure the shared Docker network exists and attach devcontainer if enabled."""
    resolved = network_name or os.environ.get("DOCKER_NETWORK_INTERNAL", "")
    _ensure_network_exists(resolved)
    if auto_connect:
        _connect_devcontainer_to_network(resolved)


def generate_ciu_env(repo_root: Path, output_path: Optional[Path] = None) -> Path:
    """Generate ciu.env with autodetected values.

    Side-effect: writes the ciu.env file only (network/TLS steps belong in
    bootstrap_env_init so tests stay simple — S2.8).

    Returns the path to the generated file.
    """
    repo_root = repo_root.resolve()
    output_path = output_path or repo_root / ENV_FILE_NAME

    env_flags = _detect_env_type()
    docker_gid = _detect_docker_gid()
    physical_root = _detect_physical_repo_root(repo_root)
    network_values = _compute_network_name(physical_root)
    public_values = _detect_public_fqdn(repo_root, require_fqdn=False)

    user_name = os.environ.get("USER_NAME", os.environ.get("USER", ""))
    user_uid = os.environ.get("USER_UID", str(os.getuid()))
    user_gid = os.environ.get("USER_GID", str(os.getgid()))
    docker_uid = os.environ.get("DOCKER_UID", user_uid)

    container_uid = os.environ.get("CONTAINER_UID", user_uid)
    container_gid = os.environ.get("CONTAINER_GID", docker_gid)

    python_exec = os.environ.get("PYTHON_EXECUTABLE", sys.executable)
    pip_exec = os.environ.get("PIP_EXECUTABLE") or shutil.which("pip") or ""

    def _emit_section(title: str, entries: list[tuple[str, str, str]]) -> list[str]:
        block: list[str] = [f"# {title}"]
        for key, value, comment in entries:
            block.append(f"# {comment}")
            block.append(f"export {key}=\"{value}\"")
        return block

    lines = [
        "# CIU Workspace Environment (Auto-generated)",
        "# Do not edit manually - regenerated by ciu --generate-env",
        "",
    ]

    lines.extend(_emit_section(
        "Environment type flags",
        [
            ("ENV_TYPE", env_flags["ENV_TYPE"], "Runtime environment: devcontainer | native | github-actions"),
            ("IS_DEVCONTAINER", env_flags["IS_DEVCONTAINER"], "1 when running inside a devcontainer"),
            ("IS_GITHUB_ACTIONS", env_flags["IS_GITHUB_ACTIONS"], "1 when running in GitHub Actions"),
            ("IS_NATIVE", env_flags["IS_NATIVE"], "1 when running on a native host"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "User identity",
        [
            ("USER_NAME", user_name, "Current user name"),
            ("USER_UID", user_uid, "Current user ID"),
            ("USER_GID", user_gid, "Current user primary group ID"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Container identity",
        [
            ("CONTAINER_UID", container_uid, "UID used for container user mapping"),
            ("CONTAINER_GID", container_gid, "GID used for container user mapping"),
            ("DOCKER_UID", docker_uid, "UID for Docker socket access (defaults to USER_UID)"),
            ("DOCKER_GID", docker_gid, "Docker group GID for host volume permissions"),
            ("DEVCONTAINER_NAME", os.environ.get("DEVCONTAINER_NAME", os.environ.get("HOSTNAME", "")), "Detected devcontainer name (if applicable)"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Repository paths",
        [
            ("REPO_ROOT", str(repo_root), "Repo root path inside the current environment"),
            ("PHYSICAL_REPO_ROOT", str(physical_root), "Host-visible repo root for Docker bind mounts"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Docker network identity",
        [
            ("REPO_NAME", network_values["REPO_NAME"], "Lowercase repository name for network naming"),
            ("INSTANCE_ID", network_values["INSTANCE_ID"], "Deterministic instance ID from repo path"),
            ("DOCKER_NETWORK_INTERNAL", network_values["DOCKER_NETWORK_INTERNAL"], "Internal Docker network name"),
        ],
    ))
    lines.append("")

    lines.extend(_emit_section(
        "Public endpoint detection",
        [
            ("PUBLIC_IP", public_values["PUBLIC_IP"], "Detected public IP address (may be empty)"),
            ("PUBLIC_FQDN", public_values["PUBLIC_FQDN"], "Detected or configured public FQDN"),
            ("PUBLIC_TLS_CRT_PEM", public_values["PUBLIC_TLS_CRT_PEM"], "TLS certificate PEM path (S2.3: required only when require_certs=true)"),
            ("PUBLIC_TLS_KEY_PEM", public_values["PUBLIC_TLS_KEY_PEM"], "TLS private key PEM path (S2.3: required only when require_certs=true)"),
        ],
    ))
    lines.append("")

    # S7.5: CIU_HOST_PROFILE placeholder — default ciu-deploy --profile for this host
    lines.append("# Host profile (S7.5)")
    lines.append('# export CIU_HOST_PROFILE=""  # default ciu-deploy --profile for this host')
    lines.append("")

    lines.extend(_emit_section(
        "Python tooling",
        [
            ("PYTHON_EXECUTABLE", python_exec, "Python interpreter for CIU subprocesses"),
            ("PIP_EXECUTABLE", pip_exec, "pip executable resolved on PATH"),
        ],
    ))

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def bootstrap_env_init(repo_root: Path) -> Path:
    """Single bootstrap entry point for --generate-env (S2.8).

    Performs the full S2.8 duty order:
      1. generate_ciu_env  — detect + write ciu.env
      2. ensure_workspace_network — create DOCKER_NETWORK_INTERNAL
      3. devcontainer self-attach  — no-op when ENV_TYPE != devcontainer (S1.9)
      4. TLS probe (_check_tls_access) — only when PUBLIC_TLS_* set (S1.9)

    generate_ciu_env is kept side-effect-light (write file only) so tests
    remain simple; this function composes the duties.

    Returns the path to the generated ciu.env file.
    """
    env_path = generate_ciu_env(repo_root)

    # Reload generated values into os.environ so the steps below see them
    generated_values = parse_workspace_env(env_path)
    for key, value in generated_values.items():
        if key not in os.environ:
            os.environ[key] = value

    # Step 2+3: network + devcontainer attach (devcontainer attach is a no-op
    # on native/CI per _connect_devcontainer_to_network's ENV_TYPE guard)
    network_name = os.environ.get("DOCKER_NETWORK_INTERNAL", "")
    if network_name:
        try:
            ensure_workspace_network(network_name)
        except WorkspaceEnvError as exc:
            _log_warn(f"Network setup skipped: {exc}")

    # Step 4: TLS probe (no-op when paths not set; degrades to warn on native)
    _check_tls_access()

    return env_path


def bootstrap_workspace_env(
    start_dir: Path,
    define_root: Optional[Path],
    defaults_filename: str,
    generate_env: bool,
    update_cert_permission: bool,
    required_keys: Iterable[str],
) -> Path:
    """Generate (if needed), load, and validate ciu.env.

    Returns the resolved env root directory.
    """
    env_root = resolve_env_root(start_dir, define_root, defaults_filename)
    env_path = env_root / ENV_FILE_NAME

    generated = False
    if generate_env or not env_path.exists():
        generate_ciu_env(env_root)
        generated = True

    if define_root:
        values = parse_workspace_env(env_path)
        for key, value in values.items():
            os.environ[key] = value
    else:
        load_workspace_env(env_root)

    if generated:
        # Run post-generate bootstrap steps (network + TLS probe).
        # These degrade to warn/no-op on native host per S1.9.
        network_name = os.environ.get("DOCKER_NETWORK_INTERNAL", "")
        if network_name:
            try:
                ensure_workspace_network(network_name)
            except WorkspaceEnvError as exc:
                _log_warn(f"Network setup skipped: {exc}")
        _check_tls_access()

    if update_cert_permission:
        public_fqdn = os.environ.get("PUBLIC_FQDN")
        update_cert_permissions(env_root, public_fqdn)

    ensure_workspace_env(required_keys)
    return env_root


def update_cert_permissions(repo_root: Path, public_fqdn: Optional[str] = None) -> None:
    """Run setup-letsencrypt-permissions.sh (requires root)."""
    if os.geteuid() != 0:
        raise WorkspaceEnvError(
            "--update-cert-permission requires root. "
            "Run: sudo ciu --update-cert-permission"
        )

    script_path = repo_root / "scripts" / "setup-letsencrypt-permissions.sh"
    if not script_path.exists():
        raise WorkspaceEnvError(
            f"Certificate permission script not found: {script_path}"
        )

    args = ["bash", str(script_path)]
    if public_fqdn:
        args.append(public_fqdn)

    subprocess.run(args, check=True)
