"""O2/O3 -- ``SqlAdapter.generate_mutation_sites`` (carve
``W3-CARVE-P34-sql-adapter.md`` §3.2, A-281/A-283): the seven operators'
spans and replacements, the five binding lexical context rules (each with
its own paired must-succeed control -- a test proving something is refused
proves nothing unless a sibling proves the near-identical valid form is
accepted), A-281's bounded worst-eviction retention, and the real,
producer-emitted dstdns oracle.

Every fixture below is a small, independently-reasoned, hand-constructed
SQL snippet (never generated by calling :meth:`SqlAdapter.generate_mutation_sites`
first and trusting its own output -- A-041/A-080's own "independent oracle"
discipline): the expected span text, replacement bytes, and line number are
all derived by READING the fixture, not by running the adapter and copying
what it printed.
"""

from __future__ import annotations

from conftest import PROJECT_ROOT

from assay.adapters.sql import SqlAdapter

ADAPTER = SqlAdapter()

FIXTURE_PATH = (
    PROJECT_ROOT
    / "tests"
    / "fixtures"
    / "mutation"
    / "sql"
    / "dstdns-21-create-workflow-corpus.sql"
)


def _all_lines(source: str) -> set[int]:
    return set(range(1, len(source.splitlines()) + 1))


def _one_site(source: str, operator: str):
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=(operator,), limit=1000
    )
    assert len(sites) == 1, sites
    return sites[0]


def _span_text(source: str, site) -> bytes:
    return source.encode("utf-8")[site.start_byte : site.end_byte]


# =============================================================================
# The real, producer-emitted oracle (O2) -- the pinned dstdns fixture
# =============================================================================


def test_real_dstdns_fixture_finds_exactly_the_two_real_restrict_foreign_keys():
    """The carve's own central measurement (§9 M3/M4), reproduced against
    the adapter's real output: the pinned dstdns file's only two
    ``ON DELETE RESTRICT`` foreign keys live INSIDE a ``DO $$ ... $$``
    idempotency guard, at source lines 327 and 332. A bare-regex scanner
    over the raw bytes reports 3 (the ``-- ON DELETE RESTRICT`` comment on
    line 99 is a phantom match); a single-level lexer that treats the
    dollar-quoted body as an opaque string literal reports 0 (both real
    sites are invisible without phase-2 recursion)."""
    source = FIXTURE_PATH.read_text(encoding="utf-8")
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:weaken-delete-action",), limit=1000
    )
    assert len(sites) == 2
    linenos = sorted(site.lineno for site in sites)
    assert linenos == [327, 332]
    for site in sites:
        assert site.replacement == b"CASCADE"
        assert _span_text(source, site) in (b"RESTRICT",)


def test_real_dstdns_fixture_produces_no_site_for_the_commented_out_occurrence():
    """Source line 99 is ``-- ... ON DELETE RESTRICT, which is the
    invariant that protects history.`` -- a comment, not code. No site of
    ANY operator may be attributed to it."""
    source = FIXTURE_PATH.read_text(encoding="utf-8")
    all_operator_sites = ADAPTER.generate_mutation_sites(
        source,
        _all_lines(source),
        operators=(
            "sql:drop-check",
            "sql:drop-unique",
            "sql:drop-not-null",
            "sql:drop-foreign-key",
            "sql:weaken-delete-action",
            "sql:drop-trigger",
            "sql:widen-check-in",
        ),
        limit=1000,
    )
    assert all(site.lineno != 99 for site in all_operator_sites)


def test_real_dstdns_fixture_produces_a_fully_valid_batch_end_to_end():
    """Every returned site survives :mod:`assay.mutation`'s own real
    validation gate (:func:`assay.mutation.collect_mutation_sites`) -- byte
    bounds, UTF-8 boundaries, no-op detection, identity ordering, and
    duplicate-freedom -- proven by driving the REAL function, not by
    inspecting this adapter's own output in isolation."""
    from assay.mutation import MutationTarget, collect_mutation_sites
    from assay.vocabulary import MUTATION_OPERATORS_BY_LANGUAGE

    source = FIXTURE_PATH.read_text(encoding="utf-8")
    target = MutationTarget(
        path="infra/db-init/init-scripts/21-create-workflow-corpus.sql",
        text=source,
        lines=frozenset(_all_lines(source)),
    )
    jobs = collect_mutation_sites(
        [target],
        adapter=ADAPTER,
        operators=MUTATION_OPERATORS_BY_LANGUAGE["sql"],
        limit=1000,
    )
    assert isinstance(jobs, tuple)
    assert len(jobs) > 0
    operators_seen = {job.site.operator for job in jobs}
    assert operators_seen == set(MUTATION_OPERATORS_BY_LANGUAGE["sql"])


# =============================================================================
# The seven operators -- span, replacement (carve §3.2's table)
# =============================================================================


def test_drop_check_replaces_the_whole_check_clause_with_check_true():
    source = "CREATE TABLE t (a INT, CONSTRAINT ck CHECK (a > 0));\n"
    site = _one_site(source, "sql:drop-check")
    assert _span_text(source, site) == b"CHECK (a > 0)"
    assert site.replacement == b"CHECK (true)"
    assert site.lineno == 1


def test_drop_unique_column_form_replaces_bare_unique_with_check_true():
    source = "CREATE TABLE t (email TEXT UNIQUE);\n"
    site = _one_site(source, "sql:drop-unique")
    assert _span_text(source, site) == b"UNIQUE"
    assert site.replacement == b"CHECK (true)"


def test_drop_unique_table_form_replaces_unique_and_its_column_list():
    source = "CREATE TABLE t (a INT, b INT, UNIQUE (a, b));\n"
    site = _one_site(source, "sql:drop-unique")
    assert _span_text(source, site) == b"UNIQUE (a, b)"
    assert site.replacement == b"CHECK (true)"


def test_drop_unique_index_form_replaces_create_unique_index_with_create_index():
    source = "CREATE UNIQUE INDEX idx ON t (a);\n"
    site = _one_site(source, "sql:drop-unique")
    assert _span_text(source, site) == b"CREATE UNIQUE INDEX"
    assert site.replacement == b"CREATE INDEX"


def test_drop_not_null_bare_form_replaces_not_null_with_null():
    source = "CREATE TABLE t (a INT NOT NULL);\n"
    site = _one_site(source, "sql:drop-not-null")
    assert _span_text(source, site) == b"NOT NULL"
    assert site.replacement == b"NULL"


def test_drop_not_null_alter_form_replaces_set_not_null_with_drop_not_null():
    """The mirror of rule 2: this is BOTH the operator's own alter-form span
    AND the paired must-succeed control for rule 4's ``DROP``-preceded
    exclusion below (the near-identical, ``SET``-preceded form is accepted)."""
    source = "ALTER TABLE t ALTER COLUMN a SET NOT NULL;\n"
    site = _one_site(source, "sql:drop-not-null")
    assert _span_text(source, site) == b"SET NOT NULL"
    assert site.replacement == b"DROP NOT NULL"


def test_drop_foreign_key_table_form_spans_through_the_on_delete_action():
    source = (
        "CREATE TABLE t (a INT, FOREIGN KEY (a) REFERENCES other(id) ON DELETE CASCADE);\n"
    )
    site = _one_site(source, "sql:drop-foreign-key")
    assert _span_text(source, site) == b"FOREIGN KEY (a) REFERENCES other(id) ON DELETE CASCADE"
    assert site.replacement == b"CHECK (true)"


def test_drop_foreign_key_bare_column_form_spans_the_references_clause():
    source = "CREATE TABLE t (a INT REFERENCES other(id));\n"
    site = _one_site(source, "sql:drop-foreign-key")
    assert _span_text(source, site) == b"REFERENCES other(id)"
    assert site.replacement == b"CHECK (true)"


def test_weaken_delete_action_replaces_only_the_restrict_word():
    source = "ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES o(id) ON DELETE RESTRICT;\n"
    site = _one_site(source, "sql:weaken-delete-action")
    assert _span_text(source, site) == b"RESTRICT"
    assert site.replacement == b"CASCADE"


def test_weaken_delete_action_replaces_the_two_word_no_action_form():
    source = "ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES o(id) ON DELETE NO ACTION;\n"
    site = _one_site(source, "sql:weaken-delete-action")
    assert _span_text(source, site) == b"NO ACTION"
    assert site.replacement == b"CASCADE"


def test_drop_trigger_spans_from_create_trigger_through_its_own_terminator():
    source = (
        "CREATE TRIGGER trg BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION f();\n"
    )
    site = _one_site(source, "sql:drop-trigger")
    assert _span_text(source, site) == (
        b"CREATE TRIGGER trg BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION f();"
    )
    assert site.replacement == b"SELECT 1;"


def test_drop_trigger_recognises_the_or_replace_and_constraint_forms():
    source = (
        "CREATE OR REPLACE TRIGGER trg BEFORE INSERT ON t "
        "FOR EACH ROW EXECUTE FUNCTION f();\n"
    )
    site = _one_site(source, "sql:drop-trigger")
    assert _span_text(source, site).startswith(b"CREATE OR REPLACE TRIGGER")
    assert site.replacement == b"SELECT 1;"


def test_widen_check_in_replaces_only_the_closing_paren():
    source = "CREATE TABLE t (k INT CHECK (k IN (1, 2)));\n"
    site = _one_site(source, "sql:widen-check-in")
    assert _span_text(source, site) == b")"
    assert site.replacement == b", 3)"


# =============================================================================
# The five binding lexical context rules, each with a paired must-succeed
# control (§3.2 rules 1-3, A-283 rules 4-5)
# =============================================================================


def test_rule1_is_not_null_predicate_produces_no_site():
    """Probe: ``IS NOT NULL`` is a predicate inside a CHECK expression, not
    a column constraint -- 35 of 267 code-context occurrences in the real
    corpus (13.1%, carve §9 M12)."""
    source = "CREATE TABLE t (a INT, CHECK (a IS NOT NULL));\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-not-null",), limit=1000
    )
    assert sites == ()


def test_rule1_control_bare_not_null_is_still_accepted():
    """Paired must-succeed control for rule 1: the near-identical form
    WITHOUT the ``IS`` predicate is a real column constraint and IS a site
    (same fixture/assertion as the bare-form span test above, restated
    explicitly as this rule's own control)."""
    source = "CREATE TABLE t (a INT NOT NULL);\n"
    site = _one_site(source, "sql:drop-not-null")
    assert site.replacement == b"NULL"


def test_rule2_and_4_set_prefixed_is_rewritten_drop_prefixed_is_refused():
    """Rule 2's probe (accepted, rewritten) and rule 4's probe (A-283,
    refused) side by side, over the SAME two-statement fixture, so the
    contrast is direct: ``SET NOT NULL`` -> ``DROP NOT NULL`` is a real
    site; ``DROP NOT NULL`` (the very text rule 2's own replacement
    emits) produces none, because ``DROP NULL`` is a syntax error."""
    source = (
        "ALTER TABLE t ALTER COLUMN a SET NOT NULL;\n"
        "ALTER TABLE t ALTER COLUMN b DROP NOT NULL;\n"
    )
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-not-null",), limit=1000
    )
    assert len(sites) == 1
    assert sites[0].lineno == 1
    assert _span_text(source, sites[0]) == b"SET NOT NULL"
    assert sites[0].replacement == b"DROP NOT NULL"


def test_rule3_widen_check_in_all_string_members_widen_with_an_unused_string():
    source = "CREATE TABLE t (k TEXT CHECK (k IN ('a', 'b')));\n"
    site = _one_site(source, "sql:widen-check-in")
    assert site.replacement == b", '__assay_widened__')"


def test_rule3_widen_check_in_avoids_colliding_with_an_existing_member():
    """If a consumer's own list already contains the default synthetic
    literal, a numeric suffix is used instead -- the new literal must never
    collide with an existing member (the whole point of "unused")."""
    source = "CREATE TABLE t (k TEXT CHECK (k IN ('__assay_widened__', 'b')));\n"
    site = _one_site(source, "sql:widen-check-in")
    assert site.replacement == b", '__assay_widened__2')"


def test_rule3_control_all_unsigned_integer_members_widen_with_max_plus_one():
    source = "CREATE TABLE t (k INT CHECK (k IN (1, 2, 5)));\n"
    site = _one_site(source, "sql:widen-check-in")
    assert site.replacement == b", 6)"


def test_rule3_mixed_shape_members_produce_no_site():
    """Probe: a column reference mixed with a literal -- "anything else"
    per rule 3 -- emits no site (an honest gap beats a crashed mutant)."""
    source = "CREATE TABLE t (k INT CHECK (k IN (a, 2)));\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:widen-check-in",), limit=1000
    )
    assert sites == ()


def test_rule3_cast_expression_member_produces_no_site():
    """Probe: a cast (``'a'::mystatus``) is not a bare string literal --
    the measured M11 hazard's own general case."""
    source = "CREATE TABLE t (k TEXT CHECK (k IN ('a'::mystatus)));\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:widen-check-in",), limit=1000
    )
    assert sites == ()


def test_rule5_declare_section_not_null_is_refused_but_the_executable_body_is_accepted():
    """Probe (A-283, refused) and control (accepted) in ONE fixture: the
    plpgsql ``DECLARE v INT NOT NULL`` is not a column constraint and must
    produce no site; the ``ALTER ... SET NOT NULL`` statement inside the
    SAME dollar body's executable section, recovered by the identical
    phase-2 recursion, is a real site."""
    source = (
        "DO $$\n"
        "DECLARE v INT NOT NULL := 0;\n"
        "BEGIN\n"
        "    ALTER TABLE t ALTER COLUMN a SET NOT NULL;\n"
        "END $$;\n"
    )
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-not-null",), limit=1000
    )
    assert len(sites) == 1
    assert sites[0].lineno == 4
    assert _span_text(source, sites[0]) == b"SET NOT NULL"


def test_rule5_control_a_dollar_body_with_no_declare_section_is_unaffected():
    """Paired must-succeed control: a dollar body with NO ``DECLARE``
    section at all (no exclusion span computed) still recovers a real
    ``NOT NULL`` site from its executable body."""
    source = "DO $$\nBEGIN\n    ALTER TABLE t ADD COLUMN a INT NOT NULL;\nEND $$;\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-not-null",), limit=1000
    )
    assert len(sites) == 1
    assert sites[0].replacement == b"NULL"


def test_grant_references_recogniser_gap_is_refused_but_a_real_fk_is_accepted():
    """A-283's recogniser-gap probe and control: ``GRANT REFERENCES`` is a
    privilege grant, not a constraint clause (``GRANT CHECK (true) ON ...``
    is a syntax error); the near-identical bare column-level
    ``REFERENCES`` clause, with no leading ``GRANT``/``REVOKE``, is a real
    site."""
    source = (
        "GRANT REFERENCES ON te TO r1;\n"
        "CREATE TABLE t (a INT REFERENCES other(id));\n"
    )
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-foreign-key",), limit=1000
    )
    assert len(sites) == 1
    assert sites[0].lineno == 2
    assert _span_text(source, sites[0]) == b"REFERENCES other(id)"


def test_revoke_references_is_also_excluded_by_the_recogniser_gap_rule():
    source = "REVOKE REFERENCES ON te FROM r1;\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-foreign-key",), limit=1000
    )
    assert sites == ()


def test_drop_trigger_inside_a_dollar_body_is_refused_but_outer_level_is_accepted():
    """The carve's own scope reduction, probed and controlled in one
    fixture: ``SELECT 1;`` is invalid inside a plpgsql body, so
    ``sql:drop-trigger`` never fires on a ``CREATE TRIGGER`` recovered by
    phase-2 recursion; the identical construct at outer level IS a site."""
    source = (
        "DO $$\n"
        "BEGIN\n"
        "  CREATE TRIGGER trg BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION f();\n"
        "END $$;\n"
        "CREATE TRIGGER trg2 BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION f();\n"
    )
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-trigger",), limit=1000
    )
    assert len(sites) == 1
    assert sites[0].lineno == 5
    assert _span_text(source, sites[0]).startswith(b"CREATE TRIGGER trg2")


# =============================================================================
# A-281: bounded worst-eviction retention, identity-ordered, never a
# per-operator walk
# =============================================================================


def test_retention_returns_an_identity_ordered_batch_regardless_of_scan_order():
    """This adapter's own internal scan order is fixed (drop-check first,
    ... widen-check-in last, the operator table's own order) and
    deliberately does NOT match this fixture's byte order: the
    ``widen-check-in`` site sits EARLIER in the file than the
    ``drop-unique`` site, but is scanned LAST internally. The returned
    batch must still be sorted by identity (byte position first)."""
    source = "CREATE TABLE t (\n    k INT CHECK (k IN (1, 2)),\n    email TEXT UNIQUE\n);\n"
    sites = ADAPTER.generate_mutation_sites(
        source,
        _all_lines(source),
        operators=("sql:drop-unique", "sql:widen-check-in"),
        limit=1000,
    )
    assert [site.operator for site in sites] == ["sql:widen-check-in", "sql:drop-unique"]
    assert sites[0].start_byte < sites[1].start_byte
    identities = [site.identity for site in sites]
    assert identities == sorted(identities)


def test_retention_at_limit_one_keeps_the_identity_smallest_site_not_the_scan_first_one():
    """A-281's own strengthened test: the carve's original "limit=1 ->
    exactly one descriptor" wording cannot distinguish a correct bounded
    heap from a per-operator walk that merely stops early (which would
    retain whichever operator's own scan happens to run first --
    ``sql:drop-unique``, scanned before ``sql:widen-check-in`` internally
    -- rather than the identity-smallest candidate)."""
    source = "CREATE TABLE t (\n    k INT CHECK (k IN (1, 2)),\n    email TEXT UNIQUE\n);\n"
    all_lines = _all_lines(source)
    unbounded = ADAPTER.generate_mutation_sites(
        source, all_lines, operators=("sql:drop-unique", "sql:widen-check-in"), limit=1000
    )
    bounded = ADAPTER.generate_mutation_sites(
        source, all_lines, operators=("sql:drop-unique", "sql:widen-check-in"), limit=1
    )
    assert len(bounded) == 1
    assert bounded[0].operator == "sql:widen-check-in"
    assert bounded[0].identity == unbounded[0].identity
    assert bounded[0].start_byte < unbounded[1].start_byte  # the evicted site was the LATER one


# =============================================================================
# Line-eligibility scoping (the *lines* parameter, mirroring Python's own
# contract: a site outside the changed-line set is never produced)
# =============================================================================


def test_a_site_outside_the_changed_lines_is_not_produced():
    source = "CREATE TABLE t (a INT NOT NULL, b INT NOT NULL);\n"
    site_on_line_1 = ADAPTER.generate_mutation_sites(
        source, {1}, operators=("sql:drop-not-null",), limit=1000
    )
    assert len(site_on_line_1) == 2  # both NOT NULLs are on line 1

    source_multiline = "CREATE TABLE t (\n    a INT NOT NULL,\n    b INT NOT NULL\n);\n"
    only_line_2 = ADAPTER.generate_mutation_sites(
        source_multiline, {2}, operators=("sql:drop-not-null",), limit=1000
    )
    assert len(only_line_2) == 1
    assert only_line_2[0].lineno == 2


# =============================================================================
# Fail-closed discovery (phase 3): a malformed target raises, propagated
# uncaught from assay.adapters.sql_lex
# =============================================================================


def test_unterminated_construct_raises_mutation_discovery_error():
    from assay.mutation import MutationDiscoveryError

    source = "CREATE TABLE t (a TEXT DEFAULT 'never closed);\n"
    try:
        ADAPTER.generate_mutation_sites(
            source, _all_lines(source), operators=("sql:drop-check",), limit=1000
        )
    except MutationDiscoveryError:
        pass
    else:
        raise AssertionError("expected MutationDiscoveryError")


def test_control_well_formed_source_does_not_raise():
    source = "CREATE TABLE t (a TEXT DEFAULT 'closed');\n"
    ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-check",), limit=1000
    )


# =============================================================================
# Replacement invariants (direct tests of the private safety net --
# every REAL operator replacement above already passes it; these probe the
# function's own branches directly, the same precedent as importing
# ``PythonAdapter``'s private ``_falsy_swap_replacement`` for a direct test)
# =============================================================================


def test_replacement_invariant_rejects_a_stray_dollar_sign():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-check", b"CHECK ($bad)") is False


def test_replacement_invariant_rejects_a_stray_double_quote():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-check", b'CHECK ("bad")') is False


def test_replacement_invariant_rejects_a_comment_opener():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-check", b"CHECK (true) --") is False
    assert _replacement_is_safe("sql:drop-check", b"CHECK (true) /*") is False


def test_replacement_invariant_rejects_a_semicolon_on_a_non_trigger_operator():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-check", b"CHECK (true);") is False


def test_replacement_invariant_accepts_the_trigger_forms_own_single_semicolon():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-trigger", b"SELECT 1;") is True


def test_replacement_invariant_rejects_a_trigger_replacement_with_two_semicolons():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-trigger", b"SELECT 1; SELECT 2;") is False


def test_replacement_invariant_rejects_a_bare_quote_on_a_non_widen_operator():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:drop-not-null", b"NUL'L") is False


def test_replacement_invariant_accepts_widen_check_ins_own_balanced_literal():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:widen-check-in", b", '__assay_widened__')") is True
    assert _replacement_is_safe("sql:widen-check-in", b", 6)") is True


def test_replacement_invariant_rejects_widen_check_ins_own_odd_quote_count():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:widen-check-in", b", '6)") is False


def test_replacement_invariant_rejects_a_semicolon_inside_widen_check_ins_replacement():
    from assay.adapters.sql import _replacement_is_safe

    assert _replacement_is_safe("sql:widen-check-in", b", 6); DROP TABLE t") is False


def test_replacement_invariant_is_actually_wired_into_generate_mutation_sites(monkeypatch):
    """None of the seven real scanners can ever construct an unsafe
    replacement (every one is fixed, controlled text), so the filter inside
    :meth:`SqlAdapter.generate_mutation_sites` is unreachable through any
    real SQL input -- proven honestly, by fault injection, rather than left
    untested: a scanner is monkeypatched to emit one deliberately unsafe
    site alongside a real one, and the unsafe one must be dropped while the
    real one survives."""
    import assay.adapters.sql as sql_module

    real_candidates = sql_module._all_candidate_sites

    def _poisoned_candidates(source, masked, dollar_bodies, declare_spans):
        sites = list(real_candidates(source, masked, dollar_bodies, declare_spans))
        sites.append(
            sql_module._Site(
                lineno=1,
                operator="sql:drop-check",
                description="poisoned",
                start=0,
                end=1,
                replacement=b"CHECK ($injected)",
            )
        )
        return sites

    monkeypatch.setattr(sql_module, "_all_candidate_sites", _poisoned_candidates)
    source = "CREATE TABLE t (a INT, CONSTRAINT ck CHECK (a > 0));\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:drop-check",), limit=1000
    )
    assert all(b"$" not in site.replacement for site in sites)
    assert any(site.replacement == b"CHECK (true)" for site in sites)


def test_bounded_retention_rejects_a_worse_candidate_without_evicting_the_retained_one():
    """The heap-eviction ``elif`` branch's own FALSE arc: a third candidate
    scanned after the heap is already full, whose identity is WORSE than
    the current worst retained entry, must be discarded without touching
    the heap -- distinct from the eviction case above, where the new
    candidate WAS better."""
    source = (
        "CREATE TABLE t (\n"
        "    email TEXT UNIQUE,\n"
        "    a INT NOT NULL,\n"
        "    CONSTRAINT ck CHECK (a > 0)\n"
        ");\n"
    )
    all_lines = _all_lines(source)
    unbounded = ADAPTER.generate_mutation_sites(
        source,
        all_lines,
        operators=("sql:drop-check", "sql:drop-unique", "sql:drop-not-null"),
        limit=1000,
    )
    # scanned in THIS order internally: drop-check (latest byte position),
    # drop-unique (earliest), drop-not-null (middle) -- so the heap fills
    # with drop-check first, drop-unique evicts it (better), and
    # drop-not-null must then be REJECTED (worse than drop-unique) without
    # disturbing the heap.
    assert [site.operator for site in unbounded] == [
        "sql:drop-unique",
        "sql:drop-not-null",
        "sql:drop-check",
    ]
    bounded = ADAPTER.generate_mutation_sites(
        source,
        all_lines,
        operators=("sql:drop-check", "sql:drop-unique", "sql:drop-not-null"),
        limit=1,
    )
    assert len(bounded) == 1
    assert bounded[0].operator == "sql:drop-unique"
    assert bounded[0].identity == unbounded[0].identity


# =============================================================================
# Direct tests of the small private scanning helpers, covering skip/failure
# branches that no REAL well-formed SQL construct can reach (malformed,
# unbalanced input) -- the same "direct private-function test" precedent
# ``test_adapters_python_generate_mutants.py`` already sets by importing
# ``PythonAdapter``'s own private ``_falsy_swap_replacement``.
# =============================================================================


def test_find_matching_close_paren_returns_none_when_unbalanced():
    from assay.adapters.sql import _find_matching_close_paren

    assert _find_matching_close_paren(b"(a, b", 0) is None


def test_find_matching_close_paren_control_balanced():
    from assay.adapters.sql import _find_matching_close_paren

    assert _find_matching_close_paren(b"(a, b)", 0) == 5


def test_split_top_level_respects_nested_parens():
    from assay.adapters.sql import _split_top_level

    assert _split_top_level(b"foo(1,2), 3") == [(0, 8), (9, 11)]


def test_unused_string_literal_tries_a_third_candidate_when_first_two_collide():
    from assay.adapters.sql import _unused_string_literal

    existing = {b"__assay_widened__", b"__assay_widened__2"}
    assert _unused_string_literal(existing) == b"__assay_widened__3"


def test_extend_references_clause_returns_none_without_a_target_name():
    from assay.adapters.sql import _extend_references_clause

    assert _extend_references_clause(b"REFERENCES ;", 0) is None


def test_extend_references_clause_control_with_a_target_name():
    from assay.adapters.sql import _extend_references_clause

    assert _extend_references_clause(b"REFERENCES x;", 0) == len(b"REFERENCES x")


def test_scan_drop_check_skips_an_unbalanced_check_clause():
    from assay.adapters.sql import _scan_drop_check

    source = b"CHECK (a > 0"
    assert _scan_drop_check(source, source) == []


def test_scan_drop_unique_skips_an_unbalanced_column_list():
    from assay.adapters.sql import _scan_drop_unique

    source = b"UNIQUE (a, b"
    assert _scan_drop_unique(source, source) == []


def test_scan_drop_foreign_key_form_skips_when_not_followed_by_open_paren():
    from assay.adapters.sql import _scan_drop_foreign_key

    source = b"FOREIGN KEY z"
    assert _scan_drop_foreign_key(source, source) == []


def test_scan_drop_foreign_key_form_skips_an_unbalanced_column_list():
    from assay.adapters.sql import _scan_drop_foreign_key

    source = b"FOREIGN KEY (a"
    assert _scan_drop_foreign_key(source, source) == []


def test_scan_drop_foreign_key_form_skips_when_references_keyword_is_missing():
    from assay.adapters.sql import _scan_drop_foreign_key

    source = b"FOREIGN KEY (a) NOT_REFERENCES x"
    assert _scan_drop_foreign_key(source, source) == []


def test_scan_drop_foreign_key_form_and_bare_form_both_skip_a_malformed_target():
    """One fixture, two branches: the FK-form's own ``REFERENCES`` target
    check (§ table row 1) and the bare-form's identical check (row 2) both
    refuse the same malformed ``REFERENCES ;`` (no target table name)."""
    from assay.adapters.sql import _scan_drop_foreign_key

    source = b"FOREIGN KEY (a) REFERENCES ;"
    assert _scan_drop_foreign_key(source, source) == []


def test_scan_drop_trigger_skips_when_no_terminating_semicolon_exists():
    from assay.adapters.sql import _scan_drop_trigger

    source = b"CREATE TRIGGER trg BEFORE INSERT ON t EXECUTE FUNCTION f()"
    assert _scan_drop_trigger(source, source, ()) == []


def test_scan_widen_check_in_skips_an_unbalanced_check_clause():
    from assay.adapters.sql import _scan_widen_check_in

    source = b"CHECK (k IN (1, 2)"
    assert _scan_widen_check_in(source, source) == []


def test_rule3_control_an_empty_in_list_produces_no_site():
    """A stray trailing comma (``IN (1, 2,)``) or a bare empty list
    (``IN ()``) produces one EMPTY member once split -- refused the same
    way any other non-literal shape is (an honest gap, not a crash)."""
    source = "CREATE TABLE t (k INT CHECK (k IN ()));\n"
    sites = ADAPTER.generate_mutation_sites(
        source, _all_lines(source), operators=("sql:widen-check-in",), limit=1000
    )
    assert sites == ()
