from __future__ import annotations


APT_SOURCES = """\
# /etc/apt/sources.list.d/debian.sources
# Generated by vbpub debian-install v2; release: {release}
Types: deb deb-src
URIs: http://deb.debian.org/debian
Suites: {release} {release}-updates
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb deb-src
URIs: http://deb.debian.org/debian-security
Suites: {release}-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb deb-src
URIs: http://deb.debian.org/debian
Suites: {release}-backports
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: http://deb.debian.org/debian
Suites: testing
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb deb-src
URIs: http://deb.debian.org/debian
Suites: unstable
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
"""


APT_CUSTOM = """\
// File: /etc/apt/apt.conf.d/custom.conf
// Generated by vbpub debian-install v2.

Debug
{
    pkgPolicy "true";
};

APT
{
    Get
    {
        Show-Versions "true";
        AutomaticRemove "true";
    };
};
"""


APT_PRIORITIES = """\
# /etc/apt/preferences.d/debian-priorities
# Generated by vbpub debian-install v2; release: {release}

Package: *
Pin: release a=stable
Pin-Priority: 500

Package: *
Pin: release a=stable-updates
Pin-Priority: 500

Package: *
Pin: release a=stable-security
Pin-Priority: 550

Package: *
Pin: release a=stable-backports
Pin-Priority: 600

Package: *
Pin: release a=oldstable, a=oldstable-backports, a=testing
Pin-Priority: 100

Package: *
Pin: release a=unstable
Pin-Priority: 50
"""


ZSWAP_SERVICE = """\
[Unit]
Description=Configure zswap before swap activation
DefaultDependencies=no
After=systemd-modules-load.service
Before=swap.target
ConditionPathExists=/sys/module/zswap/parameters/enabled

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/modprobe zstd
ExecStart=/bin/sh -c 'echo {compressor} > /sys/module/zswap/parameters/compressor'
ExecStart=/bin/sh -c 'echo {zpool} > /sys/module/zswap/parameters/zpool'
ExecStart=/bin/sh -c 'echo {pool_percent} > /sys/module/zswap/parameters/max_pool_percent'
ExecStart=/bin/sh -c 'echo 90 > /sys/module/zswap/parameters/accept_threshold_percent'
ExecStart=/bin/sh -c 'echo Y > /sys/module/zswap/parameters/shrinker_enabled'
ExecStart=/bin/sh -c 'echo 1 > /sys/module/zswap/parameters/enabled'
ExecStartPost=/bin/sh -c 'echo "zswap compressor=$$(cat /sys/module/zswap/parameters/compressor)"'

[Install]
WantedBy=sysinit.target
"""


THP_SERVICE = """\
[Unit]
Description=Configure Transparent Huge Pages
DefaultDependencies=no
After=sysinit.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled || true'
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag || true'

[Install]
WantedBy=sysinit.target
"""


# Ported from modern-debian-tools-python-debug/host-setup/scripts/
# mdt-apply-dev-caps.sh's cgroup2-mount-flags section (the *already-fixed*
# copy, CGROUP2_FLAGS=fix default) rather than reproduced inline in a unit's
# ExecStart= (which would need every '$' doubled to '$$' for systemd's own
# specifier expansion — a real script file avoids that entirely and stays
# byte-for-byte diffable against the source it was ported from).
#
# Unlike host-setup's version, this has no periodic timer behind it — a
# fresh install only gets one shot at boot, so this errs toward being
# unconditionally safe to re-run (idempotent: a no-op once both options are
# already present) rather than toward matching host-setup's sweep cadence.
CGROUP2_FLAGS_SCRIPT = """\
#!/bin/sh
# Restores memory_recursiveprot (+nsdelegate) on /sys/fs/cgroup if a later
# remount stripped it — systemd mounts cgroup2 with these by default at boot
# (>= 248), but a runtime remount from the init cgroup namespace can silently
# drop them, and without memory_recursiveprot every slice's MemoryLow/
# MemoryMin becomes a no-op while `systemctl show` keeps reporting the value
# you set. Also restores memory_hugetlb_accounting on kernel >= 6.6 (a
# systemd >= 260 mount default we can take at the raw kernel-mount-option
# level without waiting for systemd to reach that version) — kernel-gated
# because offering an unsupported mount option fails the WHOLE remount, not
# just that one option.
set -eu

CG=/sys/fs/cgroup
KVER=$(uname -r | grep -oE '^[0-9]+\\.[0-9]+')
KMAJOR=${KVER%%.*}
KMINOR=${KVER##*.}
HUGETLB_OPT=""
if [ -n "$KMAJOR" ] && [ -n "$KMINOR" ] \\
   && { [ "$KMAJOR" -gt 6 ] || { [ "$KMAJOR" -eq 6 ] && [ "$KMINOR" -ge 6 ]; }; }; then
  HUGETLB_OPT=",memory_hugetlb_accounting"
fi

CG_OPTS=$(findmnt -no OPTIONS "$CG" 2>/dev/null || true)
MISSING=0
if [ -n "$CG_OPTS" ]; then
  case "$CG_OPTS" in *memory_recursiveprot*) : ;; *) MISSING=1 ;; esac
  if [ -n "$HUGETLB_OPT" ]; then
    case "$CG_OPTS" in *memory_hugetlb_accounting*) : ;; *) MISSING=1 ;; esac
  fi
fi
if [ "$MISSING" = 1 ]; then
  mount -o "remount,nsdelegate,memory_recursiveprot$HUGETLB_OPT" "$CG"
  echo "cgroup2: restored nsdelegate,memory_recursiveprot$HUGETLB_OPT (was: $CG_OPTS)"
fi
"""


CGROUP2_FLAGS_SERVICE = """\
[Unit]
Description=Restore cgroup2 memory_recursiveprot (+nsdelegate, +memory_hugetlb_accounting)
DefaultDependencies=no
After=local-fs.target
Before=sysinit.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/vbpub-cgroup2-flags.sh

[Install]
WantedBy=sysinit.target
"""


STAGE2_SERVICE = """\
[Unit]
Description=vbpub debian install stage2
After=network-online.target local-fs.target
Wants=network-online.target
ConditionPathExists={state_dir}/stage1_done
ConditionPathExists=!{state_dir}/stage2_done

[Service]
Type=oneshot
EnvironmentFile=-{env_file}
LoadCredential={credentials_line}
WorkingDirectory={working_directory}
ExecStart={python} -m scripts.debian_install_v2.bootstrap --action resume
TimeoutStartSec=infinity
StandardOutput=append:{output}
StandardError=append:{output}

[Install]
WantedBy=multi-user.target
"""
