"""Shared Git-worktree workspace-instance primitives.

The package is intentionally product-neutral.  CIU and CMRU package this
source as an internal dependency; it does not know about either product's
configuration or runtime.
"""

from .core import (
    CURRENT_RECORD_VERSION,
    WORKSPACE_RECORD_DIR,
    GitWorktree,
    InvocationContext,
    Lease,
    ResourceNamespace,
    WorkspaceCollisionError,
    WorkspaceContext,
    WorkspaceError,
    WorkspaceRecord,
    WorkspaceState,
    acquire_lease,
    adopt_workspace,
    canonical_path,
    create_workspace,
    discover_git_context,
    discover_git_root,
    ensure_workspace,
    find_workspace,
    inspect_workspace,
    list_workspaces,
    list_git_worktrees,
    physical_path,
    read_record,
    remove_unrecorded_workspace,
    remove_workspace,
    resolve_invocation,
    workspace_id_for_path,
    workspace_lock,
    write_record,
    release_lease,
)

__all__ = [
    "CURRENT_RECORD_VERSION",
    "WORKSPACE_RECORD_DIR",
    "GitWorktree",
    "InvocationContext",
    "Lease",
    "ResourceNamespace",
    "WorkspaceCollisionError",
    "WorkspaceContext",
    "WorkspaceError",
    "WorkspaceRecord",
    "WorkspaceState",
    "acquire_lease",
    "adopt_workspace",
    "canonical_path",
    "create_workspace",
    "discover_git_context",
    "discover_git_root",
    "ensure_workspace",
    "find_workspace",
    "inspect_workspace",
    "list_workspaces",
    "list_git_worktrees",
    "physical_path",
    "read_record",
    "remove_unrecorded_workspace",
    "remove_workspace",
    "resolve_invocation",
    "workspace_id_for_path",
    "workspace_lock",
    "write_record",
    "release_lease",
]
