#!/usr/bin/env bash
# Build the profiler's venv. Run this ONCE, ahead of any profiling run —
# nothing in this tool installs, downloads, or assembles anything at run time.
# A profiler that reaches for the network while a gate is running is adding
# exactly the load it was sent to measure.
#
#   ./setup.sh              build (or rebuild) venv/ from requirements.txt
#   ./setup.sh --check      verify the venv satisfies the lock, no writes
#   ./setup.sh --relock     re-resolve from pyproject.toml and rewrite the lock
#
# pyproject.toml is the single source of dependency truth; requirements.txt is
# a generated lock pinning what was actually resolved, so a rebuild months from
# now reproduces this venv rather than whatever PyPI has moved on to. Only
# --relock changes the lock, and it is a deliberate act with a diff to review.
#
# The venv is deliberately self-contained rather than --system-site-packages:
# the devcontainer's own interpreter is already a venv, so "system" site
# packages resolve to the empty base install and matplotlib/numpy go missing in
# a way that only shows up at report time.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
venv="$here/venv"
req="$here/requirements.txt"

mode="${1:-build}"

case "$mode" in
  --check)
    if [[ ! -x "$venv/bin/python" ]]; then
      echo "cgprofile: venv missing — run $here/setup.sh" >&2
      exit 1
    fi
    if ! "$venv/bin/pip" install --dry-run --quiet --no-deps -r "$req" >/dev/null 2>&1; then
      echo "cgprofile: venv does not satisfy the lock — re-run $here/setup.sh" >&2
      exit 1
    fi
    echo "cgprofile: venv OK ($("$venv/bin/python" -V))"
    exit 0
    ;;
  --relock)
    python3 -m venv "$venv.relock"
    "$venv.relock/bin/pip" install --quiet --upgrade pip setuptools wheel
    "$venv.relock/bin/pip" install --quiet "$here[test]"
    "$venv.relock/bin/pip" freeze \
      | grep -viE '^(pip|setuptools|wheel|cgroup-profiler)([=@]|$)' \
      > "$req.new"
    {
      echo "# GENERATED by ./setup.sh --relock from pyproject.toml — do not hand-edit."
      echo "# Add or change dependencies in pyproject.toml, then re-lock."
      cat "$req.new"
    } > "$req"
    rm -f "$req.new"
    rm -rf "$venv.relock"
    echo "cgprofile: re-locked $req"
    exit 0
    ;;
  build) ;;
  *)
    echo "usage: setup.sh [--check|--relock]" >&2
    exit 2
    ;;
esac

python3 -m venv "$venv"
"$venv/bin/pip" install --quiet --upgrade pip setuptools wheel
"$venv/bin/pip" install --quiet -r "$req"

"$venv/bin/python" - <<'PY'
import matplotlib, numpy, pandas, plotly, ruptures, scipy
import plotly.offline as offline
print("cgprofile venv ready:")
for module in (numpy, scipy, pandas, plotly, matplotlib, ruptures):
    print(f"  {module.__name__:11s} {module.__version__}")
print(f"  plotly.js  {len(offline.get_plotlyjs()) // 1024} KiB (inlined into each report)")
PY
