"""O1 — ``PythonAdapter.statement_spans``, tested directly against real
Python source, hand-derived expected spans (never generated by calling the
adapter and trusting its own output).

Adopted from dstdns's own ``statement_spans`` construct catalogue: a
multi-line literal/call (the B065/P80 bug this whole package exists to
close), decorators, match-case patterns, and compound-statement header
trimming (an ``if``/``for``/``def``'s own span must stop before its first
body statement, or a nested statement's own coverage gets swallowed).
"""

from __future__ import annotations

from assay.adapters.base import StatementSpan
from assay.adapters.python import PythonAdapter

ADAPTER = PythonAdapter()


def test_a_simple_one_line_statement_spans_only_its_own_line():
    source = "x = 1\n"
    spans = ADAPTER.statement_spans(source)
    assert StatementSpan(start_line=1, end_line=1) in spans


def test_a_multiline_dict_literal_spans_every_physical_line():
    """The exact worked example from assay-P06-BRIEF.md: a changed line
    inside this dict's body must be recoverable to line 2's own status."""
    source = (
        "def build_config():\n"  # 1
        "    return {\n"  # 2
        '        "a": 1,\n'  # 3
        '        "b": 2,\n'  # 4
        "    }\n"  # 5
    )
    spans = ADAPTER.statement_spans(source)
    # The `return {...}` statement starts at line 2 and its own physical
    # span runs through line 5 (the closing brace) -- a `return` is a
    # simple statement (no nested body), so it claims its FULL span.
    assert StatementSpan(start_line=2, end_line=5) in spans


def test_a_compound_statement_header_stops_before_its_first_body_line():
    """An `if` clause's own span must NOT swallow its body -- the body's
    own statement gets its own, separately tracked span."""
    source = (
        "if condition(\n"  # 1
        "    x,\n"  # 2
        "):\n"  # 3
        "    do_thing()\n"  # 4
    )
    spans = ADAPTER.statement_spans(source)
    assert StatementSpan(start_line=1, end_line=3) in spans  # the `if` header
    assert StatementSpan(start_line=4, end_line=4) in spans  # its one body stmt
    # Nothing claims lines 1-4 as a single span -- that would swallow line 4.
    assert StatementSpan(start_line=1, end_line=4) not in spans


def test_a_one_line_compound_statement_is_a_single_line_span():
    """`if x: return 1`, header and body on the SAME physical line -- the
    clamp that stops the computed end line going below the start line
    (`first_child_line - 1` would otherwise be 0, before line 1)."""
    source = "if x: return 1\n"
    spans = ADAPTER.statement_spans(source)
    assert StatementSpan(start_line=1, end_line=1) in spans


def test_a_multiline_decorator_gets_its_own_span():
    """coverage.py tracks only a decorator's first line -- its continuation
    lines need their OWN span, separate from the decorated def's."""
    source = (
        "@lru_cache(\n"  # 1
        "    maxsize=128,\n"  # 2
        ")\n"  # 3
        "def cached():\n"  # 4
        "    return 1\n"  # 5
    )
    spans = ADAPTER.statement_spans(source)
    assert StatementSpan(start_line=1, end_line=3) in spans  # the decorator
    assert StatementSpan(start_line=4, end_line=4) in spans  # the def header
    assert StatementSpan(start_line=5, end_line=5) in spans  # its one body stmt


def test_a_multiline_match_case_pattern_gets_its_own_span():
    """A case pattern spanning several lines needs its own span, distinct
    from the enclosing (essentially-always-executed) `match` -- otherwise a
    line inside a never-taken branch would inherit the `match` header's own
    (executed) status."""
    source = (
        "match value:\n"  # 1
        "    case (\n"  # 2
        "        1\n"  # 3
        "        | 2\n"  # 4
        "    ):\n"  # 5
        "        handle()\n"  # 6
    )
    spans = ADAPTER.statement_spans(source)
    # `ast` attributes the pattern's own span to the OR-pattern's physical
    # lines (3-4: "1" through "| 2") -- the wrapping parentheses are not
    # part of the pattern node itself, verified against a real `ast.parse`.
    assert StatementSpan(start_line=3, end_line=4) in spans  # the pattern
    assert StatementSpan(start_line=6, end_line=6) in spans  # the case body


def test_a_bare_module_docstring_is_never_a_span_anchor():
    """The shared ``_is_bare_string_statement`` exclusion (P06's own
    helper) -- a docstring is never coverage-tracked, so it must never
    become a span an unattributed line could resolve to."""
    source = '"""Module docstring."""\nx = 1\n'
    spans = ADAPTER.statement_spans(source)
    assert not any(span.start_line == 1 for span in spans)
    assert StatementSpan(start_line=2, end_line=2) in spans


def test_a_bare_class_docstring_is_never_a_span_anchor():
    source = "class Thing:\n    \"\"\"Class docstring.\"\"\"\n    x = 1\n"
    spans = ADAPTER.statement_spans(source)
    assert not any(span.start_line == 2 for span in spans)
    assert StatementSpan(start_line=3, end_line=3) in spans


def test_nested_statements_each_get_their_own_span():
    """A full AST walk (not just top-level) -- an unattributed line nested
    arbitrarily deep must still be attributable."""
    source = (
        "def outer():\n"  # 1
        "    if True:\n"  # 2
        "        for i in range(3):\n"  # 3
        "            x = (\n"  # 4
        "                i\n"  # 5
        "            )\n"  # 6
    )
    spans = ADAPTER.statement_spans(source)
    assert StatementSpan(start_line=4, end_line=6) in spans  # the assignment


def test_unparseable_source_returns_none():
    spans = ADAPTER.statement_spans("def broken(:\n")
    assert spans is None


def test_a_null_byte_returns_none_the_same_as_a_syntax_error():
    """``ast.parse`` raises ``ValueError`` (not ``SyntaxError``) for an
    embedded NUL byte -- the same pair ``has_executable_code`` already
    catches, caught identically here."""
    spans = ADAPTER.statement_spans("x = 1\x00\n")
    assert spans is None


def test_an_empty_file_returns_an_empty_tuple_not_none():
    """An empty (but PARSEABLE) file has zero statements -- a real,
    non-None result naming zero spans, never confused with 'could not
    parse at all'."""
    spans = ADAPTER.statement_spans("")
    assert spans == ()


def test_the_return_shape_is_exactly_a_tuple_of_statementspan():
    """A-101's exact return shape: never a bare list of tuples."""
    spans = ADAPTER.statement_spans("x = 1\n")
    assert isinstance(spans, tuple)
    assert all(isinstance(span, StatementSpan) for span in spans)
