#!/usr/bin/env python3
"""Regenerate or verify the shared Linux-derived io.cost generator."""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
VENDOR_DIR = ROOT / "scripts/debian-install-v2/debian_install_v2/vendor"
SOURCE = VENDOR_DIR / "iocost_coef_gen.py"
PATCHES = (
    VENDOR_DIR / "0001-testdev-resolve-partition-to-parent-for-sysfs.patch",
    VENDOR_DIR / "0002-shared-lvm-file-target-support.patch",
)
OUTPUT = ROOT / "scripts/debian-install-v2/tools/iocost_coef_gen.py"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render() -> bytes:
    patch_bin = shutil.which("patch")
    if patch_bin is None:
        raise RuntimeError("the `patch` utility is required to build the shared generator")

    source_bytes = SOURCE.read_bytes()
    patch_bytes = b"".join(
        patch.name.encode("utf-8") + b"\0" + patch.read_bytes() + b"\0"
        for patch in PATCHES
    )
    with tempfile.TemporaryDirectory(prefix="vbpub-iocost-generator-") as tmp_name:
        tmp = Path(tmp_name)
        staged = tmp / SOURCE.name
        staged.write_bytes(source_bytes)
        for patch_path in PATCHES:
            result = subprocess.run(
                [patch_bin, "--batch", "--forward", "--fuzz=0", "-p1", "-i", str(patch_path)],
                cwd=tmp,
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode != 0:
                details = (result.stdout + result.stderr).strip()
                raise RuntimeError(
                    f"could not apply {patch_path.name} to the vendored source:\n{details}"
                )
        generated = staged.read_bytes()

    header = (
        "# GENERATED by tools/build-iocost-generator.py; do not edit.\n"
        f"# source-sha256: {sha256(source_bytes)}\n"
        f"# patch-series-sha256: {sha256(patch_bytes)}\n"
    ).encode("ascii")
    first_line, separator, body = generated.partition(b"\n")
    if not separator or not first_line.startswith(b"#!"):
        raise RuntimeError("vendored io.cost generator must start with a Python shebang")
    # Keep the shebang at byte zero so the checked-in shared artifact can be
    # invoked directly as well as through `python3`.
    return first_line + b"\n" + header + body


def digest_path(output: Path) -> Path:
    return output.with_name(output.name + ".sha256")


def digest_text(data: bytes, output: Path) -> str:
    # sha256sum format; the installer compares the first token with the
    # sha256 of the generated artifact's WHOLE body before running it.
    return f"{sha256(data)}  {output.name}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed shared tool matches the vendor source and patches",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help=f"output path (default: {OUTPUT})",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        try:
            actual = args.output.read_bytes()
        except OSError as exc:
            parser.error(f"cannot read generated output {args.output}: {exc}")
        if actual != expected:
            parser.error(
                f"{args.output} is stale; run {Path(__file__).name} to regenerate it"
            )
        try:
            committed_digest = digest_path(args.output).read_text(encoding="utf-8")
        except OSError as exc:
            parser.error(f"cannot read digest file {digest_path(args.output)}: {exc}")
        if committed_digest != digest_text(actual, args.output):
            parser.error(
                f"{digest_path(args.output)} does not match {args.output}; "
                f"run {Path(__file__).name} to regenerate it"
            )
        print(f"verified shared generator: {args.output}")
        return 0

    args.output.write_bytes(expected)
    args.output.chmod(0o755)
    digest_path(args.output).write_text(digest_text(expected, args.output), encoding="utf-8")
    print(f"wrote shared generator: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
