#!/usr/bin/env python3
# GENERATED by tools/build-iocost-generator.py; do not edit.
# source-sha256: 7be1ffde0780b867271ca700abd3a80a5a1c965421dcb4f4e54661f8352f80ee
# patch-series-sha256: 945abffcdfe10e9d4656e73307a3aa97e3d51456b5b028e017a8dfc42cd70567
#
# Copyright (C) 2019 Tejun Heo <tj@kernel.org>
# Copyright (C) 2019 Andy Newell <newella@fb.com>
# Copyright (C) 2019 Facebook
#
# Shared MDT/debian-install-v2 artifact generated from the pristine Linux
# kernel tools/cgroup/iocost_coef_gen.py source plus the patch series listed in
# debian_install_v2/vendor/README.md. Do not edit this generated copy; update
# the source or patch series and run tools/build-iocost-generator.py instead.
# The shared patches cover LVM-backed file targets, explicit testfile paths,
# partition sysfs lookup for raw --testdev targets, and optional no-COW setup.

desc = """
Generate linear IO cost model coefficients used by the blk-iocost
controller.  If the target raw testdev is specified, destructive tests
are performed against the whole device; otherwise, on
./iocost-coef-fio.testfile.  The result can be written directly to
/sys/fs/cgroup/io.cost.model.

On high performance devices, --numjobs > 1 is needed to achieve
saturation.

See Documentation/admin-guide/cgroup-v2.rst and block/blk-iocost.c
for more details.
"""

import argparse
import re
import json
import glob
import os
import stat
import sys
import atexit
import shutil
import tempfile
import subprocess
import signal

parser = argparse.ArgumentParser(description=desc,
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('--testdev', metavar='DEV',
                    help='Raw block device to use for testing, ignores --testfile-size')
parser.add_argument('--testfile', metavar='PATH',
                    help='Dedicated scratch file; calibration overwrites its contents (default: ./iocost-coef-fio.testfile)')
parser.add_argument('--testfile-size-gb', type=float, metavar='GIGABYTES', default=16,
                    help='Testfile size in gigabytes (default: %(default)s)')
parser.add_argument('--duration', type=int, metavar='SECONDS', default=120,
                    help='Individual test run duration in seconds (default: %(default)s)')
parser.add_argument('--seqio-block-mb', metavar='MEGABYTES', type=int, default=128,
                    help='Sequential test block size in megabytes (default: %(default)s)')
parser.add_argument('--seq-depth', type=int, metavar='DEPTH', default=64,
                    help='Sequential test queue depth (default: %(default)s)')
parser.add_argument('--rand-depth', type=int, metavar='DEPTH', default=64,
                    help='Random test queue depth (default: %(default)s)')
parser.add_argument('--numjobs', type=int, metavar='JOBS', default=1,
                    help='Number of parallel fio jobs to run (default: %(default)s)')
parser.add_argument('--quiet', action='store_true')
parser.add_argument('--verbose', action='store_true')

def info(msg):
    if not args.quiet:
        print(msg)

def dbg(msg):
    if args.verbose and not args.quiet:
        print(msg)

# determine ('DEVNAME', 'MAJ:MIN') for @path
def dir_to_dev(path):
    # find the block device the current directory is on
    devname = subprocess.run(
        ['findmnt', '-nvo', 'SOURCE', '-T', path],
        stdout=subprocess.PIPE, check=True,
    ).stdout
    devname = os.path.basename(devname).decode('utf-8').strip()

    # Resolve LVM-backed file targets as well as ordinary partitions. The
    # underlying scheduler queue can sit behind dm-N -> partition.
    if not os.path.exists(f'/dev/{devname}') and os.path.exists(f'/dev/mapper/{devname}'):
        devname = os.path.basename(os.path.realpath(f'/dev/mapper/{devname}'))
    for _ in range(5):
        if os.path.exists(f'/sys/block/{devname}/queue/scheduler'):
            break
        parents = glob.glob('/sys/block/*/' + devname)
        if len(parents):
            devname = os.path.basename(os.path.dirname(parents[0]))
            continue
        slaves = glob.glob(f'/sys/block/{devname}/slaves/*')
        if len(slaves) == 1:
            devname = os.path.basename(slaves[0])
            continue
        break
    rdev = os.stat(f'/dev/{devname}').st_rdev
    return (devname, f'{os.major(rdev)}:{os.minor(rdev)}')

def resolve_testdev_sysfs_name(devname):
    """Resolve a partition name to its parent disk for queue sysfs access."""
    parents = glob.glob('/sys/block/*/' + devname)
    if len(parents) > 1:
        raise RuntimeError(f'ambiguous whole-disk parent for test device {devname}')
    if parents:
        return os.path.basename(os.path.dirname(parents[0]))
    return devname

def create_testfile(path, size):
    global args

    try:
        existing = os.lstat(path)
    except FileNotFoundError:
        existing = None
    if existing is not None:
        if not stat.S_ISREG(existing.st_mode) or existing.st_nlink != 1:
            raise ValueError(f'benchmark testfile target must be a single-link regular file: {path}')
        if existing.st_size != size:
            raise ValueError(
                f'benchmark testfile exists with size {existing.st_size} bytes; refusing to replace '
                f'it (expected {size} bytes): {path}'
            )
        return

    info(f'Creating testfile {path}')
    fd = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_NOFOLLOW', 0),
        0o600,
    )
    os.close(fd)
    # No-COW improves repeatability on filesystems that support it, but it is
    # not part of the measurement contract. Some valid Docker data
    # filesystems reject this inode flag. Keep that advisory failure out of
    # stderr: fio can measure the persistent regular file normally.
    try:
        no_cow = subprocess.run(
            ['chattr', '+C', path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        no_cow = None
    if no_cow is not None and no_cow.returncode != 0:
        detail = (no_cow.stderr or no_cow.stdout or '').strip()
        info(
            f'NOTICE: filesystem does not support the optional no-COW flag for {path}'
            f'{f": {detail}" if detail else ""}; continuing with the file target'
        )
    pv = subprocess.Popen(
        ['pv', '-s', str(size), '-pr', '/dev/urandom']
        + (['-q'] if args.quiet else []),
        stdout=subprocess.PIPE,
    )
    assert pv.stdout is not None
    try:
        dd = subprocess.run(
            ['dd', f'of={path}', f'count={size}', 'iflag=count_bytes,fullblock',
             'oflag=direct', 'bs=16M', 'status=none'],
            stdin=pv.stdout,
            check=False,
        )
    finally:
        pv.stdout.close()
    pv_status = pv.wait()
    if dd.returncode != 0:
        raise subprocess.CalledProcessError(dd.returncode, dd.args)
    if not os.path.isfile(path) or os.path.getsize(path) != size:
        raise RuntimeError(f'benchmark testfile was not filled to {size} bytes: {path}')
    # pv may receive SIGPIPE when dd has consumed exactly the requested byte
    # count. The exact-size check above distinguishes that expected close from
    # an incomplete fill; other pv failures still fail the calibration.
    if pv_status not in (0, -signal.SIGPIPE):
        raise subprocess.CalledProcessError(pv_status, pv.args)

def run_fio(testfile, duration, iotype, iodepth, blocksize, jobs):
    global args

    eta = 'never' if args.quiet else 'always'
    outfile = tempfile.NamedTemporaryFile()
    cmd = [
        'fio', '--direct=1', '--ioengine=libaio', '--name=coef',
        f'--filename={testfile}', f'--runtime={round(duration)}',
        f'--readwrite={iotype}', f'--iodepth={iodepth}', f'--blocksize={blocksize}',
        f'--eta={eta}', '--output-format', 'json', '--output', outfile.name,
        '--time_based', f'--numjobs={jobs}',
    ]
    if args.verbose:
        dbg(f'Running {cmd}')
    subprocess.check_call(cmd)
    with open(outfile.name, 'r') as f:
        d = json.loads(f.read())
    return sum(j['read']['bw_bytes'] + j['write']['bw_bytes'] for j in d['jobs'])

def restore_elevator_nomerges():
    global elevator_path, nomerges_path, elevator, nomerges

    info(f'Restoring elevator to {elevator} and nomerges to {nomerges}')
    with open(elevator_path, 'w') as f:
        f.write(elevator)
    with open(nomerges_path, 'w') as f:
        f.write(nomerges)


args = parser.parse_args()

missing = False
for cmd in [ 'findmnt', 'pv', 'dd', 'fio' ]:
    if not shutil.which(cmd):
        print(f'Required command "{cmd}" is missing', file=sys.stderr)
        missing = True
if missing:
    sys.exit(1)

if args.testdev:
    devname = os.path.basename(args.testdev)
    rdev = os.stat(f'/dev/{devname}').st_rdev
    devno = f'{os.major(rdev)}:{os.minor(rdev)}'
    testfile = f'/dev/{devname}'
    info(f'Test target: {devname}({devno})')
    # Queue scheduler and nomerges live on the whole-disk parent, while fio
    # must still target the requested partition.
    devname = resolve_testdev_sysfs_name(devname)
else:
    # Derive the benchmark device from the file target, not the caller's cwd.
    probe_path = os.path.dirname(os.path.abspath(args.testfile)) if args.testfile else '.'
    devname, devno = dir_to_dev(probe_path)
    testfile = args.testfile or 'iocost-coef-fio.testfile'
    testfile_size = int(args.testfile_size_gb * 2 ** 30)
    create_testfile(testfile, testfile_size)
    info(f'Test target: {testfile} on {devname}({devno})')

elevator_path = f'/sys/block/{devname}/queue/scheduler'
nomerges_path = f'/sys/block/{devname}/queue/nomerges'

with open(elevator_path, 'r') as f:
    elevator = re.sub(r'.*\[(.*)\].*', r'\1', f.read().strip())
with open(nomerges_path, 'r') as f:
    nomerges = f.read().strip()

info(f'Temporarily disabling elevator and merges')
atexit.register(restore_elevator_nomerges)
with open(elevator_path, 'w') as f:
    f.write('none')
with open(nomerges_path, 'w') as f:
    f.write('1')

info('Determining rbps...')
rbps = run_fio(testfile, args.duration, 'read',
               1, args.seqio_block_mb * (2 ** 20), args.numjobs)
info(f'\nrbps={rbps}, determining rseqiops...')
rseqiops = round(run_fio(testfile, args.duration, 'read',
                         args.seq_depth, 4096, args.numjobs) / 4096)
info(f'\nrseqiops={rseqiops}, determining rrandiops...')
rrandiops = round(run_fio(testfile, args.duration, 'randread',
                          args.rand_depth, 4096, args.numjobs) / 4096)
info(f'\nrrandiops={rrandiops}, determining wbps...')
wbps = run_fio(testfile, args.duration, 'write',
               1, args.seqio_block_mb * (2 ** 20), args.numjobs)
info(f'\nwbps={wbps}, determining wseqiops...')
wseqiops = round(run_fio(testfile, args.duration, 'write',
                         args.seq_depth, 4096, args.numjobs) / 4096)
info(f'\nwseqiops={wseqiops}, determining wrandiops...')
wrandiops = round(run_fio(testfile, args.duration, 'randwrite',
                          args.rand_depth, 4096, args.numjobs) / 4096)
info(f'\nwrandiops={wrandiops}')
restore_elevator_nomerges()
atexit.unregister(restore_elevator_nomerges)
info('')

print(f'{devno} rbps={rbps} rseqiops={rseqiops} rrandiops={rrandiops} '
      f'wbps={wbps} wseqiops={wseqiops} wrandiops={wrandiops}')
