"""Reusable command-line contract helpers for vbpub projects."""

from .config import CliConfig, ConfigError, ProjectConfig, load_project_config
from .constraints import Conflicts, Constraint, Requires, RequiresChoice
from .contract import CONTRACT_VERSION
from .findings import Finding, FindingsError, FindingsFile, load_review_findings
from .identity import CliIdentity, VersionLookupError
from .output import (
    CliLoggingHandler,
    CliOutput,
    LogLevel,
    install_logging,
    logging_context,
    redact_text,
    redact_value,
    uninstall_logging,
)
from .parser import (
    ArgumentSpec,
    CliFailure,
    CliRegistry,
    CliRuntime,
    ExtendedArgumentParser,
    HelpCatalog,
    HelpFormat,
    OptionSpec,
    RegisteredCli,
    UsageError,
    VerbGroup,
    VerbSpec,
    add_common_options,
    discover_command_parsers,
    run_cli,
)
from .progress import ProgressMode, ProgressRenderer
from .prompts import PromptCancelled, PromptDriver
from .review import (
    REVIEW_SCHEMA_VERSION,
    ReviewCatalog,
    ReviewCatalogError,
    ReviewCase,
    SurfaceReport,
    SurfaceSpecError,
    assert_cli_case_tests,
    check_cli_surface,
    load_cli_review_catalog,
    render_cli_review_template,
    render_cli_surface_markdown,
    sync_cli_surface,
)
from .surface import (
    DEFAULT_MAX_CANDIDATES,
    SURFACE_SCHEMA_VERSION,
    SurfaceError,
    SurfaceLimitError,
    export_cli_surface,
    render_cli_surface_json,
)
from .doctor import CheckResult, DoctorCheck, register_doctor
from .skills import (
    SkillError,
    SkillState,
    register_skills_verbs,
    skill_states,
    validate_skill_source,
)
from .testing import assert_cli_contract, invoke_module, invoke_script, make_invoker
from .values import SelectorList

__all__ = [
    "CONTRACT_VERSION",
    "ArgumentSpec",
    "CheckResult",
    "CliConfig",
    "CliFailure",
    "CliIdentity",
    "ConfigError",
    "Finding",
    "FindingsError",
    "FindingsFile",
    "ProjectConfig",
    "load_project_config",
    "load_review_findings",
    "CliLoggingHandler",
    "CliOutput",
    "CliRegistry",
    "CliRuntime",
    "Conflicts",
    "Constraint",
    "ExtendedArgumentParser",
    "HelpCatalog",
    "HelpFormat",
    "LogLevel",
    "OptionSpec",
    "ProgressMode",
    "ProgressRenderer",
    "PromptCancelled",
    "PromptDriver",
    "REVIEW_SCHEMA_VERSION",
    "RegisteredCli",
    "Requires",
    "RequiresChoice",
    "ReviewCatalog",
    "ReviewCatalogError",
    "ReviewCase",
    "DEFAULT_MAX_CANDIDATES",
    "DoctorCheck",
    "SURFACE_SCHEMA_VERSION",
    "SelectorList",
    "SkillError",
    "SkillState",
    "SurfaceError",
    "SurfaceLimitError",
    "SurfaceReport",
    "SurfaceSpecError",
    "UsageError",
    "VerbGroup",
    "VerbSpec",
    "VersionLookupError",
    "add_common_options",
    "assert_cli_case_tests",
    "assert_cli_contract",
    "check_cli_surface",
    "discover_command_parsers",
    "install_logging",
    "invoke_module",
    "invoke_script",
    "make_invoker",
    "load_cli_review_catalog",
    "logging_context",
    "redact_text",
    "redact_value",
    "register_doctor",
    "register_skills_verbs",
    "render_cli_review_template",
    "render_cli_surface_json",
    "render_cli_surface_markdown",
    "run_cli",
    "skill_states",
    "sync_cli_surface",
    "uninstall_logging",
    "validate_skill_source",
]
