#!/usr/bin/env bash
# mk-server-slice.sh — create/update a per-server wings-<uuid>.slice unit,
# or audit the parent floor budget.
#
#   mk-server-slice.sh <short-uuid> [--min 6G] [--low 12G] [--high 8G]
#                      [--max ""] [--cpu 800] [--io 500] [--parent wings.slice]
#   mk-server-slice.sh --check-budget [--parent wings.slice]
#
# systemd dash-naming makes wings-<uuid>.slice a child of wings.slice
# automatically; the parent unit must exist (see ../t1-node-cgroup-parent/).
set -euo pipefail

UNIT_DIR="${UNIT_DIR:-/etc/systemd/system}"
PARENT="wings.slice"
MIN="" LOW="" HIGH="" MAX="" CPU="" IO=""
UUID="" CHECK=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --min) MIN="$2"; shift 2 ;;
        --low) LOW="$2"; shift 2 ;;
        --high) HIGH="$2"; shift 2 ;;
        --max) MAX="$2"; shift 2 ;;
        --cpu) CPU="$2"; shift 2 ;;
        --io) IO="$2"; shift 2 ;;
        --parent) PARENT="$2"; shift 2 ;;
        --check-budget) CHECK=1; shift ;;
        -*) echo "unknown flag: $1" >&2; exit 2 ;;
        *) UUID="$1"; shift ;;
    esac
done

to_bytes() { # 6G/512M/1024K/plain-bytes -> bytes
    local v="${1^^}"
    case "$v" in
        *G) echo $(( ${v%G} * 1024**3 )) ;;
        *M) echo $(( ${v%M} * 1024**2 )) ;;
        *K) echo $(( ${v%K} * 1024 )) ;;
        infinity|MAX) echo 0 ;;
        *) echo "$v" ;;
    esac
}

if [[ "$CHECK" == 1 ]]; then
    parent_min=$(systemctl show "$PARENT" -p MemoryMin --value 2>/dev/null || echo 0)
    total=0
    prefix="${PARENT%.slice}-"
    while read -r unit; do
        [[ -z "$unit" ]] && continue
        m=$(systemctl show "$unit" -p MemoryMin --value)
        [[ "$m" == "infinity" ]] && m=0
        total=$(( total + m ))
        printf '%-40s MemoryMin=%s\n' "$unit" "$m"
    done < <(systemctl list-units --type=slice --all --no-legend --plain "${prefix}*.slice" | awk '{print $1}')
    echo "----"
    echo "sum of child floors: $total"
    echo "parent $PARENT MemoryMin: $parent_min"
    if [[ "$parent_min" != "infinity" ]] && (( total > ${parent_min/infinity/0} )); then
        echo "WARNING: child floors exceed the parent budget — floors will compete for the shortfall." >&2
        exit 1
    fi
    exit 0
fi

[[ -n "$UUID" ]] || { echo "usage: $0 <short-uuid> [--min ..] | --check-budget" >&2; exit 2; }
unit="${PARENT%.slice}-${UUID}.slice"
file="$UNIT_DIR/$unit"

{
    echo "# Generated by mk-server-slice.sh $(date -Is) — per-server wings slice."
    echo "[Unit]"
    echo "Description=Wings server ${UUID} slice"
    echo
    echo "[Slice]"
    [[ -n "$MIN"  ]] && echo "MemoryMin=$MIN"
    [[ -n "$LOW"  ]] && echo "MemoryLow=$LOW"
    [[ -n "$HIGH" ]] && echo "MemoryHigh=$HIGH"
    [[ -n "$MAX"  ]] && echo "MemoryMax=$MAX"
    [[ -n "$CPU"  ]] && echo "CPUWeight=$CPU"
    [[ -n "$IO"   ]] && echo "IOWeight=$IO"
    echo
    echo "[Install]"
    echo "WantedBy=multi-user.target"
} > "$file"

systemctl daemon-reload
systemctl start "$unit"
echo "installed $file"
systemctl show "$unit" -p FragmentPath -p MemoryMin -p MemoryLow -p MemoryHigh
echo "Set the server's WINGS_CGROUP_PARENT=$unit in the panel, then recreate its container."
echo "Now verify the parent budget: $0 --check-budget --parent $PARENT"
